### PR TITLE
add-template: add document for template fan

### PR DESCRIPTION
**Pull request by giangvo**
**Description:**
Add document for template fans.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant/pull/12027)

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by tschmidty69** [comment]
Thanks for adding this. In the yaml file you don't need the '#' comments since that is defined in the configuration section. Also the example yaml at the top should contain only the most basic required settings  You can provide a more detailed yaml file further down.

One question, how do the defaults of low,medium. high map to the 1,2,3 as you have it? It's just not clear how those are mapped in to me. Does 1 = low?

**Comment by giangvo** [comment]
@tschmidty69, `speeds` is for define list of available speeds which is used to validate return value of `speed_template` and also input value of `set_speed`. Values of speeds are also shown in speed select box on UI.

If you don't config `speeds`, its value is default to list of "low", "medium", "high" (It means `speed_template` should return "low", "medium" or "high" and you should see "low","medium","high" in the speed selection box in UI)

If you don't like the default value, you can set `speeds` to list of other values. e.g ["1","2","3"]
(It means `speed_template` should return "1", "2" or "3" and you should see "1","2","3" in the speed selection box in UI)

Hope that I explain it clear enough :). Feel free to ping me if you have more questions.
Cheer,

**Comment by frenck** [comment]
Rebased the PR in order to fix the build

**Review by frenck — DISMISSED** [review]

**Comment by frenck** [comment]
Thanks, @giangvo! 🥇 
Can be merged as soon as the parent PR gets merged.

**Comment by giangvo** [comment]
@frenck I created a new PR for this document: https://github.com/home-assistant/home-assistant.github.io/pull/5296 
The main PR has been merged. Please review and merge it.
Thanks

**Pull request closed without merging**
