### PR TITLE
Document mandatory emulated_hue port setting

### PR DESCRIPTION
**Pull request by clach04**
Since 2019 August/September firmware updates for Echo and Echo Dot v1.

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
We should not document this in the example, but in the actual documentation itself.

**Comment by clach04** [comment]
@frenck are these changes what you had in mind?

There is a discussion thread on this at https://community.home-assistant.io/t/emulated-hue-suddenly-stopped-working-with-echo-dot-v2/133956/59 - an alternative discussed there is to use ip tables to remap ports (but the discovery service will still report the default 8300):

    sudo iptables -t nat -A PREROUTING -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 8300

I choose not to document that as the configuration would be inconsistent and then not work with well behaved clients!

**Comment by frenck** [comment]
I was just suggesting to remove the instructions from the YAML and add it to the documentation (instead of YAML comments).

**Comment by frenck** [comment]
Rebased onto `current` branch, resolved merge conflicts.

**Review by frenck — APPROVED** [review]

**Pull request merged**
