### PR TITLE
Adds documentation for Xiaomi Vibration Sensor

### PR DESCRIPTION
**Pull request by dlashua**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#16422

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by dlashua** [comment]
This documentation is dependent on https://github.com/home-assistant/home-assistant/pull/16422

**Comment by syssi** [comment]
Please move the example to https://www.home-assistant.io/components/binary_sensor.xiaomi_aqara/ and add the device to the table of "supported sensors" here, too.

**Review by frenck — CHANGES_REQUESTED** [review]
@dlashua Could you take a look at the changes requested by @syssi? Thanks 👍

**Comment by tjorim** [comment]
Can this be closed? #6600, which superseeds this PR, has been merged.

**Pull request closed without merging**
