### PR TITLE
Create sensor.pushbullet.markdown

### PR DESCRIPTION
**Pull request by jotunacorn**
**Description:**
Added doc for the new pushbullet sensor

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#6188

### CODE REVIEW

**Comment by rpitera** [comment]
I feel like this could also use a sentence or two about what a mirrored notification is or at least a link to an explanation. Also may be a good idea to explain that mirrored notification only works from Android devices at this time.

**Comment by fabaff** [comment]
The Pull request in the main repository was closed. Please re-open this PR is your changes are ready to merge.

**Comment by rpitera** [comment]
@fabaff - Not sure how to reopen the PR, but this is the addition I would propose:

`Notification Mirroring allows users to see their Android device's notifications on their computer.  It must be first enabled in the app and is currently only available on the Android platform.  For more information, please see [this announcement](https://blog.pushbullet.com/2013/11/12/real-time-notification-mirroring-from-android-to-your-computer/) on the Pushbullet Blog`

**Comment by jotunacorn** [comment]
@rpitera 
I will reopen it and add your suggestion as soon as i get around to fixing the pullrequest in the main branch. The fixes are mostly renaming and moving around stuff but I'm not sure when I'll be able to do it.

**Comment by rpitera** [comment]
Thanks!

**Pull request closed without merging**
