### PR TITLE
Add update available binary sensor and verify ssl for connection setup to synology_dsm

### PR DESCRIPTION
**Pull request by mib1185**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: home-assistant/core#42378 && home-assistant/core#42539
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Review by Quentame — DISMISSED** [review]

**Comment by mib1185** [comment]
sorry, accidental committed to the same branch on my fork, but already reverted it.

**Review by Quentame — DISMISSED** [review]

**Review by Quentame — COMMENTED** [review]
Add yourself as `ha_codeowners` (top of the file)

**Review by Quentame — CHANGES_REQUESTED** [review]
Add yourself as `ha_codeowners` (top of the file)

**Review by Quentame — APPROVED** [review]

**Comment by frenck** [comment]
@Quentame Not a problem, but the code-owner data is synced from the codebase. There is no need to correct those 😉

**Pull request merged**
