### PR TITLE
Add IoT Class to Sun Integration

### PR DESCRIPTION
**Pull request by ntilley905**
## Proposed change

Add `Cloud Polling` to Sun Integration since it periodically polls the `astral` package to determine the location of the sun and the next sun events.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: #14661 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by ntilley905** [comment]
Looks like @shift beat me to this one by two minutes in #14737 although we chose different classes...

**Comment by shift** [comment]
I was under the impression it uses maths along with the latitude, longitude and altitude in the main configuration to work out the values rather than calling an external service. I could be wrong, submitting these on my phone from the maternity ward.

**Comment by ntilley905** [comment]
I looked at the astral package and you are correct, it is just math to determine the state. I guess the idea behind Assumed State is that we can't determine the actual state of the sun so it's assumed since it's technically not the actual state of the sun? That makes sense now that I think about it, although it's a pretty darn good assumption that should hold true until the sun dies.

**Comment by ntilley905** [comment]
> submitting these on my phone from the maternity ward.

Also, congrats! Hope everyone is healthy.

**Pull request closed without merging**
