### PR TITLE
Include notes about entity_ids that start with a number

### PR DESCRIPTION
**Pull request by rpitera**
Based on info discovered by @armills in forum thread:  https://community.home-assistant.io/t/google-maps-as-a-card/9382/40

Wanted to update the docs as I had never run into this before nor had I seen it in the docs.

### CODE REVIEW

**Comment by armills** [comment]
I'd include the whole expression to be clear, so `states.device_tracker.2008_gmc` and `states.device_tracker['2008_gmc']`

**Comment by rpitera** [comment]
Agree, those changes made based on your suggestion.

**Comment by rpitera** [comment]
Thanks, @fabaff - couldn't figure out how to make that format correctly.  Now I know how for the next edit!

**Comment by fabaff** [comment]
You are welcome...was a quick one :smile:

**Pull request merged**
