### PR TITLE
Add Feasycom FSC-BP119 to the tested bluetooth adapters list

### PR DESCRIPTION
**Pull request by bdraco**
## Proposed change

Since some people have been trouble with the realtek adapters, I wanted to find a long range that worked well that wasn't realtek based.  I ordered this one and it works well. Also doesn't seem to need a periodic reset (YMMV).

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Same question is there a PR in code we can link to? 😄

**Comment by bdraco** [comment]
No PR since its the result of testing not a code change

**Comment by klaasnicolaas** [comment]
In that case, this PR belongs in the `current` branch. Or is this still a feature in the 2022.9 release?

**Comment by bdraco** [comment]
> In that case, this PR belongs in the `current` branch. Or is this still a feature in the 2022.9 release?

Normally, I would agree, but the `current` branch adapter list is completely different since bluetooth got major refactoring in 2022.9 so I figure this would just go out tomorrow anyways and we can avoid the merge conflict.

**Review by klaasnicolaas — APPROVED** [review]
✅ LGTM

**Pull request merged**
