### PR TITLE
minor edit to reflect coverage of flood agency

### PR DESCRIPTION
**Pull request by matchett808-gh**
## Proposed change

It's a minor text edit, Each home nation has its own flood agency and while this is the _UK_ flood agency, their data only covers (mainland) England.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

`This seems like a pedantic change - but I've added it as anyone from anywhere other than England will come to this component Expecting to get data for their area, but will not be able to`

Components for the following agencies will be required in order to service the entire UK

```
Northern Ireland Direct
Scottish Environment Protection Agency
Natural Resources Wales
```

## Checklist

- [x ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by matchett808-gh** [comment]
I 100% know this is a pedantic change - but it's an important distinction (for instance, I in Scotland can't use the integration)

**Review by frenck — COMMENTED** [review]
This title is pulled in from the code base and cannot be changed here. If we change this, it will automatically revert.

**Comment by matchett808-gh** [comment]
Cool, I'll change it elsewhere

**Comment by matchett808-gh** [comment]
Is it just the __init.py__ of the integration that needs changed? I'm not sure where in the documentation to check that

**Pull request closed without merging**
