### PR TITLE
Remove references to removed attribute

### PR DESCRIPTION
**Pull request by kbickar**
## Proposed change

The current_power_w attribute is no longer available so this functionality no longer works. 

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by thecode — APPROVED** [review]
Thanks

**Review by thecode — CHANGES_REQUESTED** [review]
Looking at it again I think the first part needs to stay:
`If the entity is a sensor that value will be reported as the current power usage unless the power field is defined.`

**Comment by kbickar** [comment]
@thecode Good point - mis-read that statement

**Review by thecode — APPROVED** [review]

**Comment by thecode** [comment]
Thanks again 👍

**Pull request merged**
