### PR TITLE
Add roomba total cleaned area sensor

### PR DESCRIPTION
**Pull request by Xitee1**
## Proposed change

Add roomba total cleaned area sensor.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: [#106640](https://github.com/home-assistant/core/pull/106640)
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by jpbede — CHANGES_REQUESTED** [review]
Please rebase from the `next` branch, as the PR contains unrelated commits.

**Review by jpbede — CHANGES_REQUESTED** [review]
Please check again, the PR still contains unrelated commits.

**Comment by Xitee1** [comment]
How exactly am I able to remove those unrelated commits? Also in my other PR in this repo this was also the case but didn't really make problems.

**Comment by jpbede** [comment]
Based on the commits, I would say that you created your branch from the `current` branch, but you should create your branch from the `next` branch.

Edit: This is also mentioned in the PR description :)
> I made a change that is related to an upcoming version of Home Assistant and used the next branch.

**Comment by Xitee1** [comment]
That could be it. I'll close this PR and make a new one.

**Comment by Xitee1** [comment]
New PR: #30559

**Pull request closed without merging**
