### PR TITLE
Added note to distinguish Statistics integration v.s. Long-term statistics.

### LINKED ISSUE #22161: Statistics doc: Missing important details
### Feedback

I'd like to see some extra info added, after I had to get info off a kind soul on Discord.

My goal was to make a graph of outside temperature drawn from the built-in weather component.  I'd found out how to make its State into a Sensor:
```
template:
  - sensor:
      - name: Outdoor temperature
        state: "{{ state_attr('weather.home','temperature') }}"
        unit_of_measurement: "°F"
```
But by itself that didn't became a Statistic capable of graphing over time.
Discord pointed me to https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics and the need to have a `state_class: measurement` line, at least to make it a long-term statistic.

The page also doesn't, AFAICT, explain the difference between short- and long-term statistics.

### URL

https://www.home-assistant.io/integrations/statistics/

### Version

2022.3.7

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dannytsang**
## Proposed change
Added note section to make it very clear there is a difference between the `Statistics` integration and Long-term Statistics. I have referenced the 2021.8.0 release notes because it describes the differences very well.

## Type of change
- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information
- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #22161

## Checklist
- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by dannytsang** [comment]
I am not sure if the note section is a bit too bold / eye catching for the message it's trying to convey. Happy to remove if it is.

**Comment by frenck** [comment]
What happened here?
CleanShot 2022-03-30 at 09 32 43

**Comment by dannytsang** [comment]
@frenck Most of them are my merge from upstream to my fork. Let me squash/rebase to tidy that up.

**Comment by dannytsang** [comment]
I will start again #n00b :(

**Pull request closed without merging**
