### PR TITLE
Update changes in light entity and remove priority light documentation

### PR DESCRIPTION
**Pull request by Sab44**
## Proposed change

Change goes together with HA core PR where (among other changes) priority light entity is removed as obsolete.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/80478
- Link to parent pull request in the Brands repository: (not applicable)
- This PR fixes or closes issue: fixes (see parent pull request above)

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by Sab44** [comment]
@frenck @emontnemery since the respective [PR](https://github.com/home-assistant/core/pull/80478)  has been merged and afaik is included in the 2023.7 release, this PR should be merged as well to reflect the changes in the documentation.

Also, in the release blog post I couldn't find the "Breaking Change" notes for the Hyperion integration that should be there. As discussed in the main PR, there will be significant changes to the behavior of the integrations entities, so users should be notified.

**Comment by emontnemery** [comment]
The core code changes are already released; rebased to target current

**Review by frenck — APPROVED** [review]
Thanks, @Sab44 & @emontnemery 👍 

../Frenck

**Pull request merged**
