### PR TITLE
Update device-specific.markdown

### PR DESCRIPTION
**Pull request by misterbenj34**
Update automation example code with new standard (id)

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

### CODE REVIEW

**Comment by Landrash** [comment]
Change is associated with what PR?

**Comment by frenck** [comment]
@misterbenj34 

Since you reacted on the last response of @Landrash with a 👍, I assume you have read his question. Since you did not leave any comments, I think you might have misinterpreted his request.

Therefore, another try:

@misterbenj34 Is this PR related to any other PR on the [home-assistant/home-assistant](https://github.com/home-assistant/home-assistant) repository? If so, could you be so kind to point us out which PR that might be?

**Comment by misterbenj34** [comment]
Hi, sorry for the delay
Sorry, but I don't understand "PR" ? (I'm not used to Github..)

I just updated the automation example by adding the "id" parameter.

**Comment by arsaboo** [comment]
@landrash and @frenck it seems the only change is the addition of id so that automations appear in the visual automation editor.

**Pull request merged**
