### PR TITLE
Clarify that the second miio-edit contains roborock

### PR DESCRIPTION
**Pull request by atxbyea**
**Description:**

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Please rebase this PR to the `current` branch

**Comment by frenck** [comment]
Rebased.

**Comment by frenck** [comment]
I don't see the clarification needed. It is way more than just vacuums? Why not list those?
The wildcard doesn't exclude them right?

**Comment by frenck** [comment]
No response + the change should not be needed imho.
Closing this for now.

**Pull request closed without merging**
