### PR TITLE
Add sensor as a supported Risco platform

### PR DESCRIPTION
**Pull request by OnFreund**
## Proposed change

The sensor platform was missing form the docs. Adding it.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/39594
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by OnFreund** [comment]
Not sure why this has a `needs-rebase` tag - it's based on the latest `next`, and trying to rebase I get `Current branch patch-1 is up to date.`

**Comment by klaasnicolaas** [comment]
Because you didn't add a link to PR in the core repository 😉

**Comment by OnFreund** [comment]
Thanks :)
This is just something that was missing in the docs though. I guess I can connect it to a PR

**Comment by OnFreund** [comment]
ok, so now it has the `has-parent` tag, but still has `needs-rebase` as well 🤷‍♂️

**Comment by frenck** [comment]
We deal with that @OnFreund, not everything is automated.

**Review by frenck — APPROVED** [review]

**Pull request merged**
