### PR TITLE
add timeout parameter to surepetcare integration

### PR DESCRIPTION
**Pull request by benleb**
## Proposed change

add timeout parameter

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/34944
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: https://github.com/home-assistant/core/issues/32583 & https://github.com/home-assistant/core/issues/33515

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
This PR should go into the `next` branch, change the target branch and rebase if necessary.

**Comment by benleb** [comment]
i do not really agree, but i also do not care :D https://github.com/home-assistant/home-assistant.io/pull/13236

**Comment by klaasnicolaas** [comment]
Why you don't agree? 

The docs always reflect what is in the code (core repo). The changes in this PR are not yet applicable since your parent PR in the core repo has not been merged. In other words, if something changes in the core, your PRs here always belong in the `next` branch. 

If you make changes to the existing docs, because something is wrong or an addition for which the code does not have to be changed, then you PR belongs to the `current` branch.

Kind of strange if we're going to add something to the docs if it doesn't exist in the code yet right? 😉

**Comment by benleb** [comment]
Ah sorry, little misunderstanding of current/next on my side 😄✌️

**Pull request closed without merging**
