### PR TITLE
feat: update madvr docs

### PR DESCRIPTION
**Pull request by iloveicedgreentea**
## Proposed change

Updated docs to reflect new entity names

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:  https://github.com/home-assistant/core/pull/121617
- Link to parent pull request in the Brands repository:  https://github.com/home-assistant/brands/pull/5612
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

## Summary by CodeRabbit

- **Refactor**
  - Renamed binary sensors in the `madvr` integration from uppercase to lowercase for consistency and clarity. Sensors affected include power state, signal state, HDR flag, and outgoing HDR flag.

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This PR, now has once again, multiple parent PR linked.

Just like the preview review / PRs. That is now allowed.

../Frenck

**Comment by iloveicedgreentea** [comment]
I corrected the linked PR, it should follow the sensor one

**Comment by frenck** [comment]
> I corrected the linked PR, it should follow the sensor one

So where is the PR of the binary sensor one then?

**Comment by iloveicedgreentea** [comment]
> > I corrected the linked PR, it should follow the sensor one
> 
> So where is the PR of the binary sensor one then?

I mistakenly included that in the first pr https://github.com/home-assistant/home-assistant.io/pull/33626

**Review by frenck — APPROVED** [review]
Thanks, @iloveicedgreentea 👍 

../Frenck

**Pull request merged**
