### PR TITLE
Update Slack Notify configuration variables

### PR DESCRIPTION
**Pull request by McCroden**
**Description:**
Use the new style for configuration variables description #6385 for notify.slack.markdown

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
That are a lot of commits 😆

**Comment by McCroden** [comment]
@klaasnicolaas I'm a noob at this stuff. It's just one file that changed, but all of my local commits got added. I don't know how to remove those. Those commits were in the PR #6953 that was merged 10 days ago. 

Also, I heard it was better to make more commits than fewer. 🤷‍♂️

**Comment by klaasnicolaas** [comment]
I think this is because you now use the same `branch` from your fork from the previous time and have not updated it with the upstream branch.

It is best to create a separate `branch` for each adjustment and delete it if your PR is merged with the HA repo.

**Comment by McCroden** [comment]
Oh, okay. Thank you, @klaasnicolaas. Maybe that's why when I was pushing other commits to my fork that they got added to this PR. I'm guessing the separate branch would fix that too.

**Comment by McCroden** [comment]
Ignore this PR. I'm just going to make a new one that uses a separate branch instead of the same branch. Apologies for confusion.

**Pull request closed without merging**
