### PR TITLE
Add information for the namespace option

### PR DESCRIPTION
**Pull request by alexbarcelo**
**Description:**

This modifications include information required about a new configuration parameter for Prometheus: **namespace**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant):** home-assistant/home-assistant#13738

### CODE REVIEW

**Review by frenck — DISMISSED** [review]

**Comment by frenck** [comment]
Thanks, @alexbarcelo.

Can be merged as soon as the parent PR gets merged.

**Comment by alexbarcelo** [comment]
Thanks @frenck for the thumbs up, but had to modify certain things on the main PR.

Let's wait and see, I hope that all the remaining issues were addressed, but maybe I'll have to change something else.

**Comment by alexbarcelo** [comment]
Parent PR has been merged without any additional changes. The documentation is ready then :)

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Thank you for letting me know @alexbarcelo!
I'll go ahead and merge it in 👍

**Pull request merged**
