### PR TITLE
Include support for Tradfri STARKVIND Air purifier

### PR DESCRIPTION
**Pull request by ggravlingen**
This is the documentation update for https://github.com/home-assistant/core/pull/58295

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by janiversen — DISMISSED** [review]
LGTM.

**Comment by janiversen** [comment]
I think however this should be based on next not current.

**Comment by ggravlingen** [comment]
Hmm, I tried a shortcut and used the “Edit on GitHub”-link in the docs. Should I open a new PR against the correct branch?

**Comment by frenck** [comment]
@ggravlingen You need to change the target branch of the PR to `next` and git rebase this PR onto the `next` branch.

**Comment by frenck** [comment]
Rebased onto `next`. Sorry for the notifications 🙏

**Review by frenck — APPROVED** [review]
Thanks, @ggravlingen 👍

**Comment by ggravlingen** [comment]
@frenck thanks for the help here!

**Pull request merged**
