### PR TITLE
add code_arm_required to manual alarm with mqtt

### PR DESCRIPTION
**Pull request by JumpMaster**
**Description:**
Add code_arm_required to the manual alarm as per the mqtt alarm. This option bypasses the code check if code_arm_required is false.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#22641

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
@JumpMaster This PR has merge conflicts, please resolve. 👍

**Review by balloob — DISMISSED** [review]

**Comment by balloob** [comment]
Could you resolve the merge conflicts.

**Comment by JumpMaster** [comment]
Thanks. Conflicts resolved.

**Review by frenck — DISMISSED** [review]
Thanks, @JumpMaster! 👍

**Review by frenck — APPROVED** [review]

**Pull request merged**
