### PR TITLE
ISY994 Update Documentation for Clarity and PyISYv2 Compatibility

### PR DESCRIPTION
**Pull request by shbatm**
## Proposed change

Update configuration options for the ISY994 integration to remove the `enable_climate` option and add the extra `isy994_control` event data properties, based on changes being incorporated to update to PyISYv2.

Regarding `enable_climate` Removal:
As of March 30, 2020, the ISY Climate Module which provided weather sensor information has been discontinued by UDI ([See Announcement here](https://www.universal-devices.com/byebyeclimatemodule/)). As a result, PyISY support for this module has been removed.

Also, perform some general cleanup and add some additional commentary for items that are brought up as recurring issues over the past year in the community and on PyISY and the HACS version of the integration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/35338
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - **I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.**
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by bdraco** [comment]
@shbatm Probably a good idea to make it clear why the `enable_climate` functionality is being removed.

**Comment by shbatm** [comment]
See if that note works for explaining the climate module change

**Comment by bdraco** [comment]
> @shbatm Probably a good idea to make it clear why the `enable_climate` functionality is being removed.

Sorry I should have been more specific. I was talking about in the `Proposed change` section.  I believe the standard is to not include version numbers in the docs (ok in proposed changes).

**Review by bdraco — APPROVED** [review]

**Review by frenck — APPROVED** [review]
Thanks, @shbatm! 👍

**Pull request merged**
