### PR TITLE
Add Nmap Reference guide

### PR DESCRIPTION
**Pull request by Mariusthvdb**
and some explanation on the default config setting

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by frenck** [comment]
At this point, it looks like we are fully reverting the NMap change.
Additionally, this PR is targeting the `rc` branch, which should not be targeted.

**Comment by Mariusthvdb** [comment]
ok, so is this then cancelled (because the revert) or should I await the release for some editing in the docs?

**Comment by frenck** [comment]
We edit docs on the current and next branches, not rc branch.

**Comment by frenck** [comment]
We can close this for now, as the NMap change has been revered and not yet revived.

**Pull request closed without merging**
