### PR TITLE
add code_arm_required to manual alarm

### PR DESCRIPTION
**Pull request by JumpMaster**
**Description:**
Add code_arm_required to the manual alarm with mqtt as per the mqtt alarm. This option bypasses the code check if code_arm_required is false.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#22618

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Parent PR still open. ⚠️ We have also a merge conflict!

**Review by frenck — CHANGES_REQUESTED** [review]
Hi, @JumpMaster. Could you please resolve the merge conflict so we can merge this in for 0.95? 👍

**Comment by JumpMaster** [comment]
@frenck Pulled from upstream and conflicts have been resolved.

**Comment by frenck** [comment]
Thanks for your question action there @JumpMaster! I'll take a look today.

**Review by frenck — APPROVED** [review]
Thanks, looks good to me @JumpMaster! 👍

**Pull request merged**
