### PR TITLE
Fix error about unit of average power.

### PR DESCRIPTION
**Pull request by ast0815**
The average of something has the same unit of that something. So the average power also has the unit Watt. In fact, to get the average, you would integrate the power, yielding the total energy in kWh, and then divide that by the total time: kWh / h = kW.

The only instance where you would get a unit of W/h (Watt per hour) I can think of, is when you look at the speed at which power consumption changes, i.e. the differential of the power function.

## Proposed change

Just fixing a side note about the unit of average power.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @ast0815, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#23285).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by davet2001 — APPROVED** [review]
Looks good to me. 

Yes, kW/h is rate of change of power (and not relevant here), correct unit should be kW or W.

**Comment by davet2001** [comment]
@ast0815 Only place I've come across kW/h was a power station operator telling me how quickly he could ramp up/down production.

**Review by frenck — APPROVED** [review]
Thanks, @ast0815 👍

**Pull request merged**
