### PR TITLE
Add internet sensor to documentation for Smlight integration

### PR DESCRIPTION
**Pull request by tl-sl**
## Proposed change

Document intenet sensor that displays if SLZB-06x device can connect to internet (internet is required for updates only)

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:  https://github.com/home-assistant/core/pull/125982
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

## Summary by CodeRabbit

- **New Features**
	- Introduced a new sensor for monitoring Internet connection status, enhancing overall connectivity insights alongside existing sensors.
	- Introduced the Lektrico Charging Station integration for monitoring charging metrics.
	- Added support for merging lists of triggers in automation configurations.
	- New section for "Disabling a trigger" in automation documentation.
	- Enhanced Azure DevOps integration with a new "Work item count" metric.
	- Added a new action for archiving packages in the 17track API integration.
	- New Cambridge Audio integration for controlling receivers and streamers.
	- Added support for a new "Problem" binary sensor in the SimpleFin integration.
	- Introduced the Google Photos integration for accessing recent photos.
	- Added new capabilities for the Tesla Fleet integration, including climate control features.

- **Bug Fixes**
	- Clarified device compatibility for the August integration, removing unsupported Yale models.

- **Documentation**
	- Expanded documentation for various integrations, including new sections on configuration flows and troubleshooting.
	- Added examples for merging action responses in templating documentation.
	- Improved clarity on security requirements for the Solar-Log integration.
	- Updated the Ruckus integration documentation to reflect support for multiple device types.

- **Chores**
	- Updated CODEOWNERS to assign ownership for the Lektrico integration.

### CODE REVIEW

**Comment by tl-sl** [comment]
@c0ffeeca7 can you take a look at this one? The tags are all messed up for some reason, but parent PR has been merged a few days ago.

**Review by c0ffeeca7 — APPROVED** [review]
Thank you, @tl-sl :+1:

**Comment by c0ffeeca7** [comment]
> @c0ffeeca7 can you take a look at this one? The tags are all messed up for some reason, but parent PR has been merged a few days ago.

Thank you for letting me know parent was merged. I would have missed this one.

**Comment by tl-sl** [comment]
Thanks!
There is also one more that is messed up https://github.com/home-assistant/home-assistant.io/pull/34741 since it doesnt have a parent, but should go into `next` also.

**Pull request merged**
