### PR TITLE
Remove alert detail from Environment Canada docs

### PR DESCRIPTION
**Pull request by ikifar2012**
## Proposed change
 
    Remove alert detail from Environment Canada docs 

## Type of change

    The alert detail no longer exists for now as the is used to use web scraping so it has been 
    removed for now 

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

    as a side note there are a few sensors that don't seem to appear for me and I am not sure if this 
    is a docs issue those sensors would be pop, precip_yesterday, text_summary, high_temp, 
    low_temp and wind_dir

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
It looks like this PR does 2 things?
Please split it into separate PRs.

Furthermore, we need to use bundler 2.0.1, any other version will not work with our upstream hosting provider.

**Comment by ikifar2012** [comment]
This PR should only contain one thing the additional info was for a possible future PR

**Comment by frenck** [comment]
I'm not sure what the gemlock changes have to do with this PR or what they are even for?

**Comment by ikifar2012** [comment]
> I'm not sure what the gemlock changes have to do with this PR or what they are even for?

they don't have anything to do with the PR it was just added because I tired to generate the site on windows which must have triggered this in the Gemfile 
```
# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.0" if Gem.win_platform?
```

**Review by frenck — APPROVED** [review]
Thanks, @ikifar2012 👍

**Pull request merged**
