### PR TITLE
Add config variable rgb_command_template

### PR DESCRIPTION
**Pull request by belyalov**
**Description:**
Documentation for MQTT light config variable "rgb_command_template"

### CODE REVIEW

**Comment by belyalov** [comment]
Related PR: https://github.com/home-assistant/home-assistant/pull/9304

**Comment by dale3h** [comment]
This should be merged into `next` branch instead of `current`.

**Comment by belyalov** [comment]
Should I open new pull request and close this one?

**Comment by frenck** [comment]
@belyalov If you don't mind? 👍

**Comment by fabaff** [comment]
Needs to be merged after the release of 0.53.

**Pull request merged**
