### PR TITLE
CoolMaster: Change auto to heat_cool

### PR DESCRIPTION
**Pull request by OnFreund**
**Description:**

Changing the `auto` mode to a `heat_cool` mode in CoolMaster to better reflect what it does.

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#26144

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

<a href="https://gitpod.io/#https://github.com/home-assistant/home-assistant.io/pull/10209"></a>

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by OnFreund** [comment]
@frenck Thanks. The parent PR is now merged.

**Review by klaasnicolaas — DISMISSED** [review]

**Comment by klaasnicolaas** [comment]
Could you resolve the merge conflict? As far as I see, your fork still has an old version of our repo. Make sure that it is up to date.

**Comment by OnFreund** [comment]
@klaasnicolaas really strange. Not sure how this happened. I rebased on top of upstream/next and should be ok now.

**Review by klaasnicolaas — APPROVED** [review]

**Comment by klaasnicolaas** [comment]
Yes we can merge now 😄

**Pull request merged**
