### PR TITLE
changed serial/by-id to ttyUSBx (hassio 0.69>)

### PR DESCRIPTION
**Pull request by passie**
From Hassio 0.69> the old method isn't working anymore. 
Changed serial/by-id to ttyUSBx

### CODE REVIEW

**Comment by metbril** [comment]
There's 2 more files that have references to '/dev/serial/by-id/' :

https://github.com/home-assistant/home-assistant.github.io/blob/next/source/_components/rfxtrx.markdown

https://github.com/home-assistant/home-assistant.github.io/blob/next/source/_components/litejet.markdown

**Comment by passie** [comment]
Will fix these in the docs as well. 
Thanks for pointing out 

—- Passie

**Comment by notoriousbdg** [comment]
The issue with /dev/serial is being fixed.  See https://github.com/home-assistant/hassio/issues/485 and https://github.com/home-assistant/hassio-build/commit/77cd115f76c566fae271e89c3f6f69fb02444656.

**Comment by passie** [comment]
@notoriousbdg  maybe i'm overlooking, but I don't see this fixed in  [https://github.com/home-assistant/hassio/issues/485](url) ?

**Comment by notoriousbdg** [comment]
@passie, udev was removed and https://github.com/home-assistant/hassio-build/commit/77cd115f76c566fae271e89c3f6f69fb02444656 is adding it back.

**Comment by passie** [comment]
@notoriousbdg thank your for your clarification. If a revert is needed for my PR i'll do so. Or if one of the Admins won't merge my request, it's fine.
For now i'll let the PR for what it is. 
Again, thank you for pointing me on these changes within HA.

--- Passie

**Comment by pvizeli** [comment]
Fixed on >= 0.72

**Pull request closed without merging**
