### PR TITLE
Breakup alexa

### PR DESCRIPTION
**Pull request by awarecan**
**Description:**

We support three different way to interactive with Alexa, that make the document lengthy. I want to divid them, so that I can add my another more lengthy guide to Smart Home skill integration.

I have to change travis.yml to allow my fork CI works. Don't known if it is necessary on main repo.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by awarecan** [comment]
Ah, I see now, main repo is not using travis anymore. So that my change should be good to help other people working on the fork.

**Comment by robbiet480** [comment]
@awarecan We had to upgrade the Ruby and Bundler versions today in #8938, you need to merge current into your branch so that your CI will work again.

**Comment by awarecan** [comment]
@robbiet480 No. I am on the latest current. My problem is I am still using old travis-ci, not netlify. So the fix of travis in this PR is its value for others.

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Thanks, @awarecan! 👍 

And again, I'm truly sorry for me missing this PR!

**Pull request merged**
