### PR TITLE
Move actions to their own page.

### PR DESCRIPTION
**Pull request by PureGeekery**
## Proposed change

Move actions into their own page for issue #11886.

Note: I was not able to get bundler to work on my machine, so I was unable to preview locally.

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: n/a
- This PR fixes or closes issue: #11886

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
Good start, @PurelyNicole, could you please make the build pass? Thanks! 👍 

Also, please create a separate branch on your fork next time, to prevent future issues.

**Comment by PurelyNicole** [comment]
Sorry about the lack of a separate branch on my fork. Thought that just having the fork was enough. I'll  definitely make it's own branch going forward. 

Struggling to find the cause of this error, since I can't seem to get bundler to play nicely on my machine. Going to try the setup process again, to see if I can get it to run properly.

**Comment by frenck** [comment]
Instead of setting up ruby and the bundler, you can also make use of the Visual Studio Remote Development container that is shipped in this repository.

You don't need any tools, besides Docker, VSCode and the VSCode Remote development extension pack. If you open this repository in VSCode at that point, it will ask you if it should set up an environment for you.

It all does this in Docker, and we have prepared the environment for you.

**Comment by PurelyNicole** [comment]
Oh that's phenomenal. Thanks for doing  all that ground work!

I'm going to close this PR, and create a proper branch before resubmitting.

**Pull request closed without merging**
