### PR TITLE
Update lets_encrypt.markdown

### PR DESCRIPTION
**Pull request by ghost**
Added link to broader description on SSL/TLS.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by fabaff — APPROVED** [review]

**Comment by ocdtrekkie** [comment]
@fabaff You may want to reconsider this spam commit. They appear to be trying to SEO their site.

**Comment by klaasnicolaas** [comment]
I have searched all his commits once and you are right, we are going to adjust this.

**Comment by frenck** [comment]
To bad for them since we mark these links as "external nofollow" for the search engines 😉

**Comment by frenck** [comment]
@ocdtrekkie Well spotted. I've taken the necessary action to revert and prevent this.
Thanks a ton! 🎖

**Comment by ocdtrekkie** [comment]
Happy to be of service. :)

**Pull request merged**
