### PR TITLE
Initial implementation of EnaSolar integration

### PR DESCRIPTION
**Pull request by geustace**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

https://github.com/home-assistant/core/pull/54859

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ x The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Please rebase your PR to the `next` branch, current is only for changes on documentation from integrations that is already in core.

**Comment by homeassistant** [comment]
Hi @igrybkov, @shanem2004, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#18991).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by geustace** [comment]
I am not a git guru so am not sure I have done the right thing with the rebase. I have 'rebased' my clone on my development server, that has pushed back into my GitHub repo but I don't know whether that is what I was supposed to do.

**Comment by klaasnicolaas** [comment]
Maybe it's better to close this one and start fresh: 
- checkout on next
- pull the latest changes
- create a new branch
- create your integration documentation
- commit and push
- create a new PR.

**Pull request closed without merging**
