### PR TITLE
Update xiaomi_ble.markdown mention Pink HHCCJCY10

### PR DESCRIPTION
**Pull request by Hedda**
## Proposed change

Mentioning model HHCCJCY10 (Pink coloured) variant of MiFlora Flower Care is not yet supported by this Xiaomi BLE integration. 

Did not mention, FYI, one workaround is to use pinks with BLE Monitor instead for now -> https://github.com/custom-components/ble_monitor/issues/809

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by Ernst79** [comment]
@Jc2k This HHCCJCY10 sensor has its own format, it is not using Xiaomi MiBeacon. The parser code is here, it will eventually be moved to a core integration, or we might integrate this into xiaomi-ble later. 

https://github.com/custom-components/ble_monitor/blob/master/custom_components/ble_monitor/ble_parser/hhcc.py

**Comment by Jc2k** [comment]
I was just replying: I think I'll just add support for the pink variant. It's tiny, I can probably squeeze it in today.

**Comment by Jc2k** [comment]
Given it's got 2 cousins that are supported in xiamoi_ble (white and green?) I think it makes sense to stick it in xiaomi_ble.

**Comment by Ernst79** [comment]
Yes, that is even better. Note that it uses `uuid16 == 0xFD50`

**Comment by Hedda** [comment]
> Given it's got 2 cousins that are supported in xiamoi_ble (white and green?) I think it makes sense to stick it in xiaomi_ble.

By the way, wondering if the new "green" version also has a other HHCCJCY## model number and/or if that too uses a other format as well or is it just the enclosure/casing color and the packaging for the Chinese market that differ for that?

See example sold here -> https://www.aliexpress.us/item/3256801428513169.html

image

**Comment by Jc2k** [comment]
Green is supported AIUI

**Comment by Ernst79** [comment]
Yes, Green one is recognized as HHCCJCY01. I have one at home.

**Comment by Hedda** [comment]
Can I assume the commonly available "VegTrug" branded devices are also just rebranded and is discovered as HHCCJCY01 as well?

https://www.gearbest.com/testers---detectors/pp_3007097130409044.html

https://www.aliexpress.com/item/1005001547015773.html

https://www.aliexpress.com/i/4000535170663.html

image

image

**Comment by Jc2k** [comment]
I have not personally tried a VegTrug.

First stab at pink support here: https://github.com/Bluetooth-Devices/xiaomi-ble/pull/21. Will finish it off tomorrow.

**Comment by Patrick010** [comment]
Its been pending review for over a month now. Can somebody please review this so we can start using it :)

**Comment by Jc2k** [comment]
See https://github.com/home-assistant/core/pull/82069, this PR is no longer required.

**Comment by Patrick010** [comment]
Good news. Looks like this topic can be closed then?

**Comment by Jc2k** [comment]
it is

**Comment by Patrick010** [comment]
Didnt see that, sorry

**Pull request closed without merging**
