### PR TITLE
Various Rflink integrations: fix 404 url to firmware

### PR DESCRIPTION
**Pull request by pyrrolizin**
## Proposed change

The various integrations of rflink have a broken link (404) to a former download URL for the firmware file. Also the link to the Nodo store has a permanent redirect (301), which has been fixed.

RFLink gateway firmware: http://www.nemcon.nl/blog2/ changed to https://www.rflink.nl/download.php
Nodo RFLink Gateway (shop link): https://www.nodo-shop.nl/nl/21-rflink-gateway changed to https://www.nodo-shop.nl/nl/21-rflink-

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @pyrrolizin, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#23543).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by pyrrolizin** [comment]
The modified files are not listed in the CODEOWNERS file. May I ask you for a review @javicalle ? Thank you :+1:

**Comment by frenck** [comment]
@pyrrolizin Don't ping for reviews, please. If that were wished for, the bot would handle it. Thanks 👍

**Review by frenck — APPROVED** [review]
Thanks, @pyrrolizin 👍

**Comment by javicalle** [comment]
Maybe the English version would be better:
https://www.nodo-shop.nl/en/21-rflink-

**Comment by pyrrolizin** [comment]
> Maybe the English version would be better:
> https://www.nodo-shop.nl/en/21-rflink-

I will take care of it. 👍

**Pull request merged**
