### PR TITLE
Adding italian Alexa web-based app

### PR DESCRIPTION
**Pull request by salvatorecordiano**
## Proposed change
Adding italian Alexa web-based app

## Type of change
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).

## Checklist
- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This PR adjusts existing documentation which applies to the current release of Home Assistant. Therefore this PR needs to target the `current` branch. 

Please change the target branch to `current` and rebase the PR if needed.

**Comment by salvatorecordiano** [comment]
@frenck done

**Comment by frenck** [comment]
Please rebase it, as there are now unrelated commits in this PR.

**Comment by salvatorecordiano** [comment]
@frenck rebased now

**Pull request closed without merging**
