### PR TITLE
Small site adjustments (look and feel)

### PR DESCRIPTION
**Pull request by frenck**
**Description:**

- Made background less dirty (white instead of smug)
- Made header more distinctive
- Header now looks like one with hero unit on the frontpage
- Hero unit is closer to the header

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

<a href="https://gitpod.io/#https://github.com/home-assistant/home-assistant.io/pull/9745"></a>

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
image

Can we fix that little blue stripe underneed the phone?

**Comment by frenck** [comment]
Probably, good point @klaasnicolaas!

Some other ideas/experiments I've done:

image


image


PS: In the above, those are the actual interactive demo's (not an image).

**Comment by klaasnicolaas** [comment]
Damn the first image looks nice! 🔥

**Comment by frenck** [comment]
nevermind.

**Pull request closed without merging**
