### PR TITLE
Update device-specific.markdown

### PR DESCRIPTION
**Pull request by bongfrog**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
Why not execute this using one of the SSH add-ons?

My first intuition would be that the commands for Hass.io are equal to the others.

Could you please clarify this to me?

**Comment by bongfrog** [comment]
I tried that the /dev/tty did not seem to be mapped to that container. Very
possible that i missed something simple.

**Comment by frenck** [comment]
@bongfrog You are right, not with the Core SSH add-on. The community SSH add-on does provide this (hence my reaction).
I've opened a PR on the Core SSH add-on to enable UART/Serial devices, depending on it being accepted, would decide whether or not this PR is needed.

**Comment by frenck** [comment]
The upstream PR has been accepted @bongfrog!
On the next Core SSH add-on release, the normal instruction will just work.
Therefore, closing this PR.

Thanks for bringing this up! 👍

**Pull request closed without merging**
