### PR TITLE
Added path as mandatory

### PR DESCRIPTION
**Pull request by vaidyasr**
**Description:**
Added path as mandatory as different cameras use different paths to store mp4 files

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#15266

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by fabaff — DISMISSED** [review]
Thanks :bird:

**Comment by frenck** [comment]
Parent PR, closed. So in the end, it will be a note added to the docs.

**Review by frenck — CHANGES_REQUESTED** [review]
Needs to be rebased onto current, since there is no parent PR anymore.

**Comment by frenck** [comment]
I'll pick up on the rebase.

**Review by frenck — APPROVED** [review]
Rebased, can be merged as soon as the build passes.
Thanks @vaidyasr & @fabaff!

👍

**Pull request merged**
