### PR TITLE
Cleanup Insteon documentation

### PR DESCRIPTION
**Pull request by teharris1**
## Proposed change

Clean up the Insteon documentation, remove duplicate sections and make the information easier for new users to consume. This also addresses a way to fix an Insteon Hub that has been factory reset after Insteon shut down their cloud services. This PR is time sensitive as a lot of Insteon users are looking for a way to control their Hubs now that Insteon.com has shut down!

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by balloob — APPROVED** [review]

**Comment by balloob** [comment]
Thanks Tom! 

I just emailed you too btw, can we set up a call to see how we can help people better?

**Comment by teharris1** [comment]
Yes, that would be great. When is a good time for you? I assume discord?
________________________________

**Comment by balloob** [comment]
Now works.

**Comment by balloob** [comment]
https://meet.google.com/igm-zcea-mfo

**Comment by teharris1** [comment]
i just tried to join but it says I cannot.
________________________________

**Pull request merged**
