### PR TITLE
Update slack.markdown

### PR DESCRIPTION
**Pull request by wasper17**
Updated per API change - https://api.slack.com/scopes/chat:write

## Type of change
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue:

## Checklist
- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
What does this add? Given that `chat:write:user` is already described

**Comment by wasper17** [comment]
chat:write:user is being fazed out, the new permission is just "chat:write". Wasn't sure if you wanted to update completely, or keep the reference for historical documenation.

Anthony

**Comment by klaasnicolaas** [comment]
Ah oke! Perhaps it would be more convenient to put it in a note. If the changes in the API are already in effect, you can simply change the instruction and a note is not necessary either.

**Comment by frenck** [comment]
Just replace it and update it to the latest greatest. The old is phased out, having it in the documentation as we have now, will confuse people.

**Review by fabaff — DISMISSED** [review]

**Review by frenck — APPROVED** [review]

**Pull request merged**
