### PR TITLE
Xiaomi gateway: IoT class changed & content improved

### PR DESCRIPTION
**Pull request by syssi**
IoT class changed. The gateway provides updates immediately as multicast broadcast.
Device table added for binary sensors of the xiaomi platform.
Some glitches removed.

### CODE REVIEW

**Comment by Landrash** [comment]
Changes looks good, Are these changes already merged or associated with a open PR in the main repo?

**Comment by syssi** [comment]
There is no association. The platform is already merged since HA 0.50.

**Comment by Landrash** [comment]
@syssi Thank you for the quick answer 👍

**Comment by Landrash** [comment]
@syssi I currently can't merge this in since it's against the `next` branch. If you can rebase it against the current `branch`.

**Comment by syssi** [comment]
Sure. Wait a second.

**Comment by syssi** [comment]
Uff. I hope I didn't mess it up!?

**Comment by syssi** [comment]
The branch doesn't look good anymore. I will close the PR and restart from scratch. Sorry for the noise.

**Pull request closed without merging**
