### PR TITLE
KNX Cookbook:  New chapter "Use KNX switches to control Philips Hue or Ikea Trådfri"

### PR DESCRIPTION
**Pull request by Jpsy**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by Jpsy** [comment]
@frenck: I can't see the problem that the automated check found.  Could you help and have a look? I don't see anything wrong with the code.

> 11:53:59 PM:   Liquid Exception: Liquid syntax error (line 238): Expected end_of_string but found open_round in "{{ float(trigger.to_state.state) > 0 }}" in /opt/build/repo/source/_cookbook/automation_knx.markdown

**Comment by Jpsy** [comment]
Hi @frenck could you have a look why the code check fails?
I just don't understand the problem.

**Comment by Jpsy** [comment]
@balloob Paulus, I hope, you read this. I would love to continue on the KNX cookbook, but the checks fail and the pull request is therefore blocked. I cannot see the reason for the checks failing. Could you have a look?

**Comment by balloob** [comment]
I think that we should get rid of the cookbook in favor of having people share it in the forums. Allows for questions/updates etc.

We should not merge this.

**Comment by balloob** [comment]
Also @Jpsy don't tag developers, that's how you get ignored. There are hundreds of open PRs across all our repo's, people will get to your PR when they get to it .

**Comment by Jpsy** [comment]
Sorry for that, I honestly did not mean to be pushy. I thought that a pull request that failed validation would be ignored, so I tried to ask for help.

I'm fine to transfer the cookbook into a forum posting. Will start that in the following weeks.

**Comment by frenck** [comment]
In that case, this PR is no longer needed and can be closed.

**Pull request closed without merging**
