### PR TITLE
Add save clips to Blink services

### PR DESCRIPTION
**Pull request by perdue**
## Proposed change

This documentation change is the companion to a PR that I am putting
up for the Blink integration.  It describes how to use the new save recent
clips functionality.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

Link to core PR:  https://github.com/home-assistant/core/pull/84149

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @perdue 👋 

There is a CI/build error with this PR. Could you take a look?

Thanks 👍 

../Frenck

**Comment by perdue** [comment]
> 
> There is a CI/build error with this PR. Could you take a look?
> 

I tried.  I clicked "check the logs", but nothing ever shows up.  I was hoping that someone that had access to Netlify could identify the problem.

image

**Comment by frenck** [comment]
> I tried. I clicked "check the logs", but nothing ever shows up. I was hoping that someone that had access to Netlify could identify the problem.

You don't need Netlify for that, render a local preview will result in the same issues.

**Comment by perdue** [comment]
OK, thanks!  I'll take a look at that.

**Comment by perdue** [comment]
@frenck CI checks are passing now.

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by perdue** [comment]
@frenck : I've gotten a stale message on this PR:

> There hasn't been any activity on this pull request recently. This pull
    request has been automatically marked as stale because of that and will
    be closed if no further activity occurs within 7 days.

It is waiting on the [parent PR](https://github.com/home-assistant/core/pull/84149) to be merged.  The parent PR has two community tester approvals - as well as the code owner's PR approval.  I've been running the updated integration (as a custom one) for 4 months on my production home server without issue.  I really don't know what else I can do to satisfy the code review requirements for the parent PR.  From my point of view, I have done the due diligence for a good code review.  I need a HA code maintainer to give it a look.

Now there are [additional people](https://github.com/home-assistant/core/pull/84149#issuecomment-1541501600)  asking about the [parent PR](https://github.com/home-assistant/core/pull/84149) status.  Is there any chance that this could be reviewed and merged soon?  Thank you!

**Comment by raman325** [comment]
please don't tag people to ask for reviews. PRs take time to merge unfortunately. I took a look and will give it a review but would like a second pair of eyes as saving arbitrary files to disk is not standard

**Comment by perdue** [comment]
> please don't tag people to ask for reviews. PRs take time to merge unfortunately. I took a look and will give it a review but would like a second pair of eyes as saving arbitrary files to disk is not standard

@raman325: Thanks for taking a look!

FYI: The Blink integration seems to have been [saving files to disk since 2018](https://github.com/home-assistant/core/blame/0a94d9b284466c2554972bd5befd49336443ccfe/homeassistant/components/blink/__init__.py#L139).

**Pull request merged**
