### PR TITLE
Clarifying Unifi Protect condition for downgrading

### PR DESCRIPTION
**Pull request by alexruffell**
`Manually downgrading comes with its own risks and it is not recommended unless you do not have a backup available.` does not make sense.

`Manually downgrading comes with its own risks and is not recommended unless you have a backup available.` is likely what the author meant to write.

Alternative:

`Manually downgrading comes with its own risks and it is not recommended if you do not have a backup available.`

## Proposed change

The sentence did not make sense as is. Proposed a couple alternatives.

## Type of change

- [X] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by alexruffell** [comment]
Sorry... never done this before so I don't know all the correct settings/actions.

**Review by frenck — CHANGES_REQUESTED** [review]
This PR is targeting the `rc` branch, which is almost never correct.

If this applies to existing documentation, it need to target the `current` branch. If this only applies to an upcoming release, it needs to target the `next` branch.

Please adjust the PR to target the appropriate branch and git rebase your changes if needed.

Thanks 👍 

../Frenck

**Comment by alexruffell** [comment]
@frenck Ok, I had some trouble finding the setting but I think I got it right this time. It is a correction to live current documentation.

**Review by frenck — CHANGES_REQUESTED** [review]
There are unrelated git commits in this PR now:

CleanShot 2023-01-31 at 09 28 22


As per the previous review comment, please git rebase.

../Frenck

**Comment by alexruffell** [comment]
@frenck Sorry, I can't figure out how to solve the mess. Please cancel my pull request.

**Comment by thecode** [comment]
@alexruffell in many cases the easiest option is to close the PR and create a new one with your changes, you can still copy the PR description from the closed one.

For simple PRs which are not already in review progress, I sometime choose to close and create a new one.

When creating a new PR make sure you start from the `current` branch. You can also reach for help about how to rebase or anything else in our [Discord chat server](https://discord.gg/c5DvZ4e).

**Comment by alexruffell** [comment]
@thecode Thank you! I got a bit lost as this is my first time and I don't know the lingo. Can I delete the branch and repository without causing trouble?

image

I'd like to start from scratch after watching some tutorials :)

**Comment by emlove** [comment]
> @thecode Thank you! I got a bit lost as this is my first time and I don't know the lingo. Can I delete the branch and repository without causing trouble?
> 
> I'd like to start from scratch after watching some tutorials :)

Yep! That branch belongs to your fork, and you can make a new one when you're ready.

**Pull request closed without merging**
