### PR TITLE
Update homekit_controller.markdown

### PR DESCRIPTION
**Pull request by schmuy**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by Jc2k — CHANGES_REQUESTED** [review]
It's worth documenting this but I think we should say more about what is needed.

**Comment by frenck** [comment]
@schmuy A small and friendly notification.

Are you planning on moving forward on this PR? 
I didn't see any activity recently, while there are still things to do. I hope you consider picking it up soon! 👍

../Frenck

**Comment by schmuy** [comment]
> @schmuy A small and friendly notification.
> 
> Are you planning on moving forward on this PR? I didn't see any activity recently, while there are still things to do. I hope you consider picking it up soon! 👍
> 
> ../Frenck

@frenck I'm really not familiar with GitHub and all the proper processes.  I also don't know the best place to include this documentation update.  It was submitted more as a suggestion to the developers to include something.  I won't be moving this forward myself.  Thanks

**Comment by frenck** [comment]
>  I won't be moving this forward myself. Thanks

Ok, in that case, it means this Pull Request won't be finished. I'll go ahead and close it for that reason.

../Frenck

**Pull request closed without merging**
