### PR TITLE
Doorbirdpy v2

### PR DESCRIPTION
**Pull request by Klikini**
**Description:**

Update for DoorBirdPy version 2.0.2.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#14933

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by arsaboo** [comment]
Can you please clean this PR to remove the unrelated commits.

**Comment by Klikini** [comment]
I tried rebasing from upstream/current but it's still dragging in all those commits. Do you know how else I could do it?

**Comment by arsaboo** [comment]
The PR should be against the `next` branch.

**Comment by arsaboo** [comment]
Rebase it against upstream/next.

**Comment by Klikini** [comment]
Whoops. Thank you!

**Review by frenck — APPROVED** [review]
Looks good to me!

Approved and can be merged as soon as the parent PR gets merged.

**Comment by Klikini** [comment]
Still waiting on the parent PR.

**Comment by WoLpH** [comment]
The pull request for the code has been merged but upon testing it I get the following error:
```
Invalid config for [doorbird]: required key not provided @ data['doorbird']['token']. Got None.
```

I assume that part of the documentation is still missing because I don't see it in this pull request either.

**Comment by arsaboo** [comment]
Merging as the parent is now merged :+1:

**Pull request merged**
