### PR TITLE
Adds new influxdb importer options

### PR DESCRIPTION
**Pull request by nhorvath**
Changes related to https://github.com/home-assistant/home-assistant/pull/15875

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
This PR targets an incorrect base. Since this PR has a parent PR and changes code, it should target the `next` branch, since it will be part of a next release.
Please rebase.

**Comment by nhorvath** [comment]
@frenck sorry about that... i rebased the PR

**Comment by frenck** [comment]
Thanks, @nhorvath! 👍

**Review by DubhAd — APPROVED** [review]
👍

**Comment by frenck** [comment]
Closing this PR, since the parent PR has been closed.

**Pull request closed without merging**
