### PR TITLE
Add Iliad Italy Documentation

### PR DESCRIPTION
**Pull request by eliseomartelli**
**Description:**
Adds Iliad Italy Documentation

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** https://github.com/home-assistant/home-assistant/pull/19645

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
@eliseomartelli This PR is fine! 👍 
Although, you should take a look at the attached logo. It is 250+ Kb, which is quite a lot! Maybe make it smaller and run it trough an image optimizer?

**Comment by eliseomartelli** [comment]
@frenck Now it's a lot smaller 👍 

Forgot to use an image optimizer :)

**Comment by eliseomartelli** [comment]
@frenck Fixed the size of the logo. It's under 3 Kb now.

**Comment by frenck** [comment]
Thanks, @eliseomartelli! 👍

**Review by frenck — DISMISSED** [review]

**Comment by frenck** [comment]
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

**Review by fabaff — APPROVED** [review]

**Pull request merged**
