### PR TITLE
add logo for coinmarketcap

### PR DESCRIPTION
**Pull request by fuga2136**
relates to #1071

### CODE REVIEW

**Comment by robbiet480** [comment]
Thanks! 🐬 🍪 💯

**Comment by fabaff** [comment]
This logo looks like the first hit on Google. @fuga2136 can you please point me to a Coinmarketcap page that is using this a logo? Thanks.

**Comment by fuga2136** [comment]
@fabaff 

While I don't have a link to one of their pages that is using that logo, the reason I felt it was valid is because Line 16 of their webpage source. This image is what is used when you link to their site via Facebook and Twitter (the most common Open Graph supporters)

Their favicon I didn't think was their actual logo otherwise I would have used that.

**Comment by fabaff** [comment]
I guess that they are using the Bitcoin logo because it's public domain and the most recognizable one of all currencies they support.

**Pull request merged**
