### PR TITLE
update swiss_hydrological_data docs

### PR DESCRIPTION
**Pull request by Bouni**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/49119
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Please rebase your branch to the `next` branch, that way you make sure that all additional unrelated commits disappear.

**Comment by Bouni** [comment]
@klaasnicolaas I rebased to upstream/next but I guess I messed something up!?
Can you help me figuring out what I did wrong?

**Comment by klaasnicolaas** [comment]
Looks like you were still on `current`, in this case I did the rebase for you now so that it's resolved.

**Review by klaasnicolaas — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged 👍

**Comment by Bouni** [comment]
> 
> 
> Looks like you were still on `current`, in this case I did the rebase for you now so that it's resolved.

Thanks for helping me out 👍🏽

**Review by fabaff — APPROVED** [review]

**Pull request merged**
