### PR TITLE
Add new topics for glossary

### PR DESCRIPTION
**Pull request by DanielXYZ2000**
Hass.io, HADashboard, Template, Zones,...

Issue: Improve glossary #3612

### CODE REVIEW

**Comment by DanielXYZ2000** [comment]
I'm new on github :-)
base branch should be current now
thx

**Comment by fabaff** [comment]
Can you please [rebase](https://home-assistant.io/developers/development_catching_up/) it?

**Comment by DanielXYZ2000** [comment]
oh - I see,  I'll try to rebase

**Comment by fabaff** [comment]
Included with 037f371.

**Pull request closed without merging**
