### PR TITLE
new lovelace config generator addition

### PR DESCRIPTION
**Pull request by skalavala**
**Description:**
Added a new section under Tools to generate lovelace script using Jinja2 script.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>
None

## Checklist:

- [Yes ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [Yes ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by Vasiley — APPROVED** [review]
Good Work as always

**Review by Vasiley — APPROVED** [review]

**Comment by MartinHjelmare** [comment]
Were all those commits included on purpose?

**Comment by balloob** [comment]
It's current -> next. Usually should be done in separate PR.  It's fine for this time but please make sure that PRs only contain the work as described

**Comment by frenck** [comment]
@MartinHjelmare @balloob 
I've already talked to the guys a couple of hours ago. (Which I should have documented, so that is my error).

**Comment by Vasiley** [comment]
My bad .... so sorry

**Pull request merged**
