### PR TITLE
Add cover document for EnOcean module

### PR DESCRIPTION
**Pull request by vincentsaluzzo**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#20815
## Checklist:

- [*] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [*] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by vincentsaluzzo** [comment]
**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#20815

**Comment by klaasnicolaas** [comment]
Pherhaps it is better to add the changes into the component page of EnOcean

**Review by frenck — CHANGES_REQUESTED** [review]
Please do not create a separate page for this but add it to the current existing page for this component.
Thanks 👍

**Comment by vincentsaluzzo** [comment]
Done @frenck

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by klaasnicolaas** [comment]
Parent PR still open

**Pull request closed without merging**
