### PR TITLE
Clarify title

### PR DESCRIPTION
**Pull request by tomlut**
Clarify title to prevent confusion like this: https://community.home-assistant.io/t/switch-rest-error-data-platform-got-none/184135/8

Also the title is now the same format as the RESTful Switch.

## Type of change

- [X] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
This will not work. The title is synced from the codebase and is inherited.
Change it here, will be undone automatically.

**Comment by tomlut** [comment]
It still needs changing as it is inconsistent and confusing people.

**Comment by frenck** [comment]
Honestly, it looks like 1 person right now.

But I agree is it less from ideal. The suggested change in this PR does not work. Feel free to merge the different platform pages into a single integrations page to solve this issue.

**Comment by tomlut** [comment]
That's a bit above my level of incompetence Frenk.

**Pull request closed without merging**
