### PR TITLE
Update energy gauge card images

### PR DESCRIPTION
**Pull request by TillFleisch**
## Proposed change

This PR updates the energy gauge card images to be in-line with recent changes.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
  - https://github.com/home-assistant/frontend/pull/14020
  - https://github.com/home-assistant/frontend/pull/17140
  - https://github.com/home-assistant/frontend/pull/17241
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @TillFleisch 👍 

../Frenck

**Review by frenck — CHANGES_REQUESTED** [review]
Wait, this PR contains changes from multiple parent PRs, but some of those are not merged yet. While this PR targets our current stable documentation?

I'm confused?

../Frenck

**Comment by TillFleisch** [comment]
So am I, I should have marked this PR as draft until the linked open PR has been processed. The PR which is still open only changes a single word within one of the images. I originally intended to only change one of the images - the one self-sufficiency one -, but saw that the other ones are also out-of-date. I did knot know if this should be one or multiple PRs.

The changes within the images are already currently released and part of HA, except for the missing word 'quota' in the self-sufficiency gauge. The 'quota' part of the image will be removed with the (currently) open PR.

Should I rebase this onto next and wait for the related PR to be closed?

**Comment by TillFleisch** [comment]
Since [the related PR](https://github.com/home-assistant/frontend/pull/17241) has been added to the  `2023.8 Beta` milestone, I have changed the base branch of this PR to `next`.

Sorry for the inconvenience :/

**Comment by frenck** [comment]
> Since [the related PR](https://github.com/home-assistant/frontend/pull/17241) has been added to the `2023.8 Beta` milestone, I have changed the base branch of this PR to `next`.
> 
> Sorry for the inconvenience :/

The milestone is not a factor in this. If the documentation PR has a parent PR in our code base, the documentation PR **always** need to target `next`. Milestones, patch releases, betas etc, are not a factor in that.

**Review by frenck — APPROVED** [review]
Thanks, @TillFleisch 👍 

../Frenck

**Pull request merged**
