### PR TITLE
Update Caddy Docs

### PR DESCRIPTION
**Pull request by ikifar2012**
Update Caddy Docs - add much needed improvements to the docs
I have rebased and fixed the issues with my previous pull request

### CODE REVIEW

**Comment by tjorim** [comment]
Previous PR here: https://github.com/home-assistant/home-assistant.io/pull/6813

**Comment by frenck** [comment]
So basically this is for users running manual type of installations? (`venv`)?

How about Hass.io or Docker users?

**Comment by ikifar2012** [comment]
> So basically this is for users running manual type of installations? (`venv`)?
> 
> How about Hass.io or Docker users?

havent looked into docker or hassio

**Comment by ikifar2012** [comment]
> So basically this is for users running manual type of installations? (`venv`)?
> 
> How about Hass.io or Docker users?

What should I add?

**Comment by frenck** [comment]
At this point, I'm actually unsure if we should add installation instructions for Caddy.
The problem with adding installation instructions for third-party programs and the many environments that Home Assistant provides/works with is a recipe for documentation hell.

Imaging all the components that involve third-party software providing installation instructions in the HA manual for each method... where does it end?

**Comment by frenck** [comment]
Closing this PR because of the above reasoning. Adding installation instructions for third-party application will be a beast to maintain.

**Pull request closed without merging**
