### PR TITLE
Allow templates for enabling automation triggers

### PR DESCRIPTION
**Pull request by farmio**
## Proposed change

Add documentation for template use in trigger disabling.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/114458
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by farmio** [comment]
The table of contents was auto-updated. I'm not sure if this should be this way, or if I shall revert it.

Also I'm not sure about the level of detail the example should have.

**Review by frenck — CHANGES_REQUESTED** [review]
Yeah that should be reverted @farmio.

../Frenck

**Comment by farmio** [comment]
Can we keep the one top-level item `[Disabling a trigger](#disabling-a-trigger)`, or should it be removed too?

**Comment by frenck** [comment]
It is not a normale page TOC, it is a list of triggers...

**Review by frenck — APPROVED** [review]
Thanks, @farmio 👍 

../Frenck

**Pull request merged**
