### PR TITLE
Pylontech us

### PR DESCRIPTION
**Pull request by danielschramm**
## Proposed change

Documentation for new integration to support Pylontech 48V battery packs for solar systems.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/74893
- Link to parent pull request in the Brands repository: not yet
- This PR fixes or closes issue: none

About the brands images I'm not sure how to handle image licensing correctly. Perhaps someone could support here.
Sample Link to logo used on the companies website: https://en.pylontech.com.cn/images/logo.png

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].
- [x] New file no changes to existing doc. Branch was derived from current.

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @gobanza, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#23361).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by homeassistant** [comment]
Hi @gobanza, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#23361).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by homeassistant** [comment]
Hi @gobanza, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#23361).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
There are unrelated commits in this PR

CleanShot 2022-07-13 at 20 52 56

Probably caused by basing this branch on the `current` branch instead of the `next` branch. Please git rebase your commits onto the `next` branch to clean it up.

Thanks 👍 

../Frenck

**Comment by homeassistant** [comment]
Hi @gobanza, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#23361).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by homeassistant** [comment]
Hi @gobanza, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#23361).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by danielschramm** [comment]
Hello @frenck,
I have some Issues rebasing the Branch behind this Pull.
I will close this Pull and make a new one.
Thanks,
Daniel

**Pull request closed without merging**
