### PR TITLE
guide for asuswrt to use the rt-n56u project, Padavan custom firmware

### PR DESCRIPTION
**Pull request by orrpan**
**Description:** Guide for making it possible to use asuswrt device tracker on the rt-n56u project, as the only difference is where the `dnsmasq.leases` is stored. 
`asuswrt`: /var/lib/misc/dnsmasq.leases
`the rt-n56u project` (currently): /tmp/dnsmasq.leases

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
I'm not sure if we should add such specific documentation (which essentially is a "hack" to make it work). @fabaff, what do you think?

**Comment by DubhAd** [comment]
IMO a separate component, or an update to the existing component with a configuration option, would be the right way to do this. That said, I personally have no objection to simple "hacks" like this.

**Comment by fabaff** [comment]
I agree with @DubhAd that the proper way would be to extent the `asuswrt` tracker. Till then we should add those details.

**Comment by fabaff** [comment]
Hmm, the branch is gone. I will fix it manually.

**Comment by klaasnicolaas** [comment]
Did a merge so the file is now gone 😉

**Comment by fabaff** [comment]
Was added with https://github.com/home-assistant/home-assistant.io/commit/d3160f40ad0838b007b05c9cefe96aebd8959506

**Pull request closed without merging**
