### PR TITLE
Add additional notes and examples to the camera integration docs

### PR DESCRIPTION
**Pull request by rroller**
## Proposed change
I've noticed people struggling to find the right way to configure the camera integration and often don't realize which options are available. This PR adds additional example configuration with links to camera platforms to help tip people off to the available options.

## Type of change
- [x ] Spelling, grammar or other readability improvements (`current` branch).
- [x ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information
- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist
- [x ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by rroller** [comment]
@frenck FYI

**Comment by frenck** [comment]
Thanks for the PR @rroller 

However, the documentation examples provided belong to the specific integrations,  and not in this part of the documentation.

It is really hard to track/keep them updated if they are spread across the documentation. For example, the ONVIF example provided, isn't valid in 0.110.

Therefore, I'm closing this PR.

**Comment by rroller** [comment]
Ok. What about links to some of the specific integrations? Anything. Something. Will help people discover this stuff. I’ll go and update each integration with proper examples of not there. @frenck

**Comment by frenck** [comment]
I'm not sure what you are aiming/looking for. If you go to our integrations and select the camera category, it would show all, right?

**Pull request closed without merging**
