### PR TITLE
Add fan and lights support to Balboa Spa integration docs

### PR DESCRIPTION
**Pull request by snoack**
## Proposed change

Updating documentation for new features added in home-assistant/core#111245 and home-assistant/core#111252.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by jpbede** [comment]
Reopend this as there are two PRs in core referring this

**Comment by c0ffeeca7** [comment]
I think both fan and light would need to be added to the platform and category in the header.
image

**Comment by snoack** [comment]
Done.

**Comment by klaasnicolaas** [comment]
Platforms still missing in the `ha_category` header meta

**Comment by snoack** [comment]
Damn it, there you go.

**Review by klaasnicolaas — APPROVED** [review]

**Pull request merged**
