### PR TITLE
Automation: Documentation for hiding automation entities

### PR DESCRIPTION
**Pull request by milaq**
Documentation for https://github.com/home-assistant/home-assistant/pull/3442

### CODE REVIEW

**Comment by Landrash** [comment]
One small comment. Should it be mentioned that they are grouped in the Automation group by default?
With that exception, looks good!

**Comment by milaq** [comment]
I could add a remark about that.
Should I also mention that the group itself can only be hidden as a whole when all automation entities are hidden explicitly?

**Comment by robbiet480** [comment]
@Landrash

**Comment by milaq** [comment]
fixex via 4adaa72d8c0627977b669eb92d21c6ab1bb7713d

**Pull request closed without merging**
