### PR TITLE
Add documentation for Onkyo media player zone 3

### PR DESCRIPTION
**Pull request by snikch**
**Description:**

Adds docs for Onkyo Media Player Zone 3

home-assistant/home-assistant#14295

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by frenck** [comment]
Needs to be rebased. Will take care of that.

**Comment by frenck** [comment]
Rebased. Can be merged as soon as the build passes.

**Review by frenck — APPROVED** [review]

**Review by frenck — APPROVED** [review]

**Comment by snikch** [comment]
Ah shit - I forgot about this PR sorry. @balloob asked me to make some changes in the way we detect zones so this no longer makes sense. I'll create a new PR to bring it in line with the functionality.

**Comment by frenck** [comment]
Hmmm @snikch I can revert this one if you'd like?

**Comment by snikch** [comment]
@frenck Might be easiest just to merge #5383 unless you're worried about the commit history?

**Pull request merged**
