### PR TITLE
Add documentation for Ring Intercom

### PR DESCRIPTION
**Pull request by cosimomeli**
## Proposed change

Add documentation for Ring Intercom and the added button platform to the Ring integration.

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/113514
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by c0ffeeca7** [comment]
I see that the parent has been merged. Are you still working on the docs? Or are they ready for review, @cosimomeli? Asking because the PR is marked as *draft*.

**Comment by cosimomeli** [comment]
The original PR has been split in 2, as this documentation is about the new platform moved to the second PR, I just changed the parent PR

**Comment by joostlek** [comment]
Second PR is approved and will be merged, so this can be reviewed in full :)

**Review by c0ffeeca7 — APPROVED** [review]
Thank you, @cosimomeli and @joostlek :+1:

**Pull request merged**
