### PR TITLE
add document for fan template

### PR DESCRIPTION
**Pull request by giangvo**
**Description:**
Add document for template fans.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant/pull/12027)

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by giangvo** [comment]
@frenck @balloob please review.
Thanks

**Review by balloob — APPROVED** [review]

**Comment by balloob** [comment]
This PR broke the build, I reverted the docs.

**Comment by balloob** [comment]
Please fix it and submit again

**Comment by balloob** [comment]
Found it, missed a `"` in the yaml e9aad88641

**Comment by balloob** [comment]
Please in the future test your branches 🤔

**Comment by balloob** [comment]
And another missing quotes too that caused invalid yaml 3ca0be1d3f

**Comment by giangvo** [comment]
@balloob, I am sorry about that. I though we have branch build. Noted and will check my branch next time. Have u fixed the template?

**Comment by balloob** [comment]
It's fixed now 👍 . Somehow the test on this branch passed but then failed once they hit the main repo. That should have caught it normally.

**Comment by giangvo** [comment]
👍Thank you!

**Comment by jeradM** [comment]
@balloob I'm not seeing this fix in `next` and my local build is broken after rebasing. Should it be there already?

**Comment by balloob** [comment]
I put the fix in the rc branch, let me push that up to the next branch too

**Comment by jeradM** [comment]
:+1: thanks!

**Pull request merged**
