### PR TITLE
add mention of new ZoneMinder run state sensor and set_run_state service

### PR DESCRIPTION
**Pull request by jantman**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** https://github.com/home-assistant/home-assistant/pull/15324

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by jantman** [comment]
Closing for now... parent PR is being reworked; will likely reopen when ready. See https://github.com/home-assistant/home-assistant/pull/15281#issuecomment-402680303

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
✅ Approved. Can be merged as soon as the parent PR get merged.

The build seemed stuck, fixed that by pushing an empty commit to re-trigger the build process.

**Comment by jantman** [comment]
@frenck thanks so much for looking at this. Unfortunately it seems as though the parent may end up getting closed. I'll keep this PR in the same state as the parent.

**Comment by frenck** [comment]
Closing this PR, since the parent PR has been closed as well.

**Pull request closed without merging**
