### PR TITLE
ZHA move pairing best practices to troubleshooting

### PR DESCRIPTION
**Pull request by Hedda**
## Proposed change

Moving the section about best practices pairing to be under the troubleshooting section as a readability improvement.

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by c0ffeeca7** [comment]
@Hedda: Why do you think the section about best practices on pairing is better placed further back? 
Right now, it is right after the section on adding devices. For me, this is when I run into those pairing issues. For me, it makes sense to keep those two sections together. But maybe I'm missing something.

**Comment by Hedda** [comment]
> Why do you think the section about best practices on pairing is better placed further back?
...
> For me, it makes sense to keep those two sections together.

@c0ffeeca7 I think that it would be best to try to collect all segments directly related to troubleshooting to be under that section:

https://www.home-assistant.io/integrations/zha#troubleshooting

PS: For reference, it was I that originally wrote the best practices section as well as most segments under troubleshooting.

**Comment by c0ffeeca7** [comment]
> @c0ffeeca7 I think that it would be best to try to collect all segments directly related to troubleshooting to be under that section:
> 
> https://www.home-assistant.io/integrations/zha#troubleshooting

I see your point about keeping troubleshooting information together in one place. Do you think it could be helpful to have a link in the _adding devices_ section pointing to the _pairing best practices?

**Review by c0ffeeca7 — APPROVED** [review]
LGTM, @Hedda :+1:

**Comment by Hedda** [comment]
> Do you think it could be helpful to have a link in the _adding devices_ section pointing to the _pairing best practices?

@c0ffeeca7 Yes I think that would be a good idea. I believe there are also other sections that could do with such links to other sections in troubleshooting.

**Pull request merged**
