### PR TITLE
Daikin documentation for 0.91

### PR DESCRIPTION
**Pull request by fredrike**
**Description:**

The Daikin documentation in the **next** branch contains merge conflicts (#9133), this fixes that. 

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
uuh this feels weird, let me check what happened here.

**Comment by frenck** [comment]
See issue you've raised for more details: #9133

IMHO, we should not merge this, and cherry-pick #9033 to `current` instead.

**Comment by fredrike** [comment]
e28e665 is the cherry pick of #9033 and 0592602 is a better rewrite considering the changes in 17707ae65 (#9100).

**Comment by fredrike** [comment]
@frenck, What is the status on this? As far as I see is #9033 not merged to current.

**Review by klaasnicolaas — DISMISSED** [review]

**Review by klaasnicolaas — APPROVED** [review]

**Pull request merged**
