### PR TITLE
Adds support for Gitpod.io

### PR DESCRIPTION
**Pull request by frenck**
**Description:**

This PR adds support for using Gitpod.io with the Home Assistant documentation.

This PR can be reviewed using Gitpod as well 😉 

[image](https://gitpod.io/#https://github.com/home-assistant/home-assistant.io/pull/9727)

<https://gitpod.io/#https://github.com/home-assistant/home-assistant.io/pull/9727>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
@balloob Added you as a reviewer since ideally, the Gitpod GitHub app should be installed on our org (free for open source). That makes it pre-build the working environments, allowing people to jump in quick.

**Review by balloob — APPROVED** [review]

**Comment by balloob** [comment]
Looks like I can't install the open source plan: "The plan you have selected can only be purchased by a personal account. Please select a different billing account or plan. "

image

**Comment by balloob** [comment]
I'll leave them a message.

**Comment by meysholdt** [comment]
hi @balloob! I received the message. It should work to install the GitPod App with the free open-source plan on this repo via the App-Listing: https://github.com/apps/gitpod-io/. Please note that this is a different URL than the market place. It's a known issue (https://github.com/gitpod-io/gitpod/issues/454). I'm sorry for the confusion.

**Comment by frenck** [comment]
Thanks, @meysholdt! 👍

**Pull request merged**
