### PR TITLE
Update Sense component to include devices monitored condition

### PR DESCRIPTION
**Pull request by kylekampy**
**Description:**
Hello! I'm attempting to extend the existing Sense component to include current power usage for individual detected devices from Sense. This PR cleans up and extends the existing documentation for the new devices monitored condition, as well as updates the Sense logo to a higher resolution version.

This is my first set of PRs against the home-assistant project, so any constructive criticisms are greatly appreciated!

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#13077

## Checklist:

- [X] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [X] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by frenck** [comment]
Rebased the PR in order to fix the build issues.

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Thanks, @kkamperschroer! Nice first-time contribution to the documentation 🏆 

Approved and can be merged as soon as the parent PR gets merged in.

**Comment by kylekampy** [comment]
Sorry about that. I'll get this rebased and work on getting my changes fixed in the parent PR so it all can be merged.

**Comment by frenck** [comment]
Closing this PR, since the parent PR has been closed as well.
Feel free to re-open when ready.

bitmoji

**Pull request closed without merging**
