### PR TITLE
Minor spelling corrections #1052

### PR DESCRIPTION
**Pull request by anchepiece**

### CODE REVIEW

**Comment by fabaff** [comment]
Can you point your Pull Requests to **current**?

**Comment by anchepiece** [comment]
@fabaff Ok repointed next to current. Looks like there is a necessary merge.

**Comment by fabaff** [comment]
I tried to change the branch here too. Can you do a rebase should help?

**Comment by Landrash** [comment]
It's most likely easiest for you to get a clean copy of the repo and reapply your changes.

**Comment by robbiet480** [comment]
This PR will need to be entirely recreated. Make the changes directly off the current branch and resubmit. Thanks!

**Pull request closed without merging**
