### PR TITLE
Add HADashboard docs to ecosystem

### PR DESCRIPTION
**Pull request by acockburn**
Addition of HADasboard docs to ecosystem.

### CODE REVIEW

**Comment by Landrash** [comment]
I'll happily review this when you feel it's "done" @acockburn and you want it published.

**Comment by acockburn** [comment]
It's mostly cut and paste of the existing docs so should be good to go - not that it wouldn't benefit from another pair of eyes - thanks!

**Comment by acockburn** [comment]
@landrash - do I need to do anything more at this point?

**Comment by Landrash** [comment]
Sorry no. Just life got in the way. My SO is away this evening and I got a
few hours planed for Home Assistant.

**Comment by Landrash** [comment]
Ok, finally looked over it and it can be merged since there's no major changes that would be necessary. 
If your ok with it I'll cleanup the formatting bit before merging.

**Comment by Landrash** [comment]
Merging and cleaning up formatting after.

**Pull request merged**
