### PR TITLE
Update nfandroidtv.markdown

### PR DESCRIPTION
**Pull request by redahb**
Updated documentation for updates to the nfandroidtv component.

## Proposed change

This change should be used if pull request 60159 gets merged into the HA code, as it provides updated documentation for the Notifications for Android TV component.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/60159
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This PR is based on the `current` branch as the base, which causes all the unrelated commits to show up. Please git rebase your changes onto the `next` branch.

**Comment by redahb** [comment]
OK I am sorry for being a noob but I have absolutely no idea how to rebase this. I clicked the 'Edit' on the documentation page at home-assistant.io, created the pull request (there was no mess of commits then), after which the probot asked me to target the 'next' branch so I did (on github.com).

I did not clone anything to local, and according to my limited understanding and Google that's the only way to 'rebase'? I simply followed the instructions home-assistant.io and github.com provided me.

Should I close this PR and start from scratch with a local clone instead of using the online editor? Not asking for tech support here, just wondering what the 'right' thing to do is now.

**Comment by frenck** [comment]
I've rebased PR on top of the `next` branch.

**Review by frenck — APPROVED** [review]
Thanks, @redahb 👍

**Pull request merged**
