### PR TITLE
Added Virgin Media's Hub 3 a UK variant of Router

### PR DESCRIPTION
**Pull request by phillprice**
## Proposed change
In the UK this router is provided by Virgin Media as the Hub 3.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by phillprice** [comment]
I'm unable to rebase against current as the integration isn't live yet.

**Review by frenck — CHANGES_REQUESTED** [review]
This PR must be done against the `next` branch.

**Comment by klaasnicolaas** [comment]
Is there already a parent PR in the core repo?

**Comment by phillprice** [comment]
https://github.com/home-assistant/core/pull/30972 is the original PR - this extends Documentation for a use case in the UK

**Review by frenck — APPROVED** [review]
Thanks, @phillprice! 👍

**Pull request merged**
