### PR TITLE
Update for precipitation instructions

### PR DESCRIPTION
**Pull request by endor-force**
**Description:**
Added precipitation type as possible object in sensor component.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#15935

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by frenck** [comment]
Hi there @endor-force!

This PR has a parent PR in our code base, and should, therefore, target the `next` branch. Please update the target branch of this PR and rebase if needed.

Thanks!

**Comment by endor-force** [comment]
@frenck Thanks, changed to next branch, not sure how to verify if rebase is needed, does it look ok like this or what should i look for?

**Comment by frenck** [comment]
Well @endor-force, there are commits in your PR that are not yours.
So yeah, you'll need to rebase to clean that up.

**Comment by endor-force** [comment]
Unable to rebase, probably due to incompetence from my side. New PR 6006 created to next branch accordingly.

**Pull request closed without merging**
