### PR TITLE
Xiaomi Miio: convert tables to lists to improve readability and display on mobile

### PR DESCRIPTION
**Pull request by c0ffeeca7**
## Proposed change

Xiaomi Miio: convert first tables to list to improve readability and mobile
- more tables to follow in separate PR

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

## Summary by CodeRabbit

- **Documentation**
	- Enhanced structure and clarity of the Xiaomi Miio integration documentation.
	- Reformatted supported devices and subdevices sections into bullet-point lists for improved readability.
	- Updated troubleshooting section with comprehensive explanations for common issues.
	- Consolidated and clarified device actions for better user comprehension.

### CODE REVIEW

**Comment by rytilahti** [comment]
I'm fine with cleaning up the tables, but I think most of the cases they could be removed altogether as they are not that useful. I had a PR at some point to clean up the docs accordingly, but it went stale. Perhaps worth revisiting?

**Comment by frenck** [comment]
> I had a PR at some point to clean up the docs accordingly, but it went stale. Perhaps worth revisiting?

The goal is not fully revisiting, but more about fixing the tables & combining all platform pages. More improvements are always welcome, but let's try to avoid making a big bang overhaul and instead see if we can approach this iteratively.

../Frenck

**Review by rytilahti — DISMISSED** [review]
Sure thing, LGTM and thanks a lot!

**Comment by c0ffeeca7** [comment]
> **Actionable comments posted: 0**
> 
> 🧹 Outside diff range and nitpick comments (7)
> 📜 Review details

For future reviews, please don't suggest to convert lists into tables.

**Review by frenck — APPROVED** [review]

**Pull request merged**
