### PR TITLE
Add support for glob matching in InfluxDB filters

### PR DESCRIPTION
**Pull request by mdegat01**
## Proposed change

Doc change to correspond with new feature PR https://github.com/home-assistant/core/pull/37069 . 

GLOB filtering support was added to all other recorder-like integrations in https://github.com/home-assistant/core/pull/36913 . Influx was skipped because it was not using the shared filtering logic and thus required a separate update. In addition updating Influx to use the shared filtering logic causes a breaking change as its logic for filtering is different then all the others (details of this breaking change on the implementation PR). Intent is to make influx consistent with the other recorder-like integrations and add the new glob filtering capability.

Also while doing this work I discovered that you cannot have an Influx sensor without also having the Influx history component. That wasn't clear from the documentation since it looks like you could have sensors on an external Influx database without having HA report any state changes to it. I added a note to make it clear that you do need both with instructions on what to do if you really don't want HA to write anything to your influx DB.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/37069
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @mdegat01 👍

**Comment by mdegat01** [comment]
@frenck It looks like this PR was moved to the "Awaiting Parent PR" column. Just an FYI, the parent implementation PR was already merged. So this isn't awaiting anything any more.

**Comment by frenck** [comment]
It has the `parent-merged` label. Please be patient. Thanks.

**Comment by mdegat01** [comment]
Np, take your time. I just saw the automation moved it so wanted to make sure it wasn't miscategorized.  And thanks for the review!

**Pull request merged**
