### PR TITLE
Add Alarm Control Panel to secure devices

### PR DESCRIPTION
**Pull request by engrbm87**
**Description:**

**Pull request in home-assistant (if applicable): [home-assistant/home-assistant/#26249](https://github.com/home-assistant/home-assistant/pull/26249)**

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
There are a lot of unrelated commits in this PR

**Comment by engrbm87** [comment]
I wanted to add this to the next branch as it is a new feature in the google assistant. what do you recommend to fix this PR?

**Comment by engrbm87** [comment]
I made a new PR again next branch with my commit only. i will close this one.

**Comment by klaasnicolaas** [comment]
I think you made the branch before we dit a massive merge for the 0.98 release 😉 Just pull the latest changes from the upstream repo and I think the commits will be gone.

**Pull request closed without merging**
