### PR TITLE
Add button.start_mycar_charging documentation for Nissan Leaf

### PR DESCRIPTION
**Pull request by filcole**
## Proposed change

Document the new button to start a car charging.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [X] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:  https://github.com/home-assistant/core/pull/62948
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by filcole** [comment]
Incorporated changes by @bwduncan  apart from update button) in https://github.com/home-assistant/home-assistant.io/pull/20463/files

**Comment by klaasnicolaas** [comment]
I don't think the `package-json.lock` is meant to be removed 🤔

**Comment by filcole** [comment]
> I don't think the `package-json.lock` is meant to be removed 🤔

Fixed. Thank you!

**Review by frenck — APPROVED** [review]
Thanks, @filcole 👍

**Pull request merged**
