### PR TITLE
Update dynalite.markdown

### PR DESCRIPTION
**Pull request by ziv1234**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/home-assistant/pull/32075
- This PR fixes or closes issue:

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
What is the parent PR in our codebase?

**Comment by ziv1234** [comment]
I still didn’t create it. My previous PR was reviewed and approved, so it should be merged today and then I will create the code PR. Just wanted to get a head start on the documentation. I did it online but it is failing the test so want to fix it quickly

**Comment by ziv1234** [comment]
@klaasnicolaas
klaasnicolaas, i accidentally overwrote your changes. Will reimplement them. sorry

**Comment by ziv1234** [comment]
ok. my previous PR was merged so I was able to now create a code PR for this one. hopefully everything is there that is needed for a review, but if not, please let me know what to add

**Comment by ziv1234** [comment]
closing since I am splitting the original PR into parts

**Pull request closed without merging**
