### PR TITLE
Document Climate Services

### PR DESCRIPTION
**Pull request by philhawthorne**
Adds documentation for all the services exposed by the new Climate
platform.

Based on the cover platform documentation.

### CODE REVIEW

**Comment by philhawthorne** [comment]
@Landrash thank you kind sir :)

**Comment by Landrash** [comment]
@philhawthorne Are the changes live in the 0.30 version? If so we should merge this into the `current` branch instead and get it published asap.

**Comment by philhawthorne** [comment]
@Landrash I believe so, the `climate` service was added in 0.27 I think.

Let me know if I need to open a new PR for this or can just rebase this PR

**Comment by Landrash** [comment]
Looks like I can't move it over to the current branch so if you would be so kind to rebase this I'll merge it in.

**Comment by philhawthorne** [comment]
No problem

**Pull request closed without merging**
