### PR TITLE
Update media_player.samsungtv.markdown

### PR DESCRIPTION
**Pull request by mlebrun**
Display how to change channels (or at least simulate numeric keypresses) as well as remove reference to old issue.

https://github.com/home-assistant/home-assistant/pull/14451

### CODE REVIEW

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
The documentation looks fine @mlebrun! Nice first-time contribution to the documentation project btw 👍 

Can be merged as soon as the parent PR gets merged.

**Comment by mlebrun** [comment]
Thank you @frenck ! Hoping to contribute more as I find more things of my skill-level to contribute. If you find some easier tickets or anything you'd like to pass my way, I'd be happy to take a look!

**Comment by frenck** [comment]
Since the parent PR has been merged, I'll go ahead and merge this one in as well.

Thanks again @mlebrun! 🥇
I'll enjoy this feature myself since I own these Samsung TVs...
Makes me very happy 😁

**Comment by mlebrun** [comment]
@frenck awesome! that makes me happy! the beauty of OSS! and makes me want to contribute even more features!

**Pull request merged**
