### PR TITLE
Update Discovery integration docs

### PR DESCRIPTION
**Pull request by milanmeu**
## Proposed change

- Remove migrated services/integrations
- Add missing LG Soundbars integration
- Remove zeroconf note
  - Integrations list is incomplete
  - This note also applies to mDNS and UPnP
  - Does not add useful information for Discovery integration users.
- Remove DSM/Synology section
  - Synology users now use Docker instead of the SynoCommunity package
- Update page description
- Update configuration.yaml example

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by MartinHjelmare — DISMISSED** [review]
Looks good!

**Comment by MartinHjelmare** [comment]
Some of the changes, eg to Netgear router, is not released yet though?

**Comment by milanmeu** [comment]
> Some of the changes, eg to Netgear router, is not released yet though?

Yes, Netgear should be removed in the `next` branch.

**Review by MartinHjelmare — APPROVED** [review]
Thanks!

**Comment by milanmeu** [comment]
The removed integrations are migrated except for Yeelight Sunflower bulb.
I couldn't find Yeelight Sunflouwer bulb in the discovery source code.

**Comment by MartinHjelmare** [comment]
It's this, right? 
https://github.com/home-assistant/core/blob/20ddd092f67cb83b18189b90ac371993ed9cc0a3/homeassistant/components/discovery/__init__.py#L88

**Comment by milanmeu** [comment]
The [Yeelight Sunflower docs](https://www.home-assistant.io/integrations/yeelightsunflower):
> The Yeelight Sunflower hub supports SSDP discovery, but that has not been built into the platform. Let the developer know if that would be helpful to you. 

This indicates that discovery is not supported.

---

> It's this, right?
> https://github.com/home-assistant/core/blob/20ddd092f67cb83b18189b90ac371993ed9cc0a3/homeassistant/components/discovery/__init__.py#L88

:confused: It could be for the `yeelight` integration.

---

Discovery integration docs:
> Valid values for ignore are:
>  - `yeelight`: Yeelight lamps and bulbs (not only Yeelight Sunflower bulb)

---

**I think** netdisco `yeelight` in discovery is used for all yeelight blubs. However, there are 2 yeelight integrations, both use netdisco `yeelight`. The yeelight integration migrated and sunflower was never supported.

Neither are currently supported so yeelight/sunflower should be removed.

**Comment by MartinHjelmare** [comment]
Yeah, the yeelight sunflower integration doesn't support discovery.

I didn't remember that we had two yeelight integrations. 😄

**Pull request merged**
