### PR TITLE
Add sony songpal docs

### PR DESCRIPTION
**Pull request by rytilahti**
**Description:**
Add documentation for Sony Songpal platform.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):**
https://github.com/home-assistant/home-assistant/pull/12143

## Checklist:

- [X] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [X] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by rytilahti** [comment]
The code part of this got just merged, so it would be nice if someone would review this, too :-)

**Comment by c727** [comment]
I don't understand why travis fails here...

**Comment by balloob** [comment]
@c727 invalid syntax was used for the linkable title 
9a84d72

**Comment by rytilahti** [comment]
Sorry for not noticing that before, thanks balloob for the fix!

**Pull request merged**
