### PR TITLE
Add documentation on using credstash as a secret store

### PR DESCRIPTION
**Pull request by justin8**
**Description:** Add documentation for [credstash support](https://github.com/home-assistant/home-assistant/pull/8494)

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#8494

### CODE REVIEW

**Comment by Landrash** [comment]
I think this would be better suited for the [ecosystem](https://home-assistant.io/docs/ecosystem/) to avoid diluting the documentation with non base functionality?

**Comment by justin8** [comment]
It appears that ecosystem is for functionality that is outside of core.

This works similar to keyring support for secrets, which is in core and in the paragraph above this documentation.

**Comment by fabaff** [comment]
I guess that sooner or later we need to create a section for the [scripts](https://home-assistant.io/docs/tools/scripts/). I would be fine if we place it inside the "Storing Secrets" docs for now and move the keyring and the credstash later.

**Comment by justin8** [comment]
+1 for that. It needs some cleanup, but that should be a separate CR. Right now it places it with the most logically similar information

**Comment by Landrash** [comment]
Agree wth fabaff. Merging as is and in the future this might get moved,

**Comment by MartinHjelmare** [comment]
The parent PR is not merged yet.

**Comment by Landrash** [comment]
My mistake, sorry about that.

**Comment by balloob** [comment]
About to merge it, will revert the revert 👍

**Pull request merged**
