### PR TITLE
Updated documentation for SABnzbd.

### PR DESCRIPTION
**Pull request by jeradM**
**Description:**
Updated documentation for sensor.sabnzbd to reflect that it has been moved to a component with additional configuration options and services.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#12915

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by frenck** [comment]
Rebased the PR in order to fix the build

**Review by frenck — DISMISSED** [review]

**Comment by frenck** [comment]
Thanks, @jeradM! 🥇 

Can be merged as soon as the parent PR gets merged.

**Review by frenck — APPROVED** [review]

**Review by frenck — CHANGES_REQUESTED** [review]
Hey @jeradM,
Sorry m8, but some merged conflict appeared out of nowhere. 
Could you please take a look and resolve those? 👍

**Comment by jeradM** [comment]
Yep no problem. It looks like #4942 modified the old documentation

**Comment by jeradM** [comment]
Rebased next branch. Merge conflicts should be resolved now

**Comment by MartinHjelmare** [comment]
There is still a merge conflict. The sensor page should not be removed, just streamlined and link to the component page, saying it's required to set up sensors.

**Comment by jeradM** [comment]
Ah it was a new merge conflict from #5230. Should be good to go now. I updated ha_release to 0.69, but I'm wondering, since this is a breaking change, should it wait until 0.70 so it makes it into an early beta?

**Comment by MartinHjelmare** [comment]
Yeah, this will not go out in 0.69 but 0.70.

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Thank you for this @jeradM.
I'll go ahead and merge this one in.

**Pull request merged**
