### PR TITLE
HomeSeer partnership announcement blog post

### PR DESCRIPTION
**Pull request by b-uwe**
## Proposed change

Announce the HomeSeer partnership in a blog post

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/home-assistant.io/pull/26757 which follows https://github.com/home-assistant/core/pull/90066
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/4250 & https://github.com/home-assistant/brands/pull/4252
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by frenck** [comment]
Marking as draft to prevent accidental merge (as it is dated in the future).

**Review by frenck — CHANGES_REQUESTED** [review]
Content looks good, the PR is, however, targeting an incorrect branch.

This PR should target the `current` branch, as it is just a blog post that is being put out (not directly bound to a HA release).

../Frenck

**Comment by b-uwe** [comment]
@frenck I oriented on https://github.com/home-assistant/home-assistant.io/pull/26415 which also targeted `next`. Was that wrong back then as well or did you do some magic at that time that I can't perceive today?

On a different note, the way I get it it's comparably safe to merge **beforehand** (accidentally or not) because the blog post will not be visible until the date given.

**Comment by frenck** [comment]
> @frenck I oriented on https://github.com/home-assistant/home-assistant.io/pull/26415 which also targeted next.

Yes, but that is related to a change in the code base and is release together (core + docs at the same time). This blog post isn't.

> On a different note, the way I get it it's comparably safe to merge beforehand (accidentally or not) because the blog post will not be visible until the date given.

That doesn't work like that, we have a static site generator... meaning everything you see is generated at build time. The post thus, will only show up when built after that date.

**Comment by b-uwe** [comment]
I will start over! That's quicker and easier!

**Pull request closed without merging**
