### PR TITLE
Add Energyzero get_gas_prices and get_energy_price services

### PR DESCRIPTION
**Pull request by iamrgroot**
## Proposed change

Docs of new Energyzero services that expose the energy and gas prices

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/101374
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Did you already have a modified version of the template sensor?

**Comment by c0ffeeca7** [comment]
klaasnicolaas pointed out that much of the content is identical to the Services description of the easyEnergy integration. So I took the liberty of adding an include.

**Comment by iamrgroot** [comment]
> klaasnicolaas pointed out that much of the content is identical to the Services description of the easyEnergy integration. So I took the liberty of adding an include.

@c0ffeeca7 EnergyZero does not have the `get_energy_return_prices` and `get_energy_usage_prices` services but 1 `get_energy_prices`. Can you make it variable?

**Comment by c0ffeeca7** [comment]
> > klaasnicolaas pointed out that much of the content is identical to the Services description of the easyEnergy integration. So I took the liberty of adding an include.
> 
> @c0ffeeca7 EnergyZero does not have the `get_energy_return_prices` service. Can you make it variable so EnergyZero does not get it?

right. Thank you for the catch, @iamrgroot

**Comment by c0ffeeca7** [comment]
> > klaasnicolaas pointed out that much of the content is identical to the Services description of the easyEnergy integration. So I took the liberty of adding an include.
> 
> @c0ffeeca7 EnergyZero does not have the `get_energy_return_prices` and `get_energy_usage_prices` services but 1 `get_energy_prices`. Can you make it variable?

reverted the reuse commit and aligned the wording with what is used in the easyEnergy integration. Does it look correct to you now, @iamrgroot?

**Comment by iamrgroot** [comment]
@c0ffeeca7  I've set the incl_vat option to required. Looks good to me now!

**Comment by c0ffeeca7** [comment]
> @c0ffeeca7 I've set the incl_vat option to required. Looks good to me now!

Thank you for bearing with me.

**Review by c0ffeeca7 — APPROVED** [review]
Thank you, @iamrgroot :+1:

**Pull request merged**
