### PR TITLE
Add homekit television

### PR DESCRIPTION
**Pull request by adrum**
**Description:**

CC: @cdce8p 

This adds the ability to expose `media_player` entities as Television types in HomeKit. This is an opt-in feature, requiring users with devices iOS 12.2 or later to change the `media_player` entity's `device_class: tv`.

I plan to add the ability to link a `remote` later on for additional functionality. 

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#22968

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by albertleal — DISMISSED** [review]

**Review by cdce8p — CHANGES_REQUESTED** [review]
Just a note to other reviewers that this PR still needs to be updated to reflect the changes made in the parent PR once those are finalized.

**Comment by cdce8p** [comment]
Should we include a note that this feature requires `iOS 12.2`?

**Comment by klaasnicolaas** [comment]
@cdce8p I would add that, avoids confusion.

**Comment by cdce8p** [comment]
I really like the changes you've done here. If you don't want to add anything else, I think this would be good to go.

**Review by cdce8p — APPROVED** [review]

**Pull request merged**
