### PR TITLE
Create switchbee.markdown

### PR DESCRIPTION
**Pull request by jafar-atili**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by frenck** [comment]
I think there is a parent PR missing?

**Comment by thecode** [comment]
This is the parent PR: https://github.com/home-assistant/core/pull/70201
However this should be targeted and rebased to `next` branch

**Comment by jafar-atili** [comment]
I made this PR to be a draft because I want to pull it and make changes to it on the devcontainer (this was edited directly on github).

So I pull this patch set and push another commit?

**Comment by thecode** [comment]
> I want made this PR to be a draft because I want to pull it and make changes to it on the devcontainer (this was edited directly on github).
> 
> So I pull this patch set and push another commit?

Since it is targeted to `current` branch the easiest way would be to save this file locally, close this PR, make sure you create a branch starting from `next` branch and create a new PR.

**Pull request closed without merging**
