### PR TITLE
Rewrite myuplink page to align with new quality scale

### PR DESCRIPTION
**Pull request by astrandb**
## Proposed change

This is the first step towards the ultimate goal of platinum quality.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

## Summary by CodeRabbit

- **Documentation**
	- Significantly revised the myUplink integration documentation for enhanced clarity on functionality, including information retrieval and control of heat-pump devices.
	- Added notes on the requirement of a valid subscription for controlling equipment and clarified terminology in prerequisites.
	- Introduced new sections for data updates, troubleshooting, and expanded known limitations for improved user guidance.

### CODE REVIEW

**Comment by astrandb** [comment]
CI error related to homewizard

**Comment by klaasnicolaas** [comment]
These changes could also be made in the `current` branch.

./Klaas

**Comment by astrandb** [comment]
@klaasnicolaas 

> These changes could also be made in the `current` branch.
> 
> ./Klaas

Is there a simple way to change the target branch? I made a try but lots changed files appeared in this PR.

**Comment by klaasnicolaas** [comment]
You change the target branch to `current` but you also need to rebase your own branch to that of current.

./klaas

**Comment by astrandb** [comment]
Closing this since I messed things up...
Opening a new clean PR

**Pull request closed without merging**
