### PR TITLE
fix Release-Notes link in Updating section

### PR DESCRIPTION
**Pull request by LaQuay**
## Proposed change
The previous link was poiting to an old HA repo, which was redirecting to the CORE GitHub. Instead of this, better to redirect to the main Release-Notes.

## Type of change
- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks! 👍

**Comment by LaQuay** [comment]
> Thanks! 👍

Hey Frank, just seen now. What do you think about removing the "Core" word in the same sentence?

From:
> Once the last command executes, restart the Home Assistant **Core** service to apply the latest updates. Please keep in mind that some updates may take longer to start up than others. If Home Assistant **Core** fails to start, make sure you check the **Breaking Changes** from the [Release Notes](https://www.home-assistant.io/latest-release-notes/).

To:
>Once the last command executes, restart the Home Assistant service to apply the latest updates. Please keep in mind that some updates may take longer to start up than others. If Home Assistant fails to start, make sure you check the **Breaking Changes** from the [Release Notes](https://www.home-assistant.io/latest-release-notes/).

I can do another PR. Thanks!

**Comment by frenck** [comment]
I don't think that is needed. As in both cases, it is meant to be Core.

**Comment by LaQuay** [comment]
> I don't think that is needed. As in both cases, it is meant to be Core.

OK! Thanks.

**Pull request merged**
