### PR TITLE
Mention that the new customize format is for 0.37+ only

### PR DESCRIPTION
**Pull request by andrey-git**
**Description:**

Mention that the new customize format is for 0.37+ only

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @andrey-git,

It seems you haven't yet signed a CLA. Please do so [here](https://cla.home-assistant.io/sign/andrey-git?pr=1913).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by robbiet480** [comment]
Hey, sorry the CLA link was wrong, it's now been fixed. Please sign the CLA [here](https://home-assistant.io/developers/cla_sign_start/).

**Comment by homeassistant** [comment]
Hi @andrey-git, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.github.io#1913).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by robbiet480** [comment]
Thanks! 🐬 🍪 💯

**Pull request merged**
