### PR TITLE
Fix quotes

### PR DESCRIPTION
**Pull request by fredrike**
**Description:**

As discussed in #9965 

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

<a href="https://gitpod.io/#https://github.com/home-assistant/home-assistant.io/pull/9974"></a>

### CODE REVIEW

**Comment by fredrike** [comment]
Not sure where `\201C`, `\201D` comes from.

Screenshot 2019-07-25 at 14 48 06

**Comment by klaasnicolaas** [comment]
@fredrike Think it's better now 😉

**Comment by fredrike** [comment]
@klaasnicolaas but it should be a qoute..

**Comment by frenck** [comment]
LOL @fredrike well this is awkward 😊 
I'll check out this PR locally and play with it...

Assigning myself.

**Comment by frenck** [comment]
Not the most beautiful solution, but it works for now 👍

**Review by frenck — APPROVED** [review]

**Pull request merged**
