### PR TITLE
Added documentation for remote_homeassistant

### PR DESCRIPTION
**Pull request by lukas-hetzenecker**
Added documentation for remote_homeassistant

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#13876

## Checklist:

- [X] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [X] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by frenck** [comment]
Closing this PR, since the parent PR as been closed as well.

**Comment by TangoOversway** [comment]
Where to I go for help on this? I have spent hours and hours on it - literally about 5 hours last night and 4 hours tonight and I can't get 2 instances to link together. I've posted on the HA forums and have not received help.

When I install Remote Home Assistant on the system I want to use as a remote system, ONE time, it came up with a dialog to ask if that system was remote or not. I picked remote and that was it. I set up a long term access token on that system and copied and pasted it to my notes and made the change in the remote system config file. After that, I went to the main system and installed RHA. It came up with the config dialog and I entered the system info for the remote system, including the name so it could reach it on my LAN, the port, and the authorization token. It would not work.

Thinking maybe something was wrong with the remote system, I made a new HA image, restarted with that clean image. Then I had to get HACS, then add RHA. I've done this with multiple images. I've also tried deleting the files in the config/custom_components directory and deleting it from HACS.

IT DOES NOT WORK!

Other than ONE time when I was asked if the system was the remote system, RHA *ALWAYS* comes up on the remote system asking for the data the main system needs.

I need to get this to work and there are no docs on troubleshooting and I can't find anything in the logs to tell me why the main system could not connect to the other one.

Where do I go for help?

**Comment by frenck** [comment]
This is a closed PR from 2018. It was never added. Home Assistant doesn't support linking multiple instances together. 

You, therefore, won't find support for it @ Home Assistant.

**Comment by TangoOversway** [comment]
> You, therefore, won't find support for it @ Home Assistant.

Okay, so where do I go, on GitHub, for help with Remote Home Assistant? This is the 2nd night I've been up to close to 5 AM or later to get this to work. (Only time, right now, I can work on it.) I've been to the [RHA project](https://github.com/custom-components/remote_homeassistant), but there doesn't seem to be any place there to ask for help.

**Comment by frenck** [comment]
There is no such thing provided by the Home Assistant project. So we can't help you.

If you are using a third-party component/integrations/card/plugin/addon or anything else third-party. Please contact the author of that, we can't help you with third-party things.

../Frenck

**Comment by TangoOversway** [comment]
> If you are using a third-party component/integrations/card/plugin/addon or anything else third-party. Please contact the author of that, we can't help you with third-party things.

Okay, so how do I contact the author?

**Comment by frenck** [comment]
You are asking how to contact a random person on this planet. I dunno, it is a third-party thing, not related to anything by the Home Assistant project.

Again: We can't help you.

**Comment by TangoOversway** [comment]
> You are asking how to contact a random person on this planet. I dunno, it is a third-party thing, not related to anything by the Home Assistant project.
> 
> Again: We can't help you.

Okay.

It's been rough. As I said, I've given up, now, almost all of 2 nights sleep to try to get this to work, in addition to dealing with a day job. When I was programming, it was way before things like GitHub, and I'm just trying to get things set up and running. This is a project here on GitHub, so I have been hoping to find, SOMEWHERE, someone who could tell me how, on a project like the one I linked to, to get help. This is about the last place I figured someone might tell me how to navigate around in a project like that, but I guess that's not possible and nobody can look at that link.

Clearly I've wasted 2 nights of sleep and nobody can help now.

Thank you for your kindness and understanding.

**Comment by frenck** [comment]
Sorry, I wish I could be of help, but we simply can't.

**Comment by TangoOversway** [comment]
> Sorry, I wish I could be of help, but we simply can't.

You can't even tell me how to find out who is the owner of a project on this site?

**Comment by frenck** [comment]
GitHub is a public open-source hosting website. There are millions of projects with an equal amount of owners on this site. Everybody can start a project on GitHub.

So, no, I can't tell you.

**Comment by jmsblah** [comment]
@TangoOversway did u figure out?

**Comment by TangoOversway** [comment]
> @TangoOversway did u figure out?

No. Didn't get it working properly, then, one day, without anything to trigger it, everything started showing up on the instance I wanted to use as the main system. I remember some issue with it - like friendly names not transferring or some other issue that was just going to make it a pain to set up, so I disabled it.

I feel that if software does not behave in a predictable manner, I can't trust it to behave as it should. In this case, it was over a month or more before it showed up on the main system and it wasn't after an update or a configuration change - it just started showing up out of the blue. So I have no idea what made it do that and felt I couldn't trust it to just disappear at some later date.

Without clearer documentation and reliability of behavior (like knowing, "These steps will set it up, then reboot," and then having that process work - then, and not weeks later), I consider this experimental and not useable for anything other than a test or experimental setup. I depend on my HA install to turn lights on and off and control the thermostat and ceiling fans. I don't risk creating issues with my daily use of the system by installing unreliable and unpredictable software.

(Half that is for the developer of Remote Home Assistant - not as whining, but to point out the issues. But it looks like the project is either abandon or the idea of writing or improving documentation is abandon.)

**Pull request closed without merging**
