### PR TITLE
Adds Template integration category

### PR DESCRIPTION
**Pull request by dougiteixeira**
## Proposed change

Adds Template integration category

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by frenck** [comment]
So this add a category for a single integration?

**Comment by dougiteixeira** [comment]
> So this add a category for a single integration?

Yes and no. Despite being just one integration, the documentation is separate, for the end user it appears to be several integrations as in the screenshot below:
image

So from an organization point of view and making it easier for the user to find what they want, I believe it would improve the experience.

**Comment by dougiteixeira** [comment]
In addition to the integration's filters page, adding the category is a way to browse documentation without having to search again.

image

**Comment by frenck** [comment]
It is still a single integration, we should not add categories for a single integration.

../Frenck

**Comment by frenck** [comment]
Going to friendly decline this one, simply because we should not use categories to combine a single integration.

../Frenck

**Comment by dougiteixeira** [comment]
No problem with that...

In the developer's view it really doesn't make sense to include this, but thinking about the user experience it makes a good difference.

I myself know and use the different ways of configuration, sometimes I come across confusion when consulting the documentation because it is segmented into several pages.

Thanks for the feedback!

**Comment by frenck** [comment]
> In the developer's view it really doesn't make sense to include this, but thinking about the user experience it makes a good difference.

Sure, that is a different discussion. Hacking around it by instating a category IMHO isn't the right solution, but more working around a different issue.

../Frenck

**Pull request closed without merging**
