### PR TITLE
Update netatmo.markdown

### PR DESCRIPTION
**Pull request by HFeenstra**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue:

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by cgtobi** [comment]
I don't think it is particularly helpful to link to the Dutch product site. Neither do I think that we should change the link at all.

**Comment by klaasnicolaas** [comment]
I agree with @cgtobi and will close this PR

**Comment by HFeenstra** [comment]
Hello both, my intention was to link the link to the correct device. Since the other devices in the lines below also have direct links to the product.
My typo was indeed the Dutch version, the correct English link would be:
https://www.netatmo.com/en-row/security/cam-indoor

Leave it to the community. Have a great day.

**Comment by cgtobi** [comment]
But still, the integration does not only support the welcome but also the presence camera. So it actually might confuse users.

**Pull request closed without merging**
