### PR TITLE
Update izone.markdown to include overriding temperature sensor change

### PR DESCRIPTION
**Pull request by callifo**
## Proposed change

Update to align documentation to pull request to add the ability to override the iZone temperature sensor. 

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/43285
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Please rebase to the `next` branch and also change the target branch to `next`.

**Comment by callifo** [comment]
> 
> 
> Please rebase to the `next` branch and also change the target branch to `next`.

Any suggestions on the cleanest way to do that, I have no idea how to use github TBH, and its doing my head in just changing it. It would be cleanest just to delete all changes to the current branch, and redo them in the next branch, but I cant work it out and I've just accidentally reverted one of the changes. Should I close this PR, and create a new one on the next branch?

**Comment by callifo** [comment]
Anyone confirm what I've done is right? Do I just change the base at the top of the PR? It now says there are 25 changes to commit which looks to be other peoples stuff mixed in with mine, which is weird.

**Comment by klaasnicolaas** [comment]
The problem is with the branch you used on your own fork, in this case you were using the `current` branch which is not good. 

Because you are going to adjust something in core, your adjustment here must come from the `next` branch or from a branch that descends from `next`. That's why we ask you to rebase your current branch to next, but you can also start over with a new branch / pull request 😉

**Comment by callifo** [comment]
I might do that, I don't understand this well enough and the change is tiny.

**Pull request closed without merging**
