### PR TITLE
Add duwi docs

### PR DESCRIPTION
**Pull request by duwi2024**
# Duwi Integration Support

This PR introduces the Duwi integration to Home Assistant, including:

- **Documentation:** Added a new `duwi.md` file providing setup and configuration instructions.
- **Icon:** Included the official integration icon `icons-integrations-duwi.svg`.
- **Visual Setup Guide:** Added a set of images to facilitate a clear, visual setup guide.

These additions aim to streamline the process of setting up and configuring Duwi devices for users.

### CODE REVIEW

**Comment by c0ffeeca7** [comment]
Thank you for your contribution, @duwi2024 :+1: 

A few things need to be changed before this PR can be processed.

1. As described in step 6 of the [instructions on creating a PR](https://developers.home-assistant.io/docs/review-process), use the [PR template](https://github.com/home-assistant/home-assistant.io/blob/current/.github/PULL_REQUEST_TEMPLATE.md) and fill in the required information. 
2. As this PR is related to a code PR, it needs to be pointed against the `next` branch, not `current`.
3. Add the link to the related core PR.
4. In the [brands repository](https://github.com/home-assistant/brands), create a PR adding icons and logos. Then, in this documentation PR, provide the link to the brands PR.

**Comment by c0ffeeca7** [comment]
I'm [drafting this PR](https://developers.home-assistant.io/docs/review-process#prs-are-being-drafted-when-changes-are-needed), as changes are needed. Please undraft it, once the changes have been implemented and the PR is ready for review again.

**Comment by duwi2024** [comment]
> Thank you for your contribution, @duwi2024 👍
> 
> A few things need to be changed before this PR can be processed.
> 
> 1. As described in step 6 of the [instructions on creating a PR](https://developers.home-assistant.io/docs/review-process), use the [PR template](https://github.com/home-assistant/home-assistant.io/blob/current/.github/PULL_REQUEST_TEMPLATE.md) and fill in the required information.
> 2. As this PR is related to a code PR, it needs to be pointed against the `next` branch, not `current`.
> 3. Add the link to the related core PR.
> 4. In the [brands repository](https://github.com/home-assistant/brands), create a PR adding icons and logos. Then, in this documentation PR, provide the link to the brands PR.

OK, I will check it.

**Comment by duwi2024** [comment]
I close this PR, and i commit another PR to next branch

**Pull request closed without merging**
