### PR TITLE
Consistent icon support for MQTT entitites

### PR DESCRIPTION
**Pull request by kristianheljas**
## Proposed change
Adds consistent icon support for all MQTT entities

Implementing PR: https://github.com/home-assistant/core/pull/47165

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/47165
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @kristianheljas, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#16785).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
There are unrelated commits in this PR. Please git rebase your PR onto the `next` branch in order to clean it up. Thanks! 👍

**Comment by kristianheljas** [comment]
@frenck I have rebased this PR to `next` and reflected latest changes to implementig PR.

I also changed existing icon configuration examples to be more consistent, hope you don't mind.
If you do, no problem, i'll revert them back

**Comment by kristianheljas** [comment]
@frenck It also seems [Jekyll is failing](https://github.com/home-assistant/home-assistant.io/pull/16785/checks?check_run_id=2086594145#step:7:6) unrelated to these changes.

It seems https://github.com/home-assistant/home-assistant.io/pull/16929 should be merged to next as well..

**Review by frenck — APPROVED** [review]
Thanks, @kristianheljas 👍

**Pull request merged**
