### PR TITLE
Add toggle_mode option to rflink switches

### PR DESCRIPTION
**Pull request by xvello**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#12665

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
@xvello Thank you! 🥇 
Can be merged as soon as the parent PR get merged.

**Comment by frenck** [comment]
Rebased the PR in order to fix the build issues.

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Thanks, @xvello! 🥇 

Can be merged as soon as the parent PR gets merged.

**Comment by xvello** [comment]
Closing as the feature was rejected. Thanks for the rebase anyway.

**Pull request closed without merging**
