### PR TITLE
Fix IHC config schema

### PR DESCRIPTION
**Pull request by mopolus**
**Description:**
Documentation updates for fix to issue with config schema.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):**
https://github.com/home-assistant/home-assistant/pull/19415

**Related issue:**
home-assistant/home-assistant#19353

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
Since the source fix is already released I think we should target `current` branch instead of `next` branch. Please rebase on latest current and switch target branch.

**Comment by mopolus** [comment]
> Since the source fix is already released I think we should target `current` branch instead of `next` branch. Please rebase on latest current and switch target branch.

Branch updated. Not sure how I can do the rebasing from here (currently only have web access)

**Comment by MartinHjelmare** [comment]
Probably then easiest to make a new pull request from the correct base and apply your changes again. From the command line it would be easier.

**Comment by mopolus** [comment]
@MartinHjelmare I have added PR #7913 from current
Thank you for advice and assistance :-)

**Pull request closed without merging**
