### PR TITLE
Patch 3

### PR DESCRIPTION
**Pull request by surge919**

### CODE REVIEW

**Comment by robbiet480** [comment]
@surge919 What's the purpose of this PR?

**Comment by Landrash** [comment]
@surge919 I think this pull request should probably be broken up in parts for the different edits. One for the new material and one for the white space and formatting fixes.

 - owntracks_and_bridged_mqtts Seems this page is missing some of the formatting. Have your [tested this locally](https://home-assistant.io/developers/website/) or only used the text editor on github?

**Comment by fabaff** [comment]
https://github.com/home-assistant/home-assistant.github.io/pull/804

**Comment by fabaff** [comment]
I included the guide from @surge919 with https://github.com/home-assistant/home-assistant.github.io/commit/3e84f46a85748da40584d19be45a98dd21bdf3fd

**Pull request closed without merging**
