### PR TITLE
Added documentation for notify.twilio_call component

### PR DESCRIPTION
**Pull request by fakezeta**
**Description:**
Documentation for the twilio notification platform enables sending notifications via Voice Phone Call, powered by Twilio (https://twilio.com). Passed message will be read by Text-To-Speech service provided by Twilio.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#5580

### CODE REVIEW

**Comment by danielperna84** [comment]
Just had a glimpse at the twilio site. There's something about a free API key, but they also have pricings (which makes sense for something like that). Hence I guess it would be a good addition for the documentation to mention possible costs that would be tied to the service.

**Comment by robbiet480** [comment]
@danielperna84 I think most people will realize that pretty quick when you go to sign up for an account and it says you can't make calls without entering a credit card no?

**Comment by danielperna84** [comment]
For the Amazon Polly TTS that was requested as well. Although I admit, that this case indeed may be different if it's not working for free at all. As stated above, from just looking at the site it seems like there's some free API (like for a lot of other services), but  the calling probably isn't included in that.
At least for me mentioning the financial aspects in the documentation would save me the time to examine what pricing models twilio offers. Could be just me, but I generally prefer more "verbose" documentation that tells me mostly everything I need to know instead of just point me into the right direction. :D

**Comment by fakezeta** [comment]
Hi @danielperna84,

I added some information about the free trial limitation even if I agree with @robbiet480.
Describing the service too in detail means monitoring the offer and update the documentation accordingly.

my 2 cents

**Comment by homeassistant** [comment]
Hi @fakezeta, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.github.io#1885).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by fakezeta** [comment]
Done!

**Review by fabaff — APPROVED** [review]
Thanks :bird:

**Pull request merged**
