### PR TITLE
Fix workday example config

### LINKED ISSUE #24007: First Example for Workday Sensor is Wrong
### Feedback

According to this post:

https://community.home-assistant.io/t/workday-add-holidays-not-working/359953/11

To exclude holidays you must put it in the exclude section.  Simply adding holidays doesn't do anything.  The custom holidays are **added** to the full holiday list, so there is no way to have just custom holidays (without excluding every built in one anyway).  So the first example is just flat out wrong.

### URL

https://www.home-assistant.io/integrations/workday/

### Version

2022.8.7

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by calebmah**
## Proposed change

The workday sensor doesn't work as shown in the example since holidays need to be excluded in order for custom holidays to also be excluded. See: https://community.home-assistant.io/t/workday-add-holidays-not-working/359953/11

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #24007

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This change to the documentation makes no sense to me, because:

> holidays need to be excluded in order for custom holidays to also be excluded

They are by default excluded. See:

https://github.com/home-assistant/core/blob/1c18f69c1963569fcfbca1e569c6cbd6db904e68/homeassistant/components/workday/binary_sensor.py#L38

Custom added holidays are appended to the existing list of holidays:

https://github.com/home-assistant/core/blob/1c18f69c1963569fcfbca1e569c6cbd6db904e68/homeassistant/components/workday/binary_sensor.py#L114

Could you elaborate on this change and explain why it isn't correct currently?

../Frenck

**Comment by calebmah** [comment]
The existing example suggests that it is possible to exclude custom holidays **without** also excluding pre-configured holidays.  However, like you pointed out, custom holidays are added to the existing preconfigured holidays and it is therefore not possible to exclude custom holidays **only** without also excluding the pre-configured holidays. 

This change corrects that first incorrect example. Proper usage of custom holidays via `add_holidays` and `remove_holidays` are already available in the other examples. 

Let me know if any other clarification is needed!

**Comment by frenck** [comment]
IMHO, this should just work as documented right now. If not, I believe is should be reported as a bug (instead of adjusting documentation).

The existing example seems correct to me.

**Comment by frenck** [comment]
Closing this PR stale, as after the last comment, no response was returned.

Feel free to re-open it when you are ready to work on it again.

../Frenck

**Pull request closed without merging**
