### PR TITLE
Adds a page for the custom_deps add-on

### PR DESCRIPTION
**Pull request by shred86**
**Description:**

Currently, the "Custom deps deployment" add-on has no page on home-assistant.io and the link on the add-on leads to no where. This pull request is to add a page with some basic info on how to use the add-on.

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
@shred86 Thanks for the PR, the build still fails, so that is something that needs fixing.
Secondly, I'm not sure if we should merge this PR in general.

Reasoning is: https://github.com/home-assistant/hassio-addons/issues/312#issue-327562674

**Comment by balloob** [comment]
I agree with @frenck, we shouldn't merge this.

**Comment by ludeeus** [comment]
I do not agree, as long as the addon is available there should be documentation.
currently that takes you here. <https://www.home-assistant.io/addons/custom_deps/>
image

**Comment by shred86** [comment]
Sounds good. Looks like the idea to move this add-on to the community add-on was proposed 7 months ago. I saw a few posts about the broken link 5+ months ago and I believe there’s an open issue about it from 5 months ago. Figured I’d just make something temporary in the mean time until the add-on is removed from the official list, but obviously it’s your decision. Just trying to help. :)

**Pull request closed without merging**
