### PR TITLE
Changes for Twitch integration, pull request #100859

### PR DESCRIPTION
**Pull request by jonnybergdahl**
## Proposed change
I am submitting a PR for the Twitch integration, this needs new scopes added to the OAuth flow. 

## Type of change
- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [X ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Checklist
- [ X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by jonnybergdahl** [comment]
This is related to the following PR - https://github.com/home-assistant/core/pull/100827
Did I misunderstand the current vs next branch?

**Comment by jbouwh** [comment]
Your PR has included none related commits.
Suggestion is to checkout a fresh copy of the `next` branch and start a new PR. Please assign a proper name.

**Comment by jonnybergdahl** [comment]
#100859
—————————————
Jonny Bergdahl
Bergdahl IT AB
Kapellgatan 6C
553 17  JÖNKÖPING
Sweden
Email: ***@***.***



25 sep. 2023 kl. 08:30 skrev Jan Bouwhuis ***@***.***>:



Your PR has included none related commits.
Suggestion is to checkout a fresh copy of the next branch and start a new PR. Please assign a proper name.

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
