### PR TITLE
Update nginx.markdown

### PR DESCRIPTION
**Pull request by luuloe**
Remove outdated TLSv1.0 and TLSv1.1

## Proposed change
Remove deprecated TLSv1.0 and TLSv1.1 from nginx proxy configuration. 

TLSv1.0 and TLSv1.1 seem to be non-supported anyway judging from an old pull-request (#15217), however the nginx proxy configuration was not updated accordingly. 

With this change the ssllabs.com test result changes from B to A+.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: n.a.
- Link to parent pull request in the Brands repository: n.a.
- This PR fixes or closes issue: n.a.

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by luuloe** [comment]
There is no parent PR, just this minor fix for the nginx configuration in the documentation. 
I think the probot accidently assigned the 'has-parent' label because I originally added a link to a very old pull-request that removed support for old TLS versions (https://github.com/home-assistant/core/pull/15217).

**Comment by klaasnicolaas** [comment]
If you place a link in your pull request, probot assumes that you have a parent PR and therefore this pull request belongs in the `next` branch 😉 Will remove the incorrect labels.

**Comment by luuloe** [comment]
Thanks :)

Maybe this minor change is insufficient. If I compare the configuration to the hass.io nginx proxy addon (https://github.com/home-assistant/hassio-addons/blob/master/nginx_proxy/data/nginx.conf) there are more differences. There even exists a third configuration under https://www.home-assistant.io/docs/ecosystem/nginx_subdomain/.  

In my opinion the security related settings should be identical. The hass.io addon seems the strongest and most up-to-date. I am not very familiar with markdown, nor with this project. What is a good way of ensuring these configurations are aligned and kept up to date? Is there a way to make a base config and include or link it in all variants?

**Review by frenck — APPROVED** [review]
Thanks, @luuloe! 👍

**Pull request merged**
