### PR TITLE
Update templating.markdown to reflect regex templating functions

### PR DESCRIPTION
**Pull request by mountainsandcode**
**Description:**
Updats documentation for regex templating functions

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** https://github.com/home-assistant/home-assistant/pull/13631

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by frenck** [comment]
@mountainsandcode This PR was targeted against the wrong branch. I should go into `next`.

Please rebase the PR. 👍  (Added WIP status in the mean time).

**Review by frenck — CHANGES_REQUESTED** [review]
Please rebase.

**Comment by frenck** [comment]
Rebased this PR onto next, awaiting build results...

**Review by frenck — APPROVED** [review]

**Comment by mountainsandcode** [comment]
@frenck: Cheers for doing the rebase, was out travelling without git access so you were faster than me :) 👍

**Pull request merged**
