### PR TITLE
Remove Ultraloq from the WWHA partner program

### PR DESCRIPTION
**Pull request by b-uwe**
## Proposed change

Remove Ultraloq from the WWHA partner program

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/4529
- This PR fixes or closes issue: fixes #
- This PR relates to https://github.com/zwave-js/node-zwave-js/issues/5445

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by TheOneOgre** [comment]
The wiki page should also be updated. Maybe make a pull request there for a change as well? I do not want to make any commits as I am unsure exactly what removing the WWHA stuff should look like and if any warning should be in place? Maybe someone more experienced with HA wiki editing could do a PR?

**Comment by b-uwe** [comment]
> The wiki page should also be updated.

@TheOneOgre  Can you please link me to that wiki page? I wouldn't know what you're referring to, sorry

**Comment by TheOneOgre** [comment]
> > The wiki page should also be updated.
> 
> @TheOneOgre Can you please link me to that wiki page? I wouldn't know what you're referring to, sorry

Honestly I was basing this off an edit I made but it doesn't seem like all the data is there such as the work with home assistant badge so I'm not exactly sure how you go about removing it but this is as close as I got. https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/ultraloq.markdown

**Comment by frenck** [comment]
Seems odd to me that the documentation and branding is removed, but not the virtual integration. Did you miss that one?

../Frenck

**Comment by TheOneOgre** [comment]
> Seems odd to me that the documentation and branding is removed, but not the virtual integration. Did you miss that one?
> 
> ../Frenck

We were discussing that [here](https://github.com/home-assistant/brands/pull/4529#issuecomment-1630040237). Was wondering what your thoughts on what to do are?

**Comment by frenck** [comment]
Well, this is not opinionated from my review point of view. Every integration needs documentation and preferably brand assets; otherwise, it looks weird in the UI, and a user won't be able to find any information about the integration shown in the UI.

The political question/discussion on this: I have no opinion.

**Comment by b-uwe** [comment]
> Seems odd to me that the documentation and branding is removed, but not the virtual integration. Did you miss that one?

I did miss that, indeed. Thanks! Taking care now.

**Comment by b-uwe** [comment]
@frenck Removing the virtual integration is https://github.com/home-assistant/core/pull/96355
Thanks once more for making me aware I forgot that one!

**Review by frenck — APPROVED** [review]
Thanks, @b-uwe 👍

**Pull request merged**
