### PR TITLE
Add Abode CUE support

### PR DESCRIPTION
**Pull request by shred86**
## Proposed change
Updates documentation to reflect changes with #31514.

## Type of change
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information
- Link to parent pull request in the codebase: [#32296](https://github.com/home-assistant/home-assistant/pull/32296)

## Checklist
- [x] This PR uses the correct branch, based on one of the following:
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

PS: @shred86, please don't remove items from the issue templates. 👍

**Comment by shred86** [comment]
I think this will have to be rebased once #11954 gets merged.

**Comment by shred86** [comment]
Closed the parent PR and created a new one (#32296).

**Review by frenck — CHANGES_REQUESTED** [review]
Could you please resolve the merge conflict? Thanks! 👍

**Comment by shred86** [comment]
Hm, after fetching from upstream next and rebasing to upstream/next, when I try `git push force --origin`, I'm getting this error:

````
To https://github.com/shred86/home-assistant.io.git
 ! [remote rejected]     abode_cue -> abode_cue (refusing to allow an OAuth App to create or update workflow `.github/workflows/test.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/shred86/home-assistant.io.git'
````

First time seeing this error. Any ideas?

Edit: I just made the changes from the browser. ;) Merge conflict should be resolved!

**Comment by frenck** [comment]
That is a new error, by the looks of it, is your application token not provided with the workflow scope. Maybe consider creating a new one.

Thanks for resolving the conflict!

**Review by frenck — APPROVED** [review]

**Pull request merged**
