### PR TITLE
Add USB discovery for BitronVideo AV2021 ZHA stick

### PR DESCRIPTION
**Pull request by javicalle**
## Proposed change

With the next release the USB discovery will be avaliable for the BitronVideo AV2021 ZHA stick

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

I have added the new record in alphabetical order, but I am not sure if it is the criteria to follow.

- Link to parent pull request in the codebase: [core #58337](https://github.com/home-assistant/core/pull/58337)
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Please link to the parent PR when targeting the `next` branch. Thanks 👍

**Comment by javicalle** [comment]
> Please link to the parent PR when targeting the `next` branch. Thanks 👍

I'm not sure if you mean to the core PR. I have done well?

**Comment by Hedda** [comment]
> > Please link to the parent PR when targeting the `next` branch. Thanks 👍
> 
> I'm not sure if you mean to the core PR. I have done well?

The parent PR https://github.com/home-assistant/core/pull/58337 was merged and it is listed under the all changes list for HA 2021.11

**Comment by frenck** [comment]
Thanks, @Hedda... we know. No need to message for that. Thanks 👍

**Review by Adminiuga — APPROVED** [review]
Lgtm

**Review by frenck — APPROVED** [review]
Thanks!

**Pull request merged**
