### PR TITLE
Add Huawei LTE button category and platform

### PR DESCRIPTION
**Pull request by scop**
## Proposed change

SSIA.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/91967
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
The parent PR was merged 2 weeks ago? So it cannot be `current` yet?

../Frenck

**Comment by scop** [comment]
IDK, I think `current` will be correct when 2023.12 is out which I suppose really soon now -- I believe the changes in the parent PR will be included in it. But rebased against `next` now.

**Comment by frenck** [comment]
> IDK, I think current will be correct when 2023.12 is out which I suppose really soon now -- I believe the changes in the parent PR will be included in it. 

Sure, but it isn't. Documentation follows the same process as Core. Core uses `dev` with a milestone, which is the same as the `next` branch here that also has a milestone.

../Frenck

**Review by frenck — APPROVED** [review]
Thanks, @scop 👍 

../Frenck

**Pull request merged**
