### PR TITLE
Adds SABnzdb queue count

### PR DESCRIPTION
**Pull request by bigwoof**
adding documentation for proposed change

**Description:**
Adding documentation for sensor to show number of items in SABnzdb queue 

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

  - [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`. 
  - [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by frenck** [comment]
Thanks, @bigwoof! Pretty nice addition 👍

**Comment by frenck** [comment]
@bigwoof You have created this PR against the `current` branch. Could you please rebase it on the `next` branch?

**Comment by bigwoof** [comment]
I have re-based the change to the Next branch (I think) - this is my fist contribution so please bare with me.  hopefully I have don things correctly.

**Comment by frenck** [comment]
@bigwoof No, you've changed the target branch. Not rebased it.

**Comment by bigwoof** [comment]
@frenck, sorry I am stumped - I am not sure how to change the base.  I am a little lost if you/someone can point me in the right direction that would be great.  That way I can at lease make some contributions to the documentation in the future too and I will be doing it correctly.

**Comment by frenck** [comment]
@bigwoof I've done it for you, in this case, I can imagine it is not an easy task.

For future reference, this is what I have done:
```bash
git clone https://github.com/bigwoof/home-assistant.github.io.git bigwoof
cd bigwoof
git remote add upstream git@github.com:home-assistant/home-assistant.github.io.git
git fetch upstream
git checkout next
git pull upstream next
git checkout patch-4
git rebase --onto next patch-4~1
git push -f
```

Basically, what this does, it taking your last commit and placing it on top of the latest version of the `next` branch.

**Comment by bigwoof** [comment]
OK I see now - my problem was that I simply used the github web UI to make the documentation edits and I don't know if there is a way to set the base there - I think it only applies to current.  If I was to keep doing this via the browser when I make changes I assume that it will only work for edits on the current branch - eg. helping with adding documentation for existing features.  
If I add new features then I will need to make the changes via the command line and pushing it as you describe above.

**Pull request merged**
