### PR TITLE
Fix names in the MQTT update configuration example

### PR DESCRIPTION
**Pull request by bieniu**
## Proposed change

I made a mistake in #24636 The problem will be fixed in the `next` branch by #24723, so I'm addressing this PR to the `rc` branch.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
Thanks, @bieniu 👍

**Review by frenck — CHANGES_REQUESTED** [review]
@bieniu I changed the target to the `next` branch (as that is the `dev` of documentation), but that made unrelated commits show up. Could you rebase this PR?

**Comment by bieniu** [comment]
@frenck`next` branch is newer and doesn’t contain those wrong names because #24723 was merged. Only `rc` branch contains those wrong names.

**Comment by frenck** [comment]
Flagged #24723 (and its parent PR) for beta, making this one obsolete.

**Pull request closed without merging**
