### PR TITLE
Update example in feedreader docs

### LINKED ISSUE #34964: Feedreader has dead link and lacks information
### Feedback

a) the example on the bottom of the page is dead now, because it is not a permalink.
This is essentially a re-open for  #33634

b) the old `max_entries` from the yaml can now be configured per-feed. but that's only after the feed-url was added. One needs to click the "configure" button. And it defaults to `20`. These two bits might be nice to know

@mib1185

### URL

https://www.home-assistant.io/integrations/feedreader/

### Version

2024.9.3

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mib1185**
## Proposed change

~~This removes a dead link to an example, which seems to not exists anymore.~~
This Updates the example with a permanent link

Thanks @CCOSTAN for adding this example 6 years ago with #4957. If you've still an example available, it would highly be appreciated, to update the docs with it :slightly_smiling_face: 

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #34964

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

## Summary by CodeRabbit

- **New Features**
	- Introduced the "Feedreader" integration for Home Assistant, allowing users to integrate RSS and Atom feeds.
	- Configured to poll feeds every hour and send new entries to the event bus.
	- Created event entities for each configured feed to represent the latest entry.

- **Documentation**
	- Updated documentation with usage examples for automation actions based on feedreader events, including YAML automation examples.
	- Included a video tutorial link for setting up the Feedreader integration and displaying the latest news feed item on the Home Assistant dashboard.

### CODE REVIEW

**Comment by CCOSTAN** [comment]
I removed this from my active configuration But you can still reference from my historical links. 

https://github.com/CCOSTAN/Home-AssistantConfig/blob/22c19375ac5dcb49e0648aa16c431537407aa5e4/config/packages/hasspodcast.yaml

**Review by CCOSTAN — CHANGES_REQUESTED** [review]
you can change the link to 

https://github.com/CCOSTAN/Home-AssistantConfig/blob/22c19375ac5dcb49e0648aa16c431537407aa5e4/config/packages/hasspodcast.yaml

**Comment by mib1185** [comment]
Hello @CCOSTAN many thanks for this fast reply and providing the link. This is highly appreciated :heart:

**Review by c0ffeeca7 — APPROVED** [review]
Thank you, @mib1185 :+1:

**Pull request merged**
