### PR TITLE
Mqtt alarm code_arm_required

### PR DESCRIPTION
**Pull request by ToRvaLDz**
**Description:**
Updates documentation about new configuration option lines value_template and code_arm_required.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#19558

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
@ToRvaLDz Could you please resolve the merge conflicts 👍

**Comment by klaasnicolaas** [comment]
⚠️ Damn you must clean your PR, there are a lot off unrelated commits now.

**Comment by ToRvaLDz** [comment]
Damn, I'm not a git expert. Which is the best way to clear?

**Comment by emontnemery** [comment]
This is a nice guide for next time: https://gist.github.com/Chaser324/ce0505fbed06b947d962#keeping-your-fork-up-to-date

I think the easiest option now is to simply make a new branch and just add this change again: https://github.com/home-assistant/home-assistant.io/pull/7940/commits/44cd6cef70a22b8343c105f2f29337246d27914c

**Comment by ToRvaLDz** [comment]
@emontnemery thank you for your suggestion, after that I have to make a new pull request, right?

**Comment by emontnemery** [comment]
> after that I have to make a new pull request, right?

Yeah.

**Comment by ToRvaLDz** [comment]
The new pr is #8822

**Pull request closed without merging**
