### PR TITLE
Added new daikin platform (climate + sensors)

### PR DESCRIPTION
**Pull request by rofrantz**
Create documentation for Daikin AC climate component

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#10910

## Checklist:

  - [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`. 
  - [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by rofrantz** [comment]
Sure I'll update it shortly

**Comment by rofrantz** [comment]
@tinloaf documentation is updated

**Comment by rofrantz** [comment]
@tinloaf can you provide some feedback after the changes u requested were implemented ?

**Comment by tinloaf** [comment]
One question before we merge this: The documentation regarding the component (not the platform) says that if you just provide the IP of the host, it autodiscovers all the Daikin devices. That is probably not true anymore now that auto discovery is off, right?

**Comment by rofrantz** [comment]
Docs updated @tinloaf

**Pull request merged**
