### PR TITLE
hci_device parameter for bluetooth_le_tracker

### PR DESCRIPTION
**Pull request by notabene00**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/34094
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by klaasnicolaas — CHANGES_REQUESTED** [review]
Can you rebase the branch on your repo to the `next` branch and push again to this PR.

**Comment by notabene00** [comment]
@klaasnicolaas What exactly should I do?
I'm not familiar with git very well
```
git checkout patch-2
git rebase next
```
returns huge amount of conflicts
And I'm not sure what to do with them

**Comment by frenck** [comment]
@fantomnotabene It was a little more complicated than that. Because of the merges done, it was not just a rebase. I had to strip if the last merge commits and rebase the commit before that onto the `origin/next`.

I hope you don't mind I've picked that up for you.

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Review by klaasnicolaas — APPROVED** [review]

**Comment by notabene00** [comment]
@frenck thank you so much 👍

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
