### PR TITLE
Update niko_home_control.markdown

### PR DESCRIPTION
**Pull request by VandeurenGlenn**
## Proposed change

Changed configuration.yaml -> config flow.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/130554
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

## Summary by CodeRabbit

- **New Features**
	- Added support for configuration flows in the Niko Home Control integration.

- **Documentation**
	- Updated integration documentation to reflect the new configuration flow support and changes to the IoT class.
	- Removed outdated configuration examples and added a reference to the current configuration flow documentation.

### CODE REVIEW

**Comment by c0ffeeca7** [comment]
Thank you for contributing, @VandeurenGlenn  :+1: 

1. As this PR seems to be related to a code PR, please rebase and point this PR against the `next` branch.
2. In the PR template, add the link to the related core PR.
3. Fill out the rest of the PR template and add a description of what this doc change is doing.

**Comment by VandeurenGlenn** [comment]
@c0ffeeca7 Will do! Still need to add some things and are images discouraged or can I add some to make it easier for users?

**Comment by c0ffeeca7** [comment]
> @c0ffeeca7 Will do! Still need to add some things and are images discouraged or can I add some to make it easier for users?

feel free to add images.

**Review by frenck — APPROVED** [review]
Thanks, @VandeurenGlenn 👍 

../Frenck

**Pull request merged**
