### PR TITLE
[Bayesian] Make examples easier to understand, adds tips

### PR DESCRIPTION
**Pull request by HarvsG**
## Proposed change

The [Bayesian integration](https://www.home-assistant.io/integrations/bayesian/) is not very popular with ~600 active installations. It has the potential to be powerful, however the concepts are quite complicated, good documentation and good explanations are key to increasing its utility.

(There is also a major bug, which is being fixed in https://github.com/home-assistant/core/pull/67631)

Here are some useful community links:
- https://community.home-assistant.io/t/how-bayes-sensors-work-from-a-statistics-professor-with-working-google-sheets/143177
- https://community.home-assistant.io/t/bayesian-sensors-best-methods/142401
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/67631 (Since 001f2ac)
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by HarvsG** [comment]
> It seems that this PR is targeted against an incorrect branch since it has a parent PR on one of our codebases. Documentation that needs to be updated for an upcoming release should target the `next` branch. Please change the target branch of this PR to `next` and rebase if needed. (message by DocsTargetBranch)

Should not target the Next branch. Not dependant on PR

**Comment by HarvsG** [comment]
I note the 'has-parent' tag, this is not actually true. https://github.com/home-assistant/core/pull/67631 is not a parent, just a bugfix.

Rebase is done and added some more verbosity and made the language more precise.

**Comment by HarvsG** [comment]
'Parent' PR now merged

**Review by frenck — APPROVED** [review]
Thanks, @HarvsG 👍

**Pull request merged**
