### PR TITLE
Create iAlarmXR integration docs

### PR DESCRIPTION
**Pull request by bigmoby**
## Proposed change
This PR extends Home Assistant component core support for iAlarmXR model. The current iAlarm Home Assistant component support is for GuardIP model. Unfortunately the two alarm system differs on authentication flow but the remaining API remains quite the same.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [X] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:  https://github.com/home-assistant/core/pull/67817
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
The base branch should be `next` as you want to add a new integration 😉

**Comment by bigmoby** [comment]
> The base branch should be `next` as you want to add a new integration 😉

Thanks for the review 👍
Ops sorry! 😅

**Comment by klaasnicolaas** [comment]
You also need to rebase, because you now have commits from a `current` branch in your pull request.

**Review by frenck — CHANGES_REQUESTED** [review]
There are unrelated commits in this PR

image

Please git rebase your commits onto the `next` branch. Thanks 👍

**Comment by bigmoby** [comment]
> There are unrelated commits in this PR
> 
> image
> 
> Please git rebase your commits onto the `next` branch. Thanks 👍

Thank you @frenck I reverted all commits from dev branch, I hope now it's ok

**Comment by frenck** [comment]
@bigmoby That is incorrect/not right.

1) It doesn't resolve the  unrelated commits (see your commits in this PR)
2) You should not be reverting commits of others.

Please git rebase just your commits on to the upstream next branch.

**Comment by bigmoby** [comment]
> @bigmoby That is incorrect/not right.
> 
> 1. It doesn't resolve the  unrelated commits (see your commits in this PR)
> 2. You should not be reverting commits of others.
> 
> Please git rebase just your commits on to the upstream next branch.

OMG 😓
The error comes from afar, I created this PR from current. I'm not a git guru, I'll try to do my best but probably I have to recreate this PR. I'll try, I'm sorry @frenck 🙏

**Pull request closed without merging**
