### PR TITLE
Nimbus doc

### PR DESCRIPTION
**Pull request by w1ll1am23**
**Description:**
Doc for https://github.com/home-assistant/home-assistant/pull/16520

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#16520

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by rpitera** [comment]
@w1ll1am23 - I think docs should make it absolutely clear that support is only available if you already own a Nimbus and it's already in your Wink account.  Since these can no longer be added to existing accounts, it will be frustrating for a user who sees this new support and tries to buy one on eBay or Amazon (who are still selling them) only to find out that Wink no longer supports adding them in.

**Comment by w1ll1am23** [comment]
@rpitera well that isn't entirely true, I just bought mine a few weeks back and was able to get it added by trying to pair it as a quirky refuel (took like 30 minutes to finally get it paired) but I agree I should probably make a change to indicate it isn't supported.

**Comment by rpitera** [comment]
I'd give it a shot but I haven't been lucky pairing legacy Quirky devices.  I had a Spotter that I tried everything with but finally gave up - of course that was using Electric Imp.  How does the Nimbus pair?

**Comment by w1ll1am23** [comment]
They get paired the same way (app flashing screen stuff) it isn't easy like I mentioned I probably tried 50 times before it paied.

**Comment by rpitera** [comment]
Yikes.  Nevermind then; I don't think I want to go through that again.  Even tried it in a locked bathroom with the lights off and a phone turned up to its brightest setting.  Got close once or twice, but never successful.  

As long as you mention it in the docs and put in some kind of YMMV disclaimer, I'm good with this.

**Comment by w1ll1am23** [comment]
@rpitera thank for the feedback, I'll add a disclaimer later today.

**Comment by rpitera** [comment]
No, thank YOU.  For continuing to bring new development to the Wink platform and for always being open to advisory.  It's always been my pleasure to deal with you in any capacity.

**Review by balloob — APPROVED** [review]

**Pull request merged**
