### PR TITLE
Update notify.lametric.markdown

### PR DESCRIPTION
**Pull request by frittes**
**Description:**

Updated documentation for cycles config option and additional service data example.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#10656

### CODE REVIEW

**Comment by frittes** [comment]
Changed.

**Comment by MartinHjelmare** [comment]
You need to rebase since your changes now contain other files that shouldn't be part of this PR.

**Comment by frittes** [comment]
@MartinHjelmare Need your further assistance. Created the PR here in git, not with a local repo.

What can I do to resolve the conflicts?

**Comment by MartinHjelmare** [comment]
If you want to do this all online on github then I think you need to create a new PR, starting from the next branch.

**Comment by frittes** [comment]
@MartinHjelmare Created a new one.

#4017

**Pull request closed without merging**
