### PR TITLE
Added Govee H5105 to supported devices

### PR DESCRIPTION
**Pull request by StevenSeifried**
## Proposed change
Added H5105/GoveeLife Smart Thermo-Hygrometer 2s to supported models. \
Recognized as "H5101/H5102/H5177"

grafik

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by c0ffeeca7 — APPROVED** [review]
Thank you, @StevenSeifried :+1:

**Comment by bdraco** [comment]
The underlying library doesn't support the H5105 and hasn't been tested with it. We don't have tests for this model and haven't verified it works correctly so we intentionally haven't added it to the supported list.

https://github.com/Bluetooth-Devices/govee-ble/blob/5fcd981c1277b6e1ca3610a5b4d1e23d59cdb2fe/src/govee_ble/parser.py#L171

Its showing up as the wrong model above, and its likely we will now get issue reports asking us to fix the model as it will appear incorrectly.

**Comment by c0ffeeca7** [comment]
Let me revert.
#30982

**Comment by StevenSeifried** [comment]
> The underlying library doesn't support the H5105 and hasn't been tested with it. We don't have tests for this model and haven't verified it works correctly so we intentionally haven't added it to the supported list.
> 
> https://github.com/Bluetooth-Devices/govee-ble/blob/5fcd981c1277b6e1ca3610a5b4d1e23d59cdb2fe/src/govee_ble/parser.py#L171
> 
> Its showing up as the wrong model above, and its likely we will now get issue reports asking us to fix the model as it will appear incorrectly.

Do I understand it right, that adding 
```
or (is_5105 := "H5105" in local_name)
```
and 
```
elif is_5105:
                self.set_device_type("H5105")
```
will fix this?

If yes, I will open another Pull Request later this day.

**Comment by bdraco** [comment]
> > The underlying library doesn't support the H5105 and hasn't been tested with it. We don't have tests for this model and haven't verified it works correctly so we intentionally haven't added it to the supported list.
> > [Bluetooth-Devices/govee-ble@`5fcd981`/src/govee_ble/parser.py#L171](https://github.com/Bluetooth-Devices/govee-ble/blob/5fcd981c1277b6e1ca3610a5b4d1e23d59cdb2fe/src/govee_ble/parser.py#L171)
> > Its showing up as the wrong model above, and its likely we will now get issue reports asking us to fix the model as it will appear incorrectly.
> 
> Do I understand it right, that adding
> 
> ```
> or (is_5105 := "H5105" in local_name)
> ```
> 
> and
> 
> ```
> elif is_5105:
>                 self.set_device_type("H5105")
> ```
> 
> will fix this?
> 
> If yes, I will open another Pull Request later this day.

To add support for it we need
- The above change
- Sample service info https://github.com/Bluetooth-Devices/govee-ble/blob/5fcd981c1277b6e1ca3610a5b4d1e23d59cdb2fe/tests/test_parser.py#L432.  Extract this from homeassistant by turning on debug logs for `homeassistant.components.bluetooth`
- A test for that model. You can copy https://github.com/Bluetooth-Devices/govee-ble/blob/5fcd981c1277b6e1ca3610a5b4d1e23d59cdb2fe/tests/test_parser.py#L2677 as a template
- Finally we need to verify that the assumption here https://github.com/Bluetooth-Devices/govee-ble/blob/5fcd981c1277b6e1ca3610a5b4d1e23d59cdb2fe/src/govee_ble/parser.py#L178 is still correct
- Bump the library in HA
- Than we should be good to go on a docs PR

**Comment by StevenSeifried** [comment]
> > > The underlying library doesn't support the H5105 and hasn't been tested with it. We don't have tests for this model and haven't verified it works correctly so we intentionally haven't added it to the supported list.
> > > [Bluetooth-Devices/govee-ble@`5fcd981`/src/govee_ble/parser.py#L171](https://github.com/Bluetooth-Devices/govee-ble/blob/5fcd981c1277b6e1ca3610a5b4d1e23d59cdb2fe/src/govee_ble/parser.py#L171)
> > > Its showing up as the wrong model above, and its likely we will now get issue reports asking us to fix the model as it will appear incorrectly.
> > 
> > 
> > Do I understand it right, that adding
> > ```
> > or (is_5105 := "H5105" in local_name)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and
> > ```
> > elif is_5105:
> >                 self.set_device_type("H5105")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > will fix this?
> > If yes, I will open another Pull Request later this day.
> 
> To add support for it we need
> 
>     * The above change
> 
>     * Sample service info https://github.com/Bluetooth-Devices/govee-ble/blob/5fcd981c1277b6e1ca3610a5b4d1e23d59cdb2fe/tests/test_parser.py#L432.  Extract this from homeassistant by turning on debug logs for `homeassistant.components.bluetooth`
> 
>     * A test for that model. You can copy https://github.com/Bluetooth-Devices/govee-ble/blob/5fcd981c1277b6e1ca3610a5b4d1e23d59cdb2fe/tests/test_parser.py#L2677
> 
>     * Finally we need to verify that the assumption here https://github.com/Bluetooth-Devices/govee-ble/blob/5fcd981c1277b6e1ca3610a5b4d1e23d59cdb2fe/src/govee_ble/parser.py#L178 is still correct

Thank you for the informations. I will take a look at it.

**Pull request merged**
