### PR TITLE
Inform of zwave config service

### PR DESCRIPTION
**Pull request by beinginorbit**
**Description:**
Inform the user of update_config in the zwave installation config_path documentation.

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by DubhAd — DISMISSED** [review]
👍

**Comment by frenck** [comment]
@spacesuitdiver The builds are failing, could you please take a look? 👍

**Comment by leblancexplores** [comment]
@frenck I don't understand the netlify error, the line/column it provides doesn't seem to correspond to any changes in this PR. :\

**Comment by frenck** [comment]
@spacesuitdiver Well... You've changed one line... 😉

**Review by frenck — APPROVED** [review]

**Pull request merged**
