### PR TITLE
Update code examples to remove comments

### PR DESCRIPTION
**Pull request by aidbish**
Removed comments from inside of code examples as this implies comments are allowed although they are lost as noted at bottom of the page. Just removes any additional confusion.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by frenck** [comment]
I don't think we should do this. They can get lost based on the method you use, however, this is not always the case. There is nothing wrong with adding code comments to documentation to clarify inline with what is happening.

I think the adjusted example you've made clearly shows it isn't getting clearer to read the example.

image

**Comment by aidbish** [comment]
Hi @frenck thanks for the feedback
I was under the impressions that the Automations editor formats the code and removes comments regardless.
what other methods are there when it doesnt whilst using the automations editor?

i agree it may look as equally as not being clear but on the web page it shows it as part of a config which maybe copied and then their own comments added and code. Once saved the comments are removed leading to the discussions recently seen in the forums of HA mangling YAML and changing their files.

**Comment by frenck** [comment]
The automations editor only writes to the `automations.yaml` file, however, automation can be placed in other files as well.

**Comment by aidbish** [comment]
I agree about where they can be placed, but the documentation to be modified is about the automations editor only.  If i add automation to another place is it read by the editor if i use id:.

**Comment by frenck** [comment]
It is not read by the automation editor, it is read by Home Assistant and added to the internal automations collection.

I really don't see a direct reason to make the documentation less clear.

I thank you for your thoughts but going to pass on this one. 👍

**Pull request closed without merging**
