### PR TITLE
rflink deprecation and other doc fixes

### PR DESCRIPTION
**Pull request by scop**
**Description:**

See individual commit messages for details.

home-assistant/home-assistant#29972 is related, but this can go in already now without waiting that to be applied.

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#8348 (old)

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Since this change relies on a change that is pending the `next` Home Assistant release, the documentation PR should be targeting the `next` branch.

Please change the target branch for this PR to `next` and rebase if needed.

**Comment by scop** [comment]
As I tried to note in the initial comment, in my opinion this does _not_ depend on the HA change. It is related, but we can merge this already now to current.

**Comment by frenck** [comment]
The `current` documentation should reflect the current state. By merging this, it doesn't do that. So please adjust to `next`.

**Comment by scop** [comment]
Sure it does reflect the current state, there's no reason to promote/document the deprecated values any more. The docs as modified by this PR work right away with the unchanged, current version of HA. And note that before this change, the documentation is misleading (incorrectly marked deprecations) for both current and next.

I can rebase to next if that's what it takes to get this in (please confirm), but frankly to me that is doing some (a tiny bit of) work which will only serve to delay user access to the corrected docs, i.e. that's time spent to make things worse, for no gain.

**Comment by scop** [comment]
Meh, rebased.

**Review by frenck — APPROVED** [review]

**Pull request merged**
