### PR TITLE
Add velbus auto-discovery

### PR DESCRIPTION
**Pull request by thomasdelaet**
**Description:**

Simplify velbus configuration because of implementation of auto-discovery functionality

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#13742

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by thomasdelaet** [comment]
Hey, This is still active. I received comments on code PR and will do updates soon

**Comment by frenck** [comment]
Awaiting changes. Updated the labels of the issue.
@thomasdelaet, please notify us when this is ready for review.

**Comment by MartinHjelmare** [comment]
@thomasdelaet please first solve the merge conflicts. Then we can review this.

**Comment by thomasdelaet** [comment]
@MartinHjelmare I rebased and fixed conflicts

**Review by MartinHjelmare — APPROVED** [review]
Looks good!

**Comment by thomasdelaet** [comment]
Super!

**Pull request merged**
