### PR TITLE
Add Climate platform to ZHA integration

### PR DESCRIPTION
**Pull request by Adminiuga**
## Proposed change

Add Climate as supported ZHA platform

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/35682
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by Hedda** [comment]
Does ZHA climate also need a documentation section similar to the zwave documentation that is here?

https://www.home-assistant.io/integrations/zwave/#climate

If so then can I suggest maybe copy some text about climate from the zwave documentation?

PS: I don't own any Zigbee thermostat or HVAC units myself yet so not sure how they work in ZHA.

**Comment by Adminiuga** [comment]
Not really. The device is configurable on the device itself, there's no manual configuration at this point. With that said, remains to see how well it would work as interpretation of the specs varies wildly between vendors.

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Review by fabaff — APPROVED** [review]

**Comment by noxX02** [comment]
Hello,
I am a bit in trouble with my ATLANTIC FUJITSU HVAC.
I needed to migrate from zigbee2mqtt to ZHA to solve some stuff and it looks like more stable right now.
But the thing is I do not have the same amount of entities discovered by ZHA on my HVAC.
I am missing "swing_mode", "ac_louver_position", "fan_mode", and the options fan_only and dry in "system_mode" (I only have heat, cool, auto, off).
Do you have an idea of how I can get it back in ZHA ? They were discovered and usable in Z2M.

See this doc:
https://www.zigbee2mqtt.io/devices/GW003-AS-IN-TE-FC.html

Best regards,

**Comment by Hedda** [comment]
> But the thing is I do not have the same amount of entities discovered by ZHA on my HVAC.
> I am missing "swing_mode", "ac_louver_position", "fan_mode", and the options fan_only and dry in "system_mode" (I only have heat, cool, auto, off).
> Do you have an idea of how I can get it back in ZHA ?

Closed PR is not the place to post. For your question you want to post a new device support request as per ZHA documentation-> https://www.home-assistant.io/integrations/zha#how-to-add-support-for-new-and-unsupported-devices

**Pull request merged**
