### PR TITLE
Snips.ai corrections

### PR DESCRIPTION
**Pull request by SonicMagna**
**Description:**
I made a couple of minor corrections/additions to the content of the Snips.ai page. The error was incorrect markdown syntax, the additional info are links to the Snips forum and relevant Dark Sky pages that were already mentioned.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

<a href="https://gitpod.io/#https://github.com/home-assistant/home-assistant.io/pull/9776"></a>

### CODE REVIEW

**Comment by frenck** [comment]
Hi, @SonicMagna,

Would you please be so kind to update the title and write something in the openings post what this is about? Thanks! 👍

**Comment by SonicMagna** [comment]
@frenck,
Sorry, I'm still figuring out how to use this GitHub interface. I had commented the work, but it did not show up as I expected it to. I don't know how to change the title. I did edit the Description.

**Comment by frenck** [comment]
No problem @SonicMagna! Thanks for taking the effort to learn this. If you have questions, feel free to ask them on our Discord. 👍

**Comment by SonicMagna** [comment]
@frenck 
Thanks! As I learn more, I will assist as much as I can... And I just saw the edit button for the title, lol. It was offscreen on my monitor...

**Review by frenck — APPROVED** [review]
Thanks, @SonicMagna! 👍

**Pull request merged**
