### PR TITLE
Melissa bobbie

### PR DESCRIPTION
**Pull request by kennedyshead**
**Description:**
This adds the documentation for bobbie water heater

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#18197

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Why are there files in this PR from Asuswrt?

**Comment by kennedyshead** [comment]
Sorry about that, I'm really not sure why this happened :/

**Comment by frenck** [comment]
Closing this PR, since the parent PR has been closed as well.

**Comment by kennedyshead** [comment]
:+1:

**Pull request closed without merging**
