### PR TITLE
Adds BME680 hass.io instructions

### PR DESCRIPTION
**Pull request by ctborg**
**Description:**
Adds BME680 hass.io instructions. 

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Please, just like I already commented on your last PR.
Changes to the existing documentation need to go into the `current` branch.

Please update the target branch and rebase this PR.

**Comment by ctborg** [comment]
@frenck, sure.  I can do that.   The instructions in the PR specifically ask for the `next` branch.  Can you clarify those?

**Comment by frenck** [comment]
@ctborg What do you mean specifically? Is there a code change towards this PR?
If that is the case, can you please link the PR that matched this PR in the Home Assistant repository?

**Comment by ctborg** [comment]
@frenck I was referring to the PR instructions, which can be confusing to a new contributor.

```Branch: next is for changes and new documentation that will go public with the next home-assistant release. Fixes, changes and adjustments for the current release should be created against current.```

I had no idea if this is "new" documentation.

**Pull request closed without merging**
