### PR TITLE
Update nest documentation for sensor and camera, streamlined for new users of SDM API

### PR DESCRIPTION
**Pull request by allenporter**
## Proposed change

This reformats the entire `nest` integration documentation to make a cleaner split between the new SDM API and the Legacy Works With Nest API to reduce confusion for new users.  

This is meant to match the existing supported features for `sensor` and `camera`.

This overhaul should make it a bit easier to read, rather than mixing in the differences between each API into a single document that is harder to read.

## Type of change

- [X] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/42325
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This PR links to multiple upstream parent PRs. Please split the documentation to have 1 PR per parent PR.

**Comment by allenporter** [comment]
> This PR links to multiple upstream parent PRs. Please split the documentation to have 1 PR per parent PR.

I have removed documentation for `climate`, `binary_sensor`, and some features of `camera` since they do not yet have accepted PRs.  This documentation should properly reflect what is in `next`, and now references the parent PR that was already accepted when camera support was initially added.

Once this fix has been accepted, I will send additional PRs for `binary_sensor` and `climate` separately, adding them on top of this restructured layout.

**Comment by allenporter** [comment]
Climate support was [merged](https://github.com/home-assistant/core/pull/42702#event-3966190211) into the main branch.  Would you prefer I pull documentation updates for climate into this PR or wait and follow up after this is in?  Thanks for the review.

**Review by frenck — APPROVED** [review]
Thanks, @allenporter 👍 

Yes, please open a PR for that one as well.

**Pull request merged**
