### PR TITLE
Add documentation for adding server MOTD sensor

### PR DESCRIPTION
**Pull request by itjedi42**
Add documentation for adding server Message of the Day sensor to MinecraftServer integration for home-assistant/core#66297

## Proposed change

Add server message of the day sensor to list in documentation 

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: home-assistant/core#66297
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Review by Thynix — CHANGES_REQUESTED** [review]
Do people call it a world message? I see that the Minecraft `server.properties` calls it `motd`, so my inclination would be to refer to it that way.

At minimum I'd suggest adding a space before the slash, but I also notice that the header of this list is already "This integration provides sensors for the following information from a Minecraft server:" so mentioning that it's the server's MOTD seems redundant.

What do you think about

> - World Message / Message of the Day (MOTD)

**Comment by itjedi42** [comment]
Good by me.

**Comment by Thynix** [comment]
Okay! In case it saves you work I've opened https://github.com/itjedi42/home-assistant.io/pull/1 against your branch with a fixup - feel free to close it if it doesn't.

**Review by Thynix — APPROVED** [review]

**Review by frenck — APPROVED** [review]

**Pull request merged**
