### PR TITLE
Add Camera Push

### PR DESCRIPTION
**Pull request by dgomes**
**Description:**
The push camera platform allows you to integrate images sent over HTTP POST to Home Assistant as a camera. 

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#15151

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by frenck — DISMISSED** [review]

**Comment by frenck** [comment]
LGTM!
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by dgomes** [comment]
Tks for the corrections :)

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Thanks for the updates @dgomes!
I've updated the `ha_release` to 0.74. 
Since the parent PR has been merged, this one can be merged as soon as the build succeeds.

**Comment by dgomes** [comment]
Tks!

**Pull request merged**
