### PR TITLE
Add docs for V2C integration

### PR DESCRIPTION
**Pull request by ghost**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/87774
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/4125
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
There are unrelated commits and changes in this PR.

Please `git rebase` just your documentation changes it to clean it up.

../Frenck

**Review by frenck — CHANGES_REQUESTED** [review]
The package-lock changes aren't related to this PR and should be removed.

**Comment by frenck** [comment]
You can't just deleted the package lock?! You should revert the changes, we'd like to keep the package lock file if you don't mind 😓

**Comment by V2Charge** [comment]
> You can't just deleted the package lock?! You should revert the changes, we'd like to keep the package lock file if you don't mind 😓

Solved.

**Comment by V2Charge** [comment]
Hi, sorry for the inconvenience, but we did the fix 2 weeks ago, we would like to know something about the PR. @frenck

**Pull request closed without merging**
