### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by Danielhiversen**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Is there also an English page variant? Since not everyone can read Swedish 😅

**Comment by Danielhiversen** [comment]
Not sure. I think it is only available in Sweden.
Should I remove the link instead?

**Comment by klaasnicolaas** [comment]
The link does not need to be removed because I also see that the first link is in Norwegian. But it would be nicer if the website also had the English version. Time to merge 😄

**Review by klaasnicolaas — APPROVED** [review]

**Comment by ludeeus** [comment]
They have a English version of the website, but the store is missing from it

**Review by frenck — APPROVED** [review]
I think it is fine, their market is also limited to those countries at this point.

**Comment by Danielhiversen** [comment]
Tibber is also available in Germany now :)

**Pull request merged**
