### PR TITLE
Update sensor.pi_hole.markdown

### PR DESCRIPTION
**Pull request by ambgomes**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by ludeeus** [comment]
What is the purpose of this?
The platform does not support/need authentication?
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/sensor/pi_hole.py#L61-L70

**Comment by ambgomes** [comment]
Hi,
Can you connect and get data from a pi-hole running on a different server then where is running HA, without using username and password ?
Can you please explain me how do you do it ?
Thank you.
=AGomes

**Comment by ambgomes** [comment]
How do you connect to a different server then HA, where is Pi-hole running without username and password ?

**Comment by ludeeus** [comment]
I have not tried doing that personally, but adding it to documentation without backend (platform) support will not get you that :)

**Comment by ambgomes** [comment]
This was my modest contribution.
I have pi-hole running on a different server then where I have Hassio running. Different usernames and passwords.  I tried to use my username and password for Pi-hole server (Raspberry 3 B+) and I was able to get all the variables :-) on my Hassio server.
So, I decided to purpose this update to be able to help other users.

**Comment by ludeeus** [comment]
Then you must have another issue in your network, adding those values to the configuration does nothing (since they are not defined in the platform)

I just tested adding this sensor to an Hass.io instance that is not on the same host as pi-hole, and that works great :)

And last time I checked Pi-Hole only have a password for admin, not username?

**Comment by ambgomes** [comment]
Ok, so pi-hole is really a hole. Give data to hassio, without username and password.
I am sorry but I am not an expert on programming. I did not see the code previously my initial post. 
First time I tried to get data from my Pi-hole something went wrong without username and pass. Once I use a different server for Pi-hole I decide to include username and pass and voilá. 
I have just commented in my configuration file username and pass and really I am still getting all data from Pi-hole server.
I am very sorry, for this work I gave you. I I recognize that I was a bit hasty in proposing the update. 
Thank you.

**Pull request closed without merging**
