### PR TITLE
Add Konnected component

### PR DESCRIPTION
**Pull request by heythisisnate**
**Description:**
Add documentation for the [Konnected](https://konnected.io) component

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant):** https://github.com/home-assistant/home-assistant/pull/13670

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by frenck — DISMISSED** [review]

**Comment by frenck** [comment]
Looks great @heythisisnate!
Awesome first-time contribution to the documentation 🥇 

Can be merged as soon as the parent PR gets merged.

**Comment by heythisisnate** [comment]
😊 thank you! I really tried to be thorough.

**Review by frenck — DISMISSED** [review]

**Review by frenck — DISMISSED** [review]

**Comment by heythisisnate** [comment]
@frenck Could I bug you for a quick re-review? I made some small changes based on code review feedback.

**Comment by heythisisnate** [comment]
@frenck could you re-review this really quick after I made a couple minor edits?

**Comment by heythisisnate** [comment]
bumped `ha_release` to 0.70
hopefully that's the last time 🙌

**Review by syssi — APPROVED** [review]

**Pull request merged**
