### PR TITLE
Added troubleshooting section

### PR DESCRIPTION
**Pull request by DubhAd**
Note about how to (usually) resolve issues with certbot permissions

### CODE REVIEW

**Comment by frenck** [comment]
Shouldn't this be more user specific?
Simply giving the user, group and world the executable bit feels a bit "easy way out".

**Comment by DubhAd** [comment]
It is, but you can only access a file that you know the full path and name of that way. It also works for any user that somebody's running Home Assistant as, and saves trying to take people through identifying the group of the user they run Home Assistant as, and changing the group ownership of the directories.

So, "easy way out" yes - but for the people running it too.

**Comment by frenck** [comment]
@DubhAd Thanks for the explanation. 
From a security perspective, I do not agree.
From a user perspective, I understand.

I'll let it up to another reviewer to decide.

**Comment by dgomes** [comment]
its really easy, but I don't think that should be our stance (advising a less secure solution)

A PR with better error handling (indicating not enough permissions to access the file) would be better

**Comment by frenck** [comment]
Closing this PR, because of above-stated reasoning.

**Pull request closed without merging**
