### PR TITLE
USCIS sensor documentation improvements

### PR DESCRIPTION
**Pull request by chrisrosset**
## Proposed change

Grammar improvements to the USCIS sensor documentation.

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue:

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @chrisrosset 👍

**Comment by chrisrosset** [comment]
@frenck No problem! Quick question - I wasn't sure where to ask about this. After I submitted this PR, I noticed that [the docs reference `name` as a property](https://github.com/home-assistant/home-assistant.io/blame/871d46a70875f7a4ec7794969d396f3c020ac154/source/_integrations/uscis.markdown#L25) but [the code uses `friendly_name`](https://github.com/home-assistant/core/blob/dd232a35072a68ec77d484f05872897ea82eb9f0/homeassistant/components/uscis/sensor.py#L20).

Do you know which one is right? I'm happy submit a PR to the docs or the code but I'm not sure which attribute is more correct.

**Comment by frenck** [comment]
Should be "friendly_name" indeed

**Comment by frenck** [comment]
Honestly, I think this should be corrected in the code base, "friendly_name" is not really used for this in general.

**Comment by chrisrosset** [comment]
That's what I was thinking but wanted someone who knows what they're doing to confirm. I'll send a PR for changes in the integration.

**Pull request merged**
