### PR TITLE
Doorbird auth and event data

### PR DESCRIPTION
**Pull request by oblogic7**
Adds token/auth config details as well as event_data details.

**Description:**
Update documentation to match Doorbird auth and event data changes.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#14933

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by oblogic7** [comment]
Replaces #6231

**Review by DubhAd — APPROVED** [review]
👍

**Comment by oblogic7** [comment]
What parent PR is this waiting on?

**Comment by frenck** [comment]
@oblogic7 The one you've listed in the OP: home-assistant/home-assistant#16504

**Comment by oblogic7** [comment]
Ah. Got lost and thought I was on the main repo. Thanks.

**Comment by frenck** [comment]
@oblogic7 The parent PR has been closed, but since you mentioned something about new PR, I wonder, is this documentation PR still relevant?

**Comment by oblogic7** [comment]
It will be when I’m done with changes on the other PR

**Comment by wolph** [comment]
Since https://github.com/home-assistant/home-assistant/pull/14933 has been merged, this needs to be merged as well :)

Ping @balloob

**Pull request merged**
