### PR TITLE
ADD: Services to fan integration #10622

### PR DESCRIPTION
**Pull request by SoldierCorp**
**Description:**

This PR is for this issue https://github.com/home-assistant/home-assistant.io/issues/10622

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This is an update of our current documentation, and should, therefore, be targeted against and branched of the `current` branch.

Please change the target branch for this PR to `current` and rebase the PR if needed.

Thanks! 👍

**Comment by frenck** [comment]
@SoldierCorp You've now changed the target branch, but it needs to be rebased (since it is now based of the `next` branch, you see a lot of unrelated commits).

**Comment by SoldierCorp** [comment]
Hi,

There is a conflict with a file but I don't want to make a change without knowing what should I do with that file because I didn't make that change

**Comment by frenck** [comment]
@SoldierCorp I'm not sure what you have been doing with the branch, but looking at all of this, I feel like its kinda lost. I'm not able to see your changes anymore.

Let's close this PR. Please create a new one, and make sure you are branching off the correct branch.

**Comment by SoldierCorp** [comment]
@frenck 
Sure,

So I need to work with the `current` branch right?

**Comment by frenck** [comment]
Yep, since it applies to our `current` documentation.

**Pull request closed without merging**
