### PR TITLE
Remove Arlo integration

### PR DESCRIPTION
**Pull request by anaisbetts**
## Proposed change

Updated docs for https://github.com/home-assistant/core/pull/70330

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/70330
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by thecode** [comment]
Code owners and redirects also needs to be updated, see this as an example:
https://github.com/home-assistant/home-assistant.io/pull/21820/files

**Comment by anaisbetts** [comment]
@thecode Will do

**Comment by anaisbetts** [comment]
@thecode This should be good now, there was no CODEOWNER for Arlo (not surprising)

**Review by thecode — APPROVED** [review]
Thanks!

**Comment by frenck** [comment]
This PR is missing a parent PR against the brands repository.

@anaisbetts This needed to be cleaned up too (and linked against this PR): <https://github.com/home-assistant/brands/tree/master/core_integrations/arlo>

CC @thecode

**Comment by thecode** [comment]
- https://github.com/home-assistant/brands/pull/3375

**Pull request merged**
