### PR TITLE
Bigger logo and different text font

### PR DESCRIPTION
**Pull request by johanf85**
## Proposed change

I looked with a critical eye at the homepage and something that I noticed was the current Home Assistant logo. It is sized quite small and the text next to it seems ‘unstyled’. 

**Current**:

The logo is quite detailed, with the ‘branches’ in it, and right now these branches aren’t really well visible. The logo seems a bit modest, I think it can be more pronounced

I found this png in the Assets folder 

Source: [https://raw.githubusercontent.com/home-assistant/assets/master/logo/logo-with-text.png](https://raw.githubusercontent.com/home-assistant/assets/master/logo/logo-with-text.png)   
(unfortunately there was no SVG availble, only PNG)

The font Roboto is used for the text, I ran it through the font identifier on [https://www.fontsquirrel.com/matcherator](https://www.fontsquirrel.com/matcherator) to determine this. If I am right, this logo with text is an official logo, is it still currently in use?

After fiddling with some some CSS properties, to me, this looked better:

The changes are that the logo size went from 36x36 px, to 55x55px wide and height. And applied Roboto font.

In the process of comparing and fiddling I created an SVG with the same size ratio as the [assets/master/logo/logo-with-text.png](https://raw.githubusercontent.com/home-assistant/assets/master/logo/logo-with-text.png) , however  the text seemed too big. 

With lower text size (the SVG file from this PR):

This SVG uses the home-assistant blue with white, without the gradient and shadow. 

## Type of change

*   [x] Spelling, grammar or other readability improvements (`current` branch).
*   [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
*   [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
    *   [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
*   [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
*   [ ] Removed stale or deprecated documentation.

## Additional information

*   Link to parent pull request in the codebase:
*   Link to parent pull request in the Brands repository:
*   This PR fixes or closes issue:

## Checklist

*   [x] This PR uses the correct branch, based on one of the following:
    *   I made a change to the existing documentation and used the `current` branch.
    *   I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
*   [x] The documentation follows the Home Assistant documentation [standards](https://developers.home-assistant.io/docs/documenting/standards).

### CODE REVIEW

**Comment by ludeeus** [comment]
The logo is unreadable <https://deploy-preview-19302--home-assistant-docs.netlify.app/>

**Comment by johanf85** [comment]
Forgot to add the CSS change for the logo image. Now added.

**Comment by balloob** [comment]
It's indeed Roboto. 

I don't think that this logo is one that we should use. I think that we should update it in the assets folder + here.

The truth is that we don't have a logo with text. We just use Roboto to add our name, depending on context it's bold or not.

**Comment by johanf85** [comment]
Allright, you can still make the current logo slightly bigger, but I'll leave that up to you.

**Pull request closed without merging**
