### PR TITLE
Update flux stop_time default.

### PR DESCRIPTION
**Pull request by infernix**
**Description:**

Updated docs for stop_time being set to dusk by default (needs below PR before merge!).

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#12062>

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

### CODE REVIEW

**Comment by fabaff** [comment]
This PR was created against the wrong branch (`current` instead of `next`).

**Comment by infernix** [comment]
The PR template says:
> Fixes, changes and adjustments should be created against current

This consist of a change, does it not?

**Comment by infernix** [comment]
Rebased against next. The PR template is a bit confusing though; I guess I don't consider it a new feature whereas you do :)

**Comment by frenck** [comment]
Thanks for rebasing @infernix!

It is a bit confusing, but since the Home Assistant source code changes are in the dev branch, it will be released in the next release. So, the documentation should be on the `next` branch.

**Pull request merged**
