### PR TITLE
Remove "experimental" status of TI coordinators from ZHA docs

### PR DESCRIPTION
**Pull request by puddly**
## Proposed change

ZHA with TI coordinators is relatively stable at this point so I suggest removing the "experimental" warning. There are also no version restrictions anymore with zigpy-znp.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by Hedda** [comment]
@puddly Suggest also change "CC2531" to "CC253x" since compatible with not only CC2531 but also CC2530 and CC2538 as well:

| Radio Type | Zigbee Radio Hardware |
| ------------- | ------------- |
| `znp` | Texas Instruments (e.g., CC253x, CC26x2, CC13x2, zzh!, Slaesh's coordinator) |

CC253x also match the format used to list CC26x2 and CC13x2 where the 'x' is used to represent multiple varients of those models:

https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/README.md

PS: There are today even more/newer open-source hardware USB-sticks/dongles and GPIO board available from the community:

https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/bin/README.md

**Comment by frenck** [comment]
Let's wait for upstream to decide if this is correct or not. Generally, I think this decision should be up to the maintainers.

**Comment by Hedda** [comment]
FYI please note that @puddly is today one of the core developers of upstream zigpy and zigpy-znp

**Comment by frenck** [comment]
Yes, but the upstream PR is open and not merged.

**Comment by Hedda** [comment]
> Yes, but the upstream PR is open and not merged.

@puddly Bump now that relative https://github.com/zigpy/zigpy/pull/705 and https://github.com/zigpy/zigpy-znp/pull/69 been merged by upstream zigpy/zigpy-znp respectively.

**Review by frenck — APPROVED** [review]
Thanks, @puddly 👍 

../Frenck 🚂

**Pull request merged**
