### PR TITLE
Update zha.markdown to further explain function of ZHA Device Handlers

### PR DESCRIPTION
**Pull request by Gamester17**
**Description:**

Update zha.markdown to further explain the function of ZHA Device Handlers for Home Assistant

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Something for the `current` branch?

**Comment by Gamester17** [comment]
@dmulcahey is comparing ZHA Device Handlers to Zigbee-Shepherd Converters a correct comparison?

If it's a fair comparison, I don't know if this should go into the `current` branch or the `next` branch?

It has no dependencies but not urgent as only meant to help new developers understand the concept.

**Comment by dmulcahey** [comment]
This is fine to put in current

**Comment by Gamester17** [comment]
@klaasnicolaas can you please remove the "needs-rebase" tag and merge to current branch if OK?

**Comment by Gamester17** [comment]
Closing in favor of #9067 for the current branch.

**Pull request closed without merging**
