### PR TITLE
Add documentation for YR forecast data

### PR DESCRIPTION
**Pull request by tinloaf**
**Description:**

Adds documentation for the yr.no forecast feature.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#8650

### CODE REVIEW

**Comment by frenck** [comment]
@tinloaf The parent PR seems to merged some time ago, nevertheless, the documentation is still open since there is a merge conflict on it. Could you be so kind to resolve the conflict and make this PR mergeable? 👍

**Comment by frenck** [comment]
Fixed merge conflict.

**Comment by Konstigt** [comment]
This line:

precipitation: The precipitation.

It must also explain over what period of time? Precipitation the next hour? 3 hour period? day?

**Comment by frenck** [comment]
@Konstigt This pull request is already closed. If you have any additional questions, please try our forum or Discord chat. In case you'd like to propose a change, feel free to open a PR.

**Comment by tinloaf** [comment]
@frenck Oh sorry - I just noticed this issue. No clue how I missed that this was still outstanding. Thanks for fixing!

**Comment by frenck** [comment]
@tinloaf No problem 😉

**Pull request merged**
