### PR TITLE
Add examples of events

### PR DESCRIPTION
**Pull request by gerard33**
## Proposed change
As discussed with @cgtobi in https://community.home-assistant.io/t/netatmo-in-ha-0-105/169377/133?u=gerard33

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue:

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by cgtobi** [comment]
Good point @gerard33. Could we make this a second example as `movement` is valid for indoor/welcome cameras?

**Comment by gerard33** [comment]
Sure thing, added it as a second example.

**Review by cgtobi — APPROVED** [review]
Thanks @gerard33

**Review by frenck — APPROVED** [review]
Thanks, @gerard33! 👍

**Pull request merged**
