### PR TITLE
Airtouch4 integration

### PR DESCRIPTION
**Pull request by samsinnamon**
## Proposed change

Documentation for AirTouch 4 Integration

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [X] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/43513
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/2038
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
There are unrelated commits in this PR. Please run a git rebase to rebase this PR onto the upstream `next` branch. Thanks 👍

**Comment by samsinnamon** [comment]
> There are unrelated commits in this PR. Please run a git rebase to rebase this PR onto the upstream `next` branch. Thanks

Sorry about that!

**Review by frenck — DISMISSED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by AlexanderNZ** [comment]
Just bumping this PR - is it still able to be merged?

**Comment by frenck** [comment]
There is no need to bump, as this PR cannot be merged @AlexanderNZ, as the state is: `awaiting-parent`.
Please don't bump PRs, that is not appreciated or needed. Thanks 👍

**Comment by epenet** [comment]
@AlexanderNZ this PR needs rebase due to conflicting CODEOWNERS

**Comment by frenck** [comment]
@epenet No need to ping people for that, we'll pick that up.

**Review by frenck — APPROVED** [review]

**Pull request merged**
