### PR TITLE
RESTful sensor documentation 

### PR DESCRIPTION
**Pull request by olekenneth**
See https://github.com/home-assistant/home-assistant/pull/13677

**Description:**
Add `json_template` and example

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#13677

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Thanks, @olekenneth! LGTM!

Can be merged as soon as the parent PR gets merged.

**Comment by olekenneth** [comment]
@frenck Can you or someone you know review the https://github.com/home-assistant/home-assistant/pull/13677?

**Comment by frenck** [comment]
@olekenneth We don't handle PR's based on questions. Just be patient, since this is an open source project, we are all volunteering...

**Comment by frenck** [comment]
Closing this PR since the parent PR has been closed as well.

**Pull request closed without merging**
