### PR TITLE
Update sma.markdown

### PR DESCRIPTION
**Pull request by KShips**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @KShips, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#18901).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by kellerza** [comment]
Thanks for the contribution @KShips 

It seems like useful information, but it gives the perception that this might be supported by us. 

A suggestion is to add a new section at the bottom of the page, instead of linking directly in the integrations description. What about?

> ## Alternatives
>
> The SMA integration relies on the WebConnect interface and does not support all SMA devices. 
>
> You can try the following alternatives (not supported directly by Home Assistant):
> - SBFSpot via MQTT (see [here](https://community.home-assistant.io/t/integration-with-sma-solar-stp-10000tl-20-via-sbfspot/204278) for an example)
> - [SMA Energy Meter Add-on](https://github.com/kellerza/hassio-sma-em)

**Review by frenck — COMMENTED** [review]
The added text is not about this integration. We do not support custom-made integrations or workaround in our official documentation.

Nevertheless, thanks for willing to contribute 👍

**Comment by KShips** [comment]
> Thanks for the contribution @KShips
> 
> It seems like useful information, but it gives the perception that this might be supported by us.
> 
> A suggestion is to add a new section at the bottom of the page, instead of linking directly in the integrations description. What about?
> 


Perfect, yeah good point about support.

 I've pulled my hair put trying to get inverter working on HA only to stumble on the forum by chance, hope having resource like this would help others.

**Comment by kellerza** [comment]
Agree with @frenck

@KShips my proposal is to add the alternative options to the pysma's README. But please also make it clear that it is not supported there, but alternative place to explore, so keep it as a section toward the end

**Pull request closed without merging**
