### PR TITLE
tiny text improvements

### PR DESCRIPTION
**Pull request by Mariusthvdb**
tidied up a bit

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by raman325** [comment]
this needs a rebase/cleanup

**Comment by Mariusthvdb** [comment]
tbh, I am uncertain what to do now. Am I allowed to click the "Resolve conflicts" button without getting into trouble?
Also, I have not purposely requested all of those code-owners at all, I merely rebased from next to current branch..

apologize for any inconvenience

**Comment by raman325** [comment]
yes you can, but before you do that, you need to rebase and drop all of the commits that aren't yours.

It's painful but:
1. `git rebase -i HEAD~65` opens the last 65 commits in a text editor
2. For every commit that isn't yours switch `pick` to `drop` or `d`
3. Save and quit
4. `git push origin --force`

**Comment by raman325** [comment]
or you can start over, whatever makes more sense for you

**Comment by raman325** [comment]
oh you probably created your branch off of `next` but want to merge to `current` hence the extra commits

**Comment by raman325** [comment]
you could just do `git pull upstream current --rebase` and I think that will remove all of the other commits. Still need a `git push origin --force` though

**Comment by Mariusthvdb** [comment]
yes, that is what happened. no way to simply "go back"...?

simplest would be to close and start over otherwise. doing this from the vscode browser interface, so no git commands I believe.

**Comment by Mariusthvdb** [comment]
let me restart, closing this.
again apologies

**Comment by raman325** [comment]
no worries

**Pull request closed without merging**
