### PR TITLE
Add documentation for Bedrock Edition

### PR DESCRIPTION
**Pull request by jdeath**
## Proposed change

Documentation for Bedrock Edition feature addition to minecraft_server component
home-assistant/core#47430

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/47430
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by frenck** [comment]
Seems like this belongs to PR https://github.com/home-assistant/core/pull/47430 ?

**Comment by jdeath** [comment]
Yes.

**Comment by klaasnicolaas** [comment]
If there is a relationship with the pull request in core then the target branch here must be `next`, possibly a rebase must be performed.

**Review by frenck — CHANGES_REQUESTED** [review]
Klaas is correct.

Please link to the upstream code change in the PR description (so this PR and the core PR are linked up).

Additionally, this relies on an next release of Home Assistant, therefore, this PR must target the `next` branch.

Please change the target branch of this PR to `next` and git rebase this PR onto the `next` branch if unrelated commits show up.

**Comment by jdeath** [comment]
ok. I hope I did everything correctly. Sorry, new to this.

**Comment by frenck** [comment]
There are unrelated commits in this PR, you'll need to perform a git rebase onto the `next` branch, as the current branch was originally made from the `current` branch.

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
