### PR TITLE
Add lg_netcast turn_on_action configuration variable

### PR DESCRIPTION
**Pull request by maxcanna**
## Proposed change

Adds `turn_on_action`

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/home-assistant/pull/31792
- This PR fixes or closes issue:

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Please rebase your PR to the `next` branch

**Comment by maxcanna** [comment]
Done, thank you @klaasnicolaas

**Comment by klaasnicolaas** [comment]
Can you add an advanced example like in the code base repo? Think otherwise people don't know what to do with `turn_on_action`

**Comment by maxcanna** [comment]
Done, thank you again @klaasnicolaas (sorry for the push force, it's just to avoid squashing later)

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by healeydave** [comment]
Sorry to drag up an old request, but did this ever get implemented, because I have followed the guide lines and if the TV is already on, I can get access to its media player entity but if the tv is already off or I turn it off from this entity, I can't turn the tv on despite this fix addressing this exact issue.

**Comment by frenck** [comment]
If you want to report a bug @healeydave, then please create an issue in our issue tracker. Thanks 👍

**Pull request merged**
