### PR TITLE
Documents rest_command header templates usage

### PR DESCRIPTION
**Pull request by pedrolamas**
**Description:**
Adds example for templates usage in rest_command headers.

**Pull request in home-assistant:** home-assistant/home-assistant#26099

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

<a href="https://gitpod.io/#https://github.com/home-assistant/home-assistant.io/pull/10213"></a>

### CODE REVIEW

**Review by DubhAd — DISMISSED** [review]
👍

**Comment by pedrolamas** [comment]
Rebased in order to take new paths (no other changes), @DubhAd can you please re-check?

**Review by DubhAd — APPROVED** [review]
👍

**Review by frenck — APPROVED** [review]
Thanks, @PedroLamas! 👍

**Pull request merged**
