### PR TITLE
Adding colors to light templates

### PR DESCRIPTION
**Pull request by grea09**
These modifications go along [this pull request](https://github.com/home-assistant/home-assistant/pull/12439/).
I added an example for a common classes of IR remote lights.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by arsaboo — DISMISSED** [review]
Looks good...can be merged when the parent PR is merged 🍪 👍

**Comment by c727** [comment]
base should be `next` for this PR

**Review by frenck — DISMISSED** [review]

**Comment by frenck** [comment]
@grea09 Thank you for this first contribution to the documentation! 🥇 

I've made tiny changes to your PR and changed to base to `next`. 
Can be merged as soon as the parent PR gets merged. 👍

**Comment by frenck** [comment]
Rebased the PR in order to fix the build

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
The parent PR is still open. Re-opening this.

**Comment by frenck** [comment]
Parent has been closed. Closing this one as well. Feel free to re-open when ready.

**Comment by chimpy** [comment]
Such a shame that this didn't get merged.

**Comment by grea09** [comment]
I will see if I can do it again properly.

**Comment by brianewman** [comment]
Any chance of this becoming a thing?

**Pull request closed without merging**
