### PR TITLE
Add breaking changes details

### PR DESCRIPTION
**Pull request by Kane610**

### CODE REVIEW

**Comment by frenck** [comment]
Hi @Kane610!

Thanks for your PR! PRs should never target the `rc` branch, so something is off here.
If your change is an improvement on the current release documentation, please target the `current` branch. If your change depends on a change in the code base, please use the `next` branch and be sure to link the parent PR. Also, rebase if needed.

On that topic, please do not remove the PR template.

Awaiting your response and action.

**Comment by Kane610** [comment]
Nothing is off, this is the place to update the blog post for next release. This PR updates the breaking changes section with more details. I created the PR rather than merging the fix directly just to have a second pair of eyes on it first.

**Comment by frenck** [comment]
👍 As per Discord, it was unclear to me and missed your intentions.
Thanks!

**Comment by balloob** [comment]
Shit I totally missed this PR and did it myself.  :( sorry

**Comment by Kane610** [comment]
Next time I will just merge it directly :)

**Comment by balloob** [comment]
You should !

**Pull request closed without merging**
