### PR TITLE
Remove unnecessary script usage

### PR DESCRIPTION
**Pull request by scottocs11**
**Description:**
Scripts are not necessary to perform this automation.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

### CODE REVIEW

**Comment by scottocs11** [comment]
After posting an example, someone [pointed out](https://www.reddit.com/r/homeassistant/comments/5vt72e/im_posting_my_configuration_files_for_all_to_view/de5h3rs/) how much unnecessary coding is used in this example.

**Comment by Landrash** [comment]
@scottocs11 That's a long living example for the beginning of HA.
@fabaff Where should this be merged?

**Comment by fabaff** [comment]
`current` is ok.

**Comment by joaoasilva** [comment]
This example is not right.
The light will turn off ALWAYS even if the sensor detects more movement after it goes to the 'off' state, doesn't reset the timer. The old example is the right logic and the proper implementation.

**Comment by scottocs11** [comment]
@joaoasilva No, it will wait 10 minutes after the last movement to turn the light off. The automation to turn the light off checks to see if the motion sensor has been off for 10 minutes.

**Pull request merged**
