### PR TITLE
Update the motion activated light example

### PR DESCRIPTION
**Pull request by RiRomain**
**Description:**
Make use of the new timer component for the motion activated light example.
It allow the user to cancel the timer if needed, extend it, pause it, ...

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by DubhAd** [comment]
I'd personally prefer to see it as an additional example, rather than replacing the existing one.

**Comment by RiRomain** [comment]
It might be confusing, no? Beginner usually don't really know what they need and might be confused by which of the two they should use and why.
I think the previous (current) example have no advantage over the timer.

**Comment by frenck** [comment]
I think this is confusing as well and agree with @DubhAd on making this an additional example as well.

The timer allows for additional actions (like you described, extend it, pause it e.d.).
But that's not the point of this example. It added an extra moving part (the timer) without any additional functionality.

So if you decide to add it as an additional example, I'd suggest on enriching it with a reason to use the timer instead of the current method (e.g., add something to pause/unpause it).

**Review by frenck — CHANGES_REQUESTED** [review]
See comments above.

**Comment by RiRomain** [comment]
> without any additional functionality

I cannot really agree with that, the solution with the timer allow to use any trigger. While the current solution only allow state trigger.

I use an mqtt trigger, which doesn't have a state but only a trigger event, it simply doesn't work with the state trigger and an automation based on its own state
```
    trigger:
      - platform: mqtt
        topic: home/movementsensor1
        payload: 1
```

**Comment by DubhAd** [comment]
So add it as a second way of achieving the goal. For people new to HA, the `for` option is simpler and self contained. Then your suggestion can become the _advanced_ method.

**Comment by RiRomain** [comment]
This might be confusing, having 2 automation offering the same feature. Let's leave the current one.

**Pull request closed without merging**
