### PR TITLE
Fixing common spelling mistakes

### PR DESCRIPTION
**Pull request by AshtonCampbell**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

I was able to run a program to find common spelling mistakes to help with any typos found. I personally went over every single file change to make sure that these were correct. I want to note that there were some spelling mistakes that weren't actual mistakes and I went in and reverted those changes back with new commits. Again I would like to reiterate that there were some markdown files for example that the program mistook as spelling mistakes but these were changed with new commits and were reverted back to their previous versions before spell checking.

If you have any questions or concerns, don't hesitate to ask. :)

Edit: I was told I was able to push to current so that's what I did rather than next.

### CODE REVIEW

**Comment by AshtonCampbell** [comment]
My apologies, I'm a bit newer to git and didn't mean to merge all their commits as well. Do you mind sending me some documentation to follow to properly clean the branch?

I suppose I could just push it to `next` rather than `current` as it will only commit my changes but I believe you prefer it be pushed to `current`. I've been reading up about head, revert, reflog, etc... but not sure the best way to get it done.

**Comment by AshtonCampbell** [comment]
I'm going to go ahead and close this pull request and reopen when I have solved the issue. I believe I just made it worse.

**Comment by fabaff** [comment]
Start with a new branch checked-out from an up-to-date `current` branch.

**Comment by fabaff** [comment]
Sometimes you could rebase your branch and then force a push.

**Comment by AshtonCampbell** [comment]
I figured it out, going to be submitting another pull request if that's okay? :)

**Comment by fabaff** [comment]
Sure. Less work for us to just merge a PR :wink:

**Comment by AshtonCampbell** [comment]
Whatever helps! 😛 

New PR sent out.

**Pull request closed without merging**
