### PR TITLE
Elmax/cover

### PR DESCRIPTION
**Pull request by albertogeniola**
## Proposed change

Declaring alarm_control_panel and cover platforms support.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/79409
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
There are unrelated commits in this PR. Please git rebase your changes onto the latest upstream next branch in order to clean that up.

Thanks 👍 

../Frenck

**Comment by albertogeniola** [comment]
> There are unrelated commits in this PR. Please git rebase your changes onto the latest upstream next branch in order to clean that up.
> 
> Thanks 👍
> 
> ../Frenck

Should be fine now @frenck! Sorry for having included that commit.
Can you confirm it's all in place and merge please?

Thanks!

**Comment by frenck** [comment]
> and merge please?

That is not possible, as it depends on an upstream change in the core codebase (the cover platform isn't merged).

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by xGeKox** [comment]
Hi guys. Update for implementation?

**Comment by xGeKox** [comment]
Any updates?

**Pull request merged**
