### PR TITLE
ha_iot_class in facets

### PR DESCRIPTION
**Pull request by arthurlutz**
Related to #8502 and #6387

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
#8502 has been closed and not merged, how does this PR related to a closed one?
Could you please clarify?

- Addition of iot_classes has not been completed as well, I'm not sure if this is the right timing.
- iot_class is misused in some places by listing multiple, you've updated that to be `,` separated? Why not turn it into a list?
- PR should target the `current` branch.

Secondly, you start opening PR on structural changes like a train...
Could you please stop that and start discussing things in the appropriate locations, please?

Thanks.

**Comment by balloob** [comment]
Breaks the component page + we cannot put IoT class in the same list as the categories.

image

**Comment by arthurlutz** [comment]
@balloob indeed, thanks for taking a look. Some CSS is probably required to distinguish categories and the IOT_class part. (:heart: netlify). Am also having difficulties setting up my local jekyll setup (more of a python person than ruby, so am a bit lost, but finding my way).  

@frenck here are a few answers : 

* it feels like the coverage of iot_class is pretty good to start using it, but I can understand that this change could have to wait for the coverage to be greater (having this view also helps check the consistency and might help in going through the components which are missing this information or where it is not applicable)
* you're right about the list, I'll fix to avoid parsing strings
* can you explain why the PR should target main branch ? the PR template asks to target next
* I'd rather try out code and discuss over netlify and screenshots instead of over-engineering in issues, this helps me get into jekyll and the documentation, and I fully understand that these PR will not be accepted as is, and that they will require improvements or not fit the needs and be closed

**Comment by frenck** [comment]
@arthurlutz As per PR template: 
> `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release.

Since this change has no upstream change in our code base and thus does not depend on the next Home Assistant release; it should go into `current`.

**Comment by klaasnicolaas** [comment]
Will close it for now, feel free to open it when the time is there 😉

**Pull request closed without merging**
