### PR TITLE
Update Rflink hub component configuration

### PR DESCRIPTION
**Pull request by javicalle**
**Description:**
Update style of Rflink light component documentation to follow new configuration variables description.
Related to #6385.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by klaasnicolaas — COMMENTED** [review]
Nice your first PR, welcome!

A suggestion: maybe one `.` behind the description sentences.
And you have to merge your PR in the `current` branch.
And there are 2 variables that you could add (fire event and signal repetitions), [see more](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/rflink.py)

**Comment by javicalle** [comment]
@klaasnicolaas Thanks for the review
> A suggestion: maybe one . behind the description sentences.

Are you refering to the `{% configuration %}` block, rigth?  What's the purpose of this?
> And you have to merge your PR in the current branch.

I'm working on it (I'm new in Git)
> And there are 2 variables that you could add (fire event and signal repetitions), see more

I'm not sure if that variables are used in platform definition. I will take another look to code.

**Comment by javicalle** [comment]
I have understood the issue of putting the dot _behind_ sentences. My fault, english is not my primary language.
I have changed the base branch for the PR, but now I see a lot of changed files. Please @klaasnicolaas, can you be kind enought to review this point. I just changed one file and I don't want to make a mess.

**Comment by javicalle** [comment]
Finally I have decided to close this PR.
I have opened another (correct, I hope) (PR #7171)

Sorry for the inconvenience.

**Pull request closed without merging**
