### PR TITLE
Unit_of_measurement_template

### PR DESCRIPTION
**Pull request by nessinot**
In PR  #22033 the unit_of_measurement_template is added. This is the documentation change to reflect this.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#22033

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
You first need to rebase this PR

**Comment by nessinot** [comment]
> You first need to rebase this PR

With some googling I tried to rebase, but not sure if I manged to do so. If not, could you give me some additional hints on how to make this happen?

I have installed git, I cloned the repository and have the branch locally.

**Comment by klaasnicolaas** [comment]
We can also do the rebase

**Comment by nessinot** [comment]
Yes please :-)

**Comment by frenck** [comment]
To be honest here @nessinot, since you've merged in things, probably to the only solution is to make a new PR.

**Comment by frenck** [comment]
Closing this PR, since the parent PR has been closed.

**Pull request closed without merging**
