### PR TITLE
Add formats and examples to "aspect_ratio"

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Outline all valid formats with examples and use the same text for all elements that support "aspect_ratio".

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by spacegaier** [comment]
Is there a way in the docs to define a text somewhere once and link/include it somewhere else? Then we could just have the aspect_ratio explanation defined once and use it on the various cards.

**Comment by ludeeus** [comment]
> Is there a way in the docs to define a text somewhere once and link/include it somewhere else? Then we could just have the aspect_ratio explanation defined once and use it on the various cards.

There is a concept or include.
The includable element needs to be added to `source/_includes` (preferably a sub dir of that)
You can then use `{% include subdir/element.md %}` to reference it

**Comment by frenck** [comment]
I would avoid include for just a couple of occurrences.

It can become pretty complicated pretty fast. The more plain markdown we have, the easier it is to get contributions and keep things understandable.

**Review by frenck — APPROVED** [review]
Thanks, @spacegaier 👍

**Pull request merged**
