### PR TITLE
Optimistic switch template

### PR DESCRIPTION
**Pull request by akloeckner**
## Proposed change

Document optimistic mode for template switch (see also light).

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/home-assistant/pull/31637
- This PR fixes or closes issue: none

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
There are some unrelated commits. Please update the branch on your fork and perform a rebase if necessary.

**Comment by akloeckner** [comment]
Done. 

Just to note: I simply clicked the "edit this page on github" link in the documentation. Is that broken?

**Comment by frenck** [comment]
@akloeckner It isn't broken. You probably branched of the `current` branch 😉

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Review by frenck — APPROVED** [review]
Than

**Pull request merged**
