### PR TITLE
Change upgrade homeassistant to upgrade home-assistant

### PR DESCRIPTION
**Pull request by IainPHay**
Correct
You can also use `hassbian-config` to automate the process by running `sudo hassbian-config upgrade homeassistant`
to
You can also use `hassbian-config` to automate the process by running `sudo hassbian-config upgrade home-assistant`

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by DubhAd — APPROVED** [review]
👍

**Comment by ludeeus** [comment]
@dubhAd this should be reverted since it breaks the syntax of the current version

**Comment by DubhAd** [comment]
@ludeeus Do you want to provide an update edit, and it can get approved

**Comment by ludeeus** [comment]
@DubhAd we did that 19 days ago :)
https://github.com/home-assistant/home-assistant.github.io/pull/4819

There are some other issues about the Hassbian documentation as well, I will try to get to it during this week :)

**Pull request merged**
