### PR TITLE
Update image.markdown

### PR DESCRIPTION
**Pull request by ildar170975**
~Removed "static", may be used to display a dynamically changing gif image.~
Removed "static", may be used to display a gif image.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by frenck** [comment]
Can you explain to me what a Dynamic change gif image entails?

**Comment by ildar170975** [comment]
> Can you explain to me what a Dynamic change gif image entails?

Means - image is not CONSTANT, it is changing.
For instance:
```
template:
  - image:
      - name: test_weather
        url: https://meteoinfo.ru/hmc-output/rmap/phenomena.gif
```
The word "static" may create a wrong impression - like "only static jpg" etc.

**Comment by frenck** [comment]
That image you linked is a static file. If you never update the entity or image, the image will always remain the same (thus static). The file might be replaced at times, but it is static on the URL you've provided.

Could you explain the dynamic thing about it? As the only "dynamic" image format I'm aware of, is basically MJPEG (for which this entity isn't meant).

../Frenck

**Comment by ildar170975** [comment]
> That image you linked is a static file

Correct, but presentation of this image is CHANGING.
The "static image" for most people is "an image which is not changing" (image, not a file).

**Comment by frenck** [comment]
> Correct, but presentation of this image is CHANGING.

It is not, it shows the same static frames over and over again.

Unless you have a different file then I get over the URL given above, this is a static image.

../Frenck

**Comment by ildar170975** [comment]
> It is not, it shows the same static frames over and over again.

But this is not a static picture - it is "moving pictures".
As a programmer you are correct; I am basically trying to think as an average person.

**Comment by frenck** [comment]
But your PR states:

> Removed "static", may be used to display a dynamically changing gif image.

And that simply doesn't exist? Even from a non-programmer perspective, the statement used to motivate this PR makes no sense in any world. There is no such thing as a dynamically changing gif image (unless you want to educate me on it; I'm happy to look at such a thing, as that would open lots of possibilities I guess).

Even worse, if you would use it to display an actual dynamic image, it would break (which I now realize is a bug in Core). Thus the addition of "static" is correct IMHO.

../Frenck

**Comment by ildar170975** [comment]
> And that simply doesn't exists? Even from a non-programmer perspective, the statement used to motivate this PR makes no sense in any world. There is no such thing as a dynamic changing gig image (unless you want to educate on it).

I may change the description of this PR in the 1st post if you think that it is meaningless.
But the idea is same: the presentation of the image may be not static (in case of using gif).
As I said, GIFs with "moving pictures" (does not matter that it is "over and over") are not considered as "static image" by most of people.

**Comment by frenck** [comment]
Sorry, I think that motivation and concept is incorrect, even from a user perspective.

To put it into a true end-user worded perspective, there must be a clear distinction between the `image` and `camera` entities. Both provide an image for the user; one is truly moving/live/dynamic, while the other provides static images. A `gif` is a static image (even though it is animated, it will not update).

For that reason, I'm going to friendly decline the suggestion made.

../Frenck

**Comment by ildar170975** [comment]
What Google says:

https://www.google.com/search?q=what+is+a+static+gif&newwindow=1&sxsrf=AB5stBh32EUBWjTv_hzAeHQwLFjnL3szkQ%3A1689009760889&source=hp&ei=YD6sZKOONKGqrgSU36fACg&iflsig=AD69kcEAAAAAZKxMcFuKxkMGfeBltNuJZfZ7rKBsp8ss&oq=is+gif+a+stat&gs_lcp=Cgdnd3Mtd2l6EAEYADIGCAAQFhAeMgYIABAWEB46BwgjEIoFECc6BAgjECc6CwgAEIAEELEDEIMBOggIABCABBCxAzoRCC4QgAQQsQMQgwEQxwEQ0QM6CwguEIAEELEDEIMBOgUIABCABDoOCC4QgAQQsQMQxwEQ0QM6CwgAEIoFELEDEIMBOgUILhCABDoHCAAQigUQQzoICAAQgAQQywE6BggAEB4QDToICAAQFhAeEA9QAFj2HGDDVWgAcAB4AIABeIgBkgeSAQQxMi4xmAEAoAEB&sclient=gws-wiz

image

Means - some GIFs are not "static".


> Both provide an image for the user; one is truly moving/live/dynamic, while the other provides static images.

To follow this policy, you will have to prevent using GIFs with several frames for images...

**Comment by frenck** [comment]
Thanks, but that definition defines it from a "gif" level perspective (static vs non-static gif), this documentation is defined from the integration level which generalizes that image shown to the user in general. The `gif` aspect is not relevant in this case.

As pointed out in my previous response on images.

../Frenck

**Comment by ildar170975** [comment]
Well, no problem, just was going to add some clarity for beginners 
🤷

**Pull request closed without merging**
