### PR TITLE
Include AEP utilities in the list of Opower supported utilities

### PR DESCRIPTION
**Pull request by tronikos**
## Proposed change

Include AEP utilities in the list of supported utilities. This needs to be included in rc to be included in 2024.1 that will include https://github.com/home-assistant/core/pull/105957

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/105957
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by davet2001 — DISMISSED** [review]
Thanks @tronikos!

The grammar/structure look good and the content is accurate at least as far as the current Wikipedia entry goes!

**Comment by davet2001** [comment]
@tronikos I changed the target branch based on the PR description. Please could you check and update if necessary?

**Comment by davet2001** [comment]
Scratch that, as not sure what the protocol is, it could be that this needs cherry picking after merge to get into rc?

**Review by davet2001 — APPROVED** [review]

**Comment by tronikos** [comment]
https://github.com/home-assistant/home-assistant.io/pull/30636

**Pull request closed without merging**
