### PR TITLE
Update lacrosse_view HA version to 2022.9

### PR DESCRIPTION
**Pull request by IceBotYT**
## Proposed change

I am correcting the version number in the documentation for the lacrosse_view integration

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/71896
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by IceBotYT** [comment]
> It seems that this PR is targeted against an incorrect branch. Documentation updates which apply to our current stable release should target the `current` branch. Please change the target branch of this PR to `current` and rebase if needed. If this is documentation for a new feature, please add a link to that PR in your description.
> (message by DocsTargetBranch)

This is fixing a docs page that is not released yet. This is why I’m pointing it to `next`

**Review by klaasnicolaas — APPROVED** [review]
✅ LGTM

**Comment by IceBotYT** [comment]
Hey, you seem to have typed "git co" into the file instead of the terminal. Can you see if you can fix that?

**Comment by klaasnicolaas** [comment]
It is solved 👍🏻

**Pull request merged**
