### PR TITLE
Update growatt_server.markdown

### PR DESCRIPTION
**Pull request by chenjiayi8**
Update documentary associated to PR: Update Growatt server URLs (https://github.com/home-assistant/core/pull/109122)

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:  (https://github.com/home-assistant/core/pull/109122)
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Please rebase to the `next` branch.

**Comment by chenjiayi8** [comment]
> Please rebase to the `next` branch.

Please check if I have rebased correctly. @klaasnicolaas

**Comment by anandlar** [comment]
@chenjiayi8 
Hi, I'm trying to follow the process but I am not a developer :-(.  It seems like you have solved the problem with the wrong url for Growatt integration and you are now testing it. 
Is it possible for me to try? How do I update my HA with the new testrelease?
BR Anders

**Comment by chenjiayi8** [comment]
@anandlar 
# Preparation
If you have some basic experiences to work on the Linux environment. Please consult these tutorials to have an identical test environment:

1. [installing Docker in Ubuntu on the Docker Docs website](https://docs.docker.com/engine/install/ubuntu/).
2. ["Linux - Home Assistant" on home-assistant.io](https://www.home-assistant.io/installation/linux/)

I will use `DOCKER COMPOSE` section in the second tutorial to give you an example:

You first need to create an empty folder for testing. In this folder, you need to create a `docker-compose.yml` file. You can find an example in the second tutorial, or you can use mine. This is my `docker-compose.yml`:
```
version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - ./growatt/const.py:/usr/src/homeassistant/homeassistant/components/growatt_server/const.py:ro
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
 
   ```

In your testing folder, you need to make two folders called `config` and `growatt`. In folder `growatt`, you need to create a python file `const.py`:

```
"""Define constants for the Growatt Server component."""
from homeassistant.const import Platform

CONF_PLANT_ID = "plant_id"

DEFAULT_PLANT_ID = "0"

DEFAULT_NAME = "Growatt"

SERVER_URLS = [
    "https://openapi.growatt.com/",  # Other regional server
    "https://openapi-cn.growatt.com/",  # Chinese server
    "https://openapi-us.growatt.com/",  # North American server
    "http://server.smten.com/",  # smten server
]

DEPRECATED_URLS = [
    "https://server.growatt.com/",
    "https://server-api.growatt.com/",
    "https://server-us.growatt.com/",
]

DEFAULT_URL = SERVER_URLS[0]

DOMAIN = "growatt_server"

PLATFORMS = [Platform.SENSOR]

LOGIN_INVALID_AUTH_CODE = "502"
```

In this way you create the updated `const.py` file and mount it  to `components/growatt_server`.

# Testing
Start it by running:
```
docker compose up -d
```
Once the Home Assistant Container is running, Home Assistant should be accessible using http://<host>:8123 (replace with the hostname or IP of the system).

I assume that you have experiences to use `Home Assistant` and install the `Growatt` integration.

# Cleaning
When you are done the testing, you can close the docker container
```
docker compose down -v
```
You may remove the whole testing folder now.

# Sharing
Please share your testing result with me, so I can improve this pull request.

**Review by frenck — APPROVED** [review]
Thanks, @chenjiayi8 👍

**Pull request merged**
