### PR TITLE
Clarify Orange Pi

### PR DESCRIPTION
**Pull request by pascallj**
## Proposed change

* Use Orange Pi GPIO as integration name
  * Change is also reflected in `manifest.json`.
* Make configuration subheader of Binary Sensor
* Add section Orange Pi limitations
  * It depends on the device which pins are actually usable for sensors. This section should clarify that. As pointed out by: home-assistant/core#30790.

## Type of change

- [X] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue:

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by pascallj** [comment]
I think Probot thinks there is a parent PR because of the linked issue from core. This linked issue is only for future reference and therefore there is no parent PR and no need to rebase.

**Review by frenck — APPROVED** [review]
Thanks for the PR @pascallj!

It indeed based that message on the fact it was linked to a parent PR. We can ignore that in this case 👍 

I've made a couple of small adjustments, so it matches the rest of our documentation.

**Comment by pascallj** [comment]
Thank you.

But in that case, shouldn't 2e91611 be reverted?

**Comment by frenck** [comment]
Oh right, or a new PR...

**Comment by pascallj** [comment]
> Oh right, or a new PR...

#12928, done.

**Pull request merged**
