### PR TITLE
Remove deprecated YAML config from bmw_connected_drive

### PR DESCRIPTION
**Pull request by rikroe**
## Proposed change

* Remove legacy YAML configuration (https://github.com/home-assistant/core/pull/66965)
* ~Remove "send location" option (https://github.com/home-assistant/core/pull/60938) - missed that one earlier~ (now in https://github.com/home-assistant/home-assistant.io/pull/21728)

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/66965
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by killer0071234 — DISMISSED** [review]

**Review by frenck — CHANGES_REQUESTED** [review]
@rikroe There are 2 PR listed in this PR. That is not correct. One parent PR is merged, the other is not. Meaning this PR cannot be merged and the documentation is out of sync.

Please open a documentation PR for each PR. 

Thanks! 👍 

../Frenck

**Comment by rikroe** [comment]
Moved the change against `current` to https://github.com/home-assistant/home-assistant.io/pull/21728

**Comment by frenck** [comment]
@rikroe Could you resolve the merge conflict?

**Comment by rikroe** [comment]
Rebased and resolved the conflict.

However this line might create merge conflict agains current: https://github.com/home-assistant/home-assistant.io/pull/21714/files#diff-cbd0dcc012c871642b6ab81d62d0f7f3aeb1edaf49d9937e06752f6441784085R62 as this line is removed in current.

EDIT: Nevermind, that was the sole reason for the rebase being necessary...

**Review by frenck — APPROVED** [review]
Thanks, @rikroe 👍

**Pull request merged**
