### PR TITLE
Add removal instructions for HomeWizard

### PR DESCRIPTION
**Pull request by DCSBL**
## Proposed change

SSIA, for https://developers.home-assistant.io/docs/core/integration-quality-scale/rules/docs-removal-instructions/

The change is for 'current', but it seems that `{% include common-tasks/remove_device_service.md %}` is not yet final, so I targeted it for next

image

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/131370
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

## Summary by CodeRabbit

- **Documentation**
	- Added a new section to the HomeWizard Energy integration documentation on disabling the local API after deleting the integration.
	- Emphasized the importance of managing local API settings to prevent conflicts with other integrations.

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @DCSBL 👍 

../Frenck

**Comment by klaasnicolaas** [comment]
Is this in the wrong branch? Also the include is not correct.

./Klaas

**Comment by frenck** [comment]
It is correct on that branch...

Considering the next release containing it, I would be fine with it... but yeah it might cause issues. Will merge back and fix it in that effort (as build will fail)

**Comment by DCSBL** [comment]
In current it is `{% include integrations/remove_device_service.md %}` and in next it is `{% include common-tasks/remove_device_service.md %}`. Not sure which we want to use.

**Comment by DCSBL** [comment]
For streamlining I can open a PR that uses the 'current' branch and match to what is used by other integrations and remove this variant. It will be a replace-all operation then, I think

**Comment by klaasnicolaas** [comment]
@DCSBL it will be `{% include integrations/remove_device_service.md %}`

./Klaas

**Comment by frenck** [comment]
I'll pick this one up tomorrow when I sync the branches in preparation for the beta cut next week 👍

**Pull request merged**
