### PR TITLE
Amendment comments for plugwise platform update

### PR DESCRIPTION
**Pull request by CoMPaTech**
## Proposed change
As [commented](https://github.com/home-assistant/home-assistant.io/pull/13640#pullrequestreview-422653832) by co-author in #13640 some small changes:

> Sorry, I'm a little late :)
> 
> 23: `climate`: a single Tom can also be a climate-entity. Please add Tom in the list.
> 140: typo nd --> and
> 29, 141: plug --> Plug

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: home-assistant/core#36383 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by bouwew** [comment]
Very good, thanks!

**Comment by CoMPaTech** [comment]
Add changes due to #36378 (adding binary_sensor)

**Comment by CoMPaTech** [comment]
Temp. set to draft as homeassistant.core#36383 is also running

**Comment by frenck** [comment]
@CoMPaTech ? That core PR you are referencing has been merged already, why is this draft?

**Comment by CoMPaTech** [comment]
I'll reference the ones this one is against. It started out as changes to the amendment.

**Review by bouwew — APPROVED** [review]
Looking good!

**Comment by CoMPaTech** [comment]
@frenck sorry for the inconvenience, due to the great efforts of Nick and Martin we are all-in for beta. The #36383 is approved and most likely will be merged as soon as testing is done with it and this can go as well.

**Review by bouwew — APPROVED** [review]

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Pull request merged**
