### PR TITLE
Add apply_filter to recorder.purge service

### PR DESCRIPTION
**Pull request by cdce8p**
## Proposed change

Add `apply_filter` attribute to `recorder.purge` service.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/45826
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by cdce8p** [comment]
This PR is ready for review and merge. Just needed to do a small last minute update. Not quite sure though, why the build isn't passing. Seems like a dependency issue.

**Comment by cdce8p** [comment]
@frenck Can you merge `current` into `next` again? The CI issue is likely related to #16929

**Comment by cdce8p** [comment]
@bdraco Would you mind taking a quick look at this? It's the documentation for the `apply_filter` feature. https://github.com/home-assistant/core/pull/45826

**Review by frenck — APPROVED** [review]
Thanks, @cdce8p 👍

**Pull request merged**
