### PR TITLE
Xiaomi Mijia LED Desk Lamp added to the list of supported yeelights

### PR DESCRIPTION
**Pull request by syssi**

### CODE REVIEW

**Review by akubak — APPROVED** [review]
Maybe also add a bit at the end saying “(...... - this was confirmed with the Yeelight team)”

**Comment by akubak** [comment]
You could also mention that it’s due to the small amount of ram.

**Comment by syssi** [comment]
I updated the note.

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Rebased the PR onto `current`. Can be merged as soon as the build passes.

**Pull request merged**
