### PR TITLE
Prepare for full scope with HA Cloud Link

### PR DESCRIPTION
**Pull request by cgtobi**
Prepare for full scope with HA Cloud Link with support by Netatmo.

## Proposed change

Prepare for full scope with HA Cloud Link.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
✅ I think this is fine. Feel free to merge when ready.

**Comment by cgtobi** [comment]
Thanks @frenck, this will be merged once Netatmo grants us full scope.

**Comment by frenck** [comment]
Yeah I was aware. Hence me reviewing it, so it ready to go when that happens

**Comment by cgtobi** [comment]
Still waiting for Netatmo to grant us full access.

**Review by balloob — APPROVED** [review]
Looks great !

**Pull request merged**
