### PR TITLE
Remove IFTTT from featured integrations

### PR DESCRIPTION
**Pull request by hmmbob**
## Proposed change

Yesterday, IFTTT [announced](https://ifttt.com/explore/introducing_ifttt_pro) that they will be limiting the free tier of their service to just 3 applets, while asking $10/month for unlimited applets. This does not align with the [HA Vision](https://www.home-assistant.io/blog/2016/01/19/perfect-home-automation/) and therefore IFTTT should not be a featured integration on the integrations page. This change removes their banner from the featured integrations page and the home page.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by balloob — DISMISSED** [review]
Looks good.

Can you also remove it from the home page?

**Comment by hmmbob** [comment]
Will do in this same PR.

**Comment by hmmbob** [comment]
Done.

**Review by frenck — APPROVED** [review]
Thanks, @hmmbob 👍

**Pull request merged**
