### PR TITLE
Add note about DirecTV requirements

### PR DESCRIPTION
**Pull request by ctalkington**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue:

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — APPROVED** [review]

**Comment by jscherry** [comment]
What would be causing the directv integration to be giving me these errors? ERROR (SyncWorker_3) [homeassistant.components.directv.media_player] media_player.bonus_room: Invalid status 501 received. I've updated to all the recent ha versions. Now on 107.2 running docker in Ubuntu VM. It has done this from the beginning of using the integration and floods the log files? Any help would be greatly appreciated.

**Comment by ctalkington** [comment]
@jscherry well 501 normally means Not Implemented but the code isnt documented in the DIRECTV SHEF protocol guide available to public 

Is that receiver client an older unit? How is it connected?

Please post a core issue with such info.

**Comment by jscherry** [comment]
It’s connected to two other dvrs through Moca adapters and connected to the internet with an Ethernet cable connected to a powerline network adapter. I’m installing Cat6 through the entire house soon and will get rid of the powerline stuff afterwards. I’ve already purchased quite a bit of UniFi gear just waiting for the Cat6 to be pulled. I have three dvrs that are connected to each other and the Internet. I don’t have any errors with the other two dvrs. I don’t use this one as often but the other two can see and access it properly.

**Comment by frenck** [comment]
Please don't use merged/closed PR's to start discussions. Thanks 👍

**Comment by jscherry** [comment]
Sorry just trying to find some help with a problem I’m having

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Pull request merged**
