### PR TITLE
Add Mealie removal instructions

### PR DESCRIPTION
**Pull request by andrew-codechimp**
## Proposed change

Add Mealie removal instructions

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

## Summary by CodeRabbit

- **Documentation**
	- Added a new section on "Remove integration" to the Mealie integration documentation, providing users with clear instructions for removing the integration and deleting the associated API token.

### CODE REVIEW

**Review by klaasnicolaas — APPROVED** [review]
Thnx for the PR! 🥇

./Klaas

**Comment by joostlek** [comment]
image

Now we have 2 headings for it

**Comment by joostlek** [comment]
Would it make sense to add the stuff after `once the integration...` after the snippet so we don't raise the question "what is the standard integration removal?"

**Comment by klaasnicolaas** [comment]
Oops, a bit too fast with merging. You have a good point there, removing the API key would make more sense after removing the integration.

./Klaas

**Comment by andrew-codechimp** [comment]
> Now we have 2 headings for it

I've seen this two headings on lots of PR's for removal that include the standard template.

I did think about splitting the steps but I'm not sure people would read after the template block and leave their keys.

Happy to create a new PR once consensus is reached.

**Comment by joostlek** [comment]
Oh that's something we should look into. But maybe because of the boldness I see this as 2 separate sections and not 1 section with a subsection. I'll try to see what we can best do with this, because this include seems to be expected to be placed in a section of itself

**Comment by andrew-codechimp** [comment]
Sure, I know this section is new so still finding our way on what's best.  
I did the same with Mastodon on another PR that's just been merged by @frenck, I expect there will be quite a few integrations with remove an external key to tidy up so be good to get a pattern for this.

**Comment by joostlek** [comment]
Check!

**Pull request merged**
