### PR TITLE
Spelling fixes

### PR DESCRIPTION
**Pull request by scop**
**Description:**

Spelling fixes.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by frenck** [comment]
Thank you @scop! I love these kinds of PR's 👍 

Nevertheless, in some places, you have corrected part of the blog posts where the changelog where listed. While they indeed contain spelling error, those are the commit messages. So I guess they should not be fixed and kept in sync with the original commit?

**Comment by scop** [comment]
Both leaving the errors in and fixing them are fine with me, just confirm if you'd like them left as is and I'll adjust accordingly.

**Comment by frenck** [comment]
Personally, I hate those errors.
That said, those are the commit messages and logs from Git, so I would say, those specifically, should be left alone.

**Comment by scop** [comment]
Ok, force-pushed revised commit with those removed.

**Comment by frenck** [comment]
Thank you for this @scop! 🥇

**Pull request merged**
