### PR TITLE
Upgrade Jekyll

### PR DESCRIPTION
**Pull request by balloob**
**Description:**
Update Jekyll to latest version.

We should check the netlify build to make sure it's still ok.

### CODE REVIEW

**Comment by fabaff** [comment]
- Front page :+1: 
- Component overview :+1: 
- Code block :-1: (needs some CSS tweaking)
- Documentation :+1: 
- Sidebar :+1: 
- Blog :+1: (Community integration not working for netlify preview)

**Comment by balloob** [comment]
Added fix for code block.

**Comment by balloob** [comment]
Produces a lot more errors/warnings but it doesn't prevent site from building:

```
11:49:20 PM:              Error: A Liquid tag in the excerpt of _posts/2016-03-12-z-wave-pep257-templated-service-calls.markdown couldn't be parsed.
11:49:20 PM:              Error: could not read file /opt/build/repo/source/_posts/2016-03-12-z-wave-pep257-templated-service-calls.markdown: undefined method `ancestors' for nil:NilClass
11:49:20 PM:              Error: A Liquid tag in the excerpt of _components/sensor.transport_nsw.markdown couldn't be parsed.
11:49:20 PM:              Error: could not read file /opt/build/repo/source/_components/sensor.transport_nsw.markdown: undefined method `ancestors' for nil:NilClass
11:49:20 PM:              Error: A Liquid tag in the excerpt of _components/dialogflow.markdown couldn't be parsed.
11:49:20 PM:              Error: could not read file /opt/build/repo/source/_components/dialogflow.markdown: undefined method `ancestors' for nil:NilClass
11:49:20 PM:              Error: A Liquid tag in the excerpt of _components/hangouts.markdown couldn't be parsed.
11:49:20 PM:              Error: could not read file /opt/build/repo/source/_components/hangouts.markdown: undefined method `ancestors' for nil:NilClass
11:49:20 PM:              Error: A Liquid tag in the excerpt of _components/cover.opengarage.markdown couldn't be parsed.
11:49:20 PM:              Error: could not read file /opt/build/repo/source/_components/cover.opengarage.markdown: undefined method `ancestors' for nil:NilClass
11:49:20 PM:              Error: A Liquid tag in the excerpt of _components/sensor.template.markdown couldn't be parsed.
11:49:20 PM:              Error: could not read file /opt/build/repo/source/_components/sensor.template.markdown: undefined method `ancestors' for nil:NilClass
11:49:20 PM:              Error: A Liquid tag in the excerpt of _components/sensor.pvoutput.markdown couldn't be parsed.
11:49:20 PM:              Error: could not read file /opt/build/repo/source/_components/sensor.pvoutput.markdown: undefined method `ancestors' for nil:NilClass
11:49:20 PM:              Error: A Liquid tag in the excerpt of _components/conversation.markdown couldn't be parsed.
11:49:20 PM:              Error: could not read file /opt/build/repo/source/_components/conversation.markdown: undefined method `ancestors' for nil:NilClass
11:49:20 PM:              Error: A Liquid tag in the excerpt of _components/notify.markdown couldn't be parsed.
11:49:20 PM:              Error: could not read file /opt/build/repo/source/_components/notify.markdown: undefined method `ancestors' for nil:NilClass
11:49:20 PM:              Error: A Liquid tag in the excerpt of _components/sensor.fritzbox_callmonitor.markdown couldn't be parsed.
11:49:20 PM:              Error: could not read file /opt/build/repo/source/_components/sensor.fritzbox_callmonitor.markdown: undefined method `ancestors' for nil:NilClass
11:49:20 PM:              Error: A Liquid tag in the excerpt of _components/switch.template.markdown couldn't be parsed.
11:49:20 PM:              Error: could not read file /opt/build/repo/source/_components/switch.template.markdown: undefined method `ancestors' for nil:NilClass
11:49:20 PM:              Error: A Liquid tag in the excerpt of _components/rss_feed_template.markdown couldn't be parsed.
11:49:20 PM:              Error: could not read file /opt/build/repo/source/_components/rss_feed_template.markdown: undefined method `ancestors' for nil:NilClass
11:49:21 PM:              Error: A Liquid tag in the excerpt of _components/cover.template.markdown couldn't be parsed.
11:49:21 PM:              Error: could not read file /opt/build/repo/source/_components/cover.template.markdown: undefined method `ancestors' for nil:NilClass
11:49:21 PM:              Error: A Liquid tag in the excerpt of _components/alexa.markdown couldn't be parsed.
11:49:21 PM:              Error: could not read file /opt/build/repo/source/_components/alexa.markdown: undefined method `ancestors' for nil:NilClass
11:49:21 PM:              Error: A Liquid tag in the excerpt of _components/alarm_control_panel.alarmdecoder.markdown couldn't be parsed.
11:49:21 PM:              Error: could not read file /opt/build/repo/source/_components/alarm_control_panel.alarmdecoder.markdown: undefined method `ancestors' for nil:NilClass
11:49:21 PM:              Error: A Liquid tag in the excerpt of _components/deconz.markdown couldn't be parsed.
11:49:21 PM:              Error: could not read file /opt/build/repo/source/_components/deconz.markdown: undefined method `ancestors' for nil:NilClass
11:49:21 PM:              Error: A Liquid tag in the excerpt of _components/sensor.thermoworks_smoke.markdown couldn't be parsed.
11:49:21 PM:              Error: could not read file /opt/build/repo/source/_components/sensor.thermoworks_smoke.markdown: undefined method `ancestors' for nil:NilClass
11:49:21 PM:              Error: A Liquid tag in the excerpt of _components/media_player.universal.markdown couldn't be parsed.
11:49:21 PM:              Error: could not read file /opt/build/repo/source/_components/media_player.universal.markdown: undefined method `ancestors' for nil:NilClass
11:49:21 PM:              Error: A Liquid tag in the excerpt of _components/media_player.kodi.markdown couldn't be parsed.
11:49:21 PM:              Error: could not read file /opt/build/repo/source/_components/media_player.kodi.markdown: undefined method `ancestors' for nil:NilClass
11:49:21 PM:              Error: A Liquid tag in the excerpt of _components/binary_sensor.xiaomi_aqara.markdown couldn't be parsed.
11:49:21 PM:              Error: could not read file /opt/build/repo/source/_components/binary_sensor.xiaomi_aqara.markdown: undefined method `ancestors' for nil:NilClass
11:49:21 PM:              Error: A Liquid tag in the excerpt of _components/sensor.waze_travel_time.markdown couldn't be parsed.
11:49:21 PM:              Error: could not read file /opt/build/repo/source/_components/sensor.waze_travel_time.markdown: undefined method `ancestors' for nil:NilClass
11:49:21 PM:              Error: A Liquid tag in the excerpt of _components/binary_sensor.enocean.markdown couldn't be parsed.
11:49:21 PM:              Error: could not read file /opt/build/repo/source/_components/binary_sensor.enocean.markdown: undefined method `ancestors' for nil:NilClass
11:49:21 PM:              Error: A Liquid tag in the excerpt of _components/light.template.markdown couldn't be parsed.
11:49:21 PM:              Error: could not read file /opt/build/repo/source/_components/light.template.markdown: undefined method `ancestors' for nil:NilClass
11:49:21 PM:              Error: A Liquid tag in the excerpt of _components/cover.command_line.markdown couldn't be parsed.
11:49:21 PM:              Error: could not read file /opt/build/repo/source/_components/cover.command_line.markdown: undefined method `ancestors' for nil:NilClass
11:49:21 PM:              Error: A Liquid tag in the excerpt of _cookbook/automation_first_light.markdown couldn't be parsed.
11:49:21 PM:              Error: could not read file /opt/build/repo/source/_cookbook/automation_first_light.markdown: undefined method `ancestors' for nil:NilClass
11:49:21 PM:              Error: A Liquid tag in the excerpt of _cookbook/perform_actions_based_on_input_select.markdown couldn't be parsed.
11:49:21 PM:              Error: could not read file /opt/build/repo/source/_cookbook/perform_actions_based_on_input_select.markdown: undefined method `ancestors' for nil:NilClass
11:49:21 PM:              Error: A Liquid tag in the excerpt of _cookbook/dim_and_brighten_lights.markdown couldn't be parsed.
11:49:21 PM:              Error: could not read file /opt/build/repo/source/_cookbook/dim_and_brighten_lights.markdown: undefined method `ancestors' for nil:NilClass
11:49:21 PM:              Error: A Liquid tag in the excerpt of _cookbook/restart_ha_if_wemo_switch_is_not_detected.markdown couldn't be parsed.
11:49:21 PM:              Error: could not read file /opt/build/repo/source/_cookbook/restart_ha_if_wemo_switch_is_not_detected.markdown: undefined method `ancestors' for nil:NilClass
11:49:21 PM:              Error: A Liquid tag in the excerpt of _cookbook/track_battery_level.markdown couldn't be parsed.
11:49:21 PM:              Error: could not read file /opt/build/repo/source/_cookbook/track_battery_level.markdown: undefined method `ancestors' for nil:NilClass
11:49:21 PM:              Error: A Liquid tag in the excerpt of _docs/configuration/templating.markdown couldn't be parsed.
11:49:21 PM:              Error: could not read file /opt/build/repo/source/_docs/configuration/templating.markdown: undefined method `ancestors' for nil:NilClass
11:49:21 PM:              Error: A Liquid tag in the excerpt of _docs/configuration/splitting_configuration.markdown couldn't be parsed.
11:49:21 PM:              Error: could not read file /opt/build/repo/source/_docs/configuration/splitting_configuration.markdown: undefined method `ancestors' for nil:NilClass
11:49:21 PM:              Error: A Liquid tag in the excerpt of _docs/scripts/service-calls.markdown couldn't be parsed.
11:49:21 PM:              Error: could not read file /opt/build/repo/source/_docs/scripts/service-calls.markdown: undefined method `ancestors' for nil:NilClass
11:53:51 PM:     Liquid Warning: Liquid syntax error (line 29): Expected end_of_string but found open_round in "{{ state_attr('climate.main_room', 'status').setpointStatus.setpointMode }}" in /opt/build/repo/source/_components/climate.evohome.markdown
```

**Comment by balloob** [comment]
I wonder if the error has to do with the excerpt cutting off a linkable_title tag.

**Comment by balloob** [comment]
The errors can be fixed by downgrading to 3.8.4 and then only upgrading in the future once https://github.com/jekyll/jekyll/pull/7382 has been released.

**Pull request merged**
