### PR TITLE
Update rss_feed_template.markdown

### PR DESCRIPTION
**Pull request by Valiceemo**
add missing 'a' character in line 20

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

  - [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`. 
  - [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by frenck** [comment]
Thank you @Valiceemo, well spotted!

**Comment by Valiceemo** [comment]
No problem @frenck.
Happy to be able to give back to a community I've take so much from, albeit a very, very small contribution! 
Hope I did it all properly, with this being my first ever contribution to anything ever!

**Comment by frenck** [comment]
@Valiceemo Yeah it was fine, you did great. Feel free to create more PR's 🥇

**Comment by Valiceemo** [comment]
Just one more learner query if I may...I know have a home assistant repo in my git hub? 
Can I delete this with the 'Delete Branch's button I see in this thread?

**Comment by frenck** [comment]
@Valiceemo Yep!
If you have any further questions, please join our Discord chat 🎉

**Pull request merged**
