### PR TITLE
Credits Update (Fix Atanas Palavrov line)

### PR DESCRIPTION
**Pull request by BenoitAnastay**
## Proposed change

Update credits page, I had an issue with my cached name of @palavrov 

```
[Atanas Palavrov Updating wiringPi to add support for RPi3B\+ (@palavrov)](https://github.com/palavrov "1 total commits to the Home Assistant orga:
1 commit to buildroot
```

I don't know the origin of that error, but I fixed it manually and now the right line is produced by `hass-release`

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by palavrov** [comment]
?

**Comment by BenoitAnastay** [comment]
@palavrov sorry if you got notified, it's just that there is a "bug" on the credits page of HA on your name.

So I fixed it

**Comment by palavrov** [comment]
Ah, I see ... my name was "extended" with the commit message ...

**Review by frenck — APPROVED** [review]
Thanks, @BenoitAnastay 👍

**Pull request merged**
