### PR TITLE
Update docs with sensor_type values.

### PR DESCRIPTION
**Pull request by aequitas**
**Description:**
resolves: https://community.home-assistant.io/t/sensor-type-for-rflink-devices/15191

### CODE REVIEW

**Comment by Landrash** [comment]
Having this information in each document is quite a bit of duplication of information. I would suggest linking to the document with valid sensors types instead.

**Comment by Genestealer** [comment]
Agreed, linking reduces duplication.

**Comment by Landrash** [comment]
My mistake.  These types seems to be specific for this platform.
Thank you @aequitas 🍸

**Comment by aequitas** [comment]
I tried to rebase using 'change base' functionality of github, which does not seem to give the result i expected :).

I'll rebase and push from my workstation later today.

**Comment by Landrash** [comment]
@aequitas 👍

**Comment by aequitas** [comment]
Fixed.

**Pull request merged**
