### PR TITLE
Update index.markdown

### PR DESCRIPTION
**Pull request by trentjw**
## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue:

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
We don't want to spend much time on explaining the user pro's con's in the getting started guide. This changes a simple paragraph into a numbered list with a bullet list in each of the numbered items.

I personally, kinda fail to see how this improves the "getting started" experience. It becomes more apparent and thus more likely confusing for a new user.

Could you elaborate on your proposal? (please add that part to the description next time).

**Comment by trentjw** [comment]
I did not put in any pros or cons I cleaned it up a bit by rearranging it to make it easier to navigate. by user either going to continue down the page for easy install or select the the second line for alternative installs, thanks

**Comment by balloob** [comment]
I agree with Frenck. I don't think that this is an improvement.

**Comment by trentjw** [comment]
well then rewrite it so it not all ran together and confusing to the normal installer

**Pull request closed without merging**
