### PR TITLE
WIP Documentation for cover.velux added

### PR DESCRIPTION
**Pull request by Julius2342**
**Description:**

Pull request in [https://github.com/home-assistant/home-assistant.io/pull/7867](https://github.com/home-assistant/home-assistant/pull/18738)

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

**Comment by rytilahti** [comment]
Please fix the conflict, this can be merged then!

**Review by rytilahti — DISMISSED** [review]

**Comment by Julius2342** [comment]
I solved the merge conflict. Do you think we should mention that you have to run firmware > 2.0.0.0 on the device? 

Suggested text:

"You need at least firmware version > 2.0.0.0 on your KLF 200 device. The firmware images may be obtained [here](https://www.velux.com/api/klf200) and may be imported via the webinterface of your KLF 200."

**Comment by rytilahti** [comment]
Ah, I overlooked that point. Yes, that should definitely be added to the documentation; assuming that this version requirement is for all device types, the note should go to the component documentation.

Shouldn't the name also be written as VELUX everywhere in the docs (assuming that is the brand, and not Velux)?

**Comment by klaasnicolaas** [comment]
Time to merge this PR? But first update the `ha_release` ⬆️  to 0.88

**Review by frenck — APPROVED** [review]

**Comment by klaasnicolaas** [comment]
We can close this PR

**Comment by frenck** [comment]
Closing this PR, replaced by #8486

**Pull request closed without merging**
