### PR TITLE
update doc for keyboard_remote type

### PR DESCRIPTION
**Pull request by lanrat**
## Proposed change

Document the new `type` field for `keyboard_remote` events.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/56668
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by lanrat** [comment]
> It seems that this PR is targeted against an incorrect branch since it has a parent PR on one of our codebases. Documentation that needs to be updated for an upcoming release should target the `next` branch. Please change the target branch of this PR to `next` and rebase if needed. (message by DocsTargetBranch)

Can anyone help me understand what this is asking me to do? This is a documentation update for a PR I have in the `dev` branch for come assistant.

**Comment by thecode** [comment]
> Can anyone help me understand what this is asking me to do? This is a documentation update for a PR I have in the `dev` branch for come assistant.

You ticked that you want to document new feature which goes for the `next` branch:
image
Which is correct.
But your PR is targeted to the `current` branch:
image

You can press edit and change the target branch:
image

Make sure you only see 1 file updated after that else you need to rebase your branch

**Review by frenck — CHANGES_REQUESTED** [review]
This PR depends on another PR in the core codebase, meaning it depends on a future release of Home Assistant. Therefore this documentation PR should target the `next` branch.

Please adjust the target branch of this PR to `next` and perform a git rebase if needed.

**Comment by lanrat** [comment]
Thanks for the clarifications @thecode and @frenck!

I've changed the target branch to `next` and it looks like a rebase was not needed.

**Review by frenck — APPROVED** [review]

**Pull request merged**
