### PR TITLE
Update wunderground.markdown

### PR DESCRIPTION
**Pull request by wiewior81**
## Proposed change
There's a significant change in WU API that makes the integration not working anymore. New API documentation is available [here](https://docs.google.com/document/d/1eKCnKXI9xnoMGRRzOL1xPCBihNV2rOet08qpE_gArAY/edit).

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by frenck** [comment]
So, uh...

Should we be cleaning this up as a whole, instead of documenting it is broken?

**Comment by wiewior81** [comment]
I think if no one is able to update the integration with new API, it should be deleted. If you're the one who wrote it, and you can consider updating the configuration, I can share my API key for you to test all the API calls and the data that WU returns.

**Comment by frenck** [comment]
I was trying to say, that the integration should be either removed or fixed. The latter means that there is a bug/issue, which should be reported.

Have you reported a bug?

In general, we don't document bugs, hence my questions/comments.

**Comment by wiewior81** [comment]
Hi, not really. Sorry, as you see I'm quite new on GitHub - just registered to draw attention to the non-functioning integration. Can you point me to the right place where I could at least notice the author of the integration that it doesn't work anymore and I'm willing to provide my API keys to help testing the fix?

**Comment by frenck** [comment]
Issues with an integration can be reported here:

<https://github.com/home-assistant/core/issues>

For more information on where to go in general:

<https://www.home-assistant.io/help>

Closing the PR at this end for now.

**Pull request closed without merging**
