### PR TITLE
wrong example

### PR DESCRIPTION
**Pull request by Cooper-Dale**
typos, not working

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
I think you have to add 2 spaces to it, otherwise it will not be right.

**Comment by Cooper-Dale** [comment]
It is worknig this way on my instance

**Comment by emontnemery** [comment]
@Cooper-Dale indentation in your changed example is not right:
```yaml
- type: history-graph
  title: 'My Graph'
  entities:
name: Blokovače topení
entities: 
  - switch.SW1
  - switch.sw2
  - SENSOR.TEMP1
hours_to_show: 24
refresh: 60
```

**Comment by Cooper-Dale** [comment]
sorry, my fault. Now i can see that the expample is ok. 
Please close the PR

**Pull request closed without merging**
