### PR TITLE
Add severe weather sensor to Dark Sky

### PR DESCRIPTION
**Pull request by rtclauss**
**Description:**
This change adds a severe weather sensor to the Dark Sky component.  If there are multiple severe weather conditions each condition is appended to the sensor as an additional attribute.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#22701

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Parent PR still open

**Review by frenck — CHANGES_REQUESTED** [review]
@rtclauss Could you please rebase to fix the build error? Thanks already 👍

**Comment by rtclauss** [comment]
Done.  Thanks!

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Review by MartinHjelmare — APPROVED** [review]

**Pull request merged**
