### PR TITLE
Updated docs based on user suggestions

### PR DESCRIPTION
**Pull request by brahmafear**
Thanks to @NeLLyMerC for the suggestions.  Removed the EOF syntax for creating a file.  Cleaned up the description of the systemctl commands.  Added 'sudo' to the journalctl commands as it will not show the logs if running as an unprived user.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

### CODE REVIEW

**Comment by NeLLyMerC** [comment]
Thank you @brahmafear for the partnership! Hopefully future installers find the edits to be a seamless experience

**Comment by smurfix** [comment]
Instead of sudo, you might recommend adding the user in question to the "adm" group.

> `sudo ln -s /lib/systemd/system/home-assistant.service /etc/systemd/system/home-assistant.service`

This is definitely not necessary. Where did you get that idea from? Did you simply forget `systemctl daemon-reload`?

**Comment by NeLLyMerC** [comment]
@brahmafear would be able to answer that, but the following commands are what worked for me in my fresh install on Ubuntu Server

`sudo systemctl --system daemon-reload`
`sudo systemctl enable home-assistant.service`
`sudo systemctl start home-assistant.service`

**Comment by brahmafear** [comment]
@smurfix @NeLLyMerC   I don't use hass on Ubuntu - those commands were simply copied from the existing page.  If any edits suggested from an Ubuntu systemd guru, please let me know.

**Comment by Landrash** [comment]
Looks good. Thank you :cookie:

**Pull request merged**
