### PR TITLE
Updated docs of climate.knx

### PR DESCRIPTION
**Pull request by marvin-w**
**Description:**

Updated the docs of the climate entity for the KNX platform.

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by fabaff — APPROVED** [review]
Thanks :bird:

**Comment by marvin-w** [comment]
@fabaff: Can you revert this please? I was looking at https://github.com/XKNX/xknx/blob/master/home-assistant-plugin/custom_components/climate/xknx.py#L18-L37 

instead of https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/climate/knx.py#L18-L32

Maybe @Julius2342 can use it when he releases the next version. Sorry :/.

**Comment by Julius2342** [comment]
I will port the changes of the xknx-custom-component to the main hass components asap. 

(KNX climate devices are a terrible mess, all manufacturers do it slightly different. And many users don't have an ETS so they have to use the configuration their electricians left a long time ago.)

**Comment by marvin-w** [comment]
Thanks @Julius2342, yes I know this problem. I still don't really know why they charge 1k for a single license.

One could also argue with the quality of those configurations made by at least some electricians.

**Comment by Julius2342** [comment]
@marvin-w : What do you think about the idea of splitting up the different climate devices into separate climate devices with different logic behaviour? My hope would be that this would simplify things a lot - especially we would avoid this mess of dozens of parameters.

**Comment by marvin-w** [comment]
@Julius2342: Sounds good to me but we'd have to define those climate devices upfront and also add proper documentation. If you're up to it I could help you doing that and also help during the implementation but, as I mentioned, my knowledge of python is limited but it didn't look to hard.

Maybe we could discuss those changes in some kind of instant messaging like slack for instance. Would you be up for that?

**Comment by Julius2342** [comment]
We have a chat here: https://discord.gg/5XARFNT

**Pull request merged**
