### PR TITLE
Mention another Zigbee limitation in ZHA docs

### PR DESCRIPTION
**Pull request by Hedda**
## Proposed change

Mention another Zigbee limitation in the ZHA integration docs, (and also tried to further clarify an already described limitation).

The limitation of not being able to extend a Zigbee network using some kind of  "Zigbee over IP" or "Zigbee over LAN/WAN" has become a frequently asked question in the Home community forum as network-attached Zigbee adapters are becoming more common and many people seem to assume that they can use one or more of those as a remote Zigbee Router device to extend their existing Zigbee network to multiple locations by converting and tunneling the Zigbee Router traffic over LAN and/or WAN.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

## Summary by CodeRabbit

- **Documentation**
  - Clarified limitations of Zigbee device functionality, including:
    - Single Zigbee Coordinator constraint.
    - Requirement to factory reset devices to switch networks.
    - Lack of support for "Zigbee over IP."
    - Inability to extend Zigbee networks over LAN/WAN.

### CODE REVIEW

**Comment by puddly** [comment]
I don't think listing limitations like this is useful. There are *many* limitations, too many to list, and further expanding the one page of documentation isn't good.

**Comment by Hedda** [comment]
> I don't think listing limitations like this is useful.

I disagree in the use case when new users ask in the Home Assistant community forum why something is not working it is easy to simply refer to ZHA integration documentation by just giving them a link to that section, as then they usually accept that as fact.

Alternative is having to explain to each and every new users asking the same thing, and even then they might not accept that answer because it is not documented.

Example is now a lot of new users now asking to use a network-attatched Zigbee Coordinator either to connect Zigbee devices over VPN to a other site or over LAN from a other area if flash as Zigbee Router. For those asking about that there is now always a long dialogue explaing why it is a bad idea or why it is not will not work.

Note that some makers of those even added Wireguard VPN to them which makes new users think it is a good idea to use it -> https://smlight.tech/manual/slzb-06/guide/remote-vpn-conn/

Another example is Zigbee Green Power which is documented as a limitation, here we can simply point them to the documentation and they accept that.

Reference:

* https://community.home-assistant.io/t/connecting-zigbee-devices-over-the-internet/741245

* https://community.home-assistant.io/t/how-to-connect-zigbee-lan-coordinator-and-zha-via-wireguard-vpn/719057

* https://community.home-assistant.io/t/uzg-01-vs-sonoff-more-then-1-mqtt-or-use-uzg-as-router/743332/

**Comment by puddly** [comment]
The documentation isn't a FAQ and doesn't need to hold the answers to every question someone asks. We can invest in setting up a FAQ independent of the documentation in the future but for now, I do not think this is a beneficial change.

**Comment by Hedda** [comment]
> The documentation isn't a FAQ and doesn't need to hold the answers to every question someone asks. We can invest in setting up a FAQ independent of the documentation in the future but for now, I do not think this is a beneficial change.

Resubmitting this. Think there is of benefit to having n ZHA documentation, at least until can be moved to an independent FAQ.

**Comment by puddly** [comment]
Closing for the aforementioned reason.

**Comment by Hedda** [comment]
Sad as there is still no seperate FAQ for Zigbee or ZHA, nor has anyone annonced plans to create webpages for such FAQs.

**Pull request closed without merging**
