### PR TITLE
Documentation for kwb component

### PR DESCRIPTION
**Pull request by bimbar**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#6018

### CODE REVIEW

**Comment by bimbar** [comment]
I hope this addresses your requests.

**Comment by Landrash** [comment]
Looks better but your missing documentation for the variables.

**Comment by bimbar** [comment]
Like that?

**Comment by bimbar** [comment]
Parent PR has already been merged in 0.40.

**Pull request merged**
