### PR TITLE
Update iammeter.markdown

### PR DESCRIPTION
**Pull request by lewei50**
## Proposed change

Add a demo website link in the markdown file.

## Type of change

- [*] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This is an update of existing documentation, please update the target branch to `current` and git rebase the PR if needed.

Thanks! 👍

**Comment by lewei50** [comment]
> This is an update of existing documentation, please update the target branch to `current` and git rebase the PR if needed.
> 
> Thanks! 👍

should I close this PR and open another PR using "current" branch,
or create a new PR and link it to this PR?
thanks for your reply.

**Comment by klaasnicolaas** [comment]
The first step I did for you, changing the target branch to `current`. The only thing left to do now is rebase your branch on your fork from `next` to `current`.

**Comment by lewei50** [comment]
> The first step I did for you, changing the target branch to `current`. The only thing left to do now is rebase your branch on your fork from `next` to `current`.

sorry for that I am not familiar with git rebase,I have tried to rebase my branch,but nothing happened to this PR,could I close this PR,and try create another using branch 'current' ?

**Pull request closed without merging**
