### PR TITLE
[climate] Migrate incomfort docs for climate-1.0

### PR DESCRIPTION
**Pull request by zxdavb**
**Description:**
Migrate incomfort docs for `climate-1.0`

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

<a href="https://gitpod.io/#https://github.com/home-assistant/home-assistant.io/pull/9817"></a>

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
This PR must be in the `climate-1` branch 😉

**Review by frenck — CHANGES_REQUESTED** [review]
No matter what I do (no matter which target branch) it keeps showing up with unrelated content.
Could you please take a look @zxdavb? Thanks 👍

**Comment by zxdavb** [comment]
@frenck Sorry, try now?

**Review by frenck — APPROVED** [review]
thanks @zxdavb! 👍

**Pull request merged**
