### PR TITLE
Update Discovery component configuration

### PR DESCRIPTION
**Pull request by klaasnicolaas**
**Description:**
Update style of Discovery component documentation to follow new configuration variables description.
Related to #6385.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by nwesterhausen** [comment]
You should go ahead modify the example configuration while you're at it. The example should be as generic as possible (so it should not include optional configuration). Typically you can just re-label the existing one as a configured example or advanced configuration example and provide a simpler _# Example configuration.yaml entry_

**Comment by klaasnicolaas** [comment]
I will first let @fabaff or @frenck look to it, to decide if this is really necessary in this case

**Comment by ludeeus** [comment]
For most cases, I would agree with what @nwesterhausen said since that is the standard.
But in this case, it makes sense to have them there since this is a subpage for `MQTT` with "advanced" configuration.

_Note: Feel free to disregard my views :D_

**Review by fabaff — APPROVED** [review]
Thanks :bird:

**Comment by fabaff** [comment]
Let's keep this PR to the configuration variable update and update the examples later if needed.

**Pull request merged**
