### PR TITLE
Update the theme to match branding better

### PR DESCRIPTION
**Pull request by Madelena**
## Proposed change
* Better typography (Die, Roboto!!)
* Better colors
* Better CTA for the landing page hero section
* New HERO header with an live demo baked into it
* Sexy footer
* Cleaner boxes
* Better-looking navigation
* Removal of unused sass files
* Make MDI icons available, so we can match the UI of Home Assistant in many places
* Merges the customizations and (already locally modified) theme together, making a single Home Assistant theme.
* Removes (a very old) fontawesome
* New alert boxes: note, important, tip, warning & caution
* Migrated all existing note boxes to the new alert boxes
* **1 million other tiny improvements and fixes**

It will look like this:
image
image

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

## Summary by CodeRabbit

- **Style Updates**
  - Updated link colors, background colors, and margin/padding for various components.
  - Improved typography with new font families for headings and body text.
  - Enhanced button styling including border radius and padding adjustments.

- **New Features**
  - Added preconnect links and new font stylesheets for improved font loading performance.
  
- **UI Improvements**
  - Refined grid layout and element reordering for a better visual hierarchy.
  - Enhanced the layout and spacing of page content for improved readability.

### CODE REVIEW

**Comment by frenck** [comment]
I am drafting this PR for a minute, as there is some work left to do (to prevent an accidental merge).

../Frenck

**Review by joostlek — APPROVED** [review]
Small PR, LGTM

**Review by frenck — APPROVED** [review]

**Comment by johanf85** [comment]
Well done guys, I noticed the change of the homepage yesterday. Looks great! I made the previous phone mockup screenshot PR #18582, but I also felt it could improve. I like the more modern design of the upper part and more round icons. Also like the use of an iframe with a demo with the double white line around it in the new version. 👍🏻 The white lines are a simple and elegant way to represent a smartphone.

**Pull request merged**
