### PR TITLE
Updated docs for Yandex TTS

### PR DESCRIPTION
**Pull request by gipnokote**
**Description:**
Updated docs for Yandex TTS component.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#19603

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by fabaff — APPROVED** [review]
Thanks :bird:

**Comment by frenck** [comment]
This PR should have been merged into `next`.

**Comment by gipnokote** [comment]
I'm sorry, this was my first commit into HA repo, I was reading the dev docs and I wasn't completely sure into which branch I should commit. I decided that if the component already exists then current is the appropriate one. Could you please elaborate the logic how "next" is the proper one, so I know next time where to commit? And should I take any action now?

**Comment by frenck** [comment]
@gipnokote Sure! If the change matches the current release and thus the current documentation it goes into `current`. Changes to that branch will be visible live directly after the merge. If the change to the documentation depends on a next release (e.g., new components and features), it should go into the `next` branch. The `next` branch will be merged into `current` on the next Home Assistant release. Causing these change to be visible live on the next release.

**Pull request merged**
