### PR TITLE
Add language parameter to darksky sensor.

### PR DESCRIPTION
**Pull request by cgtobi**
**Description:**
Documentation for #13297.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#13297

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by frenck — DISMISSED** [review]

**Comment by frenck** [comment]
Thanks, @cgtobi! 🥇 

Can be merged as soon as the parent PR gets merged.

**Comment by cgtobi** [comment]
Thanks @frenck. I replaced it with @syssi's documentation which was more detailed as it includes the actual language codes.

**Review by frenck — DISMISSED** [review]

**Comment by frenck** [comment]
Changes approved, but first need to rebase it onto the `next` branch

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Done the rebase, can be merged as soon as the build passes (since the parent PR has been merged already).

**Pull request merged**
