### PR TITLE
packages do not support automation.reload

### PR DESCRIPTION
**Pull request by bbrendon**
**Description:**

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by arsaboo** [comment]
Are you sure this is the case? This [PR](https://github.com/home-assistant/home-assistant.io/pull/10357) says otherwise.

**Comment by frenck** [comment]
Incorrect, they do support it for a while already.
Actually, the documentation has been adjusted only last week...

Closing PR.

**Comment by bbrendon** [comment]
anyone know where this got into the code? I can't find it.

**Comment by bbrendon** [comment]
NM. I found it. Updated the forums.

**Pull request closed without merging**
