### PR TITLE
Change recommendation for 700 series z-wave controllers due to buggy fw

### PR DESCRIPTION
**Pull request by blhoward2**
## Proposed change

Currently, we recommend people purchase 700 series controllers. There is currently a nasty bug affecting a number of people that causes the stick to become unresponsive. Essentially, it fails to send out Acks when it is receiving a lot of messages, which cause all of those devices to then begin flooding the controller with repeat messages, which makes the problem even worse as it cascades. We've reported this to SiLabs (from Z-Wave JS) weeks ago, but it doesn't seem like it'll be a quick fix. In the interim we should change our recommendation. A lot of people are downgrading from the 700 sticks temporarily. 

https://github.com/zwave-js/node-zwave-js/issues/3906

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by frenck** [comment]
Duplicate of: <https://github.com/home-assistant/home-assistant.io/pull/21209>

**Comment by blhoward2** [comment]
I didn't see that one was closed. I do think we should change our recommendation here and @AlCalzone agrees. This current bug makes the network unusable so it isn't a small thing. We don't have to mention the bug if you don't want to do so, we could just recommend people purchase 500 sticks for now and leave it at that. It's just that we're presently recommending people purchase a setup that very well may not work.

**Comment by frenck** [comment]
> I do think we should change our recommendation here

We don't document bugs. If there is a big issue affecting a lot of people, putting out an alert can be considered an alternative.

So this PR contains 2 things, 1 change the recommendation, and 2 it adds an alert/warning/note for a firmware issue. I think the first is fine, the second isn't and should be an alert imho.

I do not agree on merging this into our docs as is.

**Comment by blhoward2** [comment]
It doesn't have to document a bug. See my edit to my comment. What if we just recommend 500 series sticks and leave it at that? Just to remove the recommendation RE 700 series.

**Comment by frenck** [comment]
Sorry, I was editing my previous answer, please revisit.

**Comment by blhoward2** [comment]
@frenck How about now?

**Review by frenck — APPROVED** [review]
Thanks, @blhoward2 👍

**Pull request merged**
