### PR TITLE
esphomelib Blog Post

### PR DESCRIPTION
**Pull request by OttoWinter**
**Description:**

A bit later than I expected, but I think I've squashed all bigger bugs now. So as per @balloob, here's a blog post for esphomelib :)

I hope the guide is understandable and I've tested it a couple of times now. It would, however, be great if someone else could also try the guide in this setup once and see if it works before publishing 😀

~~🚨 I've not been able to let jekyll/octopress compile the blog post. For some reason which I've been debugging for the last two hours, the rakefile only generates all other blog posts and somehow decides not to compile mine :( I'm creating a PR to maybe see if netlify works.~~ Got it working by re-cloning the entire repo (just deleting `public/` did not work).

If there's anything expressed in a weird/complicated way or any spelling mistakes, please do say so :)

For the GIF, I've spent a bunch of time tuning a few ffmpeg parameters to make it as small as possible. I hope 2.7MB is an acceptable file size

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by balloob** [comment]
Can't we use YouTube instead of GIF? Video is on-demand, and so much lighter.

**Comment by OttoWinter** [comment]
Sure YouTube would be an option. However the content of the GIF is not *really* a YouTube video IMO - If I wanted to do a setup guide that goes through everything in detail with spoken explanations I would do that on YouTube.

Here the main motivation for the GIF is that users *do not* have to click on anything, and that they can see how good the setup process is without even clicking anything. That's also why it's sped up that much. Anyway...:

I've now managed to size the GIF down to 1.2MB with little quality loss. Additionally, I've tried it with a YouTube video, and the whole YouTube player with all its scripts and stylesheets is about 604kB for me (+ another 632kb when playing):

```html
<iframe width="560" height="315" src="https://www.youtube.com/embed/jy-oWg4M9b0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
```

Edit: Ok, the gif is not that insignificant. The yellow box is the esphomelib image:

screen shot 2018-06-04 at 17 45 42

So I can convert it to a YouTube video if you want. It's your call :)

**Comment by OttoWinter** [comment]
YouTube iframes support autoplay 🤦. It would solve the "feature discovery" aspect and additionally decrease the download size to ~400kb (if youtube is in the cache) or even less if on a bad internet connection. Sorry about the rambling ♥️

**Review by balloob — DISMISSED** [review]

**Comment by OttoWinter** [comment]
@balloob Just a quick question that I probably should have asked before too: Do you think this blog post is going in the right direction/does it put too much emphasis on the getting started and focus too little on the features?

From a few conversations I recently had I now realize that in some cases my docs are too much on the technical side of things :)

**Comment by balloob** [comment]
I think putting the emphasis on getting started is perfect. 

When writing docs, there are 4 types, and you need them all:

image

More info in this talk https://www.youtube.com/watch?v=azf6yzuJt54

**Review by balloob — APPROVED** [review]

**Comment by balloob** [comment]
Oh, and just one more thing, I've added a social image in 087dc716f07c73d454f3a762597e4ffda10444f8

It's very important as that's what people see when they share the blog post. Makes it more attractive to share.

Forgot to put the blog post on the social media this morning, did it now :)

**Comment by OttoWinter** [comment]
Ah thank you very much for that... Slowly learning all this publishing stuff :)

Will also check out that video ... I'm sure I can learn a lot from it.

**Pull request merged**
