### PR TITLE
Added new KNX auto reconnect configuration parameters

### PR DESCRIPTION
**Pull request by cyberjunky**
## Proposed change

Documented two new parameters related to auto reconnect feature added in PR mentioned below.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: #33387
- This PR fixes or closes issue:

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This PR is awaiting a change in our code base and a next release of Home Assistant. This PR should, therefore, target the `next` branch.

Please change the target branch and rebase this PR if needed. Thanks 👍

**Comment by cyberjunky** [comment]
@frenck I was fighting with rebase (as always) and did a merge in the end, I hope the damage is controllable :smile:

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by cyberjunky** [comment]
Closed because extra config parameters are dropped from PR, so no new documentation needed.
auto_reconnect hard-coded to true.

**Pull request closed without merging**
