### PR TITLE
Updating AIO docs to remove references to OZWCP

### PR DESCRIPTION
**Pull request by DubhAd**
Given that we've got a perfectly good control panel, removing historical references to OZWCP.

### CODE REVIEW

**Comment by fabaff** [comment]
The panel is [still present](https://github.com/home-assistant/fabric-home-assistant/blob/master/fabfile.py#L181) in the installer. Thus the documentation should be adapted after the installer is up-to-date.

**Comment by frenck** [comment]
@DubhAd @fabaff This PR is kinda running stale, is there anything we can do to move this PR forward?

**Comment by frenck** [comment]
I'm closing this PR since it is running stale. Feel free to re-open it.

**Comment by DubhAd** [comment]
As the AIO installer has been killed off, and contained the last reference to the OZWCP, I'm re-opening this.

**Comment by frenck** [comment]
I think it is OK to remove this reference in this case. Nevertheless, shouldn't we clean up all the AIO references?

**Comment by frenck** [comment]
Closing this PR again, page has been removed/updated already in an other PR.

**Pull request closed without merging**
