### PR TITLE
Send V_STATUS last for mysensors light

### PR DESCRIPTION
**Pull request by hko**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#15432

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by DubhAd — APPROVED** [review]
👍

**Comment by hko** [comment]
I'm not sure I understand the status of this PR, but is there anything I can do to help move it along?

Thank you!

**Comment by frenck** [comment]
Well, @hko, this PR awaits the parent PR. There is no use on adding a piece of documentation of which the parent hasn't been merged in.

**Comment by MartinHjelmare** [comment]
I'll close this, since the parent PR is closed. We can reopen when we have tested all sketch versions and parent PR is merged.

**Comment by hko** [comment]
I've spent some time trying to get the mysensors1 example to work, but so far failed.
(And also tried one of the "original" examples from the mysensors 1.5.4 tarball)

It looks like home-assistant is not assigning a child-id to my sensor when running 1.5.4 (or rather: the sensor ends up with id 255 for some reason?!)

Are we sure that mysensors-1.5.4 is still working against home-assistant at all (and/or if anyone is still using it?!)

**Comment by MartinHjelmare** [comment]
I'm not aware of a breakage for older versions. Please open a separate issue and we can troubleshoot there.

**Pull request closed without merging**
