### PR TITLE
Update discord.markdown

### PR DESCRIPTION
**Pull request by thisisnotfez**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

## Summary by CodeRabbit

- **Documentation**
  - Clarified how to set message entries in Discord.
  - Detailed the process for specifying channel IDs.
  - Provided methods for pinging users, roles, and channels within a Discord server.
  - Added a table for Discord service data attributes for extended functionality.

### CODE REVIEW

**Review by thisisnotfez — COMMENTED** [review]
Implemented the AI suggested phrasing.

**Review by thisisnotfez — COMMENTED** [review]
Actually committed the suggestions by the AI.

**Review by thisisnotfez — COMMENTED** [review]
Final AI suggested change.

**Review by c0ffeeca7 — APPROVED** [review]
Thank you, @thisisnotfez :+1:

**Pull request merged**
