### PR TITLE
Document new step_volume and input_scan parameters

### PR DESCRIPTION
**Pull request by radhus**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#17378

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Thanks, @radhus! 👍 

✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by tjorim** [comment]
@radhus, thanks for supporting this device.
If you feel like it you can update the configuration-section to the new format.
(since you're already editing it) [You can find more info here](https://developers.home-assistant.io/docs/en/documentation_create_page.html#configuration).

**Review by frenck — CHANGES_REQUESTED** [review]
@radhus Could you please resolve the merge conflict?

**Comment by frenck** [comment]
Closing this PR, since the parent PR has been closed.

**Pull request closed without merging**
