### PR TITLE
Add Reolink integration #43195

### PR DESCRIPTION
**Pull request by fwestenberg**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/43195
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/2016
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
I think this is meant as documentation for the reolink integration?

Could you please update the title of the PR, add a PR description and clean up the PR to not have unrelated commits?

Thanks 👍

**Comment by frenck** [comment]
@fwestenberg I'm not sure what you are doing, but you have now started revert changes manually. We cannot merge that.

Please use a git rebase to resolve your issue.

**Comment by fwestenberg** [comment]
Sorry, it was a little late last night. I hope it's alright now! Thanks!

**Comment by frenck** [comment]
No, it isn't as there are unrelated commits in this PR.

image

You need to git rebase (and strip off the history a bit, the last commits you made are not right as it changes history).

**Comment by fwestenberg** [comment]
Me neither, I'm not really experienced with Github so I could need some help here.

**Comment by frenck** [comment]
I'm not sure how to help you with writing instructions for this. The best place to start looking, I guess, is read into how to do a git rebase (that will help you get rid of the first part).

**Comment by fwestenberg** [comment]
I think it's the easiest way to create a new PR.

**Pull request closed without merging**
