### PR TITLE
Adding Travis CI testing to config backups

### PR DESCRIPTION
**Pull request by tradiuz**
Also gives a way to test the config against the latest code changes.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

### CODE REVIEW

**Comment by Landrash** [comment]
Wow! Love this!

**Comment by Danielhiversen** [comment]
Great, just sat this up on my config repo. :+1:

**Comment by Landrash** [comment]
@fabaff I'll let you merge , etc this after the rework your doing is done.

**Comment by eiddor** [comment]
Very cool concept, but I can't test until I'm back in the country.  There are some typos in the change, however, but I can fix those afterwards.

**Comment by Chariyski** [comment]
@tradiuz Great job 👍

**Comment by tradiuz** [comment]
After doing a lot more digging into this (and a little less whiskey), I'm going to remove the bits about encrypting files.  That could be moved to an entirely different page with other advanced travis configs.

Ex:  
Check configuration against different versions (current, dev, static, etc).  Credit to @balloob  for the idea.  See [my .travis.yml](https://github.com/tradiuz/homeassistant-config/blob/master/.travis.yml) 
Encrypt files that you want as part of full config testing, that don't want in your repo (e.g. secrets, zones, etc).

**Comment by Chariyski** [comment]
Hi @tradiuz,

Yesterday I've setup my Travis CI, but I needed to add 2 additional files:
```
www_traviswebsite.fake_key
www_traviswebsite_dot_com.fake_crt
```
I've copied those from @CCOSTAN. Maybe you can add some additional information about that in the documentation.

Best regards

**Comment by balloob** [comment]
Awesome 🐬

**Comment by Chariyski** [comment]
Hi guys,

Don't know if you have notice this, but where there is an error related to the secrets.yaml HA is logging part  of the secret variable in the log.

```
Example:
17-02-21 20:39:04 ERROR (MainThread) [homeassistant.bootstrap] Invalid config for [http]: not a file for dictionary value @ data['http']['ssl_certificate']. Got 'www_traviswebsite_dot_com.fake_crt'
not a file for dictionary value @ data['http']['ssl_key']. Got 'www_traviswebsite.fake_key'. (See /home/travis/build/Chariyski/Home-Assistant-Configuration/./configuration.yaml, line 11). Please check the docs at https://home-assistant.io/components/http/
17-02-21 20:39:04 ERROR (MainThread) [homeassistant.bootstrap] Not initializing history because not all dependencies loaded: http
17-02-21 20:39:04 ERROR (MainThread) [homeassistant.bootstrap] Not initializing api because not all dependencies loaded: http
17-02-21 20:39:04 ERROR (MainThread) [homeassistant.bootstrap] Not initializing websocket_api because not all dependencies loaded: http
17-02-21 20:39:04 ERROR (MainThread) [homeassistant.bootstrap] Not initializing frontend because not all dependencies loaded: api, websocket_api
17-02-21 20:39:04 ERROR (MainThread) [homeassistant.bootstrap] Not initializing panel_iframe because not all dependencies loaded: frontend
17-02-21 20:39:04 ERROR (MainThread) [homeassistant.bootstrap] Not initializing logbook because not all dependencies loaded: frontend
Failed config
  http: 
    api_password: password
    base_url: your.website.com
    ssl_certificate: www_traviswebsite_dot_com.fake_crt
    ssl_key: www_traviswebsite.fake_key
Successful config (partial)
  http:
The command "hass -c . --script check_config" exited with 1.
Done. Your build exited with 1. 
```

I suggest adding a note about that and to not recommend secrets.yaml encryption, the travis_secrests,yaml is the better option.

**Comment by CCOSTAN** [comment]
I would agree with @Chariyski.  I wouldn't feel comfortable with all my secrets leaving my local network anyway.  Too easy to mess something up.. I don't see why we would even propose it to users.  It's a loaded gun IMHO.

**Comment by Chariyski** [comment]
It doesn't need to be a mistake made by you.

An attacker can fork your project - > break the encrypted file with some change in it -> make pull request = exposed passwords

**Comment by Danielhiversen** [comment]
My build is not failing when there are errors in the config. The check_config script still returns 0.
Any suggestions?

```
0.58s$ hass --version
0.38.4
1.72s$ hass -c . --script check_config
INFO:homeassistant.util.package:Attempting install of colorlog>2.1,<3
Testing configuration at /home/travis/build/Danielhiversen/hass_config/.
17-02-23 17:03:28 ERROR (Thread-1) [homeassistant.util.yaml] while parsing a block mapping
  in "/home/travis/build/Danielhiversen/hass_config/./scripts/general.yaml", line 75, column 6
expected <block end>, but found '<block mapping start>'
  in "/home/travis/build/Danielhiversen/hass_config/./scripts/general.yaml", line 78, column 8
The command "hass -c . --script check_config" exited with 0.
```

**Comment by Danielhiversen** [comment]
It seams to be a bug in the check_config script https://github.com/home-assistant/home-assistant/issues/6200

**Pull request merged**
