### PR TITLE
Added Garmin Body Composition values

### PR DESCRIPTION
**Pull request by cyberjunky**
## Proposed change

home-assistant/core#32841 added body composition data support (from Garmin Index Scale) Update the documentation to cover that.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: home-assistant/core#32841
- This PR fixes or closes issue:

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Please link up the parent PR in the openings post. Thanks! 👍

**Comment by cyberjunky** [comment]
@frenck I updated the post with requested information

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by PavelHonza** [comment]
Hello all! Doesn't work for me. I think that couldn't work because Garmin api returning body data like this: 

`{
"startDate": "2020-04-21",
"endDate": "2020-04-22",
"dateWeightList": [
{
"samplePk": 1587514937000,
"date": 1587522137000,
"calendarDate": "2020-04-22",
"weight": 88849.9984741211,
"bmi": 26.799999237060547,
"bodyFat": 15.289999961853027,
"bodyWater": 61.83000183105469,
"boneMass": 6639,
"muscleMass": 36130,
"physiqueRating": null,
"visceralFat": null,
"metabolicAge": null,
"sourceType": "INDEX_SCALE",
"timestampGMT": 1587514937000,
"weightDelta": 2299.9999999999973
}
],
"totalAverage": {
"from": 1587427200000,
"until": 1587599999999,
"weight": 88849.9984741211,
"bmi": 26.799999237060547,
"bodyFat": 15.289999961853027,
"bodyWater": 61.83000183105469,
"boneMass": 6639,
"muscleMass": 36130,
"physiqueRating": null,
"visceralFat": null,
"metabolicAge": null,
"weightCount": 1,
"bmiCount": 1,
"bodyFatCount": 1,
"bodyWaterCount": 1,
"boneMassCount": 1,
"muscleMassCount": 1,
"physiqueRatingCount": 0,
"visceralFatCount": 0,
"metabolicAgeCount": 0
}
}`

There is **dateWeightList** and **totalAverage**
But we are looking for **Weight** only which is wrapped in **totalAverage** tag. It returns None for all body values. 

Here is log: 

`2020-04-22 02:24:18 DEBUG (MainThread) [garminconnect] Fetching body composition with url https://connect.garmin.com/modern/proxy/weight-service/weight/daterangesnapshot?startDate=2020-04-22&endDate=2020-04-22
2020-04-22 02:24:19 DEBUG (MainThread) [garminconnect] Body Composition response code 200, and json {'startDate': '2020-04-22', 'endDate': '2020-04-22', 'dateWeightList': [{'samplePk': 1587514937000, 'date': 1587522137000, 'calendarDate': '2020-04-22', 'weight': 88849.9984741211, 'bmi': 26.799999237060547, 'bodyFat': 15.289999961853027, 'bodyWater': 61.83000183105469, 'boneMass': 6639, 'muscleMass': 36130, 'physiqueRating': None, 'visceralFat': None, 'metabolicAge': None, 'sourceType': 'INDEX_SCALE', 'timestampGMT': 1587514937000, 'weightDelta': 2299.9999999999973}], 'totalAverage': {'from': 1587513600000, 'until': 1587599999999, 'weight': 88849.9984741211, 'bmi': 26.799999237060547, 'bodyFat': 15.289999961853027, 'bodyWater': 61.83000183105469, 'boneMass': 6639, 'muscleMass': 36130, 'physiqueRating': None, 'visceralFat': None, 'metabolicAge': None, 'weightCount': 1, 'bmiCount': 1, 'bodyFatCount': 1, 'bodyWaterCount': 1, 'boneMassCount': 1, 'muscleMassCount': 1, 'physiqueRatingCount': 0, 'visceralFatCount': 0, 'metabolicAgeCount': 0}}`

`2020-04-22 02:24:19 DEBUG (MainThread) [homeassistant.components.garmin_connect.sensor] Registering entity: weight, Weight, kg, mdi:weight-kilogram, None, False
2020-04-22 02:24:19 DEBUG (MainThread) [homeassistant.components.garmin_connect.sensor] Registering entity: bmi, BMI, , mdi:food, None, False
2020-04-22 02:24:19 DEBUG (MainThread) [homeassistant.components.garmin_connect.sensor] Registering entity: bodyFat, Body Fat, %, mdi:food, None, False
2020-04-22 02:24:19 DEBUG (MainThread) [homeassistant.components.garmin_connect.sensor] Registering entity: bodyWater, Body Water, %, mdi:water-percent, None, False
2020-04-22 02:24:19 DEBUG (MainThread) [homeassistant.components.garmin_connect.sensor] Registering entity: bodyMass, Body Mass, kg, mdi:food, None, False
2020-04-22 02:24:19 DEBUG (MainThread) [homeassistant.components.garmin_connect.sensor] Registering entity: muscleMass, Muscle Mass, kg, mdi:dumbbell, None, False
2020-04-22 02:24:19 DEBUG (MainThread) [homeassistant.components.garmin_connect.sensor] Registering entity: physiqueRating, Physique Rating, , mdi:numeric, None, False
2020-04-22 02:24:19 DEBUG (MainThread) [homeassistant.components.garmin_connect.sensor] Registering entity: visceralFat, Visceral Fat, , mdi:food, None, False
2020-04-22 02:24:19 DEBUG (MainThread) [homeassistant.components.garmin_connect.sensor] Registering entity: metabolicAge, Metabolic Age, , mdi:calendar-heart, None, False`

**Comment by cyberjunky** [comment]
Hi Pavel, can you open an issue here: https://github.com/cyberjunky/python-garminconnect/issues
And close this one

It's a better location, since thats the repository of the library parsing these values.
And I will have a look/fix.
Can you tell me where your weight values come from, garmin smart scale, smartphone app, other linked portal?

**Pull request merged**
