### PR TITLE
Add hashop to the list of SkyConnect distributors

### PR DESCRIPTION
**Pull request by b-uwe**
## Proposed change
Add hashop to the list of SkyConnect distributors

## Type of change
- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information
-

## Checklist
- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Did something go wrong here?

The content doesn't match the description of the PR:

image

**Comment by b-uwe** [comment]
> Did something go wrong here?
> 
> The content doesn't match the description of the PR:
> 
> image

That's weird! SmartGuys were added with https://github.com/home-assistant/home-assistant.io/pull/25864 🧐

**Comment by b-uwe** [comment]
SCR-20230125-idk

🤔

**Comment by b-uwe** [comment]
I have no clue what went wrong here! It's a mystery to me...
I'll start anew @frenck and see what happens

**Comment by klaasnicolaas** [comment]
Your code wants to add a link from smartguys, but you say you want to add a link from hashop?

**Comment by b-uwe** [comment]
I assume, the issue was that my fork was totally out of sync with upstream 🤦 ! I'm not even 100% sure if that really describes it, but I started anew with https://github.com/home-assistant/home-assistant.io/pull/25939 and I think it looks much better now!
Sry for the hassle! I learned what to watch out for today!

**Pull request closed without merging**
