### PR TITLE
Add binary sensor platform to Renault integration

### PR DESCRIPTION
**Pull request by epenet**
## Proposed change

Add binary sensor plaform to Renault integration, as a follow up to #14383

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/54750
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Why adding 2 times the same file to this repository?

**Comment by epenet** [comment]
Hi @klaasnicolaas,
This is the reason it is currently marked as draft.
The root cause is that PR #14383 was merged inside `current` but not inside `next` branch, and I am waiting for @frenck to sort this out before I do a rebase.

**Review by frenck — APPROVED** [review]
Thanks, @epenet 👍

**Comment by epenet** [comment]
Thanks @frenck

**Pull request merged**
