### PR TITLE
Update MPD configuration variables

### PR DESCRIPTION
**Pull request by definitio**
**Description:**
Update style of MPD component documentation to follow new configuration variables description.
Related to #6385.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
I think you should do this in the `current` branch

**Comment by definitio** [comment]
> I think you should do this in the `current` branch

Should I create a new pull request?

**Comment by klaasnicolaas** [comment]
I think it is the easiest way, how do you normally always correct this @frenck ?

**Comment by definitio** [comment]
I will make a new pull request into current branch.

**Comment by frenck** [comment]
@klaasnicolaas Normally you'd change the target branch and rebase your changes onto the `current` branch.

**Pull request closed without merging**
