### PR TITLE
shell_command: Fix minor typo

### PR DESCRIPTION
**Pull request by RoboMagus**
## Proposed change

Minor typo fix for previous PR of mine that already got merged: #28226
Found while referencing this example in another PR: #28329

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by RoboMagus** [comment]
Hhm, don't think this needs to be on the current branch as suggested by the bot seeing as the spelling change is on changes that are on the next branch...

**Review by frenck — APPROVED** [review]
Thanks, @RoboMagus 👍 

../Frenck

**Comment by RoboMagus** [comment]
So fast every time! Thanks Frenck 😄

**Pull request merged**
