### PR TITLE
Revert "Add target_temp_step to generic_thermostat"

### PR DESCRIPTION
**Pull request by thecode**
Reverts home-assistant/home-assistant.io#20052

- https://github.com/home-assistant/core/pull/70299

Note: we can wait with this revert few days as we try to resolve and undo the core revert

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Pre-approved. Merge when you see fit 👍

**Comment by arantes555** [comment]
> Note: we can wait with this revert few days as we try to resolve and undo the core revert

https://github.com/home-assistant/core/pull/70303

I just pushed a new PR to revert the core revert, so I support waiting before reverting this documentation change.

**Comment by bdraco** [comment]
Marking this as a draft since I think we can merge the new PR and close this pending the discussion there

**Comment by thecode** [comment]
No need for this anymore

**Pull request closed without merging**
