### PR TITLE
Add doc for api.ai component

### PR DESCRIPTION
**Pull request by adrianlzt**
**Description:**
Doc for Api.ai component.

I will add more examples with api.ai configuration.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#5462

### CODE REVIEW

**Comment by adrianlzt** [comment]
Maybe should be created another category like "chat" ?

**Comment by adrianlzt** [comment]
I have uploaded an example file for Api.ai in filebin.ca
Can I put somewhere in this repo? It is just 8KB

**Comment by fabaff** [comment]
Sorry, I missed that one for 0.38.

**Comment by fabaff** [comment]
> I have uploaded an example file for Api.ai in filebin.ca

@adrianlzt, can you please provide a link to the file? Thanks.

**Comment by fabaff** [comment]
Sorry, found it

**Pull request merged**
