### PR TITLE
Improve Enphase Envoy documentation

### PR DESCRIPTION
**Pull request by DavidDeSloovere**
**Description:**
Mentioning 2 types of models/metrics.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#17032

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by fabaff** [comment]
Can you please rebase your branch?

**Comment by DavidDeSloovere** [comment]
Figuring out how to do that now. Not used to working with forks.

**Comment by DavidDeSloovere** [comment]
I'm just making it worse. Will have to restart.

**Comment by DavidDeSloovere** [comment]
https://github.com/home-assistant/home-assistant.io/pull/6409 recreated it.

**Pull request closed without merging**
