### PR TITLE
Climate 1.0

### PR DESCRIPTION
**Pull request by balloob**
**Description:**
PR to keep track of all the changes made for climate 1.0.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** https://github.com/home-assistant/home-assistant/pull/23899

Climate docs to check:

* [x] Climate platform

### Integrations affected

* [x] homematic
* [x] demo
* [x] xs1
* [x] hive
* [x] mill
* [x] lcn
* [x] oem
* [x] toon
* [x] deconz
* [x] tesla
* [x] vera
* [x] zwave
* [x] velbus
* [x] wink
* [x] dyson
* [x] tefiac
* [x] tado
* [x] mqtt
* [x] venstar
* [x] zhong_hong
* [x] tuya
* [x] spider
* [x] radiotherm
* [x] sensibo
* [x] smartthings
* [x] melissa
* [x] fibaro
* [x] mysensors
* [x] nest
* [x] ecobee
* [x] elkm1
* [x] flexit
* [x] coolmaster
* [x] daikin
* [x] honeywell #9816
* [x] proliphix
* [x] ephember
* [x] incomfort
* [x] homekit
* [x] homekit_controller
* [x] geniushub
* [x] touchline
* [x] stiebel_eltron
* [x] opentherm_gw
* [x] nuheat
* [x] netatmo
* [x] modbus
* [x] maxcube
* [x] knx
* [x] homematicip_cloud
* [x] heatmiser
* [x] generic_thermostat
* [x] fritzbox
* [x] evohome #9819
* [x] esphome
* [x] eq3btsmart
* [x] ambiclimate

### Others

* [x] Alexa
* [x] Google Assistant

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

<a href="https://gitpod.io/#https://github.com/home-assistant/home-assistant.io/pull/9799"></a>

<a href="https://gitpod.io/#https://github.com/home-assistant/home-assistant.io/pull/9799"></a>

### CODE REVIEW

**Comment by frenck** [comment]
Tagging code owners for integrations with climate platforms. Please help migrate your integration documentation to the new Climate 1.0 architecture by opening a PR against the `climate-1` branch:

| integration | Code owners |
| -- | -- |
| smartthings | @andrewsayre |
| nest | @awarecan |
| daikin | @fredrike, @rofrantz |
| honeywell | @zxdavb |
| ephember | @ttroy50 |
| incomfort | @zxdavb |
| homekit | @cdce8p |
| homekit_controller | @Jc2k |
| geniushub | @zxdavb |
| stiebel_eltron | @fucm |
| opentherm_gw | @mvn23 |
| knx | @Julius2342 |
| evohome | @zxdavb |

Thanks, guys! Your help is greatly appreciated 👍

**Comment by ttroy50** [comment]
I don't think ephember docs need any update. If they do can you give more details / an example of what's needed?

**Comment by frenck** [comment]
@ttroy50 Thanks for taking a look. I was not sure if it was needed since the docs mention something about ON/OFF. Since that behavior changed a bit, an extra pair of eyes was appreciated.
I've checked off `ephember` 👍

**Comment by Jc2k** [comment]
@frenck I checked and the homekit_controller docs are really basic and there are no climate specific bits there that need changing, so that can be checked off.

**Comment by frenck** [comment]
Done! Thanks, @Jc2k 👍

**Comment by andrewsayre** [comment]
We also need to [update the climate developer docs](https://developers.home-assistant.io/docs/en/entity_climate.html) -- not sure if that's something we want to track here or in the other repo?

**Comment by balloob** [comment]
@andrewsayre https://github.com/home-assistant/developers.home-assistant/pull/289

**Comment by mvn23** [comment]
`opentherm_gw` docs need not be updated for this as far as I can see.

**Comment by frenck** [comment]
Thanks, @mvn23, checked it off. ✅

**Pull request merged**
