### PR TITLE
Add weeday blueprint example

### PR DESCRIPTION
**Pull request by SirGoodenough**
## Proposed change

Little trick I came up with to help people looking to have a weekday selector in their blueprint.
This seemed the best place to put it.
As always, if it fits elsewhere or is not appropriate, I understand.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #
https://community.home-assistant.io/t/wip-day-time-selector/333870

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by frenck** [comment]
What is the trick? 🤷‍♂️

**Comment by SirGoodenough** [comment]
Weekday as such is not on the 'select-able' list.  This makes it available.  I found comments in the community asking how to do it and there was no answer.
Also there was not an example of label / value pairs, only mentions of it and I thought an example would be helpful.
Since this is the only place I found the weekday (time) condition, it seemed to me to fit here.

**Comment by frenck** [comment]
So the goal is to document the Selectors capability of handling key/value pairs in the select selector?

**Comment by SirGoodenough** [comment]
And primarily how to show the weekday as a selector item.

**Comment by frenck** [comment]
Isn't this a better fit for the selectors documentation instead in that case?

**Comment by SirGoodenough** [comment]
If you think it fits better there, I could replace the mapping example here.
https://www.home-assistant.io/docs/blueprint/selectors/#configuration-variables

**Pull request closed without merging**
