### PR TITLE
Fix all occurences of markdownlinter MD009 warning

### PR DESCRIPTION
**Pull request by stefanroelofs**
## Proposed change
The markdownlinter gives a warning when there are trailing spaces.
This pull request removes all trailing spaces in this repo (270 files).

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information
Read the definition of rule MD009 [here](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md009).

Here are some of the steps I did to make this pull request:
- Run this command: `mdl -r MD009 home-assistant.io > output.txt`
- Output is piped to a text file
- Clean up the text file
- Use an [online service](https://www.textfixer.com/tools/remove-duplicate-lines.php) to clean up duplicate lines
- Create an Notepad++ session file, and enter all file paths into this session file
- Open the session file in Notepad ++ to load all 270 files at once
- Open find and replace and enter the following regex: `[ \t]+$`
- Hit: Replace all in all opened documents
- Save everything

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by frenck** [comment]
image

This is a PR size that is not re-viewable, please split this into multiple PRs

**Comment by stefanroelofs** [comment]
> image
> 
> This is a PR size that is not re-viewable, please split this into multiple PRs

Yeah, I was afraid of that...

Considering the type of code changes (only removing whitespace),
how big should the PR be? How many affected files at once?

**Comment by klaasnicolaas** [comment]
Just smaller batches, let's say max 20 files for each PR. Makes it for us better to review 😉

**Comment by stefanroelofs** [comment]
Alright, thanks for checking!
I'll close this and see if I can make some smaller batches.

**Pull request closed without merging**
