### PR TITLE
Add deprecated warning to synology integration

### PR DESCRIPTION
**Pull request by shenxn**
## Proposed change

The `synology` integration is deprecated. Adds warning note to the documentation.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: home-assistant/core#39958
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @shenxn 👍

**Comment by S-Przybylski** [comment]
Dear @shenxn 
dear @frenck 
its a good idea to consolidate integrations, but currently i am only using the camera integration and this doesn't necessarly need an administrative account. Now it does! This needs to be considered too...
Is a documentation update for the integration synology_dsm available (new camera items)?

Currently I do not get my current configuration moved to the new one. It seems that the stream changed too. In the past it was mjpeg using a medium solution (i have three streams available per cam). Now it seems to be different - i have no picture at all (Android app and also PC).

**Comment by frenck** [comment]
@S-Przybylski PRs (especially handled ones) are not the place for support or questions.
If you are in need for help or support, please use or community forum or use the Discord chat. In case you suspect a bug, please file an issue report.

Thanks 👍

**Comment by S-Przybylski** [comment]
Sorry @frenck 
I promise I'll do better. :mask:

**Pull request merged**
