### PR TITLE
Cleanup Xiaomi Miio docs

### PR DESCRIPTION
**Pull request by rytilahti**
## Proposed change

The current `xiaomi_miio` documentation is very verbose in terms of what types of sensors, switches, and other entities are available. As "miio" itself is a platform supporting a wide variety of different types of devices from a variety of different vendors, it does not make sense to document each and every available device-specific detail in the homeassistant documentation.

The goal of this PR is to relieve both developers and documentation writers from the burden of keeping the information stored in the documentation in sync with the code. This (or a follow-up PR) should reorganize the docs to document the supported platforms and only document the custom services, alongside with known limitations if any.

Therefore, this cleanup PR removes the pieces of documentation that I personally consider unnecessary:
* Documentation that is already done for standardized platforms
* Documentation that is too specific for any given model, considering that xiaomi_miio is a platform integration much like homekit & co.

Note that this PR at places also removes information about the list of supported device models and device-specific limitations, which should be forced by the implementation. If wanted, such information (e.g., oscillation angles, available modes, ..) should be codified in a more general way (using entity descriptions?) to automatically generate documentation in the future.

### Follow-up PRs will handle the following
- [ ] Restructure the document to be based on supported platforms
- [ ] Rewrite the intro to follow that structure instead of pointing to specific devices
- [ ] Clean up the token extraction (mostly unnecessary for people using the cloud access, so just add a link or two for alternative approaches for manual configuration?)

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by syssi — APPROVED** [review]
I would be happy to have this cleanup merged as first step.

**Comment by rytilahti** [comment]
This is still pending for feedback.

**Comment by frenck** [comment]
@rytilahti From who?

**Comment by frenck** [comment]
Because there hasn't been any activity on this PR for quite some time now, I've decided to close it for being stale.

Feel free to re-open this PR when you are ready to pick up work on it again 👍

**Pull request closed without merging**
