### PR TITLE
Update links to smartthings developer website

### PR DESCRIPTION
**Pull request by mbo18**
## Proposed change

Smartthings developer website has changed, so I updated all links the smartthings documentation

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by frenck** [comment]
Hi there @mbo18 👋 

Any specific reason for this PR to be marked as draft at this point?

../Frenck

**Comment by mbo18** [comment]
Not really because it is finished. It includes the change I made in this PR: https://github.com/home-assistant/home-assistant.io/pull/22903
So I’m waiting for next week as I used the current branch (I don’t know if it matters or not)

**Comment by frenck** [comment]
If this PR contains two different changes (on to the existing documentation and another for new features), it should be split into separate PRs.

Please, if a merged new feature lands in HA 2022.7, that part should target the `next` branch.

**Comment by mbo18** [comment]
I've updated my PR (no more conflict + added a link I missed). It is now ready for review. 
This PR now only contains updated links and so it is using the correct branch (current)

**Review by frenck — APPROVED** [review]
Thanks, @mbo18 👍

**Pull request merged**
