### PR TITLE
rflink: Add hint about which configuration file is used

### PR DESCRIPTION
**Pull request by JulianGro**
## Proposed change
This adds the same ``# Example configuration.yaml entry`` line that is used in other code blocks to the two code clocks that are missing it.

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: -
- Link to parent pull request in the Brands repository: -
- This PR fixes or closes issue: https://github.com/home-assistant/home-assistant.io/issues/16354

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @JulianGro, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#16360).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by frenck** [comment]
@JulianGro This PR looks ready to go, but is marked as a draft. Is the draft status correct?

**Comment by JulianGro** [comment]
I wanted to include some other information to fully close #16354
I undraft the PR if you would rather merge this sooner.

**Review by frenck — APPROVED** [review]
Thanks, @JulianGro 👍

**Pull request merged**
