### PR TITLE
Mqtt scene has no default for `payload_on`

### PR DESCRIPTION
**Pull request by jbouwh**
## Proposed change

Mqtt scene has no default for `payload_on`. Removed the default.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by emontnemery** [comment]
Next is current in a week, not today..

@frenck Are merge conflicts a concern, and if they are, what's the best approach to avoid them?

Should we reopen the revert-PR, https://github.com/home-assistant/home-assistant.io/pull/22194 and merge that to current and only do changes to next?

**Comment by jbouwh** [comment]
removed the last commit that should be in next

**Comment by jbouwh** [comment]
Could we cherry-pick the commit https://github.com/home-assistant/home-assistant.io/pull/22193 into next? That makes it possible to re-add an option that is is still in next, but not in current.

This PR will enable to re-add it in next: https://github.com/home-assistant/home-assistant.io/pull/22197

**Comment by jbouwh** [comment]
Not up-to-date anymore.

**Pull request closed without merging**
