### PR TITLE
Moving Lovelace Dashboards to Views page

### PR DESCRIPTION
**Pull request by akasma74**
## Proposed change

Based on [this](https://github.com/home-assistant/home-assistant.io/issues/12462) issue #12462 
As dashboards are not limited to YAML mode, it makes the information on them hard to find when it's a part of Lovelace YAML mode page.
I propose to add informatin about dashboards' configuration to the page about Views and rename it accordingly (don't know where to change link to it from the right-hand panel though). The Lovelace YAML mode page has a link to Dashboards page.

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Looks good! 👍 

Please update the sidebar menu as well, to reflect the title.

**Comment by akasma74** [comment]
> Please update the sidebar menu as well, to reflect the title.

happy to if you tell me where it is, couldn't find it :(

**Comment by frenck** [comment]
The file can be found here:

<https://github.com/home-assistant/home-assistant.io/blob/current/source/_includes/asides/lovelace_navigation.html>

**Comment by frenck** [comment]
All good! One thing I just realized, because of your menu edit commit, we need to make sure the old URL still works.
Please add a redirect to the redirects file in `_source/redirects`

**Review by frenck — APPROVED** [review]
Awesome! Thanks 👍

**Pull request merged**
