### PR TITLE
Add Tahoma binary_sensor docu

### PR DESCRIPTION
**Pull request by fucm**
**Description:**
Add Tahoma binary_sensor docu

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#15441

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Looks fine @fucm! 👍 
Can be merged as soon as the parent PR gets merged.

**Comment by frenck** [comment]
Closing this PR, since the parent PR has been closed.

**Comment by fucm** [comment]
Can this PR opened again? I adjusted the referenced PR. There were two parent PR, one old closed and a new one.

**Comment by frenck** [comment]
Done!

**Pull request merged**
