### PR TITLE
Add spider power plug component

### PR DESCRIPTION
**Pull request by peternijssen**
**Description:**
This PR adds the power plug component of Spider

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#15682

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by peternijssen** [comment]
The mentioned PR has been merged. 

I noticed in the last build/deploy, that I couldn't find the switch. Not sure if it only built the last commit.

**Comment by frenck** [comment]
I'm unsure why it is not in the latest build, for now, I'm assuming this will be taken care of by the latest build. Surely something we need to monitor on release.

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Did some minor tweaks.
Can be merged as soon as the build passes.

**Comment by peternijssen** [comment]
I checked a recent PR that was created here after this PR got merged and it contains both the Hub, Climate and Switch component. So I believe everything is okay!

**Pull request merged**
