### PR TITLE
Updated HipChat discontinuation information

### PR DESCRIPTION
**Pull request by ketilmo**
**Description:**

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
I don't see the added value of your adjustment in this PR

**Comment by ketilmo** [comment]
Ok, understood. I attempted to clarify the fact that HipChat has now been discontinued, but understand that this might have little value given that it’s going away anyway. :)

**Comment by klaasnicolaas** [comment]
In the 0.101 release it will be removed, that PR has already been merged 😉

**Comment by ketilmo** [comment]
All right, my apologies for missing out on that one. Thanks for clarifying! 😊

**Pull request closed without merging**
