### PR TITLE
Modified to fit the pull request

### PR DESCRIPTION
**Pull request by SupremeSports**
**Description:**
Added the user exposed functionality or configuration variables

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#20764

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
I think this is something that must in the `next` branch

**Comment by SupremeSports** [comment]
> I think this is something that must in the `next` branch

How do I do this? It creates my PR using patch-1 by default

**Comment by klaasnicolaas** [comment]
Make a new branch of the `next` on your fork, redo your changes and then create a new PR that will merge this time into the `next` branch.

**Comment by SupremeSports** [comment]
So I delete this one?

**Comment by SupremeSports** [comment]
[Changed](https://github.com/home-assistant/home-assistant.io/pull/8412)

**Pull request closed without merging**
