### PR TITLE
Updated omnilogic documentation for new switch platform

### PR DESCRIPTION
**Pull request by djtimca**
## Proposed change

Added documentation for switch platform to Omnilogic integration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/42116
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by djtimca** [comment]
Rebased as requested to next branch.

**Comment by klaasnicolaas** [comment]
Your branch is still on the `current` branch.

**Comment by djtimca** [comment]
@klaasnicolaas my local repo branch is current, but I rebased to the next branch from this repo.

**Comment by klaasnicolaas** [comment]
Rebase local and push it to the brach related to this PR 😉

**Comment by djtimca** [comment]
@klaasnicolaas that was what I thought I did... is it not?

**Comment by klaasnicolaas** [comment]
You did, but the base of your branch is still `current`, maybe it is better to start with a fresh start and create a new branch that descends from the `next` branch.

**Comment by djtimca** [comment]
Thanks @klaasnicolaas - that does sound easier. Will do.

**Pull request closed without merging**
