### PR TITLE
Update for Refactor Waze Travel Time & Update Requirements #22428

### PR DESCRIPTION
**Pull request by Petro31**
update to the documentation when https://github.com/home-assistant/home-assistant/pull/22428 hits.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#22428

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
There is a new parent PR

**Comment by Petro31** [comment]
@frenck will this get merged automatically when 0.95 is released?  Or should this get merged before then?  The other PR was merged 10 days ago.

**Comment by klaasnicolaas** [comment]
@Petro31 First you need to solve the merge conflic. Rebase/update your fork with a recent version because the file name is not correct 😉

**Review by frenck — CHANGES_REQUESTED** [review]
@Petro31 Could you please take a look at the merge conflict so we are able to merge it for 0.95?

**Comment by balloob** [comment]
Cherry picked the commits for release.

**Pull request closed without merging**
