### PR TITLE
Fix typo in unifi direct docs

### PR DESCRIPTION
**Pull request by bullb0g**
form -> from

**Description:**

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This needs to be based on and targeting the `current` branch.

**Comment by bullb0g** [comment]
I've never used git/github before and I thought I could do rebase via the web interface. This doesn't look right so I'll close this one.   :expressionless:

**Comment by frenck** [comment]
@bullb0g You could have asked? I'm happy to rebase for you, however, you've deleted the branch now. Could you do a new PR?

**Comment by frenck** [comment]
You can also click the restore branch button and re-open the PR. I'll pick up from there.

**Pull request closed without merging**
