### PR TITLE
update Xbox docs to accurately represent manual setup

### LINKED ISSUE #15375: Xbox Integration not adding
## The problem

Unable to add Xbox integration.

## Environment

- Home Assistant Core release with the issue: 0.117.0b1
- Last working Home Assistant Core release (if known): n/a
- Operating environment (OS/Container/Supervised/Core): Container
- Integration causing this issue: Xbox
- Link to integration documentation on our website: https://rc.home-assistant.io/integrations/xbox/

## Traceback/Error logs

```txt
n/a
```

## Additional information
Error message: `The component is not configured. Please follow the documentation.`

image

### PR DESCRIPTION
**Pull request by hunterjm**
## Proposed change

Fix install instructions and reference "cloud" in the account linking description.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: N/A
- Link to parent pull request in the Brands repository: N/A
- This PR fixes or closes issue: closes #15375

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This PR needs to be targeted at the `next` branch (same procedure as the `dev` branch in the core repository).

Please change the target branch of this PR and git rebase if needed.

**Comment by hunterjm** [comment]
Done

**Comment by frenck** [comment]
@hunterjm Still needs a git rebase (unrelated commits in this PR)

**Comment by frenck** [comment]
Rebased PR onto the latest next branch

**Review by frenck — APPROVED** [review]
Thanks, @hunterjm 👍

**Pull request merged**
