### PR TITLE
Update blebox.markdown

### PR DESCRIPTION
**Pull request by riokuu**
Changes regarding PR merged in https://github.com/home-assistant/core/pull/74395

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @gobanza, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#23356).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by riokuu** [comment]
Is there any action required from me? Cheers

**Review by frenck — CHANGES_REQUESTED** [review]
There are unrelated commits in this PR

CleanShot 2022-07-12 at 08 53 14@2x

Most likely caused by basing this branch of `current` instead of the `next` branch. Please git rebase your commits onto the `next` branch to clean it up.

Thanks! 👍 

../Frenck

**Comment by riokuu** [comment]
@frenck will it be fine if I close this PR, pull current `next` and proceed from here?

**Comment by klaasnicolaas** [comment]
It just depends on what works for you, rebasing is not very difficult. But alternatively you could indeed open a new pull request with the correct branch.

**Pull request closed without merging**
