### PR TITLE
Update home_connect.markdown

### PR DESCRIPTION
**Pull request by Sjack-Sch**
Functional and ambient light added.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/44091
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
Please rebase and target next branch.

**Comment by Sjack-Sch** [comment]
> Please rebase and target next branch.

I am not sure what to do next. Do  I need to create a new branch?

**Comment by MartinHjelmare** [comment]
Rebasing is a `git` command. If you're not comfortable with git you can also open a new PR from a fresh branch based on `next` branch, and link the new PR here.

**Comment by Sjack-Sch** [comment]
> Rebasing is a `git` command. If you're not comfortable with git you can also open a new PR from a fresh branch based on `next` branch, and link the new PR here.

This is the new PR: Functional and ambient light added. #15968

**Pull request closed without merging**
