### PR TITLE
Update Bond documentation to include all applicable categories

### PR DESCRIPTION
**Pull request by prystupa**
## Proposed change

Add three additional categories applicable to bond integration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
For completeness, are there links to the pull requests (core repo) that these additional platforms add? To make sure everything is merged and working in release 0.114 😉

**Comment by prystupa** [comment]
> For completeness, are there links to the repositories that these additional platforms add? To make sure everything is merged and working in release 0.114 😉

Thanks @klaasnicolaas - just to make sure I understand what links you are looking for. This is the integration code in the rc branch: https://github.com/home-assistant/core/tree/rc/homeassistant/components/bond

It has support for all the categories this PR is adding to documentation.

**Review by marciogranzotto — DISMISSED** [review]

**Comment by marciogranzotto** [comment]
@klaasnicolaas since this integration is going to be on release 0.113 today, can we get this merged?

**Comment by frenck** [comment]
It was unfortunately not tagged on the milestone, and thus missed. I've already cut and merged the release. So I'll be handling this after the release.

**Comment by frenck** [comment]
Alright, 0.113 is live. I've rebased this PR onto the `current` branch, so it would show up on the current documentation after merge.

Will merge it after the build passes.

**Review by frenck — APPROVED** [review]

**Pull request merged**
