### PR TITLE
Reverse the placement of the phone mockup on mobile phones

### PR DESCRIPTION
**Pull request by johanf85**
## Proposed change

Currently  on mobile phones in portrait mode, the phone image is displayed first and the "Awaken your home" text is displayed. This makes that the phone doesn't align to the edge of the blue section. Which it does do on desktop. It think it looks better when the phone is aligned below the blue section.

The current divs containing the content are using flexbox. With flexbox it is possible to set the order of the items. It is possible to reverse the order, which is suitable for this. 

I looked at the _grid-fix.scss file to make sure flexbox is applied to palm screens as well and set the order to column-reverse. I added classnames to make a generic solution. Next to that added a class in hero_unit.html and removed the margin on the phone image on palm screens. 

Current situation:

Proposed:

image

See it live: https://deploy-preview-19596--home-assistant-docs.netlify.app/ in mobile view. 

## Type of change

*   [x] Spelling, grammar or other readability improvements (`current` branch).
*   [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
*   [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
    *   [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
*   [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
*   [ ] Removed stale or deprecated documentation.

## Additional information

*   Link to parent pull request in the codebase:
*   Link to parent pull request in the Brands repository:
*   This PR fixes or closes issue:

## Checklist

*   [x] This PR uses the correct branch, based on one of the following:
    *   I made a change to the existing documentation and used the `current` branch.
    *   I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
*   [x] The documentation follows the Home Assistant documentation [standards](https://developers.home-assistant.io/docs/documenting/standards).

### CODE REVIEW

**Comment by johanf85** [comment]
Note: I set the threshold for this at palm-end, it might be better to set this to lap-start, cause in horizontal mode it doesn't display nicely yet.

**Comment by frenck** [comment]
I personally think that a picture says more than a thousand words, in this case starting with an image 

From the image, one can instantly see one can toggle e.g., the kitchen lights. "Awaken your home", however, does not trigger such imagination at all.

For that reason, I think it isn't right to swap this.

**Comment by johanf85** [comment]
I understand what you mean, the image is important. Though, the sudden cut of the phone image, without the image aligned to a border seems not so nice looking to me. Seems unfinished.  
  
As an alternative, how do you feel about something like below?



This could be done by CSS on mobile screens.  What's your opinion @balloob?

**Comment by balloob** [comment]
What if we drop/shrink "Awaken your home" on mobile and do text above the screenshot?

**Comment by johanf85** [comment]
I am afraid that will drive the focus away from the screenshot image. But the image placement actually isn't a big issue. It's not a vital change, I think it's okay to leave it like it is now.

**Pull request closed without merging**
