### PR TITLE
Timer restore state on restart documentation

### PR DESCRIPTION
**Pull request by e2m32**
To be paired with pull request in core: https://github.com/home-assistant/home-assistant/pull/28593#

**Description:**
Updated docs for timer with restored state support.

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#28593

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Please rebase this PR to the `next` branch

**Comment by e2m32** [comment]
## Edit:
Nevermind. I was doing it backwards. Got it. I'll push now.



------
oops. How do I do that on a single commit? I tried this:

```
git checkout patch-7
git cherry-pick 382a88e5694a1c353a6af8af0032d4cdc305e006
```

but I get this error:
```
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git cherry-pick --skip'
On branch patch-7
Your branch is up to date with 'origin/patch-7'.

You are currently cherry-picking commit 382a88e569.

Untracked files:
        _deploy/

nothing added to commit but untracked files present

```

**Comment by klaasnicolaas** [comment]
Cherry picking is not the right way, you need to use the `git rebase` command.

**Comment by e2m32** [comment]
I tried that first, but it rebased the entire patch-7 branch. I just gave up and deleted my fork and started over. New pull request is here: https://github.com/home-assistant/home-assistant.io/pull/11117

**Pull request closed without merging**
