### PR TITLE
updated nuki documentation

### PR DESCRIPTION
**Pull request by pree**
## Proposed change

This updates the nuki documentation due to breaking changes in my PR in homeassistant/core.
(https://github.com/home-assistant/core/pull/40933)

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by frenck** [comment]
The parent for this PR is merged, however, a wild merge conflict appeared out of nowhere! 🙈 

Could you take a look @pree?

**Comment by pree** [comment]
I think this PR is obsolete, the parent doesn't change the nuki configuration, since it moved to config_flow anyway. Should we document, that the doorsensor is now also available? Otherwise we can close this PR

**Comment by apmosss** [comment]
I think you should document that door sensor is now also available.

**Comment by frenck** [comment]
This PR is obsolete.

**Pull request closed without merging**
