### PR TITLE
Add Airzone System ID config

### PR DESCRIPTION
**Pull request by Noltari**
## Proposed change
Add new System ID configuration parameter:
https://github.com/home-assistant/core/pull/69751

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/69751
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This PR is targeting an incorrect branch. Since it has a parent PR in our main codebase, it means it depends on a next release of Home Assistant.

Please change the target of this branch to the `next` branch and git rebase your PR.

Thanks already! 👍 

../Frenck

**Comment by Noltari** [comment]
> This PR is targeting an incorrect branch. Since it has a parent PR in our main codebase, it means it depends on a next release of Home Assistant.
> 
> Please change the target of this branch to the `next` branch and git rebase your PR.
> 
> Thanks already! 👍
> 
> ../Frenck

@frenck the problem is that the next branch hasn't been updated with the latest airzone changes made to the current branch: 5e6108bb35e498154de894e11b3b19cfc01cb35c
BTW, I target the current branch on purpose because I thought that's what I should do when the parent PR of the core repository is a bugfix. Sorry!

**Comment by frenck** [comment]
> the problem is that the next branch hasn't been updated with the latest airzone changes made to the current branch

That has been resolved 🤟 

> BTW, I target the current branch on purpose because I thought that's what I should do when the parent PR of the core repository is a bugfix. Sorry!

It adds a new feature from the Home Assistant perspective, so it needs to go into the next release.

**Comment by Noltari** [comment]
> > the problem is that the next branch hasn't been updated with the latest airzone changes made to the current branch
> 
> That has been resolved 🤟

Awesome 👍 
I've changed the PR to the next branch and applied the commit on top of the latest upstream next branch.

**Review by frenck — APPROVED** [review]
Thanks, @Noltari 👍

**Pull request merged**
