### PR TITLE
Lovelace: custom badges and state-badge actions

### PR DESCRIPTION
**Pull request by iantrich**
**Description:**

https://github.com/home-assistant/home-assistant-polymer/pull/3867
https://github.com/home-assistant/home-assistant-polymer/pull/4028

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by iantrich** [comment]
So, I've added custom badges here and need them listed on the sidebar as cards are but I'm not sure how to accomplish this; will need some guidance

**Comment by iantrich** [comment]
I need further help on this. I'm not sure how to structure the docs so that I can get the badges in the sidebar.

**Comment by frenck** [comment]
@iantrich The main problem with this is, that Jekyll does not support nested collections (which you are trying to do as it seems).

I see 2 possible options:
1. Add a `_badges` folder next to `_lovelace` but that will disconnect it from the user experience maybe.
2. Add a `type` kinda variable to the frontmatter in every markdown in the `_lovelace` collection (e.g., `card`, `badge`) and filter the collection when creating those 2 separate menu's. In order to reduce effort on changing all of them, the default of the frontmatter config can be set to `card` in the Jekyll config, so it only needs to be overridden for badges.

I have to be honest here: Both aren't pretty IMHO. 😢

**Comment by iantrich** [comment]
I might just throw this in the views markdown for now 🤷‍♂

**Comment by frenck** [comment]
Well, that is a good start, right? :)

**Comment by frenck** [comment]
Working first, pretty later :)

**Review by frenck — APPROVED** [review]
👍

**Pull request merged**
