### PR TITLE
[climate] Migrate evohome docs for climate-1.0

### PR DESCRIPTION
**Pull request by zxdavb**
**Description:**
Migrate evohome docs for climate-1.0

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

<a href="https://gitpod.io/#https://github.com/home-assistant/home-assistant.io/pull/9819"></a>

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
This PR must be in the `climate-1` branch 😉

**Comment by zxdavb** [comment]
OMG should it be `climate-1`, or `next`?

**Comment by klaasnicolaas** [comment]
`climate-1` but sometimes when we adjust the target branch in github, there will be commits added that have nothing to do with the PR.

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
It should have been `climate-1` @zxdavb, nevertheless, we are running short on time, so merging it into `next` and I'll note/refer the PR in the main climate PR.

**Pull request merged**
