### PR TITLE
Add BMW deactivate_air_conditioning service

### PR DESCRIPTION
**Pull request by rikroe**
## Proposed change

Add documentation for  `bmw_connected_drive.deactivate_air_conditioning`.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: home-assistant/core/pull/57772
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by rikroe** [comment]
Oh, something happened that shouldn't happen. Apparently the Online Editor rebased against the wrong branch. Will try to rebase manually against `next`.

**Comment by rikroe** [comment]
Rebased against `next` is done. Or should it have been `current` as the core PR is already merged???

**Review by rytilahti — APPROVED** [review]
LGTM :+1: The 'next' branch is correct for new features to appear in the next homeassistant release, the 'current' branch will be published without a new release.

**Review by frenck — APPROVED** [review]
Thanks, @rikroe 👍

**Pull request merged**
