### PR TITLE
Update 2023-01-23-help-others-leave-ai-at-the-dor.markdown

### PR DESCRIPTION
**Pull request by nickrout**
Clarify rules (per @centralcommand's post in the forum thread.)

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — COMMENTED** [review]
This blog post is not about the forums only, but affects all places we interact with each other in and around the Home Assistant project.

Adding this here is a bit to specific for the goal of this blog post. If needed, we can check up with the moderator to see if we need to adjust the forums rules pages.

For the above reasoning, I'm going to friendly decline this PR.

../Frenck

**Comment by nickrout** [comment]
What, despite a PR being suggested by a developer?

People have been asking for clarification, what is it with you guys. The wording is as written by @centralcommand.

**Comment by frenck** [comment]
> What, despite a PR being suggested by a developer?

yes.

**Comment by aidbish** [comment]
> This blog post is not about the forums only, but affects all places we interact with each other in and around the Home Assistant project.

Other my post about it, i couldnt see anything official on the facebook group about its use.

Seems strange people try to help to clarify stuff and its knocked back and then we wonder why nobody wants to submit documentation updates.

**Comment by frenck** [comment]
Cool, yet this PR for the blogpost isn't the place. Thanks 🙏

**Pull request closed without merging**
