### PR TITLE
Add YS1604 SpeakerHub support

### PR DESCRIPTION
**Pull request by matrixd2**
## Proposed change

Add Number platform for  Speaker Hub volume setting

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:  https://github.com/home-assistant/core/pull/104678
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by klaasnicolaas — DISMISSED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged 👍

**Review by joostlek — CHANGES_REQUESTED** [review]
You also introduced a new platform, please add it to the header properties

**Comment by matrixd2** [comment]
> You also introduced a new platform, please add it to the header properties

Thanks, description changed.

**Comment by joostlek** [comment]
No I mean, you have to update your markdown file to include that change

**Review by joostlek — DISMISSED** [review]

**Review by joostlek — COMMENTED** [review]
Oh, apparently this branch has merge conflicts

**Review by joostlek — APPROVED** [review]

**Pull request merged**
