### PR TITLE
Restore away configuration options

### PR DESCRIPTION
**Pull request by dieselrabbit**
**Description:**

Restore away configuration options.
Clarify that "away" is a preset mode.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#25912

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

<a href="https://gitpod.io/#https://github.com/home-assistant/home-assistant.io/pull/10125"></a>

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @dieselrabbit!

There are unrelated commits in this PR, please rebase.

**Comment by dieselrabbit** [comment]
I'm sorry. I think I screwed something up. The original PR was accidentally created against current. I tried to correct it to next and got all those added. I'm not sure exactly what my next step would be. Git newbie.

**Comment by frenck** [comment]
Check out the repository with your branch locally and git rebase onto the `next` branch, followed by a force push.

**Comment by dieselrabbit** [comment]
I think I further messed this up. Tried to rebase, but had a conflict. Tried to resolve the conflict, but then ended up merging and now can't rebase. Easy change to redo. Should I just close this one and start over? Sorry I'm a pain.

**Comment by frenck** [comment]
Don't worry sir! We all need to learn at some point, right? I agree it is probably easier to put your changes in a new PR now.

**Pull request closed without merging**
