### PR TITLE
Add Xiaomi router device tracker documentation

### PR DESCRIPTION
**Pull request by RiRomain**
**Description: Documentation for new component Xiaomi Device Tracker**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#5283

### CODE REVIEW

**Comment by joaoasilva** [comment]
Hi,

After some time, for some reason the plugin doesn't refresh the token:

> 17-01-18 10:53:37 homeassistant.components.device_tracker.xiaomi: No list in response from mi router. {'msg': 'Invalid token', 'code': 401}
> Traceback (most recent call last):
>   File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/device_tracker/xiaomi.py", line 139, in _extract_result
>     return result[key_name]
> KeyError: 'list'

Thanks

**Comment by RiRomain** [comment]
Hi @joaoasilva ,

Which Xiaomi device are you using? With which firmware?

On my Xiaomi Mini, as long as the token is reused, he seems to be kept alive and considered valid by the router. It might be different on other Xiaomi router/Firmware.

I'll see to implement a token refresh method.

**Comment by joaoasilva** [comment]
Xiaomi router 3. Oh, maybe it's because I have the auto-restart everyday at 5am?
A token refresh method would be awesome though, please. :)

Thanks!

**Comment by RiRomain** [comment]
A yes that make sense, after the restart the token is not valid anymore.

I will implement a refresh method. If it fails, the program will search a new token and retry to get the list one more time.

**Comment by RiRomain** [comment]
@joaoasilva Good news, the change where merged in the dev branch:
https://github.com/home-assistant/home-assistant/pull/5437

The correction should therefore be available to you at the beginning of February with the next home-assistant release (0.37)

**Pull request merged**
