### PR TITLE
Merge netatmo_public into netatmo sensor.

### PR DESCRIPTION
**Pull request by cgtobi**
**Description:**
This is the accompanying docs change for the merge of `netatmo_public` into `netatmo`

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#23531

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
why not using the file name `netatmo.markdown`?

**Comment by cgtobi** [comment]
@klaasnicolaas Your wish is my command. ;-) Let's see if this builds fine and looks ok.

**Comment by klaasnicolaas** [comment]
Good job 😉

**Comment by cgtobi** [comment]
New documentation PR home-assistant/home-assistant.io#9414

**Pull request closed without merging**
