### PR TITLE
add Switcher Runner S12 support

### PR DESCRIPTION
**Pull request by YogevBokobza**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/127277
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

## Summary by CodeRabbit

- **Documentation**
	- Updated the list of supported devices to include the `Switcher Runner S12`.
	- Specified that the `Switcher Runner S12` requires a token for operation.
	- Enhanced descriptions for light control devices to include the `Switcher Runner S12`.
	- Added a new section detailing cover control for `Switcher Runner`, `Switcher Runner S11`, and `Switcher Runner S12`.

### CODE REVIEW

**Review by thecode — CHANGES_REQUESTED** [review]
Please add explanation about covers support (similar to lights)

**Comment by YogevBokobza** [comment]
> Please add explanation about covers support (similar to lights)

It is done.. see if this is ok

**Review by thecode — APPROVED** [review]

**Comment by thecode** [comment]
@YogevBokobza please avoid constantly force pushing the branch, this PR is already approved and waits for core PR to be ready. In any case don't use force-push unless there is no other option.

**Comment by YogevBokobza** [comment]
> @YogevBokobza please avoid constantly force pushing the branch, this PR is already approved and waits for core PR to be ready. In any case don't use force-push unless there is no other option.

Yeah, that is done by mistake.. I wanted to rebase the main core code

**Comment by thecode** [comment]
@frenck core PR for this is still in progress

**Comment by frenck** [comment]
Oh oh! I am out just now. I'll tag and fix later

**Comment by thecode** [comment]
> Oh oh! I am out just now. I'll tag and fix later

Parent PR approved, so we don't need to revert this.

**Pull request merged**
