### PR TITLE
Fix prometheus filter usage

### PR DESCRIPTION
**Pull request by pixeye33**
**Description:**
Fix docs to have accurate infos about how to configure filters

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#13738

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Is there a parent PR in the main repo?

**Comment by pixeye33** [comment]
Documentation was probably wrong since a long time and should have been fixed earlier.

EDIT : I've tracked down the PR related : https://github.com/home-assistant/home-assistant/pull/13738
docs were wrong for a whole year :)

**Comment by klaasnicolaas** [comment]
I think it is better to put this in the  `current` branch

**Comment by pixeye33** [comment]
I do not know how to do that rebase thing while using the same PR.
I've tried to do this : https://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html
without success. Any advice ?

**Comment by pixeye33** [comment]
Created a new PR for current branch
https://github.com/home-assistant/home-assistant.io/pull/9226

**Pull request closed without merging**
