### PR TITLE
Fix default tankerkoenig radius

### PR DESCRIPTION
**Pull request by guillempages**
The default value specified in the documentation did not match the implementation.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

Pushed to the "next" branch, because I could not find the integration yet in the current branch, but this PR is actually a "typo" fix.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue:

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by guillempages** [comment]
@springstan This should fix your issue in https://github.com/home-assistant/core/pull/32784 ;-)

**Comment by guillempages** [comment]
@frenck Since you also commented on the (now closed) code PR, you might want to check this.

As discussed in the original PR with @fabaff , there isn't really a sane default; in cities 5 km. would be too much, but in the country side it might be too little. So we agreed on 2 km as a default.

**Comment by klaasnicolaas** [comment]
Please rebase this PR to the `current` branch

**Comment by frenck** [comment]
@klaasnicolaas This doesn't exist in `current` as the integration is currently in beta...

Thanks @springstan, let's take this approach. 👍

**Review by frenck — APPROVED** [review]

**Pull request merged**
