### PR TITLE
updated documentation for tolo component select platform

### PR DESCRIPTION
**Pull request by MatthiasLohr**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/60326
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
`ha_platforms` should add `select`, 
`ha_category` could use an update adding lights, sensor, and select as well.

**Comment by MatthiasLohr** [comment]
> `ha_platforms` should add `select`

Oops, sorry, added!

> `ha_category` could use an update adding lights, sensor, and select as well.

I'm wondering about the ha_category in general: Should it be just the same as ha_platforms? For a sauna, just using "Health" might be a good, maybe even the best fit? @frenck, what do you think?

**Comment by frenck** [comment]
> I'm wondering about the ha_category in general: Should it be just the same as ha_platforms? 

There is some overlap, something that needs fixing... someday 😄 

> For a sauna, just using "Health" might be a good, maybe even the best fit? @frenck, what do you think?

🤷‍♂️  I have no strong opinion on that to be honest.

**Comment by MatthiasLohr** [comment]
I checked some other integrations. It looks like they are usually using a subset of their platforms + other "fitting" things. So, if you agree, I would change it to:
  * Climate
  * Health
  * Light
 
This would match, imho, the actual idea behind a sauna. I would keep sensors etc. out, since they are not part of the primary functionality of the sauna but more for diagnostic/informative aspects. If you agree with this selection, I will update the pull request ASAP.

**Comment by frenck** [comment]
LGTM 👍

**Comment by MatthiasLohr** [comment]
Done.

**Review by frenck — APPROVED** [review]
Thanks, @MatthiasLohr 👍

**Pull request merged**
