### PR TITLE
adding EasyMeter Q3D to dsmr.markdown

### PR DESCRIPTION
**Pull request by Aeroid**
adding EasyMeter Q3D

## Proposed change

Adds support for EasyMeter Q3D

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/60088
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @Aeroid, @Mrten, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#20389).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — CHANGES_REQUESTED** [review]
Thanks for the PR @Aeroid 👍 

As this PR depends on a parent PR in the Core repository, it means this PR depends on a next release of Home Assistant. Therefore this documentation PR needs to target the `next` branch.

Please change the target of this PR to the `next` branch and git rebase this PR if needed.

Thanks 👍

**Comment by Aeroid** [comment]
Hi @frenck,

> Please change the target of this PR to the `next` branch and git rebase this PR if needed.

It was on `next` but I was asked to rebase. I did so, Now it's back on `next`. 

Thanks for your help, I'm new here.

**Comment by frenck** [comment]
> but I was asked to rebase. I did so, Now it's back on next.

If you rebased, did you forget to push it? As in, I don't see the rebase being pushed?

**Comment by Aeroid** [comment]
@frenck: only via github (see above) back and forth:

... changed the base branch from next to current 11 hours ago 
... changed the base branch from current to next 2 hours ago 

as instructed by probot-home-assistant and afterwards by you.

**Comment by frenck** [comment]
You need to perform a git rebase to rebase your commits onto the `next` branch as a base branch.

**Comment by frenck** [comment]
Closing PR as the parent PR is closed.

**Pull request closed without merging**
