### PR TITLE
Alexa: proactive api config

### PR DESCRIPTION
**Pull request by abmantis**
**Description:**
Add config docs for enabling Alexa's proactive API.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#18114

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by pc-coholic** [comment]
Hi @abmantis,

thank you for integrating the proactive notifications - a feature I was hoping for :-)

I just tested it and it works pretty well - however I would like to propose to add a little bit more information to the documentation regarding enabling the proactive ChangeReports:
- Document that there are different endpoints available for different regions. Either have them directly in the documentation or link to https://developer.amazon.com/docs/smarthome/send-events-to-the-alexa-event-gateway.html#endpoints
- Explain, that the client_id and client_secret are *not* the ones used by the skill that have been set up using "Login with Amazon" (in the Alexa Developer Console: Build > Account Linking), but rather from the "Alexa Skill Messaging" (in the Alexa Developer Console: Build > Permissions > Alexa Skill Messaging).
- In order to get mentioned client ID and secret, the "Send Alexa Events"-permission must be checked.
- If  the "Send Alexa Events" was not enabled before, the user needs to unlink and relink the skill/account using the Alexa-App - else it won't work (`Token invalid and no refresh token available.`)

Best regards,
Martin

**Comment by abmantis** [comment]
@pc-coholic Thank you for the suggestions, Marting, I've updated the docs with them.

**Comment by balloob** [comment]
It seems like you have some commits in this branch that are not yours, can you please it up.

**Comment by abmantis** [comment]
It is fixed now.

**Review by balloob — APPROVED** [review]

**Pull request merged**
