### PR TITLE
Add Dynalite panel to 2023.6 release notes

### PR DESCRIPTION
**Pull request by farmio**
## Proposed change

Mention the new Dynalite UI panel in the release notes. This looks really nice and for sure was a lot of work, so I think it should be added to the `Other noteworthy changes` section instead of `Integrations now available to set up from the UI` (it also isn't really a config flow that's the big new here). 

@ziv1234 I think the integrations docs should reflect your changes - that wasn't changed yet.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/77181
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by frenck** [comment]
I'm going to friendly decline it, as this is a very very small nice (29 instances known). I do appreciate the effort, but that goes for all 1k+ contributions made this month.

We simply can't mention all.

../Frenck

**Comment by farmio** [comment]
I see. Should it still be mentioned in the "Integrations now available to set up from the UI" section? I was under the impression that all integrations deprecating Yaml config were listed there, regardless of userbase size.

**Comment by frenck** [comment]
@farmio The source PR wasn't tagged correctly, hence it was missed. I've tagged it now and it will show up on my next iteration.

**Comment by farmio** [comment]
Great! Thanks Frenck!

**Pull request closed without merging**
