### PR TITLE
Updated provider name in blockchain.markdown

### PR DESCRIPTION
**Pull request by P-Verbrugge**
@Quentame Updated provider name in blockchain.markdown

## Proposed change
Updated provider name from blockchain.info to blockchain.com

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

https://github.com/home-assistant/home-assistant/pull/31534

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
please link the PR to the parent PR. Thanks 👍

**Comment by P-Verbrugge** [comment]
> please link the PR to the parent PR. Thanks 👍

Would like to, but not sure how to do that. :-) Can you tell me where I do this?

**Comment by klaasnicolaas** [comment]
Maybe reading the text would help 😉 Just add the PR link from the code base repo here
image

**Comment by P-Verbrugge** [comment]
> Maybe reading the text would help 😉 Just add the PR link from the code base repo here
> image

Whoops. It’s all still kinda new to me. Was looking in the sidebar at the linked items. Learning the hard way. Hopefully I did it correct now.

**Comment by frenck** [comment]
Everybody gotta learn sometime, right? 👍

**Review by frenck — APPROVED** [review]
Thanks, @P-Verbrugge! 👍

**Comment by P-Verbrugge** [comment]
> Thanks, @P-Verbrugge! 👍

Your welcome and thanks for the patience! ;)

**Comment by Quentame** [comment]
Sorry @P-Verbrugge I couldn’t see it before, but we took care of you 😉
Thanks for your contribution !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by P-Verbrugge** [comment]
> Sorry @P-Verbrugge I couldn’t see it before, but we took care of you 😉
> Thanks for your contribution !
> 
> Sent with [GitHawk](http://githawk.com)

No problem! Now I know what to look for the next time. :-)

**Pull request merged**
