### PR TITLE
for compring and review on local

### PR DESCRIPTION
**Pull request by himanshu035**
- Notes added to Z-wave `soft-reset` about known issues by @sgauche 
- Fixed usage of `zwave` component, Z-Wave for references to a Z-Wave network, and OpenZWave as a project name by @sgauche

### CODE REVIEW

**Comment by fabaff** [comment]
This PR has conflicts which needs to be solved before merging.

**Comment by sgauche** [comment]
@fabaff this feels like a spam PR

**Comment by devdelay** [comment]
The correct spelling is Z-Wave. I believe that is the intent of this PR

**Comment by sgauche** [comment]
This is definitely a spam PR for the hacktoberfest shirt.  Look at the account history.

**Comment by Landrash** [comment]
Closing this since most of these changes have been made with other pull request already.

**Pull request closed without merging**
