### PR TITLE
Updated docs for Google Hangout hub component

### PR DESCRIPTION
**Pull request by teliov**
Added information on how to authenticate using the authorization code, and also how to obtain the authorization code

**Description:**
This PR updates the documentation with instructions on obtaining an authorization code from Google for authentication and how to use this code to complete the authentication flow for the hangout component.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#22158

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
There is a lot of unneeded HTML in here (e.g., the `<br>` linebreaks are not needed in Markdown).
Please remove those.

Also, there is a merge conflict which needs to be resolved.

@teliov Could you please take a look? 👍

**Comment by teliov** [comment]
@frenck, maybe I'm doing something wrong but this is how the preview looks without the <br> tags.
It was why I added the tags in the first place. My guess is that the fact the content is in the  `<p class='note'></p>` section is causing markdown to not behave properly.

Any pointers would be appreciated!

Screen Shot 2019-04-10 at 6 08 09 PM

**Comment by klaasnicolaas** [comment]
I think it is better to put this not in a note 😉

**Comment by teliov** [comment]
@klaasnicolaas , good point. Was trying to preserve the original format but yeah the instructions do not need to be in a note

**Pull request merged**
