### PR TITLE
Telegram Bot enhancements with callback queries and new notification services

### PR DESCRIPTION
**Pull request by azogue**
**Description:**
Telegram Bot enhancements with callback queries and new notification services. 

Documentation for new PR home-assistant/home-assistant#7454 (previously, PR home-assistant/home-assistant#7294), it’s the new version of #2508, with which I had conflicts between branches, so I made a new one, and I'm going to close #2508.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#7454

### CODE REVIEW

**Comment by Landrash** [comment]
Looks good. Thank you :cookie:

**Comment by Landrash** [comment]
I think you made the same mistake on this one.

**Comment by azogue** [comment]
But now the two are fixed, right?
Both say there are no conflicts ... 

I think I've learned a couple things here, but I'm still not sure

**Comment by azogue** [comment]
Definitely no, okey... the third time lucky?

**Comment by azogue** [comment]
Closing to redo properly, hope

**Pull request closed without merging**
