### PR TITLE
Followup on rework modbus

### PR DESCRIPTION
**Pull request by janiversen**
## Proposed change

Added a link to the parameter usage in each entity section, so there are no excuse :-)

Removed "int" "uint", which have been deprecated for a year or more.

Remove "int8", "uint8" which have been allowed but never worked since Modbus uses 16 bit as minimum.

Both are still in the code, but will be removed, when the documentation have a been published a while.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by janiversen** [comment]
This PR is independent of the issue I raised a couple of hours ago:

https://github.com/home-assistant/home-assistant.io/issues/28691

That issue goes into the builder core.

**Review by c0ffeeca7 — APPROVED** [review]
LGMT, @janiversen

**Comment by janiversen** [comment]
Just wondering if LGMT is a new way of saying LooksGood MeToo, since normally it's LooksGoodToMe 😀 

You never know with all these modern expressions

**Comment by c0ffeeca7** [comment]
> Just wondering if LGMT is a new way of saying LooksGood MeToo, since normally it's LooksGoodToMe 😀
> 
> You never know with all these modern expressions

haha, just a typo. :-D. Although I'm sure I'm looking great today.

**Pull request merged**
