### PR TITLE
Remove universal XZG Firmware under recommended adapters

### PR DESCRIPTION
**Pull request by Hedda**
## Proposed change

Remove listing of universal XZG Firmware under the list of recommended radio adapters since the XZG Firmware linked is not actually a Zigbee Coordinator adapter pruduct itself but instead a open-source firmware SDK for ESP32 that allows anyone to create a network-attached Zigbee Coordinator as a Serial over IP proxy, and because it is not a specific product it would not be a good idea to add it to the list there as blanket recommendation for any adapter that is built using XZG Firmware, and there is today in fact multiple companies and people making XZG Firmware based adapters that use different Zigbee Coordinator chips (including both various Texas Instruments and Silicon Labs radio MCUs as well as others).

- https://github.com/xyzroe/XZG

  - https://xzg.xyzroe.cc/

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

This will partially revert https://github.com/home-assistant/home-assistant.io/pull/33161 but not the important part about auto discovery.

Please do not get me wrong, @xyzroe is doing a great job, but the "XZG Firmware" itself does not belong under the list of recommend radio adapters for ZHA as it is not a specific adapter so it can not be generalized as a catch-all for all possible adapters based on it today and in the future.

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

## Summary by CodeRabbit

- **Documentation**
	- Enhanced documentation for the Zigbee Home Automation (ZHA) integration.
	- Improved clarity on device compatibility and configuration instructions.
	- Expanded hardware compatibility section with detailed recommendations.
	- Updated troubleshooting guidance for common issues and best practices.

### CODE REVIEW

**Comment by xyzroe** [comment]
> today in fact multiple companies and people making XZG Firmware based adapters that use different Zigbee Coordinator chips (including both various Texas Instruments and Silicon Labs radio MCUs as well as others).


@Hedda This statement is not true, because XZG only supports TI 2652*. Support for other families is not implemented.

**Comment by Hedda** [comment]
@xyzroe XZG firmware is open-source so what is stopping anyone from using it on for example anDIY or Smlight’s EFR32MG21 and/or EFR32MG24 based adapters? They might not be able to use all the extra features out of the box but can still use the serial to iP server which is the only feature that is direct relevant to the ZHA integration.

https://smlight.tech/

image

**Comment by xyzroe** [comment]
https://github.com/xyzroe/XZG/issues/66
https://github.com/xyzroe/XZG/issues/77
and many others cases in PM and community chats

**Comment by puddly** [comment]
I don't think a generic serial-to-TCP firmware itself is useful to note in ZHA documentation, as issues with specific adapters won't reflect in the firmware.

Once https://github.com/home-assistant/core/pull/126294 is finished the specific TCP-enabling firmware will be irrelevant, since they all will be supported identically.

**Review by puddly — APPROVED** [review]

**Pull request merged**
