### PR TITLE
Provide an individual color temperature range per Yeelight model

### PR DESCRIPTION
**Pull request by syssi**
**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#14083

### CODE REVIEW

**Comment by frenck** [comment]
Hi @syssi,

This PR has now a merge conflict with the `next` branch. 
Could you please take a look resolve this? 👍

**Review by frenck — CHANGES_REQUESTED** [review]
Resolve merge conflicts.

**Comment by syssi** [comment]
I will update the PR asap.

**Comment by frenck** [comment]
Closing this PR since the parent PR is closed as well. Feel free to re-open when ready.

**Review by frenck — APPROVED** [review]

**Pull request merged**
