### PR TITLE
Add new sensors for HomeWizard Energy Socket

### PR DESCRIPTION
**Pull request by DCSBL**
## Proposed change

The HomeWizard Energy Socket firmware has now support for new sensors like Voltage, Current and Frequency.

This update is available for everyone and because these sensor are already implemented we do not need to update core.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/113406
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by DCSBL** [comment]
> It seems that this PR is targeted against an inc..

I think this is incorrect 🤷

**Comment by frenck** [comment]
> > It seems that this PR is targeted against an inc..
> 
> I think this is incorrect 🤷

That is caused by an upstream PR linked. The bot therefore thinks this documentation is dependent on a future release.

**Review by frenck — APPROVED** [review]
Thanks, @DCSBL 👍 

../Frenck

**Comment by DCSBL** [comment]
> > > It seems that this PR is targeted against an inc..
> > 
> > 
> > I think this is incorrect 🤷
> 
> That is caused by an upstream PR linked. The bot therefore thinks this documentation is dependent on a future release.

Ah :)

**Pull request merged**
