### PR TITLE
Spotify: Play owned/starred playlists

### PR DESCRIPTION
**Pull request by tringler**
**Description:**

I added the documentation for PR yxz, which allows you to play owned/starred playlists on automations by name without the uid and/or by front end.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant)
https://github.com/home-assistant/home-assistant/pull/11887

## Checklist:

  - [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`. 
  - [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by frenck** [comment]
Thanks @tringler, can be merged as soon as the parent PR gets merged.

**Comment by frenck** [comment]
Closing this PR for now. The parent PR was closed by @tringler for some rework. The docs can be re-opened when done (or create a new PR).

**Comment by tringler** [comment]
I updated the parent PR to home-assistant
home-assistant/home-assistant#11887

**Comment by frenck** [comment]
OK, lets re-open the PR in that case.

**Comment by frenck** [comment]
Closing this PR, since the *new* parent PR has been closed as well.

**Pull request closed without merging**
