### PR TITLE
Update dynalite.markdown

### PR DESCRIPTION
**Pull request by ziv1234**
## Proposed change

removing logo line per ask from homeassistant/brands

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/815
- This PR fixes or closes issue: https://github.com/home-assistant/brands/issues/210

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
This should be targeting the `current` branch @ziv1234, could you please adjust that?

**Comment by ziv1234** [comment]
how do i adjust it?

**Comment by ziv1234** [comment]
i tried changing the base, but now it has all the other commits by everyone else. Should I open a new PR?

**Comment by frenck** [comment]
That is probably the quickest, I can rebase it as well...

Whatever you prefer 👍

**Comment by ziv1234** [comment]
> That is probably the quickest, I can rebase it as well...
> 
> Whatever you prefer 👍

**Comment by ziv1234** [comment]
sorry. pushed the wrong button...

**Comment by ziv1234** [comment]
just tried rebasing and failed...

will open a new PR

**Comment by ziv1234** [comment]
ok. just opened. PR #12559

**Pull request closed without merging**
