### PR TITLE
Updated troubleshooting with authentication

### PR DESCRIPTION
**Pull request by iguana007**
I was able to setup new account only after I cleared my cookies in browser, otherwise normal login prompt has been displayed.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by awarecan** [comment]
This is not right, we are not using cookie. We use Local Storage

**Comment by iguana007** [comment]
But until I deleted cookies I was not able to setup new account after deletion of files in .storage folder, whatever I did, I saw login form instead of new account setup form. When I deleted cookies, new account form showed up.

**Comment by awarecan** [comment]
You need understand different between local storage and cookie, see: https://stackoverflow.com/a/19869560

Some browser may simplified the term on UI, provided functions such as "Clear cache" or "Clear storage", under the hood it will clean both cookies and local storage. But in our document, we should use appropriate terms.

**Review by frenck — CHANGES_REQUESTED** [review]
@iguana007 Please make the changes requested by @awarecan. Thanks already! 👍

**Comment by iguana007** [comment]
@frenck I would love to, but I do not know how, eg. what exactly should be written there to make this pull request pass.

**Comment by frenck** [comment]
@awarecan Could you provide an alternative description that fits this better?

**Comment by frenck** [comment]
Since there is a lack of response on this PR, and because the documentation has been updated in the meanwhile, I'm going to close this PR.

**Pull request closed without merging**
