### PR TITLE
Update 2022-03-02-release-20223.markdown

### PR DESCRIPTION
**Pull request by ggravlingen**
## Proposed change

I propose making this addition as I received tons of help with this update. Credit given where credit is due!

The other change is just to add some clarification.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by ggravlingen** [comment]
@frenck: I just wanted to mention this for your consideration for the final release notes and wasn't sure which was the proper means of communication. Please feel free to close this PR again.

**Review by frenck — APPROVED** [review]
Thanks, @ggravlingen 👍 

❤️

**Comment by ggravlingen** [comment]
@frenck that didn't quite go as I had planned. I'm thinking the the Github alias is case sensitive?

image

**Comment by frenck** [comment]
@ggravlingen Don't worry, I'll pick that up in an iteration 😉

**Comment by ggravlingen** [comment]
Thanks!

**Pull request merged**
