### PR TITLE
Remove pre 0.80 upgrade help

### PR DESCRIPTION
**Pull request by elupus**
**Description:**
Drop some old notes about how to upgrade an old 0.80 configuration. That is way to old to have such a prominant place in documentation.

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @elupus! 👍 

Happy Hacktoberfest 🎉

**Comment by klaasnicolaas** [comment]
Why not in `current` branch?

**Comment by elupus** [comment]
No real reason. Just some sneaky suspicion it might conflict with my other google assistant changes. No rush in getting the change out either.

**Comment by frenck** [comment]
@elupus @klaasnicolaas I've cherry-picked it to `current` in b66d329266

**Pull request merged**
