### PR TITLE
Update docs for payload string->template

### PR DESCRIPTION
**Pull request by jantenhove**
**Description:**
Accompanying code PR: https://github.com/home-assistant/home-assistant/pull/25417

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

<a href="https://gitpod.io/#https://github.com/home-assistant/home-assistant.io/pull/9864"></a>

<a href="https://gitpod.io/#https://github.com/home-assistant/home-assistant.io/pull/9864"></a>

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Please rebase to the `current` branch

**Comment by jantenhove** [comment]
@klaasnicolaas 
A rebase cannot be performed from Github. Is it acceptable to create a new pull request?

**Comment by frenck** [comment]
Closing this PR for the following reason:

The parent PR targets your own fork of Home Assistant and not our codebase.
Hence this documentation does not apply to our project at this moment.

If you are meaning to contribute to the Home Assistant code base, please open a PR against our repository. Feel free to re-open this PR when ready.

**Comment by jantenhove** [comment]
> Closing this PR for the following reason:
> 
> The parent PR targets your own fork of Home Assistant and not our codebase.
> Hence this documentation does not apply to our project at this moment.
> 
> If you are meaning to contribute to the Home Assistant code base, please open a PR against our repository. Feel free to re-open this PR when ready.

That was stupd :S
This is the correct PR: https://github.com/home-assistant/home-assistant/pull/25417 (updated the first post)

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by frenck** [comment]
Closing PR, since the parent PR has been closed.

**Pull request closed without merging**
