### PR TITLE
Add battery sensors to august integration

### PR DESCRIPTION
**Pull request by bdraco**
## Proposed change

Add battery sensors to august

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/home-assistant.io/pull/12172
- This PR fixes or closes issue:

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by frenck** [comment]
Closing PR since the parent PR has been closed.

**Comment by bdraco** [comment]
> Closing PR since the parent PR has been closed.

@frenck  The parent PR merged in another PR.  This one should be good to merge now

**Comment by frenck** [comment]
Please link up the PR's correctly.

Thanks! 👍

**Comment by bdraco** [comment]
> Please link up the PR's correctly.
> 
> Thanks! 👍

fixed

**Review by frenck — APPROVED** [review]
Thanks, @bdraco! 👍

**Pull request merged**
