### PR TITLE
Add Heatzy integration

### PR DESCRIPTION
**Pull request by cyr-ius**
## Proposed change

Heatzy is a connected programmer that allows converting convectors with a pilot wire into a connected system

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:  [50663](https://github.com/home-assistant/core/pull/50663)
- Link to parent pull request in the Brands repository:  [2581] (https://github.com/home-assistant/brands/pull/2581)
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
This PR is changing something in QNAP but you introduce a new integration? 🤷🏻‍♂️

**Review by frenck — CHANGES_REQUESTED** [review]
Something got mixed up here, please take a look 👍

**Comment by cyr-ius** [comment]
> Something got mixed up here, please take a look +1

I correctly correct

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
