### PR TITLE
Add tag information for "antifeatures"

### PR DESCRIPTION
**Pull request by arthurlutz**
so far : self-hosting, requires-registration, proprietary,
opensource, openhardware

Related to #6402

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
@arthurlutz IMHO you are to soon, the discussion in the related issue was not resolved. Nevertheless, you are opening a PR.

We are currently reviewing the way the documentation is structured. One of the recent changes made it possible to reduce the number of pages and allows a page to be in multiple categories.

While I do appreciate the effort, I do not agree on the chosen route. Just adding a `tags` parameter and simply displaying them? The name tags are misused in this case, it is not a tag, but a collection of properties. 

Secondly, as @fabaff pointed out in #6402:

> Also, for contributors it must be super easy to determine if the integrations is a match for the particular flag. This means that "Non free Dependencies" and "Tracking" are not really practicable because it would require that a license review is performed and the network traffic analysed in detail.

Other thoughtfull mentions: self-hosted is not always the only option. Some offert both self-hosted and a hosted version. So how would that reflect in this change?

I think we should close this PR, until the discussion is resolved, before doing this.

**Review by frenck — APPROVED** [review]
Blocking PR until the discussion is resolved.

**Review by frenck — CHANGES_REQUESTED** [review]
Blocking PR until the discussion is resolved.

**Comment by arthurlutz** [comment]
@frenck thanks for taking the time to review my code and answer in detail. 

I am trying to figure out how to start on this subject, and I think that discussing over some code (and the awesome netlify previews) is easier than discussing theoretically in the issue so I am glad to get your feed back. 

No, displaying is not enough, I am trying out changes to components/index.html to have more facets and displaying information. 

As for the name of "property", lets discuss it, "Naming things is difficult", that's ok. 

For the self-hosted and hosted also available. I would recommend having a  "self-hosting" (first) and "hosted-sass-also-available" to encourage user to choose self-hosting which is better in terms of privacy.

**Comment by balloob** [comment]
I don't want to merge this.

With Home Assistant we're aiming to reach a wide audience, wider than just "techies". The non-techies will not understand this and for them it will just be extra words on the page that they don't understand, scaring them away.

I also agree with others that the maintenance burden is too big. You're new to this community and want us to make changes that have to be supported forever, even when you are long gone.

So no, we're not doing this.

**Comment by arthurlutz** [comment]
I'm sorry to see this closed this way and the way it is being closed. 

> You're new to the community

How would you define "being established in the community" ? I've been a user of home-assistant for a while now, have presented home-assistant in python conferences in France (https://youtu.be/Eu6umBJ51I4?t=180) ... I am starting to regret promoting the plateform if we can't find a user friendly way of encouraging **privacy first** services with home-assistant. 

> even when you are gone.

I'm familiar with open source projects and accept that you can refuse something you're not at ease maintaining, but please don't presume of my implication in the project. 

I'm trying to stay open to this discussion because I firmly believe in open-source, privacy oriented, user-oriented informed choice for home automation, but you're making it a bit hard.

**Pull request closed without merging**
