### PR TITLE
Update sun elevation example to Home Assistant Documentation standards

### PR DESCRIPTION
**Pull request by tomlut**
## Proposed change

Update sun elevation example to documentation standard (single quotes inside double quotes).

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This isn't a standard?

Furthermore, if changing this, please move the `{% raw %}` tags out of the YAML example, and instead wrap the whole code fenced block as a whole.

**Comment by tomlut** [comment]
It’s what this says:

https://developers.home-assistant.io/docs/documenting/standards#templates

**Comment by frenck** [comment]
Hmm conflicting stuff in that document, will adjust that.

the first line is correct though: `All examples containing Jinja2 templates should be wrapped outside of the code markdown with the {% raw %} tag.`

````yaml
{% raw %}

```yaml
bla
```

{% endraw %}

````

**Review by frenck — APPROVED** [review]
Thanks, @tomlut 👍

**Pull request merged**
