### PR TITLE
Update desc that Dyson integration is broken since 2021.2

### PR DESCRIPTION
**Pull request by deftdawg**
see https://github.com/home-assistant/core/issues/46400

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by deftdawg** [comment]
Alternatively, the whole Dyson integration could be archived until such time as it can be fixed.

**Comment by nickw444** [comment]
> Alternatively, the whole Dyson integration could be archived until such time as it can be fixed.

I think this would be a better approach. Yes it won't be so simple to just "unrevert" it should it need to come back, given the pace at which development moves, but it would stop it from becoming a stale, broken integration (like it already is). 

If/when the Dyson integration is re-added, I imagine a lot of things would need to be changed anyway (e.g. adding a config flow)

**Comment by epenet** [comment]
I have opened #20231

**Review by frenck — CHANGES_REQUESTED** [review]
We don't add that to the description. Please raise an alert instead:

<https://alerts.home-assistant.io>

Repo: <https://github.com/home-assistant/alerts.home-assistant.io/tree/master/alerts>

**Pull request closed without merging**
