### PR TITLE
Mqtt fan command templates

### PR DESCRIPTION
**Pull request by jbouwh**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/48413
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This PR adds a new feature to the codebase, thus depends on a next release of Home Assistant Core.

Therefore, this PR should go into the `next` branch. Please change the target branch of this PR to `next` and git rebase this PR if needed.

Thanks 👍

**Comment by jbouwh** [comment]
> This PR adds a new feature to the codebase, thus depends on a next release of Home Assistant Core.
> 
> Therefore, this PR should go into the `next` branch. Please change the target branch of this PR to `next` and git rebase this PR if needed.
> 
> Thanks 👍

I am not sure. The PR for code change is targeted to current, not to next, I have changed this later in this documention PR.

**Comment by frenck** [comment]
I am sure, this targets the wrong branch. Please adjust as instructed in my last response.

**Comment by jbouwh** [comment]
I think I need some help, I messed up this PR in order to target it it right.

**Comment by frenck** [comment]
It seems like you have been merging branches, instead of rebasing. At this point, either strip of the merge and do a rebase after that or hard reset the branch and cherry-pick your changes.

Alternatively, creating a new PR based from the `next` branch is an option as well.

**Comment by jbouwh** [comment]
I will start a new PR for this.

**Pull request closed without merging**
