### PR TITLE
Changed broken link to Mi Flora product page

### PR DESCRIPTION
**Pull request by wmn79**
Changed broken link to a product description on gadget-freakz.com

Related to #10491

Pull request in home-assistant (if applicable): home-assistant/home-assistant#

Description:

Pull request in home-assistant (if applicable): home-assistant/home-assistant#

**Description:**

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by walebant** [comment]
Hi, I'd like to work on this.

**Comment by klaasnicolaas** [comment]
@wale-bant Look at this issue: #10491

**Comment by klaasnicolaas** [comment]
@wmn79 Can you fix the merge conflict?

**Comment by wmn79** [comment]
@klaasnicolaas: not sure if I do it correctly like this, but I think the conflict is due to the components are renamed from components to integrations. I have done a commit to the _integrations/miflora.markdown as well and referred to this pull request. The _components one can be discarded I think.

**Comment by frenck** [comment]
Rebased PR.

**Review by frenck — APPROVED** [review]
Thanks, @wmn79! 👍 

Happy Hacktoberfest 🎉

**Pull request merged**
