### PR TITLE
Added target_wlans attribute to device tracker unifi

### PR DESCRIPTION
**Pull request by GenericStudent**
Added to the current unifi device tracker documentation on new
functionality developed to allow a user to filter unifi clients
based on the wireless network they are connected to.

The user specifies which WLANs they want targetted and only
devices on those networks are added.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

### CODE REVIEW

**Comment by fabaff** [comment]
To which PR does this change belong?

**Comment by GenericStudent** [comment]
Apologies, but I haven't  submitted the PR yet as I'm having issues with getting all the tests passing (relevant tests pass, but other sensor tests fail)

**Comment by andrey-git** [comment]
Is this PR still relevant?

**Comment by GenericStudent** [comment]
Apologies, you can remove this PR

**Comment by andrey-git** [comment]
Thanks

**Pull request closed without merging**
