### PR TITLE
Add documentation for current_temperature_template in climate.mqtt

### LINKED ISSUE #6467: climate.mqtt missing documentation for 'current_temperature_template'
The [documentation](https://www.home-assistant.io/components/climate.mqtt/) doesn't document that 'current_temperature_template' is available to extract/parse the temperature (for example from a json structure) but [it is](https://github.com/home-assistant/home-assistant/blob/07972c84a15740a8de47883749f7eb9301bcdc89/homeassistant/components/climate/mqtt.py#L61).

(I added it to my configuration.yaml without even a glance at the documentation and it worked. I only realised after that it was absent!)

### PR DESCRIPTION
**Pull request by mvn23**
**Description:**
An undocumented feature (current_temperature_template) was accidentally discovered in the mqtt climate platform.
This PR adds documentation for this feature.
Fixes #6467 

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** N/A

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by fabaff** [comment]
Was introduced with https://github.com/home-assistant/home-assistant/pull/11623.

**Comment by mvn23** [comment]
@fabaff's comment on home-assistant/home-assistant#17101 makes me want to add some info about the `initial` value and how it's used slightly different than with some of the other components. Added [WIP] for now.

**Comment by frenck** [comment]
Seems like `power_state_template` is missing as well.

@mvn23 Maybe consider adding that to this PR as well?

**Comment by mvn23** [comment]
I have checked all config options in the source and found that there are more missing entries.
Problem is, both `power_state_topic` and `power_state_template`, while present in the `PLATFORM_SCHEMA`, seem unused anywhere else in the code.
I am preparing a commit to add the other missing features, but I will omit the two mentioned above.

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Thanks, @mvn23! 👍 

Happy Hacktoberfest 🎉 

../Frenck

**Pull request merged**
