### PR TITLE
Clarification of time formats

### PR DESCRIPTION
**Pull request by akasma74**
I couldn't find anything in the current docs on time formats and thought it would be useful to give more details (rather than time | integer description) about ones available.

**Description:**

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Please rebase to the `current` branch and remove the `notes` / `example` tags

**Comment by akasma74** [comment]
Rebased and comverted extra tags into paragraphs' headers, please check it out.

**Comment by frenck** [comment]
Hi there @akasma74,

I don't see a rebase, the only thing I see is that you've changed the target branch. Could you please rebase the PR's onto the `current` branch as well?

Feel free to ask if you need any help with that.

**Comment by akasma74** [comment]
Hi @frenck , tbh I don't know how to rebase PRs so any help is highly appreciated.

Update: I ended up creating a new PR to the current branch to speed up things.
Still happy to learn how to rebase a PR onto the current branch.

**Comment by frenck** [comment]
Thanks for creating a new PR, however, you didn't have to. I would have rebased it for you.... 
But yeah, this works I guess. 🤷‍♂

**Pull request closed without merging**
