### PR TITLE
Provide an example of how to make a 'when dark' condition by ORing su…

### PR DESCRIPTION
**Pull request by Human**
…nrise and sunset conditions.

See issue#12308 at https://github.com/home-assistant/home-assistant/issues/12308

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by Human** [comment]
Resolves issue #12308

**Comment by Human** [comment]
@mf-social Would you like to handle the review?

**Comment by ryanwinter** [comment]
The truth table is still misleading, or just downright wrong.

**Comment by arsaboo** [comment]
@ryanwinter Create a separate PR for the truth table please..thanks!

**Comment by ryanwinter** [comment]
I'm wondering if the current code makes sense. It uses midnight as an additional state change point, but this isn't obvious, or something anyone would need.

I actually think the current table reflects what it should do. Let me think of a code change to propose instead.

**Comment by mf-social** [comment]
^ I think that's intentional, otherwise it will always be true.

If you make it go past midnight, at any given daylight time it is after sunrise today and before sunrise tomorrow, at any given darkness time it is after sunset today and before sunset tomorrow.

There has to be a cutoff and midnight makes perfect sense IMO.

**Comment by ryanwinter** [comment]
I think that the cutoff should be the next sun event which will trigger the end state change, rather than an arbitrary time which was likely picked as midnight to simplify logic. I mean why not 3am, midday, 8:57pm?

**Comment by mf-social** [comment]
Because it is after sunrise / sunset on the *day* in question, a day runs from midnight to midnight, not 3 - 3 or any other time. 🤔

**Comment by ryanwinter** [comment]
Yes, but a night runs from sunset to sunrise, and we are talking about sun related conditions.

**Comment by mf-social** [comment]
Yes, and sun related conditions do not exclusively cater for when it is dark. They currently cater for whether the sun is up or down on that particular **day**. Day as in Monday, Wednesday etc, not 'the time it was (or will be)  light' 

Like I say, it works well for me in that format, but if you think it's better another way then that's cool. I was just thinking it will be a massive breaking change for people's long-standing automations so you might want to garner some more opinions before spending time rewriting the logic.

**Comment by ryanwinter** [comment]
Well I agree this could be a breaking change, people (including myself) have either written logic to work around this weird effect, or moved to sun elevation instead to bypass the confusing logic which contradicts the documentation.

Let me look at a coding solution first and see if this makes sense.

**Pull request merged**
