### PR TITLE
Update apache_configuration.markdown

### PR DESCRIPTION
**Pull request by elbowz**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

### CODE REVIEW

**Comment by fabaff** [comment]
Can you give/add some context about/to your change? At least on a default installation of Debian with Apache it seems that `a2enmod` is not available.

**Comment by elbowz** [comment]
about the Apache module: https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html

The command is executed on Ubuntu 16.04...I thought that could run also on debian

**Comment by asbach** [comment]
Debian jessie provides the file in the apache2 package. (https://packages.debian.org/jessie/amd64/apache2/filelist)

**Comment by fabaff** [comment]
@elbowz, I was more thinking about why a user need to enable this module.

> Debian jessie provides the file in the apache2 package. 

Wired. Have to check it again.

**Comment by mmaret-geny** [comment]
By the module description (https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html), it looks like the ProxyPass directive used in the Apache configuration need this module when used with websocket.
But, on my configuration, I do not need this. May be, this is required on ubuntu because of some compilation configuration...
IMO, describing the error or the context that may lead you to enable this module in the documentation could be interesting

**Comment by elbowz** [comment]
> By the module description (https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html), it looks like the ProxyPass directive used in the Apache configuration need this module when used with websocket.

Exact!

> But, on my configuration, I do not need this. May be, this is required on ubuntu because of some compilation configuration...
> IMO, describing the error or the context that may lead you to enable this module in the documentation could be interesting

What I can say is that after the latest update, apache proxy stop working for web socket and I need refresh page (F5) for get update

**Pull request merged**
