### PR TITLE
Update emulated_hue with info about initial device

### PR DESCRIPTION
**Pull request by Spartan-II-117**
**Description:**
Add a note about the need to keep the device that connected to emulated_hue online

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** 

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by Spartan-II-117** [comment]
I have tested it with my own google home devices, if i unplug the one i used for initial setup, emulated hue stops functioning properly on all the others, I do not have an alexa device to test possible fixes as google home no longer allows adding emulated_hue devices.
the forum mentions that the OP had to re-connect his original alexa to get functionality restored, which was how i figured out to plug mine back in in the first place.
I just wanted to pus a note inthis page as it was the first place i went looking to troubleshoot.

**Comment by Spartan-II-117** [comment]
https://community.home-assistant.io/t/emulated-hue-depending-on-a-specific-echo-being-online-was-eh-not-working-in-0-61/41839/5?

"I had replaced my main Echo device (a Dot) with an Echo Spot and after that none of my various Echos could reach HASS. Once powering up the Dot again, it works (on all Echos), but taking it down, none of the Echos can reach HASS."

**Comment by c727** [comment]
Thanks for your feedback, I'll change your note a bit for a better understanding :+1:

**Comment by Spartan-II-117** [comment]
Looks good to me, i just wanted the information available, Thanks!

**Pull request merged**
