### PR TITLE
Remove broken link

### PR DESCRIPTION
**Pull request by wrt54g**
## Proposed change

Remove a broken link from the Help page.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
A merge conflict occurred, could you please take a look?

**Comment by wrt54g** [comment]
> A merge conflict occurred, could you please take a look?

I'll open another pull request for this. I've never seen the "Can't automatically merge" error.

**Comment by frenck** [comment]
> I'll open another pull request for this. I've never seen the "Can't automatically merge" error.

You could just fix the merge conflict?

For the future, you are allowed to make multiple changes the same thing in a single PR (if you did that, this merge conflict would not have been happening in the first place).

**Comment by wrt54g** [comment]
#22604 is the new one

**Comment by wrt54g** [comment]
> > I'll open another pull request for this. I've never seen the "Can't automatically merge" error.
> 
> You could just fix the merge conflict?
> 
> For the future, you are allowed to make multiple changes the same thing in a single PR (if you did that, this merge conflict would not have been happening in the first place).

The new one is able to merge automatically. Maybe I used a branch name that was already used for one of my pull requests. fix-broken-link-4 (the new one) does not seem to have any issues.

**Comment by frenck** [comment]
> Maybe I used a branch name that was already used for one of my pull requests.

No, there was a simple merge conflict in the diff. You could have just resolved the straight from this PR.

**Comment by wrt54g** [comment]
> > Maybe I used a branch name that was already used for one of my pull requests.
> 
> No, there was a simple merge conflict in the diff. You could have just resolved the straight from this PR.

Now I see the issue. I made a new fork for the new pull request. The old fork does not exist anymore.

**Pull request closed without merging**
