### PR TITLE
Update basic setup instructions for onboarding

### PR DESCRIPTION
**Pull request by SeanPM5**
**Description:**
Updated instructions to reflect onboarding improvements in Home Assistant 0.94 (see video in blog post: https://www.home-assistant.io/blog/2019/06/05/release-94/) and mention the fact that this can be updated directly in the user interface now.

## Checklist:
- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

<a href="https://gitpod.io/#https://github.com/home-assistant/home-assistant.io/pull/10000"></a>

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks! 👍

**Comment by klaasnicolaas** [comment]
10.000 PR a little milestone 🎉 🎂

**Comment by SeanPM5** [comment]
Very cool, honored to be number 10,000! 😃🎉

**Comment by frenck** [comment]
Don't wanna spoil the party... but that is actually incorrect 😉 
GitHub issues & PR's count towards the same number 😉

**Comment by SeanPM5** [comment]
Aha, so really a few hundred away from the true milestone. Slightly less cool, but still kind of cool in my book hehe 😉

**Comment by klaasnicolaas** [comment]
Still number 10000 🤣  it just whats inside/ outside the scope. Could also only count the merged PR's 😉

**Pull request merged**
