### PR TITLE
Rename template.markdown to sensor.template.markdown

### PR DESCRIPTION
**Pull request by akasma74**
## Proposed change

as title of the page comes from filename, template sensor should be in sensor.template.markdown

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue:

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
It should not. We have been moving away from that for over a year now. Please do not undo all the work we have done. Thanks. 👍

**Comment by akasma74** [comment]
Coult you refer me to te reason why it should not?
The thing is it looks different: compare it to [binary template binary sensor](https://www.home-assistant.io/integrations/template), why cannot they be similar?

**Comment by frenck** [comment]
We are removing all platform-specific documentation, converting everything to integrations. Yes, there is some things that need fixing, but rolling back isn't the solution.

**Comment by akasma74** [comment]
By no mean I wanted to roll anything back, just spotted this inconsistency and thought that'd fix it.
Hope you won't forget about the issue as currently it doesn't look nice and is a bit inconvenient in use.
Thanks for your time. Cheers!

**Comment by akasma74** [comment]
JFYI, the same problem is with command line binary sensor - it does not come up as [binary sensor](https://www.home-assistant.io/integrations/#binary-sensor)

**Comment by frenck** [comment]
Yes, we know.

**Pull request closed without merging**
