### PR TITLE
Merge documentation update for PR 4981

### PR DESCRIPTION
**Pull request by Duoxilian**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

### CODE REVIEW

**Comment by Duoxilian** [comment]
I am not sure whether I did this right, because I don't see my changes in the list above. For what it is worth, I updated components.climate on fork duoxilian,  12389ec.

**Comment by MartinHjelmare** [comment]
Yeah, something is not right with this branch. I can try to pull your commit and push it upstream. I'll see what I can do. Your changes look good.

**Comment by MartinHjelmare** [comment]
@Duoxilian there's a tutorial how to do the PR here:
https://github.com/home-assistant/home-assistant.github.io/issues/1052

Only difference is that you should change branch to `next` first before editing the page. The PR should also target `next`.

It looks as your existing commit is orphaned on github, cause I can't find any way of fetching it to my local repo.

**Comment by Duoxilian** [comment]
Thanks. The trick was going to next first.

**Pull request closed without merging**
