### PR TITLE
Add discord doc for user support

### PR DESCRIPTION
**Pull request by vermium**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: home-assistant/core#33692
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

<a href="https://gitpod.io/#https://github.com/home-assistant/home-assistant.io/pull/12769"></a>

### CODE REVIEW

**Comment by vermium** [comment]
Documentation for https://github.com/home-assistant/core/pull/33692

**Review by frenck — CHANGES_REQUESTED** [review]
Your fork is outdated and thus now has a merge conflict.

Please rebase your branch onto the latest `next` branch. Thanks 👍

**Comment by vermium** [comment]
New https://github.com/home-assistant/home-assistant.io/pull/12770

**Comment by vermium** [comment]
Could you delete this PR?

**Pull request closed without merging**
