### PR TITLE
Add bronze to IQS section and sync naming with ha frontend

### PR DESCRIPTION
**Pull request by wendevlin**
## Proposed change
- Integration: integration quality scale section:
  - add bronze option
  - Sync naming with frontend

## Type of change
- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: home-assistant/frontend#23036

## Checklist
- [x] This PR uses the correct branch, based on one of the following:
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

## Summary by CodeRabbit

- **New Features**
	- Enhanced the component navigation in the Home Assistant documentation by linking quality scale levels to their respective sections for improved clarity.
- **Bug Fixes**
	- Retained the logic for displaying active installations percentage, ensuring consistent functionality.
- **Documentation**
	- Updated the HTML template for better presentation of quality scale information.

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Nice! But we have a total of 7 tiers now (well 8 if one would count "No score" as a tier as well).

Let's make sure we list them all of we are touching this now anyway 👍 

../Frenck

**Comment by wendevlin** [comment]
> Nice! But we have a total of 7 tiers now (well 8 if one would count "No score" as a tier as well).
> Let's make sure we list them all of we are touching this now anyway 👍 

Ok so I have to add legacy. 
Because custom won't be listed in the official docs right?

**Comment by frenck** [comment]
> Because custom won't be listed in the official docs right?

Custom will be listed, and also communicated to the frontend.

From the backend that was an uncompleted task, which I've just completed with this PR: https://github.com/home-assistant/core/pull/131795

**Comment by wendevlin** [comment]
> > Because custom won't be listed in the official docs right?
> 
> Custom will be listed, and also communicated to the frontend.
> 
> From the backend that was an uncompleted task, which I've just completed with this PR: [home-assistant/core#131795](https://github.com/home-assistant/core/pull/131795)

Yes but this is not the frontend PR, this is the docs PR and custom integration won't appear in our official docs.

**Comment by frenck** [comment]
> Yes but this is not the frontend PR, this is the docs PR and custom integration won't appear in our official docs.

Not following. This is the navigation bar you are adjusting, it should link to all our available scales as listed on our page.

**Review by frenck — APPROVED** [review]
Thanks, @wendevlin 👍 

../Frenck

**Pull request merged**
