### PR TITLE
Beta release notes for 0.115

### PR DESCRIPTION
**Pull request by frenck**
## Proposed change

⚠️ This is in progress! Nothing is final in here, nor is it checked for anything. That is why this PR is marked as "draft".

Beta release notes for 0.115

### CODE REVIEW

**Comment by spacegaier** [comment]
@frenck Just an idea: It's not technically a breaking change, but perhaps something that many users might come across and therefore perhaps could be mentioned in the change log: https://github.com/home-assistant/frontend/issues/6652#issuecomment-687749176

**Comment by frenck** [comment]
Yes and tons of other things. This PR is not ready for review yet. Nevertheless, thanks for the suggestion.

**Comment by Stirfry70** [comment]
#14415

**Comment by Stirfry70** [comment]
does that work?

**Comment by frenck** [comment]
This is going to be merged and continue on developing/extending from the rc branch.

**Pull request merged**
