### PR TITLE
17TRACK docs improve

### PR DESCRIPTION
**Pull request by OldShaterhan**
Improve layout side of 17TRACK documentation - making a bit more clear.

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by frenck** [comment]
Could you elaborate on how this is an improvement? I'm not totally getting what this change improves...

**Comment by OldShaterhan** [comment]
Sure!

So basically, my goal was to improve case, when `friendly_name` is null (None), what happens by default when package is being added to 17 track - with no memo. I was wondering yesterday what strange thing appeared on the packages list (it was: "None": "Some information"). Adding the `package_number` to the listing guarantees that there will be some more useful information, when memo of the packages is not set.

Second change that is attached here (and potentially it is my bad as result of misundestanding configuration) - I added it listing as an unordered list - similarly to previous I was trying to understand the result of one message that came from the 17track, but were set as "None".

Compare of results (after & before):
image

I don't have now package with no memo set, but if memo is unset you get sth like:
```None: The shipment has been processed in the parcel center```, what doesn't make things clear, as for me - first time user.

**Review by frenck — APPROVED** [review]
Thanks, @OldShaterhan 👍

**Comment by OldShaterhan** [comment]
Hi @frenck , sorry for disrupting you and making problems, but however demo code is working properly on Lovelace cards, but I see that docs page took some of the changes as a comment - it is marked as green and I'm not sure what caused it:

image

https://www.home-assistant.io/integrations/seventeentrack/#lovelace-summary-card

Sorry for any inconvienience.

**Pull request merged**
