### PR TITLE
Xiaomi MiIO Sensor: Xiaomi Air Quality Monitor (PM2.5) integration

### PR DESCRIPTION
**Pull request by syssi**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#13264

### CODE REVIEW

**Review by frenck — DISMISSED** [review]

**Comment by frenck** [comment]
Looks good @syssi, can be merged as soon as the parent PR gets merged 🥇

**Comment by frenck** [comment]
Rebased PR onto the `next` branch in order to fix the build issues.

**Comment by syssi** [comment]
@frenck Are you sure a rebase is needed?

**Comment by frenck** [comment]
@syssi This PR branch needed to catch up with the base branch (`next` in this case). So you have 2 options; Merge next into this PR or Rebase onto next. The latter is cleaner IMHO.

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
✅ Approved.

Can be merged as soon as the parent PR gets merged.

**Comment by rytilahti** [comment]
Parent merged now, merging this too, thanks for the review & docs!

**Pull request merged**
