### PR TITLE
Update lutron.markdown to add fan information

### PR DESCRIPTION
**Pull request by wilburCforce**
## Proposed change

This is related to PR 97076 to include the functionality needed for the Lutron Fan controls

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/97076
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @wilburCforce 👋 

A couple of things are not correct with this PR.

- This PR is not linked from here to the parent PR (and the reverse).
- This PR needs to target the `next` branch, as it depends on a new feature that will be release in a future (next) release of Home Assistant. Please change the target branch to `next` and git rebase your changes onto the upstream next branch.

Thanks!

../Frenck

**Comment by cdheiser** [comment]
Something is off in this PR as it has 153 commits in it.

**Comment by wilburCforce** [comment]
> Something is off in this PR as it has 153 commits in it.

@cdheiser 
I started it off the wrong branch and then was told by a reviewer to move it to the .next branch and that's when all that came in.
Should I hose it and start fresh?  I'm a NooB and not sure what's right or wrong there.

**Comment by wilburCforce** [comment]
ignore this request.  it has been replaced with: https://github.com/home-assistant/home-assistant.io/pull/28297

**Pull request closed without merging**
