### PR TITLE
Add support for multiple Doorbird stations

### PR DESCRIPTION
**Pull request by oblogic7**
**Description:**
Edits documentation for supporting multiple devices.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#13994

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

### CODE REVIEW

**Comment by alandtse** [comment]
@oblogic7 Good work on this. I just closed my own PR because I forgot to check to see if someone else did it already.  Please remember to conform the docs to your code so we can see this in the next release. ;)

**Comment by oblogic7** [comment]
Wanted to make sure I had all of the requested changes done before updating
the docs. Gonna work on that today.

**Comment by oblogic7** [comment]
Documentation has been updated to match changes on https://github.com/home-assistant/home-assistant/pull/13994

**Comment by syssi** [comment]
Could you recycle and update the config section of #5414. It's the preferred format for config schemas.

**Review by syssi — DISMISSED** [review]

**Comment by syssi** [comment]
Please update the section, too. It doesn't include the multiple device support right now.

**Comment by syssi** [comment]
Please rebase the docs and fix the merge conflict. Does all changes still apply?

**Comment by oblogic7** [comment]
Yes, it is up to date with all changes on https://github.com/home-assistant/home-assistant/pull/13994

**Review by syssi — APPROVED** [review]

**Pull request merged**
