### PR TITLE
hdmi_cec enhancement

### PR DESCRIPTION
**Pull request by konikvranik**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant):** home-assistant/home-assistant#4781

### CODE REVIEW

**Comment by Landrash** [comment]
Review of this one will wait until component is done.
Just a quick overview of this and it looks way more complicated than before to configure. If we update the config of the component we should always try to keep it compatible with the previous version to prevent breakage. If there's breakage don't forget to document it and how to update the previous configurations to match the new requirement.

**Comment by konikvranik** [comment]
@Landrash 
Do you find it more complicated? I changed format of config because previous approach seems complicated to me.
But maybe there is posibility to retain both approaches. If number is on left side and string on right, we use original way and if string on left and pattern %x.%x.%x.%x we use new format.

**Comment by Landrash** [comment]
@konikvranik Your right, either will work. If there's no reason to change I would recommend not doing it as it will break some deployments of Home Assistant.

**Comment by konikvranik** [comment]
@Landrash 
OK, you're right, backwards compatibility is important. Reworked to offer both approaches.

**Comment by robbiet480** [comment]
Thanks! 🐬 🍪 💯

**Pull request merged**
