### PR TITLE
Updated Fire TV Logo

### PR DESCRIPTION
**Pull request by pattyland**
New official Logo: https://press.aboutamazon.com/images-videos

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
I'm not sure how this could be a merge conflict?
@pattyland?

**Comment by pattyland** [comment]
Me neither... I'm not a git expert, could this happen because git don't know how to merge binary files?
I don't see any other commit to this image that could conflict with mine

**Comment by frenck** [comment]
Hmm... I've assigned myself to look into this. Interesting!

**Comment by frenck** [comment]
image

I've been able to resolve locally, but there is no use in updating as it seems...

**Comment by frenck** [comment]
Closing this PR because above reasoning.

**Comment by pattyland** [comment]
Uhm so there is no update for logo?

https://github.com/home-assistant/home-assistant.io/pull/7057/commits/6105f006a1fe04ac985d725078d3fe27ec5f4448

**Comment by frenck** [comment]
That is not a valid way to look at the repository @pattyland...

If you look into the `next` branch you'll see this:

https://github.com/home-assistant/home-assistant.io/blob/next/source/images/supported_brands/firetv.png

**Comment by pattyland** [comment]
I linked my commit to change the logo to the new version.
Your link still shows the old logo.

I'm confused what I did wrong :(

**Comment by frenck** [comment]
image

**Comment by frenck** [comment]
Look you have a caching issue somewhere...

**Comment by pattyland** [comment]
bildschirmfoto 2018-11-15 um 20 20 38

The new logo does not have the word "amazon" in it. On the screenshot you see the logo I added in this pull request.

**Pull request closed without merging**
