### PR TITLE
Added documentation for proposed "seconds" functionality

### PR DESCRIPTION
**Pull request by DTekNOdev**
**Description:**

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#28320

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
Hi there @jeremycook61!

Could you point me to the matching PR in the Home Assistant main repository?

Thanks! 👍

**Comment by DTekNOdev** [comment]
Hi! I'm not sure if I pressed all the buttons correctly. Is this what you
are asking for?

https://github.com/jeremycook61/home-assistant/pull/1

Jeremy

**Comment by frenck** [comment]
That is a PR against your own codebase (your fork), you'll have to open a PR on the main code base right here: <https://github.com/home-assistant/home-assistant>

**Comment by DTekNOdev** [comment]
https://github.com/home-assistant/home-assistant/pull/28320

**Review by frenck — APPROVED** [review]
Thanks, @jeremycook61!

Please change the target branch for this PR to the `next` branch, since this documentation depends on a PR in our main codebase (and thus depends on a future next release of Home Assistant). Rebase the PR onto the `next` branch if needed.

**Review by frenck — CHANGES_REQUESTED** [review]
Sorry, the wrong button, I meant to do the "Request changes". Retrying 😉

**Comment by DTekNOdev** [comment]
> Sorry, the wrong button, I meant to do the "Request changes". Retrying 😉

I'm not sure what you are asking me to do or how to do it (set the target branch?)

**Comment by jeremycook61** [comment]
> Sorry, the wrong button, I meant to do the "Request changes". Retrying 😉

**Comment by frenck** [comment]
Yes, you've set the target branch, but you need to rebase this PR in Git as well (base it off the `next` branch, since you originally branched of the `current` branch).

**Comment by DTekNOdev** [comment]
> Yes, you've set the target branch, but you need to rebase this PR in Git as well (base it off the `next` branch, since you originally branched of the `current` branch).

I'm struggling to figure this out. Is there a menu for this in github? Can anyone help with more detailed instructions? Thx

**Comment by frenck** [comment]
@jeremycook61 You'll have to do this on a local checkout, you can't do that from the GitHub web interface.

<https://developers.home-assistant.io/docs/en/development_catching_up.html>

**Comment by DTekNOdev** [comment]
Ok, I tried this again and did something, but I have to admit to feeling a
bit lost, not having worked on the actual github before, I'm not totally
sure whether I have submitted my request to the right branch etc.

Hopefully the changes that I have submitted can be used, as it's useful.

**Pull request closed without merging**
