### PR TITLE
Fix some wrong redirects

### PR DESCRIPTION
**Pull request by AmirHosseinKarimi**
Looks like the developer documentations pages changed recently, I have fixed some new URLs.

Also there is other wrong links which I have not found correct links, Like these:
/developers/server_sent_events https://developers.home-assistant.io/docs/en/external_api_server_sent_events.html
/developers/releasing https://developers.home-assistant.io/docs/en/releasing.html
/developers/python_api https://developers.home-assistant.io/docs/en/external_api_rest_python.html

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This applies to our current documentation.
Please change the target to the `current` branch and rebase your PR if needed.

Thanks 👍

**Comment by AmirHosseinKarimi** [comment]
Now its okay?
I have commit this change and PR from Github, Not local clone, So do not know how to rebase in Github website.
If not I will make a new PR to `current` branch.

**Comment by frenck** [comment]
You need to git rebase the PR (as it now contains 105 commits).

**Comment by AmirHosseinKarimi** [comment]
Okay, I do not want to clone in local system, So I request a new pull.

**Comment by frenck** [comment]
superseded by #13459

**Pull request closed without merging**
