### PR TITLE
Update the fact that it's no more usable

### PR DESCRIPTION
**Pull request by vincegre**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by fabaff — APPROVED** [review]
Change looks good to me.

**Comment by vincegre** [comment]
> Change looks good to me.

Thanks for the approval. As I was not sure it's ok I didn't put any comment about the new non official integration for TTN V3. Is it ok to indicate it with URL to github ? with a warning that it's not an official integration ? If it's ok I'll submit a new commit ;)

Vincèn

**Comment by frenck** [comment]
I don't think this is the right approach...

This is not how we deprecate or handle these type of things. IMHO, either the integration needs to be fixed, or we need to decide to remove/deprecate the integration.

../Frenck

**Comment by vincegre** [comment]
> I don't think this is the right approach...
> 
> This is not how we deprecate or handle these type of things. IMHO, either the integration needs to be fixed, or we need to decide to remove/deprecate the integration.
> 
> ../Frenck

Well the integration should be deprecated since ages, I tried in past but process too complicated for me :( The new non official integration is not enough clean to be an official one and I don't think the maintainer wants to do that work (not really any answers at tickets/bugs opened on github...

**Pull request merged**
