### PR TITLE
Added documentation for password mode in input_text

### PR DESCRIPTION
**Pull request by covrig**
**Description:**
Added `mode: password` to `input_text` documentation.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** 
https://github.com/home-assistant/home-assistant/pull/11849
https://github.com/home-assistant/home-assistant-polymer/pull/824
## Checklist:

  - [ x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`. 
  - [ x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by frenck** [comment]
Thanks, @covrig! Can be merged as soon as the parent PR gets merged.

**Comment by covrig** [comment]
@balloob @frenck I noticed that https://github.com/home-assistant/home-assistant/pull/11849 was merged, but this documentation (and https://github.com/home-assistant/home-assistant-polymer/pull/837) wasn't.

**Comment by balloob** [comment]
Thanks! Merged

**Comment by frenck** [comment]
I didn't merge since there where 2 parent PR referenced in this PR, from which I concluded both where mandatory.  Only one of them was merged, so yeah... that is why.

**Comment by balloob** [comment]
Ah yes, we ended up splitting the frontend PR in 2 and merged the password one.

**Pull request merged**
