### PR TITLE
Update discord.markdown

### PR DESCRIPTION
**Pull request by vermium**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by vermium** [comment]
Documentation for home-assistant/core#33692

**Review by frenck — CHANGES_REQUESTED** [review]
Please take a look at the files changed in this PR.
It is full of unrelated edits, and reverts the file back to like the state of 6 months ago.

**Comment by vermium** [comment]
What do you mean with 
It is full of unrelated edits, and reverts the file back to like the state of 6 months ago.

**Comment by frenck** [comment]
Your new changes are not in this PR, furthermore it restored the file to a state is was in 6 months ago. E.g., the frontmatter is thrown back at a very old state.

**Comment by vermium** [comment]
Could you delete this PR?

**Pull request closed without merging**
