### PR TITLE
[WIP] Blog post proposal: Home Assistant on Kubernetes

### PR DESCRIPTION
**Pull request by titilambert**
**Description:**

This is a blog post, describe how to deploy Home Assistant on Kubernetes using k3s.

This is my first draft.
It's not made for beginner, and I would recommend it only for Kubernetes users (advanced ?)

So, maybe a blog post is not the right place for it.

Thanks for your feedback

### CODE REVIEW

**Comment by frenck** [comment]
I'm kinda in the middle on this being a blog post.
The thing with blog posts is that updating them is a pain. Since this tutorial/guide/how to, is prone to change in the near future, I'm kinda leaning towards saying: No.

In general, IMHO, the forums are a better place for those kinds of things.

**Comment by titilambert** [comment]
@frenck Fair enough, I'm closing it, I will post the fourm link here

**Comment by techguydave** [comment]
@titilambert Did you ever make the forum post?

**Comment by klaasnicolaas** [comment]
https://community.home-assistant.io/u/titilambert/activity nope

**Comment by titilambert** [comment]
@synth3tk not yet :/ Sorry, missing time to do it
But you can still read this PR diff, this is a good start

**Pull request closed without merging**
