### PR TITLE
Add Powerwall off grid switch

### PR DESCRIPTION
**Pull request by daniel-simpson**
## Proposed change

This PR adds a "Take Powerwall Off-Grid" switch which allows powerwall users to take their battery off grid programmatically.

This is a feature I (and other powerwall users) have been after for a while, as it would allow us to use power price data from other integrations to add home assistant automations around this behaviour.

Personally, I've taken the time to write this because where I live (Australia) and the power provider I use (Amber Electric) offers negative feed in for solar exports at certain times of the day. This feature would allow me to take my home off-grid (and effectively curtail solar generation) during these negative Feed in events.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/86357

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by daniel-simpson** [comment]
Sorry about the messing around, I've removed the documentation for a feature that is no longer part of the core repo's PR.

Ready for re-review when someone has time, thank you!

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
We should update `ha_category` and `ha_platforms` as well

**Review by bdraco — CHANGES_REQUESTED** [review]
One small comment : https://github.com/home-assistant/home-assistant.io/pull/25879#issuecomment-1401169166

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
Thanks @daniel-simpson

**Comment by daniel-simpson** [comment]
This ok to merge now?  Core PR is now merged: https://github.com/home-assistant/core/pull/86357

**Pull request merged**
