### PR TITLE
Add Lovelace Tips and Tricks page

### PR DESCRIPTION
**Pull request by dale3h**
**Description:**
With Lovelace becoming the new hottest thing, we need a place to share tips and tricks with users.

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by c727** [comment]
I'm against this:

- the migration script is a pain for Hass.io users: install SSH, install packages. Last time we removed it as it was outdated
- the config generator is not for the generic user
- the tips and tricks are already in the config or have config options


- we already have a FAQ section
- we have a syntax for notes

**Comment by dale3h** [comment]
@c727 Thank you for your feedback, these are all valid points.

> the migration script is a pain for Hass.io users: install SSH, install packages. Last time we removed it as it was outdated

This migration script is up-to-date with 0.74.0, and runs smoothly on Hass.io given that you, yes, install SSH and the required Python packages. One option is to create a simple run-it-once add-on that does all of this for you.

Hass.io usage is laid out in three steps:
1. Go to the **Add-On Store** and install **SSH & Web Terminal** add-on from the **Community Hass.io Add-ons**.
2. Login to the shell (either through SSH or the web terminal).
3. Run these commands:
```shell
$ pip3 install "requests>=2.14.2" "pyyaml>=3.11,<4"
$ wget -O /share/lovelace_migrate.py https://raw.githubusercontent.com/dale3h/python-lovelace/master/lovelace_migrate.py
$ python3 /share/lovelace_migrate.py -o /config/ui-lovelace.yaml
```

> the config generator is not for the generic user

Moving forward, I do agree that we gear more toward the "generic user" with our documentation. If this is truly holding this section back, I am more than happy to remove it. Or, if it would be acceptable, I can go with my original section format and lay it out as "Beginner Tips and Tricks," "Advanced Tips and Tricks," and "Expert Tips and Tricks."

> the tips and tricks are already in the config or have config options

Neither of the two tricks mentioned on this page are available in the current card documentation.

> we already have a FAQ section

I feel that FAQ differs vastly from Tips and Tricks.

> we have a syntax for notes

I completely overlooked that, my apologies. I have pushed a new commit with the correct note syntax.

**Comment by c727** [comment]
https://www.home-assistant.io/lovelace/vertical-stack/#examples

https://www.home-assistant.io/lovelace/picture-elements/#tap_action -> none

**Comment by dale3h** [comment]
Vertical Stack Examples = similar, but does not point out the "trick" that I am.

`tap_action` = does not apply to State Badge nor custom elements.

**Comment by dale3h** [comment]
Everything that is planned to be mentioned on this page is completely optional for a user to use or not to use, and every user should have the option to see their options. The goal is to share "great ideas" that our users have figured out along their journey with Lovelace. Why should we leave it up to each 
individual user to reinvent the wheel?

**Comment by dale3h** [comment]
Update: There is now a Hass.io add-on that does the Lovelace migration for you. I am hoping for it to be released tomorrow. The new steps are expected to be:

1. Go to the **Add-On Store** and install the **Lovelace Migration** add-on from the **Community Hass.io Add-ons** repository.
2. Start the **Lovelace Migration** add-on.

It *seriously* cannot get any simpler than that.

**Comment by ludeeus** [comment]
I think this looks great, and with the addition of an addon, we can point users here so we don't have to supply the same info in discord over and over :)
Great addition @dale3h ! :D

**Review by DubhAd — APPROVED** [review]
👍 I think this is a key feature in persuading people to explore Lovelace, and provide the feedback (and testing) that is critical to rolling out a feature like this.

**Pull request merged**
