### PR TITLE
Added new supported device HmIP-STE2-PCB

### PR DESCRIPTION
**Pull request by hahn-th**
## Proposed change

Added new supported Device HmIP-STE2-PCB to docs in Integration Homematicip_cloud

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/75369
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by frenck** [comment]
Is there a parent PR that add it to the codebase?

**Comment by hahn-th** [comment]
Yes it is: #75369
https://github.com/home-assistant/core/pull/75369

Thanks for your work!

**Comment by frenck** [comment]
@hahn-th There are unrelated commits in this PR now, probably because it was based on the `current` branch. Please git rebase your commits onto the `next` branch.

**Comment by hahn-th** [comment]
Hopyfully it is alright now. Thanks for your patience.

**Review by frenck — APPROVED** [review]
Thanks, @hahn-th 👍

**Pull request merged**
