### PR TITLE
Update command for final pairing

### PR DESCRIPTION
**Pull request by bjohnson8949**
Changed from pair_finish to pair-finish the first didn't work for me but the pair-finished work for me.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by frenck** [comment]
I'm sorry, but it actually is `pair_finish`.

See code:
https://github.com/vkorn/pyvizio/blob/master/pyvizio/cli.py#L60

Maybe this recently changed? Nevertheless, the latest version of the code matches our documentation.

**Comment by bjohnson8949** [comment]
I updated documents there as well. 

See command line output for help
http://i67.tinypic.com/orjdyr.png

**Comment by frenck** [comment]
@bjohnson8949 Well, I guess that does it. Seems like this behavior changed in the Click package.

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Thanks! 👍 
Happy Hacktoberfest 🎉

**Pull request merged**
