### PR TITLE
Mention to clear out any application credentials in troubleshooting Google Calendar

### PR DESCRIPTION
**Pull request by dannytsang**
## Proposed change
Added a note about clearing any application credentials in the troubleshooting section. I just came across this when I regenerated new keys.

## Type of change
- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: n/a

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by allenporter** [comment]
Pending PR https://github.com/home-assistant/home-assistant.io/pull/22980 also adds this. Want to give that a review?

**Comment by allenporter** [comment]
(thank you for the contribution however)

**Comment by dannytsang** [comment]
@allenporter  #22980 does cover it. Thank you.

**Comment by allenporter** [comment]
Ok thanks, would be great for you to review, and leave any other feedback about the updates.

**Pull request closed without merging**
