### PR TITLE
Update ted5000.markdown

### PR DESCRIPTION
**Pull request by SupremeSports**
## Proposed change

- Added sensors that are readily available from TED5000 API
- Created modes to get more sensors depending on needs
- Added state_class and device_class where applicable

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

Added new features (sensors) to TED5000 integration.
1. `device_class` added for all applicable sensors
2. `state_class` added for all applicable sensors
3. Created a config mode (base, advanced or extended)

- Link to parent pull request in the codebase: [57933](https://github.com/home-assistant/core/pull/57933)
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by SupremeSports** [comment]
New code PR to replace the old one: https://github.com/home-assistant/core/pull/57933

**Comment by AndyZaa** [comment]
Hi Jean, thanks for working on this. I’m looking forward to getting my TED5000 data into the new Energy feature. Has this been released yet? I tried enabling advanced mode in config but it doesn’t accept it.

**Comment by SupremeSports** [comment]
> Has this been released yet? 

No, not yet...

> I tried enabling advanced mode in config but it doesn’t accept it.

Have you created a custom component with the manifest? Integrations don't need the manifest, but you have to add it in a custom component otherwise it uses the default integration and it's probably why the advanced mode doesn't work.
image

```yaml
{
  "domain": "ted5000",
  "name": "The Energy Detective TED5000",
  "version": "4.0.0",
  "documentation": "https://www.home-assistant.io/integrations/ted5000",
  "requirements": ["xmltodict==0.12.0"],
  "codeowners": [],
  "iot_class": "local_polling"
}
```

Then, your configuraton should look like this:
```yaml
  sensor:
    - platform: ted5000
      host: !secret ted_ip
      port: !secret ted_port
      name: TED5000
      mode: extended
```

**Comment by AndyZaa** [comment]
Thank you Jean. I haven't created a custom component yet so I gave it a try using your example. With the manifest.json in the proper folder, I added the mode parameter to the TED5000 in my sensor.yaml. I then get a "Platform error sensor.ted5000 - No module named 'custom_components.ted5000.sensor'" when I Check Configuration and the two default Ted5000 entities disappeared. I'm sure it's my inexperience in creating a custom component. But no worries, I unwound the changes. I can wait for the official release - do you know when it will work its way through the release process? It's hard to tell for a newbie. Thanks again for championing this update - probably not a lot of us TED5000 users out there but I know I appreciate getting utility from the gear.

Update: I realized I need the __init__.py and sensor.py files in the custom_components/ted5000 directory so I grabbed all the files at core/homeassistant/components/ted5000/ and installed them. I get "Invalid config for [sensor.ted5000]: [mode] is an invalid option for [sensor.ted5000]. Check: sensor.ted5000->mode. (See ?, line ?)." when I Check Configuration.

**Comment by SupremeSports** [comment]
You have to first let it load without the mode as it doesn't exist yet in the default integration (as you used to use that one), restart HA without the mode, then add the mode and restart again

**Comment by AndyZaa** [comment]
Yes, that worked - so exciting!

I was getting a "No 'version' key in the manifest file for custom integration" so I added "version": "1.0.0" to the manifest.json file, according to https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions

I tested both extended and advanced modes and they worked. I'm using advanced mode because the extended isn't required for me just now. Thank you so much for your contributions, and in furthering my knowledge of HA!

**Comment by SupremeSports** [comment]
Original HA PR closed

**Pull request closed without merging**
