### PR TITLE
Update iot class for fints integration

### PR DESCRIPTION
**Pull request by WiiPlayer2**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/69041
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @WiiPlayer2 👍 

This will reset every release automatically (as this information is gathered from the code base/integration manifest).

**Comment by WiiPlayer2** [comment]
@frenck So that would mean, when my other PR is merged this change would be made anyway automatically?

**Comment by frenck** [comment]
> when my other PR is merged this change would be made anyway automatically?

Yes

**Comment by WiiPlayer2** [comment]
Good to know. Thanks.

**Pull request merged**
