### PR TITLE
Move up warning and update ZHA info about Zigbee serial radio over WiFi

### PR DESCRIPTION
**Pull request by Hedda**
## Proposed change

Move up the warning in the [ZHA integration](https://www.home-assistant.io/integrations/zha/) documentation and update info about Zigbee serial radio over WiFi.

"ZHA requires a robust connection between the zigpy radio library and the serial port of the Zigbee radio. With solutions such as _ITEAD Sonoff ZBBridge_ or a Ser2Net serial proxy connection over a WiFi network it is expected to see `NCP entered failed state. Requesting APP controller restart` in the logs. This is a normal part of the operation and indicates there was a drop in communication which caused packet loss to occurred between the zigpy radio library and the Zigbee radio. The use of serial network proxies/bridges/servers over WiFi is therefore not recommended when wanting a stable Zigbee environment in ZHA."

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: NA
- Link to parent pull request in the Brands repository: NA
- This PR fixes or closes issue: NA

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
There are more warnings and notes, than actual documentation. Moving it up, more prominent and even extending it more, feels way out of place.

I'm considering not merging this.

**Comment by Hedda** [comment]
IMHO this specific warning against using a Zigbee to WiFi bridge is essential as it can completely ruin users experience with ZHA.

FYI, dependency library bellows readme file has now also been updated with the same warning against using a Zigbee to WiFi bridge:

https://github.com/zigpy/bellows#warning-about-zigbee-to-wifi-bridges

It is recommended to instead use a wired Ethernet bridge based solution if want to a stable Zigbee to IP function with ZHA, e.g.:

https://community.home-assistant.io/t/zigbee-3-0-to-ethernet-bridge-gateway-wired-not-wifi-inexpensive-diy-project-for-zha/257020

**Comment by frenck** [comment]
Yes, but dropping a massive warning block in the user's face without any context, to begin with isn't friendly or a good user experience either.

**Comment by Hedda** [comment]
> Yes, but dropping a massive warning block in the user's face without any context, to begin with isn't friendly or a good user experience either.

Though I added almost too much context when added info in the warning about WiFi not being stable for a serial proxy connection.

"**_ZHA requires a robust connection between the zigpy radio library and the serial port of the Zigbee radio. With solutions such as ITEAD Sonoff ZBBridge or a Ser2Net serial proxy connection over a WiFi network it is expected to see NCP entered failed state. Requesting APP controller restart in the logs. This is a normal part of the operation and indicates there was a drop in communication which caused packet loss to occurred between the zigpy radio library and the Zigbee radio. The use of serial network proxies/bridges/servers over WiFi is therefore not recommended when wanting a stable Zigbee environment in ZHA._**"

**Comment by Hedda** [comment]
For more low-level context see https://github.com/zigpy/bellows/issues/377 and https://github.com/zigpy/bellows/issues/385 where @Adminiuga recommendation to avoid this is to simply never ever use a serial TCP server over WiFi with the bellows library.

**Comment by Adminiuga** [comment]
Having full context in bellows should suffice.  I see  no point having this huge warning here. At most, just add a bellows warning link to existing warning in zha docs.

**Comment by frenck** [comment]
Ok, leaving it as is now and not moving it up. Closing this PR.

**Pull request closed without merging**
