### PR TITLE
Update lock.mqtt example with state_locked and state_unlocked

### PR DESCRIPTION
**Pull request by rwarner**
Had an issue with my HASS not working with locks. Turns out the docs didn't reflect the new "state_lock" and "state_unlock" payload breaking change mentioned here: https://www.home-assistant.io/blog/2020/01/15/release-104/#breaking-changes

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue:

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by rwarner** [comment]
This actually may be irrelevant, I may be misunderstanding the documentation. In my own HASS, it seems like I need both for a Schlage Deadbolt:
```
payload_lock: "locked"
payload_unlock: "unlocked"

state_locked: "locked"
state_unlocked: "unlocked"
```

After this was integrated: https://github.com/home-assistant/core/pull/29808

Maybe the sample at the bottom would benefit from including both? Unsure... Doesn't seem like removing payload_lock and payload_unlock is needed.

**Comment by emontnemery** [comment]
> Maybe the sample at the bottom would benefit from including both? Unsure... Doesn't seem like removing payload_lock and payload_unlock is needed.

Yeah, you're right. Would you mind updating this PR to update the example?

**Comment by rwarner** [comment]
> Yeah, you're right. Would you mind updating this PR to update the example?

Sure thing, thanks for looking. I just made the suggested change and added the payload_lock/unlock back in the docs along with the example at the bottom showing both.

**Review by emontnemery — APPROVED** [review]

**Comment by emontnemery** [comment]
Looks good, I updated the issue description also to better match the changes.

**Pull request merged**
