### PR TITLE
Create configuration_yaml_by_skalavala.markdown

### PR DESCRIPTION
**Pull request by skalavala**
**Description:**
Added a link to my GitHub repo under Examples section.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Why not putting this in the `current` branch?

**Comment by skalavala** [comment]
Not in a hurry :) I think the default branch that presented to me was"Next", and ijust chose it. Not sure if that can be changed or not... if not, let it be in the next release :)

**Comment by klaasnicolaas** [comment]
or you perform a rebase so that it can go into the `current` or you have to wait a while for the release 0.93. I would go for the first option 😉 😆

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Thanks, @skalavala 👍 

Welcome back 😉

**Pull request merged**
