### PR TITLE
Add template support to numeric_state trigger's for option

### PR DESCRIPTION
**Pull request by pnbruckner**
**Description:**
Allow the use of templates with the numeric_state trigger's `for` option.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#24955

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

<a href="https://gitpod.io/#https://github.com/home-assistant/home-assistant.io/pull/9781"></a>

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by balloob** [comment]
Parent merged, please resolve conflicts to merge this 👍

**Comment by pnbruckner** [comment]
Will do...

**Comment by pnbruckner** [comment]
Sorry, forgot about fixing the merge issue. I rebased and force pushed. Should be good now.

**Comment by klaasnicolaas** [comment]
Thnx @pnbruckner time for a merge! 😄

**Review by klaasnicolaas — APPROVED** [review]

**Review by frenck — APPROVED** [review]

**Pull request merged**
