### PR TITLE
Onkyo radio preset

### PR DESCRIPTION
**Pull request by pszafer**
**Description:**

Support for switching radio preset by play_media function.

https://github.com/home-assistant/home-assistant/pull/16258

## Checklist:

- [ x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by fabaff — DISMISSED** [review]
This PR point to the wrong branch. It should be `next`.

**Comment by pszafer** [comment]
@fabaff Is it okay right now?

**Review by MartinHjelmare — APPROVED** [review]

**Comment by MartinHjelmare** [comment]
@fabaff ok?

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Looks good! Merging this one in.

**Pull request merged**
