### PR TITLE
Update Tado configuration variables

### PR DESCRIPTION
**Pull request by luukdobber**
**Description:**
Update Tado configuration variables to new style. #6385

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
You merge it into the wrong branch, you must have the `current` branch and I think the configuration has already been updated for Tado.

**Comment by frenck** [comment]
@klaasnicolaas Incorrect, they are not updated yet.

@luukd Could you please rebase this PR onto the `current` branch? If you need any help with that, please let me know.

**Review by frenck — CHANGES_REQUESTED** [review]
Needs to be rebased onto `current`

**Comment by klaasnicolaas** [comment]
@frenck see: #6545 Have already changed the same 2 files 2 days ago 😉

**Comment by frenck** [comment]
Thanks, @klaasnicolaas, not sure what I have been looking at, at the time of checking that... 😩 

@luukd, as stated by @klaasnicolaas, this was already done.

Closing this PR.

**Comment by luukdobber** [comment]
> Thanks, @klaasnicolaas, not sure what I have been looking at, at the time of checking that... 😩
> 
> @luukd, as stated by @klaasnicolaas, this was already done.
> 
> Closing this PR.

No problem, I missed that one 🤭

**Pull request closed without merging**
