### PR TITLE
add iottty cover docs

### PR DESCRIPTION
**Pull request by shapournemati-iotty**
## Proposed change

Add iotty cover entity details.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/125422
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

## Summary by CodeRabbit

- **New Features**
	- Enhanced documentation for the iotty integration with a new category for "Shutter" devices, including specific products.
	- Introduced a new section titled "Covers," detailing functionality for opening, closing, and positioning cover entities.
- **Documentation**
	- Improved overall structure and clarity of the iotty integration documentation.

### CODE REVIEW

**Comment by c0ffeeca7** [comment]
Thank you for contributing, @shapournemati-iotty  :+1: 

 As this PR seems to be related to a code PR, please rebase and point this PR against the `next` branch.

**Comment by c0ffeeca7** [comment]
I'm [drafting this PR](https://developers.home-assistant.io/docs/review-process#prs-are-being-drafted-when-changes-are-needed), as changes are needed. Please undraft it, once the changes have been implemented and the PR is ready for review again.

**Comment by c0ffeeca7** [comment]
please rebase and point this PR against the `next` branch.

**Comment by c0ffeeca7** [comment]
I'm [drafting this PR](https://developers.home-assistant.io/docs/review-process#prs-are-being-drafted-when-changes-are-needed), as changes are needed. Please undraft it, once the changes have been implemented and the PR is ready for review again.

**Comment by shapournemati-iotty** [comment]
To avoid issues with the change in target branch, I made a new PR here: https://github.com/home-assistant/home-assistant.io/pull/34752

**Comment by c0ffeeca7** [comment]
Closing PR as it is superseded by #https://github.com/home-assistant/home-assistant.io/pull/34752/

**Pull request closed without merging**
