### PR TITLE
[WIP] Remove alias from script

### PR DESCRIPTION
**Pull request by dshokouhi**
**Description:**

After trying to help a user troubleshoot an issue with scripts the alias line was giving a mapping values error, after it was removed the configuration check passed without errors.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant# N/A

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by frenck** [comment]
@dshokouhi Isn't this a bug?

**Comment by dshokouhi** [comment]
@frenck is it?  I was honestly not sure as I only saw the alias mentioned in 1 place so I thought maybe the docs were not correct.

**Comment by point-4ward** [comment]
Aliases work fine with scripts, I use a few myself for frontend display purposes. Here's an example...

https://github.com/mf-social/Home-Assistant/blob/master/packages/virtual_devices/maintenance.yaml

Several scripts in there.

**Comment by dshokouhi** [comment]
@mf-social ok interesting, I had only raised this because when I was helping out a user in Discord after comparing my scripts to theirs the alias was the only line I was not using.  After they removed the alias it worked but its possible some other change may have made it work as well.   If scripts are working fine for you and you are not getting config errors we can close this.

**Comment by frenck** [comment]
Closing this one, see conversation above for reasoning.

**Pull request closed without merging**
