### PR TITLE
add new Pushsafer Parameter

### PR DESCRIPTION
**Pull request by appzer**
**Description:**
add new Pushsafer Parameter priority, retry, expire, answer to the last example.
Minifiy the first example to show only important parameter

### CODE REVIEW

**Comment by frenck** [comment]
Parent PR: home-assistant/home-assistant#16060

@appzer Please use the PR template next time.

**Comment by appzer** [comment]
OK, i will do.
do I have to do something now, or is everything OK

**Comment by frenck** [comment]
This PR dates pre Netlify and fails the build because of age.

Things to do to resolve this:
- Resolve merge conflict
- Rebase the PR

**Comment by appzer** [comment]
@frenck  i dont know where the issue is
What should i do?

Kevin

**Comment by frenck** [comment]
@appzer Don't worry, I'll pick this one up.

**Comment by appzer** [comment]
@frenck thanks, do I have to do something else?

**Comment by frenck** [comment]
No you don't have to do anything, I've been out for 2 weeks on a holiday. I will pick this one up asap.

**Comment by frenck** [comment]
Resolved merge conflict.

**Review by frenck — APPROVED** [review]

**Pull request merged**
