### PR TITLE
spelling mistake

### PR DESCRIPTION
**Pull request by haqthat**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by WofWca — APPROVED** [review]

**Review by WofWca — COMMENTED** [review]
This needs to go to `current` branch.

**Review by WofWca — CHANGES_REQUESTED** [review]
Branch.

**Review by frenck — CHANGES_REQUESTED** [review]
@haqthat Thanks for this PR!

Unfortunately, this PR targets an incorrect branch. Changes to the current documentation need to go into the `current` branch. Please change the target and rebase your changes onto `current` as well.

Thanks already 👍

**Comment by fabaff** [comment]
Those changes do not make much sense as this file is shipped by a third-party. Please fix the spelling at https://github.com/inuitcss/inuitcss.

**Pull request closed without merging**
