### PR TITLE
Update nest configuration instructions for new configuration flow

### PR DESCRIPTION
**Pull request by allenporter**
## Proposed change

Update nest configuration instructions for new configuration flow. The new config flow is an interactive version of the existing documentation, with steps matching the steps on this page.

Remove the `configuration.yaml` instructions entirely since they are no longer needed. Update troubleshooting instructions based for `missing_configuration` which is expected if following these instructions on an old home assistant version.

See screenshots of the new config flow steps below. The config flow `more info` links send you to the integration docs which have more details and screenshots of the cloud console.

Screen Shot 2022-01-22 at 11 43 00 PM

Screen Shot 2022-01-22 at 11 43 47 PM

Screen Shot 2022-01-22 at 11 47 44 PM

(I did not add these screenshots to the integration docs)

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/64680
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
We currently do not allow configuring OAuth inside configuration flows.

**Comment by allenporter** [comment]
I see! I guess I had a more optimistic view of the conversation happening in https://github.com/home-assistant/architecture/discussions/692 than you did :)

**Comment by frenck** [comment]
> I see! I guess I had a more optimistic view of the conversation

In general, I'm against creating PRs that require architectural issue/discussion to be revolved first (unless it contributes to clarification, which is not the case here IMHO).

It pollutes our review queue with things we can't action right now.

**Comment by allenporter** [comment]
> > I see! I guess I had a more optimistic view of the conversation
> 
> In general, I'm against creating PRs that require architectural issue/discussion to be revolved first (unless it contributes to clarification, which is not the case here IMHO).
> 
> It pollutes our review queue with things we can't action right now.

**Pull request closed without merging**
