### PR TITLE
Updated Glances instructions

### PR DESCRIPTION
**Pull request by genestealer**
Updated to correct to new Glances API instructions and how to install for Linux and Windows.

**Description:**

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by genestealer** [comment]
Issues with Windows instructions

**Comment by klaasnicolaas** [comment]
Perhaps also mention that there is an add-on from Glances for Hass.io users

**Comment by frenck** [comment]
I truly think we should not merge this.

While I appreciate the effort, we are not a website that provides documentation on how to install Glances. We should prefer linking to the Glances website in those cases.

The reasoning is that this is hard to maintain, and there are way too many variants. Besides that, this documentation also pins a version, keeping that updated, is most likely not going to happen.

**Comment by frenck** [comment]
This has been discussed on Discord with some of our maintainers, and we agree that this type of documentation does not belong in the Home Assistant docs. Therefore, closing up this PR.

Nevertheless, thank you for contributing, that is greatly appreciated 👍

**Comment by genestealer** [comment]
No problem I understand I also appreciate you taking the time to have a discussion before making a decision. Unfortunately the information I put into the update isn't available on the glances website, they cater very little to the windows environment. I will see whether or not I can update their documentation, in addition to perhaps adding the configuration example in the HA forum.

**Pull request closed without merging**
