### PR TITLE
Change image of phone on homepage to newest iPhone model 12

### PR DESCRIPTION
**Pull request by johanf85**
## Proposed change

This is new PR, I closed the initial PR #18374 to split that one up in two PRs and create a different image with lower filesize. 

The iPhone on the homepage is displayed with an old model, nowadays phones have less large bezels.  The most recent model is the iPhone 12, an image with this model gives an up to date feel. 

I have used the same image as displayed on the current iPhone on the homepage. Will be happy to use any other screenshot if desired, let me know! 

This is the current:

Image size: 613px x 636px - 25 kB

I kept the ratio of the screenshot part (without the phone) the same as the original, therefore there is no stretching of the screenshot content, but will the total image be slightly smaller in width/height.

Proposed image:

Image size: 594px x 553 px - 41 kB

I saved the image as PNG-8 which made the download size smaller. 

Source used for iPhone 12 parts: [https://designmodo.com/iphone-mockups/#iphone-12-mockup-set](https://designmodo.com/iphone-mockups/#iphone-12-mockup-set)  
Next to that I took the status bar from this photoshop psd: [https://www.free-mockup.com/downloads/iphone-x-with-status-bar-icons-free-psd-mockup/](https://www.free-mockup.com/downloads/iphone-x-with-status-bar-icons-free-psd-mockup/)

## Type of change

*   [x] Spelling, grammar or other readability improvements (`current` branch).
*   [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
*   [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
    *   [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
*   [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
*   [ ] Removed stale or deprecated documentation.

## Additional information

*   Link to parent pull request in the codebase:
*   Link to parent pull request in the Brands repository:
*   This PR fixes or closes issue:

## Checklist

*   [ ] This PR uses the correct branch, based on one of the following:
    *   I made a change to the existing documentation and used the `current` branch.
    *   I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
*   [ ] The documentation follows the Home Assistant documentation [standards](https://developers.home-assistant.io/docs/documenting/standards).

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
We should also update the UI in the image. The Home Assistant UI is very outdated.

**Comment by johanf85** [comment]
I agree. Would love to help out with making an iPhone image. If someone would like to provide a screenshot image, I can set it to a iPhone image.

**Comment by balloob** [comment]
Looks like there are some white pixels in the used iPhone border

image

I have good experience with bezels from [Facebook Design](https://design.facebook.com/toolsandresources/devices)

**Comment by balloob** [comment]
For making screenshots, I recommend opening [the demo](https://demo.home-assistant.io/). Lovelace dashboard can be edited so you can drop cards you don't need / rename entities, icons etc. 

Maybe we can do a "Living Room" card showing 2 lights, temperature and a [graph footer](https://www.home-assistant.io/lovelace/header-footer/#graph-header--footer) that should represent temperature?

**Comment by balloob** [comment]
Although I also don't mind keeping my picture on there 🤣

**Comment by balloob** [comment]
image

Not a super big fan of the black frame, it looks too dark imo

**Comment by johanf85** [comment]
Hi Paulus,   
  
Thanks for checking it out. 

I agree with you on the dark frame, which is kind of present (aanwezig) and different from the blue and white which are pretty much the theme colors. 

Apple doesn't have any recent iPhone models that are white colored. How do you feel about using an Android model instead of iPhone? There are recent white android phones, with even smaller bezels. 

For instance the Samsung Galaxy S10. I found this Mockup Template. [https://www.anthonyboyd.graphics/mockups/clay-samsung-galaxy-s10-top-view-mockup/](https://www.anthonyboyd.graphics/mockups/clay-samsung-galaxy-s10-top-view-mockup/) 

The author does want an attribution placed with his name somewhere on the site. I think it is important to respect that, however it can seem a bit of a hassle to that for this and maybe other designs in the future. What do you think of that?

Also a possibility is a 'generic' not really existing model. For instance.   
  
https://www.freepik.com/free-psd/app-interface-mock-up-phone-screen-composition_14063477.htm#page=1&query=mockup%20phone%20white&position=12

Same applies with attribution here. 

I am aware of the Facebook Design files, however they don't have a recent white model in their database.   
  
It's a good idea to use the demo for using a couple of elements for creating a screenshot image. Using your current picture wouldn't be much of a problem, I recognize it from your Twitter! I already used my own Home Assistant installation to make that part:



scale 100%



A bit magnified in the browser  
  
Or, a bit smaller part of the image:



Scale 100%



Magnified

Do you have the photo from Anne Therese, on the current screenshot, available too? I am guessing she is your girlfriend of wife?

**Comment by johanf85** [comment]
I did some fiddling around with the white Galaxy S10 template and got to this (still a concept). Is this what you meant when it comes to the elements?



The current image is 613x636 pixels

When I apply the same width/height ratio on the above image, it results in below image:



So then the graph is lost. 

How do you feel about this phoneframe?

**Comment by johanf85** [comment]
Oh wait, you meant something like this:



At first glance I thought you meant something else. Will get to it later.

**Comment by johanf85** [comment]
Another interesting link: https://store.ramotion.com/product/samsung-galaxy-s20-mockup-clay

**Comment by balloob** [comment]
I'm not set on using iPhone. Anything nice and white is ok I think. Maybe next week a better frame for iPhone comes available.

**Comment by balloob** [comment]
Drop the badges at the top and you get a lot more space to show the graph.

**Comment by johanf85** [comment]
I made this one:



*   Added an image of Anne-Therese her Instagram profile picture (just like the current image). Found that via your (Paulus) Instagram in one of the photos in which she was tagged. Just letting the family Schoutsen be in the example, just like the current image ;-).
*   It's slightly higher than the current one, 30 pixels higher. But the current one scales with the page, so I think that's okay.
*   Compressed it, size is now 38 kB
*   Added blue edge so it blends in nice with the blue background (no white pixels)
*   I photoshopped the three dots more to the left, so I doesn't fall under the camera lens
*   It's a possibility to remove the camera lens, it doesn't add much

I noticed that the current image as used on the website is never scaled larger than 406 pixels wide in the browser. Therefore the source image can also be smaller regarding wide x length. This makes the file even smaller in filesize(kb). 



406x437 pixels, 21 kB

Using this, will give below output:



The content of the phone is saved loose of the rest and can be used for other models too:



  
 

What do you guys think about this concept?

**Comment by balloob** [comment]
I think it's great! My wife's photo is pretty old (as old as that iPhone frame), let's use this one

IMG_0743


We are also showing the living room temperature twice. I think that we should rename that badge maybe Office?

**Comment by balloob** [comment]
Oh and maybe we can swap sun for the weather? Not sure if that rendering is nice or not. 

And maybe update one of the people badges to be "Home" (you can use state dev tools to mimic that)

**Comment by johanf85** [comment]
Cool. Regarding the badges, do you mean these?



In my Home Assistant configuration I don't use the Weather badge. Is  it meant to have a textual display of the weather, or did you mean a badge with a certain icon? In my installation, this seemed the only option for me.

**Comment by balloob** [comment]
Yes, those badges. I guess we can drop the weather badge completely.

**Comment by balloob** [comment]
Oh, maybe we can add a scene or two ?

**Comment by johanf85** [comment]
I am not familiar with scenes, as I don't use them. Are there badges to execute scenes? Do you have an Example?

By the way, I noticed that there isn't any white Samsung Galaxy s10 phone. The template I found is a 'Clay' template. I didn't know that term, but apparently with Mockups there is a distinction between clay and realistic. 

Clay is a design form to make the device less pronounced I guess. For instance these are iMac clay mockups. 



There are iPhone clay mockup template available as well. I will add this one too to decide which is preferred. Are you okay with using this non-realistic phone pictures?

This is the iPhone 12 clay white (with old badges):  

screenshotiphone406

Here I have some badges I saw within the demo and my own HA to choose from, will use weather instead of 'Buienradar' if necessary.

**Comment by balloob** [comment]
The 2nd demo has a scene. You can add it as a badge. However it shows "scening" as text and not the state/scene icon as I thought 🤔 

it does indeed activate the scene when tapped.

**Comment by balloob** [comment]
Samsung clay one without the camera hole has my preference 👍

**Comment by balloob** [comment]
I opened a PR so we start rendering the scene badge correctly https://github.com/home-assistant/frontend/pull/10020

**Comment by spacegaier** [comment]
> 
> 
> Cool. Regarding the badges, do you mean these?
> 
> 
> 

Now the two pictures are quite different color spectrum wise, which makes it a bit jarring. Ideally we would color grade the "wife picture" a bit so it gels better in the overall look.

**Comment by balloob** [comment]
Let's use this one https://photos.app.goo.gl/FTwPnwzYUiFhcGSk8

**Comment by johanf85** [comment]
Here are some changed images:

**Galaxy S10, With some other badges and with the picture of Anne-Therese first provided:**



**Same, with latest photo of Anne-Therese:**



**iPhone 12, with same screenshot:**



Let me know about desired improvements.

**Comment by johanf85** [comment]
See I made an error with using a comma instead of a dot in the Solar badge

**Comment by spacegaier** [comment]
The 2nd picture of Anne-Therese provides a much more coherent visual 👍 

BTW: Why is the weather badge image to blurry? Looks a bit out of place.

**Comment by johanf85** [comment]
Personally don't have a preference regarding the avatars, think they are both suitable. If desired we can zoom in on Paulus face a little bit, makes the face more recognizable. However then the robe he is wearing is less visible.

The weather badge is indeed a bit blurry. I used the Buienradar integration, a dutch weather service, and made a screenshot with my phone as a base. It is how it is presented on my screen.

**Comment by balloob** [comment]
The robe is important.

Can we drop the camera hole on the Samsung? That way it looks still like a phone, but we get the most screen real estate.

**Comment by balloob** [comment]
And then let's go for the 2nd profile pic of AT. And then I think we should ship it 🚢

**Comment by johanf85** [comment]
I already thought the robe was important 😁. I am really busy at the moment. Will submit the changed version next week.

**Comment by johanf85** [comment]
Here is de Samsung S10 White clay mockup, without camera. I changed the weather image, which was blurry as noticed by @spacegaier . Replaced with this one: [https://www.iconfinder.com/icons/1530390/weather_clouds_cloudy_rain_sunny_icon](https://www.iconfinder.com/icons/1530390/weather_clouds_cloudy_rain_sunny_icon) Which is royalty free.  And changed the black parts of that icon to grey. 

The template for the mockup is this: [https://www.anthonyboyd.graphics/mockups/clay-samsung-galaxy-s10-top-view-mockup/](https://www.anthonyboyd.graphics/mockups/clay-samsung-galaxy-s10-top-view-mockup/) 

The author does want an attribution placed with his name somewhere on the site. Is there room for that?



Filesize: 21 kb Dimensions: 406 X 442 px

**Comment by balloob** [comment]
We can add attribution in bottom right 
image

Oh actually, license states "A link back to my portfolio site is optional but for mockup sharing websites a Link back is required.". We're not sharing a mockup so don't need to link back?

**Comment by johanf85** [comment]
I think this is image is considered as a mockup and therefore some kind of link is asked by the author. 

I also stumbled on this online shop with mockup templates: [https://store.ramotion.com/product/samsung-galaxy-s20-mockup-clay](https://store.ramotion.com/product/samsung-galaxy-s20-mockup-clay)

For 9$ you can get a mockup template, which doesn't need attribution. I'll leave it up to you. 

For the iPhone template I used this one: [https://freemockup.net/iphone-12-pro-clay-scene-free-mockup/](https://freemockup.net/iphone-12-pro-clay-scene-free-mockup/)  , here I didn't find information about attribution. But do I think this mockup is shared among many sites, so maybe not shown what is the creators wish is. Using this iPhone template is also still possible.

BTW, damn, forgot to replace to comma in 88,6 kwH for a dot. Here is a change:



Filesize: 21 kb width: 406 px

**Comment by balloob** [comment]
$9 is not a problem. Want me to buy this one?

image

Ping me on email in my profile and I'll get you the file.

**Comment by johanf85** [comment]
Email sent!

**Comment by johanf85** [comment]
Thanks for sending the template to me, here is the mockup with that template:



I added a blue line around it, so that it will blend in with the background. I removed the camera just like with the previous template. Personally I like this model even more than the S10 model used in the previous model.

I also did a version with a status bar (time and battery etc)



Same, but with camera lens.

**Comment by johanf85** [comment]
I am not really satisfied with how the text turns out, during all the processes of resizing and compression, I think the text is not clear enough. Will submit a changed version for this.

**Comment by balloob** [comment]
That looks great! Agreed on the text. If you open the dev tools in a browser, you can enable mobile view -> responsive and set the width that you want to use.

**Comment by johanf85** [comment]
Yes, viewing with developer tools in responsive mode was an option. Did this with adding text in Photoshop though, using the same fonts as in lovelace. Here are two images, one with a status bar (time and battery) and one without. 





I updated the file in the PR with the image without the status bar

**Review by balloob — APPROVED** [review]
Amazing, this is perfect.

**Comment by johanf85** [comment]
Allright, cool!

**Pull request merged**
