### PR TITLE
Update LIFX for config entry per device reliability refactor

### PR DESCRIPTION
**Pull request by bdraco**
## Proposed change

Update LIFX for config entry per device reliability refactor

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/74316
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by Djelibeybi** [comment]
I need to double check what happens when you upgrade to the new discovery method but do not have an interface on the same subnet as the LIFX devices but either way, we should probably document that specific scenario so that we have something explicit to point people to in the docs when they all start opening issues and/or threads on the forum. :)

**Comment by bdraco** [comment]
> I need to double check what happens when you upgrade to the new discovery method but do not have an interface on the same subnet as the LIFX devices but either way, we should probably document that specific scenario so that we have something explicit to point people to in the docs when they all start opening issues and/or threads on the forum. :)

Good idea.  Please inline suggestions once you have results.

Thanks!

**Comment by Djelibeybi** [comment]
> Good idea. Please inline suggestions once you have results.

Will do. What's the expected/intended release version for this?

**Comment by bdraco** [comment]
> > Good idea. Please inline suggestions once you have results.
> 
> 
> 
> Will do. What's the expected/intended release version for this? 

2022.8.0. If all goes well we can likely switch out the underlying library in 2022.9.0

**Comment by Djelibeybi** [comment]
Things started to break with 2022.4.0 so I'm not going to be able to inline. I'm busy writing up the scenarios so I can simplify it down and we can discuss how to document it properly without confusing folks.

**Comment by bdraco** [comment]
> Things started to break with 2022.4.0 so I'm not going to be able to inline. I'm busy writing up the scenarios so I can simplify it down and we can discuss how to document it properly without confusing folks.

Another option would be to send a PR to this branch

**Comment by Djelibeybi** [comment]
Righto. Let me finish testing first. I had to go back a fair way to find the last version of HASS that would discover and instantiate bulbs with broken networking. :)

**Comment by bdraco** [comment]
> > Things started to break with 2022.4.0 so I'm not going to be able to inline. I'm busy writing up the scenarios so I can simplify it down and we can discuss how to document it properly without confusing folks.
> 
> Another option would be to send a PR to this branch

Or maybe just another PR after this one to add it to keep it simple

**Comment by Djelibeybi** [comment]
> Or maybe just another PR after this one to add it to keep it simple

Yeah, I think it's going to all be under the heading of "Upgrading from 2022.4 or older" because that's when discovery of actual devices changed.

**Comment by Djelibeybi** [comment]
The problem of previously accessible LIFX devices being inaccessible due to a lack of locally connected interface only occurs from v2022.5.0 until the parent PR is merged. The changes in that PR restore the pre-2022.5 experience because devices discovered via Zeroconf/HK are connected to directly using whatever inteface is enabled. 

Given that routing and firewalls would have to be properly configured to permit this pre-2022.5, it'll work again now. So migrating hard-coded configurations from `configuration.yaml` to config entries works fine too.

Not sure if we need to call this out if it's not going to be a problem much longer. Easier just to tell people to upgrade because it's fixed in 2022.8.

**Comment by bdraco** [comment]
> Not sure if we need to call this out if it's not going to be a problem much longer. Easier just to tell people to upgrade because it's fixed in 2022.8.

This is the way

**Pull request merged**
