### PR TITLE
Update media_player.panasonic_viera.markdown

### PR DESCRIPTION
**Pull request by dilruacs**
**Description:**

Add documentation for new feature to turn on some Viera models over LAN without WOL

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#22084

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by klaasnicolaas — APPROVED** [review]

**Comment by klaasnicolaas** [comment]
Strange.. why the PR says from`unknown repository`?

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Thanks, @dilruacs! Looks good! 👍 


> Strange.. why the PR says from`unknown repository`?

@klaasnicolaas because the fork was deleted from GitHub already.

**Comment by YRRK** [comment]
Is it possible to add the tv not as a mediaplayer but as deviceclass: tv. So you can change inputs and channels also in the homekit pass trough component. Or/also add something you can change the input from lovelace.

**Comment by klaasnicolaas** [comment]
@YRRK Please ask this kind of questions on the discord channel or community forum

**Comment by ghost** [comment]
> @YRRK Please ask this kind of questions on the discord channel or community forum
sorry typed in wrong browser tab.

**Pull request merged**
