### PR TITLE
Update caldav.markdown

### PR DESCRIPTION
**Pull request by nicx**
##  Proposed change

Update needed for PR https://github.com/home-assistant/core/pull/34584

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/34584
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Can you update your branch? I see a unrelated commit in this PR.

**Comment by nicx** [comment]
@klaasnicolaas hm this is my first PR, and I just update the caldav documentation with the Github GUI. Could you give me a hint what you mean with "unrelated PR"? Sorry for that ;)

**Comment by klaasnicolaas** [comment]
What you need to do is perform a rebase on your branch, because I see that your branch (`patch-1`) comes from the current branch. If you don't know how to rebase I can do it for you.

**Comment by nicx** [comment]
@klaasnicolaas that would be great, because I just checked it and I have no clue where to do that with the browser.

**Review by klaasnicolaas — DISMISSED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged 👍

**Review by frenck — APPROVED** [review]

**Pull request merged**
