### PR TITLE
Update switch.mqtt.markdown

### PR DESCRIPTION
**Pull request by Talentfrei87**
**Description:**

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
Hi there, 

Thanks for opening a PR, however, it lacks the explanation of what you are trying to do here.

I see some topics changed (🤷‍♂) and 3 unstyled non-connected lines of text added.

Could you please elaborate?

**Comment by Talentfrei87** [comment]
Hi there
I corrected the response of an EasyEsp switch / relay. And written a little help for integrating the controller.

**Comment by frenck** [comment]
That is not totally clear from the lines added. Could you please add a little bit of context? Place yourself in the mindset of a user who is new to this all...

**Review by Talentfrei87 — COMMENTED** [review]
This is the right Setup for the config.yalm and the right EasyEsp Setup config

**Comment by frenck** [comment]
That I get, that is not what I asked, I asked if you could add some additional text to your PR, so it is clear what the user is looking at.

Again, imagine a new user looking at this, he sees just a couple of lines, no clue what it is. We should guide new users. Please adjust.

**Comment by frenck** [comment]
PR is running stale, closing it.

**Pull request closed without merging**
