### PR TITLE
Update Lametric notifiy

### PR DESCRIPTION
**Pull request by PhilRW**
**Description:**
This documents home-assistant/home-assistant/pull/14414

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#14414

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by MartinHjelmare — DISMISSED** [review]
Thanks! Can be merged when parent PR is merged.

**Review by fabaff — DISMISSED** [review]
:bird:

**Comment by fabaff** [comment]
Points to the wrong branch.

**Comment by MartinHjelmare** [comment]
@PhilRW please rebase your branch on next, to not include other commits than yours.

**Comment by PhilRW** [comment]
Oops, didn't notice that.

**Review by MartinHjelmare — APPROVED** [review]
:tada:

**Pull request merged**
