### PR TITLE
Remove hashes in front of commands

### PR DESCRIPTION
**Pull request by Derkades**
On the website they look like commented lines:
image

### CODE REVIEW

**Comment by fabaff** [comment]
> On the website they look like commented lines:

Then the CSS needs to be adjusted. `#` and `$` are used to distinguish between commands which should be run as root and those for users.

**Comment by Derkades** [comment]
It makes sense to display them as comments for bash scripts. They are actually comments

**Review by frenck — APPROVED** [review]
Thanks, @Derkades! 👍 

@fabaff These are being removed for many reasons.
1) Copy/paste made easy.
2) Conflicts with Markdown rules MD014.
3) Is requested not to in our own developer docs.
4) Highlighting issues, as `#` in shell scripts are used as comments.
5) If `$` & `#` root/user? TBH if that is the indicator, the documentation around it is incomplete and unclear. Most of our user base will not know the difference.

**Comment by DubhAd** [comment]
@fabaff Looks like our own documentation standards on this were updated by Frenck last month - it's caught quite a few of us out having the standard reversed ;)

**Comment by frenck** [comment]
@DubhAd As explained to you in the other PR as well, this has been applied by me & @klaasnicolaas for quite some time now, and have been actively removing it from many places way longer already.

**Pull request merged**
