### PR TITLE
Add outputs, pipes, and playlists

### PR DESCRIPTION
**Pull request by uvjustin**
## Proposed change

Parent docs PR: https://github.com/home-assistant/home-assistant.io/pull/12163

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/31953
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by uvjustin** [comment]
Logo PR https://github.com/home-assistant/brands/pull/1610

**Comment by uvjustin** [comment]
@frenck Not sure how to get rid of the needs-rebase and in-progress labels, can you point me in the right direction?

**Comment by klaasnicolaas** [comment]
Add a link to the parent PR in our core repository

**Comment by klaasnicolaas** [comment]
This PR belongs to this one: https://github.com/home-assistant/home-assistant.io/pull/12163

**Review by frenck — APPROVED** [review]
Thanks, @uvjustin 👍

**Pull request merged**
