### PR TITLE
Add pi4 and pi4B boards to orangepi_gpio

### PR DESCRIPTION
**Pull request by drizzle1**
## Proposed change

updated for pi4 and pi4B boards

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/58392

- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by pascallj** [comment]
Please note that in this PR your other changes from the previous PR were dropped: https://github.com/home-assistant/home-assistant.io/pull/19956/files#diff-51d5cdfb03a69e09a7f4ab85ec000564d7cfd2b65ec28e951498a9a623d41ec1

**Comment by drizzle1** [comment]
Yes, sorry for the new PR, I had to create a new PR to escape from rebase
hell. Should be fine now, I've added my changes from previous PR.
Also, the opigpio dependency maintainer is going to add the new version
(0.5.2) to pypi.

**Comment by pascallj** [comment]
> Yes, sorry for the new PR, I had to create a new PR to escape from rebase hell.

Rebasing can be quite intimidating if you're not familiar with it. This also works.

> Should be fine now, I've added my changes from previous PR. Also, the opigpio dependency maintainer is going to add the new version (0.5.2) to pypi.

LGTM now. I'm not sure why the CI still fails. Doesn't seem to be caused by your changes.

Once the dependency has been released to PyPI, you can ask for the workflows to be re-run in the core PR and all should be good.

**Review by frenck — APPROVED** [review]
Thanks, @drizzle1 👍

**Pull request merged**
