### PR TITLE
Document new CDR functionality in asterisk_mbox

### PR DESCRIPTION
**Pull request by PhracturedBlue**
**Description:**
Document support for call data record lists (new asterisk_cdr platform) for the asterisk mailbox.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#11043

## Checklist:

  - [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`. 
  - [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by PhracturedBlue** [comment]
I've gotten no feedback on the original pull request since December 10...

**Comment by frenck** [comment]
Rebased the PR in order to fix the build.

**Review by frenck — DISMISSED** [review]

**Comment by frenck** [comment]
@PhracturedBlue Looks good!

Can be merged as soon as the parent PR get merged.

**Comment by frenck** [comment]
Closing this PR, since the parent PR has been closed. Feel free to re-open when ready.

**Pull request closed without merging**
