### PR TITLE
Update python logger link

### PR DESCRIPTION
**Pull request by liranbg**
Refer to python 3.7 (instead of 3.4) logger documentation

**Description:**

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by fabaff — APPROVED** [review]
Thanks

**Comment by klaasnicolaas** [comment]
Why not 3.8?

**Comment by fabaff** [comment]
> Why not 3.8?
 
Because 3.8 is still marked as `pre` in the Python documentation.

**Comment by liranbg** [comment]
> Why not 3.8?

Mainly because I saw in the documentation that python 3.7 is the recommended (atm) version to run hass with.

Since `https://docs.python.org/3/library/logging.html` refers to 3.8, I intentionally used the specified link of version 3.7 

I will let the authors decide

**Pull request merged**
