### PR TITLE
Add support for Ubee Router DVW32CB

### PR DESCRIPTION
**Pull request by seanvictory**
Tied with Home Assistant issue

## Proposed change

Informs users on the recent update to PyUbee, which allows users to connect to their Ubee Router DVW32CB. 

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/32406
- This PR fixes or closes issue: N/A

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
There are all kind of unrelated commits in this branch, please clean it up by doing a rebase. Thanks! 👍

**Comment by seanvictory** [comment]
@frenck Sure thing! Do you know how I would be able to do a rebase? Thanks for all of your help :)

**Comment by frenck** [comment]
@seanvictory Check out the you branch locally and rebase it onto the `next` branch locally.

For more information, a Google for "GitHub git rebase brand onto another branch" might help. E.g., result: <https://medium.com/@gabriellamedas/git-rebase-and-git-rebase-onto-a6a3f83f9cce>

If you run into trouble, we can do it for you as well. Please let us know in that case.

**Review by frenck — APPROVED** [review]

**Comment by seanvictory** [comment]
> @seanvictory Check out the you branch locally and rebase it onto the `next` branch locally.
> 
> For more information, a Google for "GitHub git rebase brand onto another branch" might help. E.g., result: https://medium.com/@gabriellamedas/git-rebase-and-git-rebase-onto-a6a3f83f9cce
> 
> If you run into trouble, we can do it for you as well. Please let us know in that case.

 @frenck Can you please do it for me as well? I'll start learning how to do it so it doesn't block me next time. Thank you again so much for your help and understanding :) I'm so excited to finally contribute to Home Assistant after 3 years!

**Comment by frenck** [comment]
I just did 😉

**Pull request merged**
