### PR TITLE
Correct command for installing node.js

### PR DESCRIPTION
**Pull request by forsberg**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by frenck** [comment]
I'm not sure about this one, `nvm install` should look into the requirements for stuff to install, not just `node`.

I've followed these steps myself a couple of times, but never ran into this one?

**Comment by forsberg** [comment]
Well, I'm a complete newbie in this whole nvm/node world, but I followed the instructions for installing nvm, and if I run just `nvm install` it just shows me the usage message.

```
$ nvm --version
0.33.8
```

**Comment by frenck** [comment]
`nvm install node` would install the latest version of node.
`nvm install` will look into the `.nvmrc` file in the root of the project for the version to install (and use).

I'm closing this PR, since adding it has consequences.

**Comment by forsberg** [comment]
Ah. There's the missing piece of information. In order for `nvm install` to do the right thing, you must be *inside* the home-assistant-polymer directory. This was not clear to me.

**Pull request closed without merging**
