### PR TITLE
Update installation-raspberry-pi-image.markdown

### PR DESCRIPTION
**Pull request by DavidDeSloovere**
Add info to customize. I had to search a few minutes to figure out how to change the keyboard layout. 

Add Windows 10 SSH in bash info. Maybe there should be a seperate page in the documentation, where all 'How to connect/SSH' topics link to. That way it won't have to be repeated throughout the docs.

### CODE REVIEW

**Comment by Landrash** [comment]
@DavidDeSloovere Tweaked it a bit since changing the password was in twice in the guide with your change. I'm uncertain about the SSH stuff on win 10 since it still requires installation off quite a lot of extras including half of a Linux OS in the back end. That's not really no third party tools.

**Comment by DavidDeSloovere** [comment]
I activated the 'Windows Subsystem for Linux' a few months back, I forgot how I had set it up and looked it up again.

From this page https://msdn.microsoft.com/en-us/commandline/wsl/install_guide

> In order to run Bash on Windows, you will need to manually:
> 
> Turn-on Developer Mode
> Enable the "Windows Subsystem for Linux (beta)" feature via the GUI §or the command-line)

Maybe in the future the developer mode won't be required. Who knows.

I have used putty before, but favor Bash on Windows. 
Found putty to be overwhelming with all to options.
Getting Bash on Windows does require a few steps, you are right about that, but it's pretty basic.

Bash on Windows it's an official part of Windows 10, supported by Microsoft and Canonical.
I'm excited about it, so I want people to now about it and use it :-)

**Comment by Landrash** [comment]
@DavidDeSloovere Reworked the mention a bit. Are you happy with this compromise?

**Comment by DavidDeSloovere** [comment]
Just changed the wording a bit, looks good to me now.

**Comment by Landrash** [comment]
Looks good 😊

**Pull request merged**
