### PR TITLE
Update switch.rfxtrx.markdown

### PR DESCRIPTION
**Pull request by Marcel030nl**
**Description:**
Code was not showing correctly. Trying <code> instead of 3 backticks.

Updated example descriptions.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

### CODE REVIEW

**Comment by Marcel030nl** [comment]
Thanks; updated with the raw-tag.

**Comment by Landrash** [comment]
There's currently a merge conflict with this file. Would you mind looking at this @Marcel030nl ?

**Comment by Marcel030nl** [comment]
I'm not an experienced GitHub user @Landrash. After the tip from @fabaff I've added the raw-tag en committed the change. As far as I'm concerned this can be merged.

https://github.com/home-assistant/home-assistant.github.io/pull/1394/commits/2ee71d94208aab7162376bc616e80cc81d139743

**Comment by Landrash** [comment]
Closed with https://github.com/home-assistant/home-assistant.github.io/commit/5ecf4e6909ec3af50d16477413c516477c7bd67b .
Credit to @Marcel030nl for changes in commit.

**Pull request closed without merging**
