### PR TITLE
Add InelNet central control unit integration documentation

### PR DESCRIPTION
**Pull request by mariusz-schimke**
## Proposed change

I'm adding a documentation file for those that have an [InelNet Internet central control unit](https://www.inel.gda.pl/en/offer/internet-central-control-unit.html) to control their home appliances, especially covers. **The documentation is not related to any 'integration' package as such.** It's just a set of predefined REST requests that you can paste into your Home Assistant configuration.yaml file to be able to control your covers, garage door, etc. by using the requests.

An InelNet unit is connected to a LAN and exposes an HTTP API. The documented REST requests cover the part of the API that allows sending control commands to appliances. The unit communicates unidirectionally with cover controllers (and possibly other appliances) by radio. It is manufactured by a Polish company named [Inel](https://www.inel.gda.pl/en/).

I wasn't sure of a few things though (since this is my first contribution):

- if a standalone integration document like this is acceptable, since it is not associated with any 'integration' package as such,
- what HA release (_ha_release_) to specify in the header if it's not strictly related to any version (it uses REST requests, so the first HA release that supports them would be okay),
- if I should put a link to this documentation file anywhere so it is searchable (I assume it's not necessary, but am not sure).

I also created another pull request here to add an icon and a logo for the documentation (and I assume that no other action like linking is required if I understood the guide correctly). I placed it in a directory that has the same name as the documentation file (_inelnet_).

Thank you!

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/3520
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @mariusz-schimke, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#23341).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by frenck** [comment]
This is not adding documentation for an integration, therefore is cannot be accepted as such.

**Comment by mariusz-schimke** [comment]
Okay, I understand now. But is there any proper place I could post it so others can use it?

**Comment by frenck** [comment]
You are free to share it on, for example, our community forums.

**Pull request closed without merging**
