### PR TITLE
Add closest_match function in template

### PR DESCRIPTION
**Pull request by stephanerosi**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#16199

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by frenck** [comment]
Hi @stephanerosi!

Thank you for adding this. Nevertheless, the PR is targeted against the wrong branch.
Documentation for features added in a `next` release, should go into the `next` branch. Your PR targets the `current` branch, which is incorrect.

Please change the target branch and rebase if needed.

**Comment by stephanerosi** [comment]
Ok, sorry, I'll rebase and update by PR

**Comment by stephanerosi** [comment]
Hi @frenck
It's done :-)

**Comment by frenck** [comment]
Thanks for the update @stephanerosi 👍 
Marked the PR ready for review.

**Review by DubhAd — APPROVED** [review]
👍

**Comment by frenck** [comment]
Closing this PR since the parent PR has been closed as well.

**Comment by frenck** [comment]
New parent appeared. home-assistant/home-assistant#16199

**Comment by frenck** [comment]
Closing this PR, since the parent PR has been closed.

**Pull request closed without merging**
