### PR TITLE
Remove the documentation for the ruter integration

### PR DESCRIPTION
**Pull request by ludeeus**
**Description:**

This removes the documentation for the `ruter` integration.

**Pull request in home-assistant (if applicable):**

home-assistant/home-assistant#26041

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

<a href="https://gitpod.io/#https://github.com/home-assistant/home-assistant.io/pull/10169"></a>

### CODE REVIEW

**Review by MartinHjelmare — DISMISSED** [review]
When we remove an integration, is the process to completely remove the docs too?

**Comment by klaasnicolaas** [comment]
I think that is the normal way, after all there has been a warning for a while that it is deprecated. Or do you have other ideas here about how it should be?

**Comment by MartinHjelmare** [comment]
I don't have specific ideas, but was thinking about what happens with old links to the removed docs page and if that should be handled.

**Comment by klaasnicolaas** [comment]
You have a very good point there. As far as I see, there are no links to the page on the doc website itself.

@ludeeus what do we do with the logo, do you remove it or do we keep it?

**Comment by ludeeus** [comment]
Forgot the logo, will update the PR later today.

**Review by MartinHjelmare — APPROVED** [review]

**Review by klaasnicolaas — APPROVED** [review]

**Pull request merged**
