### PR TITLE
fix broken images on all sleepiq components

### PR DESCRIPTION
**Pull request by requenym**
Corrected sleepiq logo file name on all sleepiq components.  Logo file already existed in correct location...

### CODE REVIEW

**Comment by robbiet480** [comment]
@requenym Congrats on completing 4 PR's in the month of October which means you have now qualified for the t-shirt! Doesn't mean you should stop submitting changes though 😄 Thanks! 🐬 🍪 💯!!!!

**Comment by requenym** [comment]
@robbiet480 I didn't even realize that was a thing.  Thanks for the heads up.

**Comment by robbiet480** [comment]
@requenym This warms my dark heart that you were editing for fun. Please make sure you sign up for Hacktoberfest so you get the sweet t-shirt. [More info is available on the blog.](https://home-assistant.io/blog/2016/10/02/hacktoberfest/)

**Comment by fabaff** [comment]
Well, this was already fixed in `next`.

**Pull request merged**
