### PR TITLE
Command line command is template for binary sensor and sensor

### PR DESCRIPTION
**Pull request by gjohansson-ST**
## Proposed change

Command is a template for `binary_sensor` and `sensor` in `command_line`

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by c0ffeeca7** [comment]
In future, could you reference the related section in the source code? It makes it easier for review:
- Are you referring to this section? https://github.com/home-assistant/core/blob/480b2ec84a16085092fb651699a3e8620a05fbf0/homeassistant/components/command_line/sensor.py#L221C1-L232C1
- If so, would it be correct to say that it is a string, but everything after the space can be a template?

**Review by c0ffeeca7 — CHANGES_REQUESTED** [review]
In future, could you reference the related section in the source code? It makes it easier for review:
- Are you referring to this section? https://github.com/home-assistant/core/blob/480b2ec84a16085092fb651699a3e8620a05fbf0/homeassistant/components/command_line/sensor.py#L221C1-L232C1
- If so, would it be correct to say that it is a string, but everything after the space can be a template?

**Comment by gjohansson-ST** [comment]
Yes. The arguments is a template while the command itself is not.

**Review by c0ffeeca7 — APPROVED** [review]
Thank you, @gjohansson-ST :+1:

**Pull request merged**
