### PR TITLE
Mention Dirigera in tradfri

### PR DESCRIPTION
**Pull request by ggravlingen**
## Proposed change

IKEA released an updated version of their gateway this week. I haven't tried it myself, but there are [reports](https://github.com/home-assistant/core/issues/80851) of it not working with Home Assistant (IKEA have probably, and hopefully, changed from COAP). I suggest we update the documentation and advise that there is no native support.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by VIKTORVAV99 — APPROVED** [review]
Until we get a working integration I think this is a good idea.

**Comment by ggravlingen** [comment]
@MartinHjelmare what's your take on this given that we've worked a lot on the code for the legacy gateway? Anecdotal evidence suggests people are successfully using the Homekit integration to use the new gateway. Should we perhaps mention that as well in these docs?

**Comment by MartinHjelmare** [comment]
I've also heard that homekit may work, but I don't think we should mention that until there's further information. It's not the same integration anyway.

**Review by MartinHjelmare — APPROVED** [review]

**Comment by ggravlingen** [comment]
> I've also heard that homekit may work, but I don't think we should mention that until there's further information. It's not the same integration anyway.

Thanks!

**Pull request merged**
