### PR TITLE
Update discord with embed information

### PR DESCRIPTION
**Pull request by popboxgun**
Update discord with embed information

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/44986
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Please rebase your `patch-2` branch to the `next` branch

**Review by frenck — CHANGES_REQUESTED** [review]
This PR contains unrelated commits. Please git rebase it onto the next branch in order to clean it up. 

Thanks 👍

**Comment by homeassistant** [comment]
Hi @matt-gnu, @Fietspomp86, @strelniece, @mendhak, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#16136).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by mendhak** [comment]
Hi @homeassistant , signed it.  Thanks.

**Comment by frenck** [comment]
As per discord, I'll pick this up.
Assigned myself.

**Review by frenck — APPROVED** [review]
Thanks, @popboxgun 👍

**Pull request merged**
