### PR TITLE
Update HomematicIP Cloud logo and change to cloud push type

### PR DESCRIPTION
**Pull request by worm-ee**
**Description:**
- Change logo to homematicip_cloud.png
- Change type to Cloud Push

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by frenck** [comment]
Shouldn't this go into the `current` branch?

**Comment by worm-ee** [comment]
Sorry, somehow I made the PR against the `next` branch by mistake. Should I make a new PR to `current`?

**Comment by frenck** [comment]
@mxworm, I was just checking, will handle that for you. No biggie.

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Thanks, @mxworm! 👍

**Pull request merged**
