### PR TITLE
Improves documentation with better example and link to algorithm

### PR DESCRIPTION
**Pull request by dgomes**
**Description:**

Improves documentation with better example and links

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

### CODE REVIEW

**Comment by frenck** [comment]
Rebased this PR in order to fix the build

**Review by frenck — DISMISSED** [review]

**Comment by frenck** [comment]
Looks good @dgomes! 🏅 
Can be merged as soon as the parent PR gets merged.

**Review by frenck — CHANGES_REQUESTED** [review]
@dgomes Merged conflicts appeared from the dark forests... could you please take a look? 👍

**Comment by dgomes** [comment]
My other pull request got accepted meanwhile and that caused the conflict. 

Merged accomplished 👍

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Awesome! Approved 🥇 

Can be merged as soon as the parent PR gets merged.

**Comment by dgomes** [comment]
@frenck I just realised the current PR does not depend on home-assistant/home-assistant#13075 anymore. I've since dropped the extra argument in favor of automation.

So this PR is now only an improvement to the existing documentation.

**Comment by frenck** [comment]
Because of the earlier merge, rebasing it onto `current` is kinda hard to do. So I'm going to merge this one into `next`, it will become current with the next release 😉

**Pull request merged**
