### PR TITLE
Enhance script choose action description

### PR DESCRIPTION
**Pull request by pnbruckner**
## Proposed change

There seems to be a lot of confusion around the new `choose` script action and how it can be used. This change enhances the description and provides more examples to hopefully make it clearer.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Maybe it is better to put the 3 examples in 3 separate code blocks? 🤔 Is it just me or are we actually missing a lot more information in the docs, such as what is described in the 113 release notes?

**Comment by pnbruckner** [comment]
I put the three `choose` examples into separate blocks.

> Is it just me or are we actually missing a lot more information in the docs, such as what is described in the 113 release notes?

What specifically do you think is missing? I may not have used the exact same examples, but what do you feel is not documented well enough?

FWIW, I kind of already feel like this page has changed from a reference manual to a novel. It's almost to the point where each type of action may need it's own page. At the very least, it might make sense to add a sort of table of contents to the top of the page???

**Comment by frenck** [comment]
> At the very least, it might make sense to add a sort of table of contents to the top of the page???

Adding a simple list on the top, linking to the separate heading anchors makes sense. We hope to have this automatically available on the short term. But for now, yeah that will do.

**Comment by pnbruckner** [comment]
So is this just waiting on @klaasnicolaas to elaborate on what he thinks is missing still?

**Comment by klaasnicolaas** [comment]
I will respond soon, today 😉

**Comment by klaasnicolaas** [comment]
I'm missing information about these 4 mode options. They are here and there, but don't see any clear information about what they stand for.

image

**Comment by pnbruckner** [comment]
@klaasnicolaas that information is here:

<https://www.home-assistant.io/integrations/automation/#automation-modes>

and here:

<https://www.home-assistant.io/integrations/script/#mode>
<https://www.home-assistant.io/integrations/script/#script-modes>

**Comment by klaasnicolaas** [comment]
In that case, forgot what I say and merge it 😄

**Review by frenck — APPROVED** [review]
Thanks, @pnbruckner 👍

**Pull request merged**
