### PR TITLE
HomeMatic support changes blog post

### PR DESCRIPTION
**Pull request by agners**
## Type of change

Add blog post to announce changes in HomeMatic support.

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
Looks good 👍

**Comment by agners** [comment]
@jens-maus the current RaspberryMatic add-on still has the experimental batch/bad security rating. Isn't that addressed with https://github.com/home-assistant/supervisor/pull/3421?

**Comment by jens-maus** [comment]
> @jens-maus the current RaspberryMatic add-on still has the experimental batch/bad security rating. Isn't that addressed with [home-assistant/supervisor#3421](https://github.com/home-assistant/supervisor/pull/3421)?

I didn't modify the `config.yaml` for the current stable release of the Add-on yet, but only for the development snapshot. And I am simply waiting for HomeAssistantOS 7.3 to be released as this seems to be another dependency. So https://github.com/home-assistant/supervisor/pull/3421 seems to be not the only thing that is required.

**Comment by jens-maus** [comment]
So please take this screenshot for the blog post:

ha-addon-step5a

**Comment by pvizeli** [comment]
The new supervisor is all ready on all devices. You can safe edit the yaml

**Comment by agners** [comment]
@jens-maus ok, 7.3 is on stable channel now: https://github.com/home-assistant/version/pull/200. I'll replace the screenshot.

**Comment by jens-maus** [comment]
> @jens-maus ok, 7.3 is on stable channel now: [home-assistant/version#200](https://github.com/home-assistant/version/pull/200). I'll replace the screenshot.

Perfect. doing my final tests and will adapt the stable config.yml of the Add-on then as soon as I have tested that everything is working nicely!

**Comment by agners** [comment]
:+1: 

Deployment preview of the post: https://deploy-preview-21527--home-assistant-docs.netlify.app/blog/2022/02/07/improved-homematic-support/

Let me know when you are ready then we can publish it.

**Comment by jens-maus** [comment]
> Let me know when you are ready then we can publish it.

Done! Everything works as expected with OS 7.3 and the stable RaspberryMatic add-on. Thanks a lot! Looking forward to see the blog post being published.

**Review by pvizeli — APPROVED** [review]

**Pull request merged**
