### PR TITLE
add documentation note for Q3D support in dsmr

### PR DESCRIPTION
**Pull request by Aeroid**
## Proposed change

Documentation note for Q3D support in DSMR integration

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: [#63669](https://github.com/home-assistant/core/pull/63669)
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by RobBie1221** [comment]
You should target `next` branch when making PR for new features.

**Comment by Aeroid** [comment]
> You should target `next` branch when making PR for new features.

That's the point where you lost me last time. ;-/  ... the advice went back and forth between two branches and was unable to rebase it. 

see https://github.com/home-assistant/home-assistant.io/pull/20389#issuecomment-974858365

Are you sure?

**Comment by RobBie1221** [comment]
See PR template:

I made a change to the existing documentation and used the `current` branch.
I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.

You are making changes for an upcoming version so `next` is the correct branch.

So you should do two things:
1. Change the target branch to `next`
2. Use git to rebase your branch `Aeroid:dsmrQ3D` to `next`

**Comment by Aeroid** [comment]
stuck in rebase ... is there a quick way thru the merge conflicts? ... sorry, this is also new to me.

**Comment by RobBie1221** [comment]
I think you broke it. You should rebase and force push changes. Perhaps it's easier to close this pull and create a new one where you start a branch from `next` instead of `current`.

**Comment by Aeroid** [comment]
> I think you broke it. You should rebase and force push changes. Perhaps it's easier to close this pull and create a new one where you start a branch from `next` instead of `current`.

think so to -> https://github.com/home-assistant/home-assistant.io/pull/21113

**Pull request closed without merging**
