### PR TITLE
Only run periodic GitHub Actions in main repository

### PR DESCRIPTION
**Pull request by davidjb**
## Proposed change

This limits the stale/lock GitHub Actions to running in the main repository (by checking the repository owner before executing) in order to prevent unnecessary action runs and prevent [intermittent failures](https://github.com/davidjb/home-assistant.io/actions/runs/1340726836) creating notifications when they fail.  In this example, periodic failures occur because the action causes my account to exceed a GitHub rate limit.

It is possible to [manually disable a workflow](https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow), but this requires contributors (forks) knowing these actions exist, that they run periodically, and how to disable them. 

In the unlikely situation that a forked repository wants or needs these actions to run, that fork can edit the relevant .yaml file.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: #19779 (added to appease probot)

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by davidjb** [comment]
Fwiw this needs to be open against `next` as this is the default GitHub branch so @probot-home-assistant isn't right in this case.

**Review by frenck — CHANGES_REQUESTED** [review]
This PR needs to target the `current` branch.

**Comment by davidjb** [comment]
@frenck Thanks for reviewing.  I've cherry-picked the commit onto `current` and adjusted the PR accordingly.

**Review by frenck — APPROVED** [review]
Thanks, @davidjb 👍

**Pull request merged**
