### PR TITLE
Update Smappee doc

### PR DESCRIPTION
**Pull request by bsmappee**
## Proposed change

Review documentation for Smappee integration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/36445
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/1707
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Please rebase your branch to the `next` branch and change the target branch to `next`.

**Comment by frenck** [comment]
This PR contains unrelated commits, please git rebase it onto the `next` branch. 👍

**Comment by klaasnicolaas** [comment]
@bsmappee I think you need some help with the rebase 😅 I can do it for you 😉

**Comment by bsmappee** [comment]
> @bsmappee I think you need some help with the rebase 😅 I can do it for you 😉

That would be nice!

**Comment by klaasnicolaas** [comment]
@bsmappee It's done 😉

**Review by frenck — APPROVED** [review]
Thanks, @bsmappee 👍

**Pull request merged**
