### PR TITLE
Update traccar configuration with added parameters

### PR DESCRIPTION
**Pull request by lapy**
Added scan_interval and monitored_conditions

**Description:**
Added scan_interval and monitored_conditions

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
There's one unrelated commit in this branch. Please rebase and remove that commit.

**Comment by lapy** [comment]
> There's one unrelated commit in this branch. Please rebase and remove that commit.

I am not able to rebase, I guess I would need to open a new PR.

**Comment by MartinHjelmare** [comment]
Yes, that's also ok.

**Comment by lapy** [comment]
Ok, PR #8618 created, I will close this. Thank you.

**Pull request closed without merging**
