### PR TITLE
Convert Nextcloud integration to use Brand media

### PR DESCRIPTION
**Pull request by meichthys**
## Proposed change

Removes the explicit reference to logo in favor of using the images in the Brand repository.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/30871
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/836
- This PR fixes or closes issue: N/A

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
There are unrelated commits in this PR. Could you please clean that up? Thanks 👍

**Comment by meichthys** [comment]
@frenck I'm not sure what happened here. Those other commits are old commits that i thought were already merged in https://github.com/home-assistant/home-assistant.io/pull/11780
I'm not sure how to clean this up :/

**Comment by frenck** [comment]
@meichthys The problem is you didn't create a new branch or your fork. You should create a new branch each time you start working on something new.

**Comment by meichthys** [comment]
Ok, Thanks for tolerating us noobs :)
Should i close this pull request and submit a new one on a new branch?

**Comment by frenck** [comment]
That is probably the fastest thing to do :)

**Pull request closed without merging**
