### PR TITLE
Update google_maps.markdown

### PR DESCRIPTION
**Pull request by costastf**
**Description:**

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#26361

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
There are many unrelated commits in here. You've probably based off an incorrect branch. Please rebase your PR onto the `next` branch. Thanks! 👍

**Comment by costastf** [comment]
Hi Franck, I used next as specified since the change should probably go
live with the next release after
https://github.com/home-assistant/home-assistant/pull/26361 gets accepted.
I am very confused though with the release process so any help is
greatly appreciated!

kind regards
Costas

**Comment by frenck** [comment]
@costastf That is correct, however, you started your branch of the `current` branch (I guess), effectively not only creating a PR for your change, but ending up creating a PR to merge all commits the `current` branch into `next` as well.

So if you create a branch targeting `next`, you should branch of `next`.

**Comment by costastf** [comment]
Got it, I did it straight from the github ui and current was default. i
think I did it correctly now.

**Pull request closed without merging**
