### PR TITLE
Troubleshooting Zigbee interference/coverage/range

### PR DESCRIPTION
**Pull request by Hedda**
## Proposed change

Add guidance to ZHA docs `current` branch for troubleshooting Zigbee interference which also relates to achieving a better setup for improved network coverage and range (e.i. well-known best practices for optimizing your environment for low-power/low-bandwidth 2.4GHz digital radio devices).

Based on approved/merged troubleshooting tips for Bluetooth https://www.home-assistant.io/integrations/bluetooth/#bluetooth-interference-with-other-devices from -> https://github.com/home-assistant/home-assistant.io/pull/23688 (which in turn was based on this zigpy wiki article that I wrote on this subject -> https://github.com/zigpy/zigpy/wiki/Generic-best-practice-tips-on-improving-Zigbee-network-range-and-general-stability ).

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes # https://github.com/home-assistant/home-assistant.io/issues/21565

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by homeassistant** [comment]
It seems that this PR is targeted against an incorrect branch since it has a parent PR on one of our codebases. Documentation that needs to be updated for an upcoming release should target the `next` branch. Please change the target branch of this PR to `next` and rebase if needed.

**Comment by homeassistant** [comment]
It seems that this PR is targeted against an incorrect branch since it has a parent PR on one of our codebases. Documentation that needs to be updated for an upcoming release should target the `next` branch. Please change the target branch of this PR to `next` and rebase if needed.

**Review by frenck — CHANGES_REQUESTED** [review]
You already had a PR open for this. Please close this PR and update the existing one instead.
Thanks 👍

**Comment by Hedda** [comment]
Hoping this will clean rewrite and will be easier for a fresh review. The previous one had not had a new review in over 6-months(!).

**Comment by frenck** [comment]
That is not how it works. Please update the previous PR instead and close this one, as requested. Thanks 👍

**Comment by igorsantos07** [comment]
But how does it work, then? A rewrite was requested multiple times, what the OP did - back in March, when you requested it the last time. Then, 6 or so releases have passed and the PR was mostly forgotten, even tagged as stale while waiting for a final review and merge - with multiple approval reactions.

This _is_ an important information for the community, as stated since the start, and something "ready" for more than a year now. Why delay even more those changes, bashing a contributor for trying to revive his additions with a new, cleaner PR?

In the meantime, people have to refer users to a _pull request_ to get actual instructions on how to do stuff with HA.

**Comment by puddly** [comment]
I believe the main issue with this PR is it does not follow the style of the rest of the Home Assistant documentation: it's just a nested list of facts, rather than a document you can read from beginning to end.  Lists nested down to *five* sublevels are not readable. It does, however, function as a very extensive outline for potential documentation.

Try to distill this to basic information that someone can glance at and follow, after skimming a subsection (e.g.`Network Troubleshooting` or something).

As a very rough example:

> If you are struggling to to join new devices or have regular network outages, make sure you are using a USB 2.0 extension cable to keep your coordinator away from USB 3.0 ports, SSDs, power supplies, motherboards, etc. They cause interference that significantly reduces the range of your network or outright prevents your coordinator from starting up.

And possibly:

> Zigbee relies on a mesh of always-powered devices to extend the range of your network. Most bulbs, outlets, custom-flashed USB sticks, etc. function as routers and do this. If you are unable to join devices far from your coordinator, you may be suffering from interference (see above) or are lacking routers in your network. Consider adding more mains-powered devices to your network.

---

Regarding a comment from the previous PR:

> is it not better to add this 'as-is' now and then let someone rewrite parts of it in a new PR?

I understand and appreciate the intent of the PR but this is *not* a maintainable approach for either code or documentation. Unless the original PR is in a readable form, it's likely *not* ever going to be rewritten or fixed by anyone else.

---

Again, I understand the intent: people regularly do suffer from these same network problems that can easily be fixed by a simple USB 2.0 extension cable or another Zigbee router.  I won't be able to rewrite an entire PR, but if you have any specific questions about prose, feel free to tag me and I will do my best to help.

**Comment by Hedda** [comment]
> I believe the main issue with this PR is it does not follow the style of the rest of the Home Assistant documentation: it's just a nested list of facts, rather than a document you can read from beginning to end. Lists nested down to _five_ sublevels are not readable. It does, however, function as a very extensive outline for potential documentation.
> 
> ...
> 
> I understand and appreciate the intent of the PR but this is not a maintainable approach for either code or documentation. Unless the original PR is in a readable form, it's likely not ever going to be rewritten or fixed by anyone else.

@puddly Well at least this newly rewritten PR follows the same format accepted for the Bluetooth integration documentation, see -> https://www.home-assistant.io/integrations/bluetooth/#bluetooth-interference-with-other-devices

Yes it is a long list of facts but does it not do more harm to new users not having anything about this in the documentation at all?


> That is not how it works. Please update the previous PR instead and close this one, as requested. Thanks 👍

@frenck The old PR was locked by github-actions bot so I can not reopen that old PR myself, please see -> https://github.com/home-assistant/home-assistant.io/pull/18864

image

**Comment by frenck** [comment]
> But how does it work, then? A rewrite was requested multiple times, what the OP did - back in March, when you requested it the last time. Then, 6 or so releases have passed and the PR was mostly forgotten, even tagged as stale while waiting for a final review and merge - with multiple approval reactions.

I explained it well above.

> @frenck The old PR was locked by github-actions bot so I can not reopen that old PR myself, please see -> https://github.com/home-assistant/home-assistant.io/pull/18864

Happy to reopen that one, you shouldn't have closed it to being with.

edit: unlocked.

**Comment by nawwman** [comment]
Can you just implement any one of these PRs to the documentation? While it's certainly quite some info to process for a new user, what is even worse for new users is NOT having this basic information in the documentation for troubleshooting purposes so they can learn new things and investigate. I had to find these PRs via searching through the forum. Whatever you think about the readability, it's more difficult for users to find random PRs through the forum rather than just having it plain in the documentation

**Comment by frenck** [comment]
@Hedda No response. I've re-opened the previous PR as per above (even though I unlocked it, you didn't re-open, which I've done now. I'm closing this one.

**Pull request closed without merging**
