### PR TITLE
Add select platform to Motionblinds BLE

### PR DESCRIPTION
**Pull request by LennP**
## Proposed change

Add select platform to Motionblinds BLE

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/114228
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by c0ffeeca7** [comment]
Could you add a bit of documentation on how the select platform is used?
It looks like unless it's curtain or vertical type, you can select between 3 speed levels, low, medium, or high.

**Comment by LennP** [comment]
> Could you add a bit of documentation on how the select platform is used?
> It looks like unless it's curtain or vertical type, you can select between 3 speed levels, low, medium, or high.

Same as the sensors:

The current documentation already contains information on this and mentions you can change the speed for certain blinds.

```
## Setup

During the setup of a Motionblinds BLE device, you will be asked what kind of blind your Motionblind is. There are 8 different blind types:

- **Roller blind**: has the ability to change position and speed.
- **Honeycomb blind**: has the ability to change position and speed.
- **Roman blind**: has the ability to change position and speed.
- **Venetian blind**: has the ability to change position, tilt, and speed.
- **Venetian blind (tilt-only)**: has the ability to change tilt and speed.
- **Double Roller blind**: has the ability to change position, tilt, and speed.
- **Curtain blind**: has the ability to change position. May need to be calibrated if the end positions are lost, which can be done by using the open/close cover button or the set cover position slider. This will trigger a calibration which will first make the curtain find the end positions after which it will run to the position as indicated by the command that was given.
- **Vertical blind**: has the ability to change position and tilt. May need to be calibrated if the end positions are lost, which has to be done using the Motionblinds BLE mobile app.
```

**Review by c0ffeeca7 — DISMISSED** [review]
Thank you, @LennP :+1:

**Comment by LennP** [comment]
> Thank you, @LennP 👍

Thank you too. I included more information about the select as I also did for the sensors.

**Review by c0ffeeca7 — APPROVED** [review]
Nice! Thank you, @LennP :+1:

**Pull request merged**
