### PR TITLE
Add LedSC integration documentation

### PR DESCRIPTION
**Pull request by PatrikKr010**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/116957
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/5443
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by PatrikKr010** [comment]
[Add icon pull request](https://github.com/home-assistant/brands/pull/5443)

**Comment by PatrikKr010** [comment]
> It seems that this PR is targeted against an incorrect branch. Documentation updates which apply to our current stable release should target the `current` branch. Please change the target branch of this PR to `current` and rebase if needed. If this is documentation for a new feature, please add a link to that PR in your description.

Hello, I added a link to the [PR](https://github.com/home-assistant/core/pull/116957) for the new integration

**Comment by c0ffeeca7** [comment]
Hi @PatrikKr010 
Thank you for your contribution. As this is a new documentation page, related to a new integration, you need to add the header information, as described in the [documentation on creating a new page](https://developers.home-assistant.io/docs/documenting/create-page/). Please add a title, description, ha_release, ha_category, etc.

**Comment by PatrikKr010** [comment]
@c0ffeeca7 
Done

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
