### PR TITLE
Update modbus configuration to use new 

### PR DESCRIPTION
**Pull request by janiversen**
## Proposed change

Update documentation to reflect the new modbus configuration.

Moved the platform pages into the modbus (integration) page, since this is a list of integrations.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 

https://github.com/home-assistant/core/pull/46591

- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by frenck** [comment]
Is this related to a parent PR?

**Comment by janiversen** [comment]
yes #46591 I wrote that above but did not make a link, sorry for that. I have updated the text

**Comment by janiversen** [comment]
Update to reflect documentation error, that was already merged in current.

**Review by frenck — APPROVED** [review]
Thanks, @janiversen 👍

**Pull request merged**
