### PR TITLE
Specify that only the owner can set analytics settings

### PR DESCRIPTION
**Pull request by hmmbob**
## Proposed change

Added a small note that only the _owner_ user can set the analytics setting.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @hmmbob 👍

**Comment by partneroid-zz** [comment]
https://github.com/home-assistant/frontend/pull/8842 from yesterday removed the owner guard while this PR adds (to docs) its required so if i'm not completely lost here this change should be now reverted?

**Comment by hmmbob** [comment]
Yes, I guess those crossed paths. As the fix hasn't been released yet (as far as I can see it was tagged for 2021.4.1 but not actually added to that release) we should keep this in for now - I'll revert the change as soon as the fix is released.

**Comment by partneroid-zz** [comment]
FYI https://github.com/home-assistant/home-assistant.io/pull/17367

**Comment by hmmbob** [comment]
Thinking a bit more about it, I disagree with removing it but I left the comment in the other PR you just linked.

**Pull request merged**
