### PR TITLE
Fix typos in Remote Access section

### PR DESCRIPTION
**Pull request by pixelasticity**

### CODE REVIEW

**Comment by Landrash** [comment]
@pixelasticity Sadly enough there was two pull request for similar changes. Feel free to resolve this conflict and I'll merge this. (Trying to merge these in the order they come in)

**Comment by pixelasticity** [comment]
@Landrash I'd be happy to resolve, but I can't seem to find conflict markers.

**Comment by robbiet480** [comment]
@Landrash @pixelasticity Resolved the conflict. Will leave it to @Landrash to merge.

**Comment by Landrash** [comment]
Thank you @pixelasticity for the find and @robbiet480 for the fix!

**Pull request merged**
