### PR TITLE
Correct 'play_media' to 'media_play'.

### PR DESCRIPTION
**Pull request by jeremysv**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

### CODE REVIEW

**Comment by frenck** [comment]
@jeremysv, thank you for this PR! 🏅

**Comment by MartinHjelmare** [comment]
`play_media` is also a service.

**Comment by frenck** [comment]
@MartinHjelmare What is your suggestion? Since the change proposed here does fit in the context of the location where it was changed.

**Comment by MartinHjelmare** [comment]
It's fine. Missed the categorization.

**Pull request merged**
