### PR TITLE
Update motion_blinds.markdown

### PR DESCRIPTION
**Pull request by kmikiy**
This integration also works with Smart Home blinds (rebranded Dooya blinds). https://www.smart-home.hu

## Proposed change

I added an additional brand to the documentation of the Motion Blinds integration that is supported. I've been using the version of the Motion Blinds integration that's in this PR (https://github.com/home-assistant/core/pull/50067) for a couple months now and it has been working without any issues.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @kmikiy, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#19054).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by starkillerOG** [comment]
Thanks, nice to hear that it is also working with Smart Home blinds!
This PR looks good to me

**Comment by frenck** [comment]
This PR can't be merged, as it depends on the parent PR linked in the description.
Therefore, this PR should be targeting the `next` branch and coupled with the parent PR listed.

**Comment by starkillerOG** [comment]
@frenck Actually I split up that big PR listed in the discription and now that https://github.com/home-assistant/core/pull/55710 has already been merged, the documentation can be updated.
I made a new PR here to target the next branch: https://github.com/home-assistant/home-assistant.io/pull/19435

**Comment by kmikiy** [comment]
Just to be clear, Smart Home blinds should work with the version on the `current` branch. I used the version in the PR because I have UDP multicast issues and that PR has polling option implemented

**Comment by frenck** [comment]
Thanks for clearing that up @kmikiy 👍

**Review by frenck — APPROVED** [review]

**Pull request merged**
