### PR TITLE
Fixing typos in Google Assistant documentation

### PR DESCRIPTION
**Pull request by hmmbob**
Fixed typos in description how to migrate to 0.80. No changes in information/workflow.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by hmmbob** [comment]
Huh? What did I do that it know says “Hmmbob wants to merge 9 commits”? I just changed one file with 2 typos....

**Comment by klaasnicolaas** [comment]
You must rebase and merge it into `current`

**Comment by hmmbob** [comment]
> You must rebase and merge it into `current`

Thanks, but it is not meant for current but for 0.80 AND I’ve only done things via the Github website. Probably I shouldn’t have?

**Comment by klaasnicolaas** [comment]
You are right, can not really explain why you get this now

**Review by frenck — CHANGES_REQUESTED** [review]
Please rebase.

**Comment by frenck** [comment]
@hmmbob You can use the GitHub edit function, you'll just make to make sure you are looking that the right base branch before you hit edit.

Please rebase this PR onto the `next` branch.

**Comment by hmmbob** [comment]
I am on the road working from my iPad, but @frenck offered to help and rebase :)

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Rebased. Awaiting build results...

**Comment by frenck** [comment]
Thanks for the PR @hmmbob!

Happy Hacktoberfest 🎉 

../Frenck

**Pull request merged**
