### PR TITLE
Fix Raspberry model to be consistent in docs

### PR DESCRIPTION
**Pull request by vzahradnik**
**Description:**
In the Getting Started guide you recommend RPi 4 as a suggested hardware; however, in description you mention the older RPi 3 B+ model. I fixed the description to match with the rest of page.

I created the PR against the ```next``` branch, because it is not critical. If you suggest to create it against ```current```, I can do that as well.

**Related Pull request:** #11516

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Can you please rebase this to the `current` branch?

**Comment by vzahradnik** [comment]
@klaasnicolaas sure, I can rebase that. Just a few practical questions:
- At the end of release cycle, do you merge changes from ```next``` into ```current```? I.e. will my commit into ```current``` survive the release cycle or the next branch will become new current?
- Can I change this pull request to point to another branch or should I close it and create a new one?

Thanks!

**Comment by vzahradnik** [comment]
@klaasnicolaas I created PR #11516 with the same change against ```current```. Please use whatever PR you want and close the rest. The change is exactly the same. Thanks!

**Comment by klaasnicolaas** [comment]
@vzahradnik ofcourse it will survive 😄 At the end `next`/`rc` will be merged into `current`. We only have a few rules about which PRs belong in a `next` branch and which in the `current`.

**Comment by vzahradnik** [comment]
@klaasnicolaas thanks for clarifying up, it will be helpful for me in the future.

**Pull request closed without merging**
