### PR TITLE
Added docs for state attributes in Dyson fan

### PR DESCRIPTION
**Pull request by soraxas**
**Description:**
Added descriptino of the newly added state attributes in dyson fan devices.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#15716

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
Needs rebase.

**Comment by frenck** [comment]
@soraxas Thank you for the PR.
Documentation for a new platform, component and/or features should target the `next` branch.
Please rebase your PR.

**Comment by soraxas** [comment]
Apology for that! I initially thought this counts toward *fixes, changes, and adjustment*, but completely overlooked this as *new features*. Thanks for letting me know, will rebase it soon.

**Comment by frenck** [comment]
@soraxas I understand the confusion.
If the code base changes, it will be staged for the `next` release right? As in, changing the `current` documentation would cause the documentation to not match 😉

**Comment by soraxas** [comment]
Hi! Is this approach correct? I rebased only my commit onto `next` and force pushed it. It's my first time rebasing PR so let me know if it's incorrect. Thanks! :)

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Approved. Can be merged as soon as the parent PR gets merged.

**Pull request merged**
