### PR TITLE
Document credentials update for Enphase Envoy

### PR DESCRIPTION
**Pull request by catsmanac**
## Proposed change

HA PR #110474 enables credentials update by adding another Envoy integration with the envoy IP and updated credentials. This PR adds the description for this to the documentation. 

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/110474
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by catsmanac** [comment]
Did I mess this one up?

**Comment by klaasnicolaas** [comment]
Yep you did 😉 You need to rebase the branch to the `next` branch.

**Comment by catsmanac** [comment]
Ah ok,  my track record on rebase is really, really poor. I'll give it a try, hope I don't make it worse. Sorry for the trouble.

**Comment by catsmanac** [comment]
making it worse rather then improving. Canceling this one.

**Pull request closed without merging**
