### PR TITLE
Default port for MariaDB 10 is 3306

### PR DESCRIPTION
**Pull request by jeffh0821**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Well this change is not true.

MariaDB 10 = 3307 and MariaDB 5 = 3306

**Comment by jeffh0821** [comment]
The documentation says otherwise and the default port on the MariaDB 10.x official docker containers is 3306.
https://mariadb.com/kb/en/library/connecting-to-mariadb/

**Comment by fabaff** [comment]
I don't think that they changed the port between the releases. The default port is 3306 as far as I know.

**Comment by klaasnicolaas** [comment]
https://forum.synology.com/enu/viewtopic.php?t=90966&start=30

Today I have set the recorder component in my config and I used 3307 as port for my MariaDB on the synology NAS. I added that piece of text in the past because I noticed that a port number had to be added.

Edit:
Just tested port 3306 and I get the message that Home Assistant can no longer connect to the database, in my case I have to use port 3307 for connecting to my MariaDB 10 database.

**Comment by jeffh0821** [comment]
Your reference article is specific to a parallel installation of MariaDB 5 and MariaDB 10 which would require independent ports. However, MariaDB documentation and docker images are all adhering to the standard MariaDB port of 3306. The HA page that I am attempting to correct is wrong and likely specific to your implementation only. It causes unneeded confusion and issues. Unless there is MariaDB official documentation stating that the default port in MariaDB changed from 3306 to 3307, the PR should be approved.

**Comment by jeffh0821** [comment]
Or the PR should be rejected and the documentation should be corrected to clarify the default port MAY be overridden in certain-use cases. In either case, we SHOULD NOT be documenting that the MariaDB 10.x default port is 3307 as it clearly is not.

**Comment by klaasnicolaas** [comment]
That is a better option, I think the 3306 is the default, but it may be that you have to use 3307 if it turns out that you still get a `can not connect to mysql database` error.

In any case, I had to approach my Synology NAS and my Hosting provider via 3307, 3306 results in an error.

I'll see what Synology does at MariaDB 5

**Comment by klaasnicolaas** [comment]
MariaDB 5 and 10 side by side on the Synology
photo

**Comment by jeffh0821** [comment]
I still don't think you understand that YOUR implementation is not typical and it is YOUR implementation of MariaDB that requires port 3307.

All MariaDB versions use port 3306 as default. Other ports MAY be used based on the requirements of the implementation. It is not relevant how it is setup on your Synology NAS.

I will close the PR and do a new one.

**Comment by klaasnicolaas** [comment]
YES I know what you mean 😉 

And YES also the setup on a synology or third parties is important. It's fine that the port is changed to 3306 if that is the default. There should only be a note that the port can also be different, Before people will open an issue because the port for them also was not correct 😉

**Pull request closed without merging**
