### PR TITLE
Adds documentation for Kodi discovery

### PR DESCRIPTION
**Pull request by escoand**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#13790

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by frenck — DISMISSED** [review]

**Comment by frenck** [comment]
Thanks, @escoand, looks good 👍 

Can be merged as soon as the parent PR gets merged.

**Comment by escoand** [comment]
The parent PR got merged.

**Comment by frenck** [comment]
Thanks for the ping @escoand!

**Comment by frenck** [comment]
Rebased the PR in order to fix the build issue on Netlify.
Awaiting build results.

**Review by frenck — APPROVED** [review]

**Pull request merged**
