### PR TITLE
Remove removed config option for Google Assistant

### PR DESCRIPTION
**Pull request by SNoof85**
## Proposed change

Remove removed config option.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by frenck** [comment]
In which parent PR has this been removed?

**Comment by SNoof85** [comment]
I didn't looked for it, but it stated in the doc it'll be removed in 0.105.
Or you prefer not to remove because some could still use 0.105

**Comment by frenck** [comment]
The documentation reflects the code base, according to the codebase, this configuration option still exists.

**Comment by SNoof85** [comment]
As you want 👍

**Pull request closed without merging**
