### PR TITLE
Sound mode support

### PR DESCRIPTION
**Pull request by starkillerOG**
**Description:**
Add documentation for sound mode support

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#14910

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by frenck — APPROVED** [review]
The docs look good @starkillerOG! Thank you.

✅ Approved. Can be merged as soon as the parent PR gets merged.

**Review by frenck — CHANGES_REQUESTED** [review]
Docs need to be updated with the latest changes from the parent PR. @starkillerOG, could you take a look?

**Comment by starkillerOG** [comment]
@frenck was allready working on it.
Can you look at the new text I wrote?

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Made some really small tweaks.

✅ Approved. Can be merged as soon as the build passes.

**Pull request merged**
