### PR TITLE
Ezviz Documentation

### PR DESCRIPTION
**Pull request by RenierM26**
New pull request adds config_flow. 
The documentation references services that doesn't exist in the integration.  - Removed sections that refer to the services.

## Proposed change

There is an open pull request that adds config flow to this integration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [X] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/45722
- Link to parent pull request in the Brands repository: N/A. The logos are already there.
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
Please rebase your branch on latest `next` branch.

**Comment by MartinHjelmare** [comment]
It may be easier to start over in a fresh branch based off next branch. The rebase didn't work cleanly. Unrelated commits are still present.

**Comment by RenierM26** [comment]
Can I just delete this branch? I think it might close this Documentation PR. 

If I then create a new one then we'll need to update the documentation url reference in the code pull request?

**Comment by RenierM26** [comment]
Looks like I can still edit it? Just don't want to cause any more problems.

**Comment by RenierM26** [comment]
New documentation pull request : https://github.com/home-assistant/home-assistant.io/pull/17364

 @MartinHjelmare, 
Really sorry for the inconvenience and any extra work caused by this mistake.

**Comment by MartinHjelmare** [comment]
Good, thanks! No worries.

**Pull request closed without merging**
