### PR TITLE
Add wait_for_trigger script action

### PR DESCRIPTION
**Pull request by pnbruckner**
## Proposed change

Add documentation for new `wait_for_trigger` script action. Also update `delay` descriptions.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: home-assistant/core#38075
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by pnbruckner** [comment]
Need to add description of `wait` variable.

**Comment by frenck** [comment]
@pnbruckner, the parent is merged, what is the state on this PR?

**Comment by pnbruckner** [comment]
@frenck I was waiting for a couple of other doc PRs to get merged that affected the same doc page so I could finish this up, which I will do today.

**Comment by frenck** [comment]
@pnbruckner Don't rush! I was just checking if this was still on the radar 👍

**Review by frenck — APPROVED** [review]
Awesome, thanks 👍

**Pull request merged**
