### PR TITLE
Add locate feature

### PR DESCRIPTION
**Pull request by dshokouhi**
**Description:**

Locate feature was missing from the list so it is now added.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by ludeeus** [comment]
Also added in this <https://github.com/home-assistant/home-assistant.io/pull/6036>

**Comment by dshokouhi** [comment]
@ludeeus yes I added it in both places to ensure that the locate feature shows up in `current` and the upcoming additons get added with `next` once the PR merges.  Should I just close this one in favor of #6036?

**Comment by ludeeus** [comment]
@dshokouhi I swear that both said `next` earlier....
_never mind me_ :D

**Comment by dshokouhi** [comment]
@ludeeus no worries :)

**Comment by fabaff** [comment]
Yeah, this one is not needed as the changes made with #6036 will be available if the feature #16035 is released.

**Pull request closed without merging**
