### PR TITLE
correct typo

### PR DESCRIPTION
**Pull request by Mariusthvdb**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by bdr99** [comment]
This PR should target the `current` branch, not `next`, since it is not specifically related to an upcoming version of Home Assistant.

**Comment by Mariusthvdb** [comment]
Yea it is.
It is targeted against next?
Functionality isn't even working in dev yet... ;-)

**Comment by bdr99** [comment]
> Yea it is. It is targeted against next? Functionality isn't even working in dev yet... ;-)

My apologies, you're correct. I didn't realize this was a new feature that hadn't been merged to `current` yet.

**Comment by Mariusthvdb** [comment]
hehe, thanks.
I have to correct my own statement on the functionality: it is actually working nicely, I made a user error in the config.

doesn't matter for this small typo correction though

**Review by balloob — APPROVED** [review]

**Pull request merged**
