### PR TITLE
Update August integration presence detection example docs

### PR DESCRIPTION
**Pull request by sbressler**
## Proposed change
Be explicit about where the example goes (automations.yaml). It took me a while to figure this out, being new to HASS. Probably super obvious to any regulars...

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue:

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
Your PR seems to be based on the `next` branch. Please rebase the PR to clean it up. (Oh, and please provide a proper title on this PR).

**Comment by sbressler** [comment]
Fixed I think?

**Comment by frenck** [comment]
Since this is a change to the documentation of our current release, it needs to target the `current` branch, so the target branch was right.

Your PR was based on the `next` branch, which caused the issue. You need to rebase the PR onto the `current` branch (using a git rebase locally).

If you need any help on that, please let me know.

**Review by frenck — APPROVED** [review]
Thanks, @sbressler! 👍

**Comment by sbressler** [comment]
> Since this is a change to the documentation of our current release, it needs to target the `current` branch, so the target branch was right.
> 
> Your PR was based on the `next` branch, which caused the issue. You need to rebase the PR onto the `current` branch (using a git rebase locally).
> 
> If you need any help on that, please let me know.

Sorry I never got around to rebasing!

**Pull request merged**
