### PR TITLE
adjust proximity breaking change message

### PR DESCRIPTION
**Pull request by mib1185**
## Proposed change

Adjust the breaking change message according to #31236 and https://github.com/home-assistant/core/pull/109630

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/109630
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Review by frenck — CHANGES_REQUESTED** [review]
Oh wait, this PR is targeting an incorrect branch.

Please target the `next` branch.

**Comment by mib1185** [comment]
but `next` does not contain the `2024-02-07-release-20242.markdown`, yet ... or did i oversee it

**Review by frenck — APPROVED** [review]
🤦  You are right... time for me to call it a day 😬 

✅ Approved. Can be merged as soon as the parent PR gets merged.

../Frenck

**Comment by mib1185** [comment]
i think you heavily deserve it 😁

**Pull request merged**
