### PR TITLE
Add Home Assistant API example to RESTful command description

### PR DESCRIPTION
**Pull request by ronschaeffer**
I cannot find this type of example documented anywhere else in the manual, and the few examples on the forum are incorrect.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
Hi @ronschaeffer, 

Thanks for the PR. Nevertheless, I'm wondering why one would ever do this / use this method?
This is in Home Assistant right? You'd just change states of things directly?

../Frenck

**Comment by ronschaeffer** [comment]
Hi @frenck -
Have I overlooked a simpler way of achieving my goal? I want to set the state of an entity, for example to on from off, without also executing the associated action.

The use case is to set a light with an assumed state to on or off when it is controlled from the wall switch instead of through HA. I use other methods to track the state of the light through a binary sensor, and use the binary sensor state change as a trigger for an automation to change the state of the light in the frontend to match its actual state. (Hope that sentence makes sense!)

According to manual https://www.home-assistant.io/docs/configuration/state_object/, "if you overwrite a state via the states dev tool or the API, it will not impact the actual device." As far as I can find, the manual does not mention an alternative method within HA of changing just the state without executing the associated action.

This use of RESTful commands could be applied to any object with an assumed state, especially those for which you can use other methods to know the actual state.

**Comment by arsaboo** [comment]
@ronschaeffer Isn't using the REST command the same as executing the action? I agree with @frenck that this may not be the right use case.  

Also, other than using the long_lived_token, the REST command is like any other REST command. Thus, I am not sure if we need it.

**Comment by frenck** [comment]
Thanks for the PR and detailed explanation @ronschaeffer, nevertheless, we are going to friendly decline it for the earlier stated reasons.

Again, thanks, since opening a PR is really appreciated 👍

**Comment by ronschaeffer** [comment]
@arsaboo In this case, it's not the same as performing the action. It's about setting the state without performing the action. Unless I've missed it, a rest command or a shell command with curl are the only ways to automate/script that within HA. There are a few threads on the forum where people are looking for ways to do that. The main point here, though, was to show how to use the long-lived access token with the rest command. I couldn't find it documented anywhere else. Maybe there is a better location in the manual?

**Comment by fabaff** [comment]
The [REST API](https://developers.home-assistant.io/docs/en/external_api_rest.html) documentation should describe the usage.

**Comment by ronschaeffer** [comment]
OK @fabaff . Raised a PR over there https://github.com/home-assistant/developers.home-assistant/pull/194. Can close that one if you guys think this is too much of an edge use case, but it would have saved me a world of trial and error pain following incorrect or outdated advice in the forum.

**Pull request closed without merging**
