### PR TITLE
Renamed telegram files (#10489)

### PR DESCRIPTION
**Pull request by marcelherd**
**Description:**
Fixes issue #10489 hopefully

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
There are merge conflicts in this PR, could you please resolve them?

**Comment by marcelherd** [comment]
@frenck The resolve conflicts button is greyed out for me, how do I go about resolving them?

**Comment by frenck** [comment]
You need to merge the current branch manually/locally on your computer (or rebase and resolve the conflicts that way).

**Comment by marcelherd** [comment]
Oh I'm sorry, it says theres like 1500+ changed files, I really don't know howto fix this

**Comment by frenck** [comment]
I'll take a look later today, don't worry :+1:

**Comment by frenck** [comment]
@marcelherd I have tried in a couple of ways to salvage this PR (rebasing, merging, etc), but did not manage to do so. I'm sorry to say, it has to be redone/re-applied on a fresh branch.

This is caused by a big migration I did yesterday, I hope you will accept my sincere apology for this.

**Comment by marcelherd** [comment]
@frenck Should I rename the existing redirects

`/components/polling /integrations/polling` to `/components/polling /integrations/telegram_polling`

Or add a new rule?

`/integrations/polling /integrations/telegram_polling`

**Comment by frenck** [comment]
@marcelherd, this PR can be closed and should be build up fresh. The new URL structure uses `/integrations/` instead of `/components`. 
We redirect the "old" `/components/` urls to the newer versions.

**Pull request closed without merging**
