### PR TITLE
Integration Input_number: Attribute step is relevant for both modes.

### PR DESCRIPTION
**Pull request by edenhaus**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: home-assistant/frontend#5302
- This PR fixes or closes issue: #12470 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by edenhaus** [comment]
I was not sure, what exactly you mean by parent and so I linked the frontend pull request as parent. If this was wrong, please correct it.

**Review by bramkragten — APPROVED** [review]

**Review by frenck — CHANGES_REQUESTED** [review]
This PR needs to target the `next` branch, as the parent PR is pending for the `next` release of Home Assistant.

Please change the target branch to `next` and rebase if needed. Thanks 👍

**Comment by edenhaus** [comment]
@frenck Are you sure about the `next` branch? The parent pull request fixes only that the attribute step is always shown and not only if you select slider. The attribute step is also relevant for the box mode in the current and older version of home assistant, so we should adjust the docs independent. It was my fault to link them together.

**Review by frenck — APPROVED** [review]
✅  Thanks for clarifying @edenhaus 👍

**Pull request merged**
