### PR TITLE
Simplify the Hyperion documentation to reflect the new configuration flow

### PR DESCRIPTION
**Pull request by dermotduffy**
## Proposed change

Simplify the Hyperion documentation to reflect the new configuration flow.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/42104
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @dermotduffy 👍

**Comment by dermotduffy** [comment]
@frenck Oh oh, my apologies. Whilst the parent PR was merged, in the codereview process we decided to merge it into a custom branch (`add-hyperion-config-options-flow`) rather than `dev` as the work ended up being split into a few different PRs. Most of that work is done, but there are two outstanding PRs that have to be reviewed (https://github.com/home-assistant/core/pull/42945 and and https://github.com/home-assistant/core/pull/42960 ) that I was hoping to get merged in, before the merge of `add-hyperion-config-options-flow` into `dev`.

I should have listed this documentation PR on those sub-PRs, my apologies.

Not sure what the protocol here is. I suppose the safest is to roll it back and I can re-submit a new doc PR along with the branch merge PR?

**Comment by frenck** [comment]
I'm rolling it back. Please open a fresh PR and link it to the main PR.

**Comment by dermotduffy** [comment]
Will do. Thank you @frenck .

**Pull request merged**
