### PR TITLE
Introduce the check_config script in 0.27

### PR DESCRIPTION
**Pull request by kellerza**

### CODE REVIEW

**Comment by robbiet480** [comment]
Thanks! 🐬 🍪 💯

**Comment by robbiet480** [comment]
Oh wait, why is this merging to `current` and not `next` @fabaff?

**Comment by fabaff** [comment]
I tried to change the branch but there are conflicts. I suggest to merge the PR to `current` when #843 is done.

**Comment by kellerza** [comment]
Thanks @robbiet480 

@fabaff probably conflicts since I made the original changes to `current` and not `next`

**Pull request merged**
