### PR TITLE
Update Telegram notify

### PR DESCRIPTION
**Pull request by icovada**
Add documentation for Document file format as per pull request 2937 on main project

### CODE REVIEW

**Comment by robbiet480** [comment]
@icovada When I try to view the files changed tab I get a lot of red syntax highlighting telling me that there is an unclosed tag somewhere. Can you try to find it and fix it in this PR? I'll come back to this tomorrow morning if you don't get to it and take care of it.

Thanks!

**Comment by Landrash** [comment]
@robbiet480 @icovada Open bracket on line 28.

**Comment by robbiet480** [comment]
@icovada If you could take care of this ASAP that would be great! Should only take a second or five :smile:

**Comment by Landrash** [comment]
@robbiet480 @icovada I'm apparently blind. There's a bunch of open brackets in that code.
Two options would be to just add closing brackets or replace the whole thing with a complete one.
```
Option 1:
{
   "ok":true,
   "result":[
      {
         "update_id":254199982,
         "message":{
            "message_id":201,
            "from":{
               "id":123456789,
               "first_name":"Your first name",
}}]}}
```
Option 2:
```
{"ok":true,"result":[{"update_id":254199982,
"message":{"message_id":27,"from":{"id":123456789,"first_name":"YOUR_FIRST_NAME YOUR_NICK_NAME","last_name":"YOUR_LAST_NAME","username":"YOUR_NICK_NAME"},"chat":{"id":123456789,"first_name":"YOUR_FIRST_NAME YOUR_NICK_NAME","last_name":"YOUR_LAST_NAME","username":"YOUR_NICK_NAME","type":"private"},"date":1678292650,"text":"test"}}]}
```

I personally prefer the second option since it's more true to how the information is presented when following the guide.

**Comment by icovada** [comment]
Fixed it as you said... though I don't know if it should be in this commit. I didn't modify that part of the page. Git blame says the problem originated in e8ae78c

**Comment by fabaff** [comment]
This one should be merged after #843 is done. As "Changing base..." pull in too many commits.

**Comment by robbiet480** [comment]
@icovada Thanks for fixing this!! :cookie:

@fabaff roger roger, will merge after 843

**Pull request merged**
