### PR TITLE
Update mqtt.markdown for Hassio & Mosquitto integration

### PR DESCRIPTION
**Pull request by bberg115**
I'm new to Hass.io and noticed that the current instructions were not very detailed. I have added the steps that were suggested via discord, and that worked for me for 81.6. 

This is my first proposed change - please let me know if there's a better process or format.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by fabaff — COMMENTED** [review]
If details are missing then they should be added to the [Mosquitto Add-on documentation](https://www.home-assistant.io/addons/mosquitto/). 

Nothing wrong with adding an additional section here for Hass.io but the content should life in the [Add-on section](https://www.home-assistant.io/addons/mosquitto/#home-assistant-configuration) for the configuration.

**Comment by frenck** [comment]
@bberg115 Are you planning on addressing the comment by fabaff?

**Comment by bberg115** [comment]
Franck,

My apologies. I totally forgot about this. Give me the day to move it over
:)

Cheers-
Ralph

**Comment by bberg115** [comment]
7746 - new pull for correct location. Sorry if this could have been done a different way.

**Pull request closed without merging**
