### PR TITLE
Moved and edited WAQI component documentation for migration

### PR DESCRIPTION
**Pull request by reefab**
**Description:**

Moved and edited WAQI component documentation for migration from sensor to air_quality.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#20356

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by rohankapoorcom** [comment]
Since the component type (and subsequently link to page) changed, should we add a redirect from the old to the new?

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
@rohankapoorcom Well spotted, added redirect from old location.

**Review by rohankapoorcom — APPROVED** [review]

**Comment by frenck** [comment]
Closing this PR, since the parent PR has been closed as well.

**Pull request closed without merging**
