### PR TITLE
Add verify_ssl option to generic camera docs

### PR DESCRIPTION
**Pull request by fliphess**
**Description: Add a `verify_ssl` option to the generic camera component**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#15949

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by frenck** [comment]
Hi there @fliphess!

This PR targets an incorrect branch. Since this PR has a parent PR in the code base, it should have targeted the `next` branch in the documentation. This because it will be part of a `next` release.

Please change the target and rebase your PR if needed.

**Comment by frenck** [comment]
Rebased. Marked ready for review.

**Comment by tjorim** [comment]
Hi @fliphess, thanks for this feature! While updating this documentation anyway, would you mind updating the Configuration variables:-section to use the new {% configuration %} tags as explained [here](https://developers.home-assistant.io/docs/en/documentation_create_page.html#configuration)? Thanks for helping out.

**Review by frenck — APPROVED** [review]

**Comment by fliphess** [comment]
Sure :) Np @tjorim 

I'll create a new pull request to the right branch converting the docs for this page to the new standard if that's okay ?

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
@fliphess That is perfectly fine since it is a little out of scope.

I've changed to target to be `current` since this is already shipped in 0.77.

**Pull request merged**
