### PR TITLE
tesla_wall_connector: Clarify Gen 3 TWC only

### PR DESCRIPTION
**Pull request by purcell-lab**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This PR is targeting an incorrect branch. 
Please target the `next` branch and git rebase if needed.

**Comment by purcell-lab** [comment]
@frenck Beginner github question, how do I rebase on github.com?

I can see how to edit the PR and change the target branch, but I cannot see how to rebase. Do I need to use the cli rebase command or can I do it from github.com web interface, where I raised the PR?

**Comment by frenck** [comment]
>  how do I rebase on github.com?

You can't on GitHub, you need to do that locally, using `git rebase`

I've merged the other PR that made this change.

**Comment by purcell-lab** [comment]
> > how do I rebase on github.com?
> 
> You can't on GitHub, you need to do that locally, using `git rebase`
> 
> I've merged the other PR that made this change.

Thanks, I'll clean up my other PR's in the same fashion and follow this process for future.

**Pull request closed without merging**
