### PR TITLE
Systemmonitor to integration key

### PR DESCRIPTION
**Pull request by gjohansson-ST**
## Proposed change

Move yaml for Systemmonitor to integration key

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/84859
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
Doesn't this integration fall under ADR10 devices / services? Ie we want it to move to config flow only, eventually.

https://github.com/home-assistant/architecture/blob/master/adr/0010-integration-configuration.md

**Comment by gjohansson-ST** [comment]
> Doesn't this integration fall under ADR10 devices / services? Ie we want it to move to config flow only, eventually.
> 

Not sure. My guess was that this one should be both so started with moving yaml to integration key.
I have been wrong before 😄

**Comment by MartinHjelmare** [comment]
I don't think the integration falls under any of the other bullets. The system monitor retrieves state from psutil which is a service running on the host computer.

**Comment by gjohansson-ST** [comment]
Given responses I had before (for example with `scrape`) I think perhaps it can be defined within "Integrations that integrate transports. These integrations allow users to define their own protocol. Examples include MQTT, serial, GPIO." as the user defines what the sensor should display among the options available/possible.

**Comment by MartinHjelmare** [comment]
No, we don't define a transport for system monitor. MQTT is a transport, serial is a transport. There's no special transport in the system monitor integration. We're just using a service.

**Comment by gjohansson-ST** [comment]
Alright. So we'll close this one then and move to config flow instead. No point in a debate.

**Comment by MartinHjelmare** [comment]
👍

**Pull request closed without merging**
