### PR TITLE
Update Balboa spa integration documentation (core PR #115285)

### PR DESCRIPTION
**Pull request by kotope**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/115285
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by c0ffeeca7 — APPROVED** [review]
Thank you, @kotope.

**Review by c0ffeeca7 — CHANGES_REQUESTED** [review]
It looks like this PR should be based against *next*, not the *current* branch.

**Comment by kotope** [comment]
> Thank you, @kotope. It looks like this PR should be based against _next_, not the _current_ branch.

Sorry, will change the branch.

However, the core code itself needs some changes still that affects the documentation as well. Will change this PR back to draft and open again once the code + documentation is updated.

**Comment by kotope** [comment]
Core PR merged.

**Comment by kotope** [comment]
Somehow target branch change (or latest rebase) indicates too many file changes regarding this PR. Will try to resolve it, since only Balboa spa integration documentation should be changed on this PR..

**Comment by kotope** [comment]
I will close this PR and make a new one (seems to be easiest for me). Sorry about the hassle :-)

**Pull request closed without merging**
