### PR TITLE
Add Alfawise Humidifer documentation

### PR DESCRIPTION
**Pull request by HydrelioxGitHub**
**Description:**
Add Alfawise Humidifer documentation

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#15091

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by frenck — DISMISSED** [review]

**Comment by frenck** [comment]
Thank you for this @HydrelioxGitHub!

I've tweaked it a little and approved it.

Can be merged as soon as the parent PR gets merged.

**Comment by HydrelioxGitHub** [comment]
Thank you @frenck . I will do the changes needed on the parent PR as soon as possible to get it mergers.

**Comment by frenck** [comment]
@HydrelioxGitHub You should do the changes on the docs as well... the parent PR should not be merged if the docs are not OK.

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Closing this PR, since the parent PR has been closed as well.

**Pull request closed without merging**
