### PR TITLE
Update Misc Typos

### PR DESCRIPTION
**Pull request by jhollowe**
**Description:**
Correct several miscellaneous typos as found.

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
@jhollowe Thanks for opening the PR!

Any reason why it is Draft?

Happy New Year! 🍾

**Comment by jhollowe** [comment]
I'm working through getting HA up and running and reading through a bunch of documentation. I didn't want to spam a bunch of small fix PRs, so I'll just build up a few fixes before requesting a pull.

**Comment by frenck** [comment]
A couple of days has passed since the last activity, shall we continue on trying to get this one merged?

(P.s.: We don't mind multiple PR's, not at all 😉 )

**Comment by jhollowe** [comment]
Yeah. I just started back into school, so I've been a bit busy.

**Review by awarecan — APPROVED** [review]
LGTM

**Review by frenck — APPROVED** [review]
Thanks, @jhollowe! 👍

**Pull request merged**
