### PR TITLE
Update list of dependencies

### PR DESCRIPTION
**Pull request by magnusoverli**
Add docker to the list of dependencies

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by fabaff — APPROVED** [review]
Thanks :bird:

**Comment by frenck** [comment]
@magnusoverli This is confusing and a risky change.
Reasoning, please might install the Docker that came with their OS distribution, which is a really bad idea...

**Comment by magnusoverli** [comment]
Suggested fix in [#7678](https://github.com/home-assistant/home-assistant.io/pull/7678).

**Comment by fabaff** [comment]
It's just a list of deps. We don't say how to install it. It's an advance method and really depends on the underlying OS.

**Comment by magnusoverli** [comment]
In that case, specifying Docker-CE should be enough?

**Pull request merged**
