### PR TITLE
New integration fmi

### PR DESCRIPTION
**Pull request by anand-p-r**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/42409
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by lapintom — DISMISSED** [review]
Additionally, the FMI open data license (CC40BY) should me mentioned and linked: https://en.ilmatieteenlaitos.fi/open-data-licence

**Comment by anand-p-r** [comment]
> Additionally, the FMI open data license (CC40BY) should me mentioned and linked: https://en.ilmatieteenlaitos.fi/open-data-licence

Thanks! I have added this reference to the latest commit.

**Comment by Kirbo** [comment]
Any possibility to use this soon-ish?

**Comment by ludeeus** [comment]
Closing as the parent PR has been closed

**Pull request closed without merging**
