### PR TITLE
Remove CONF_MONITORED_CONDITIONS from Ambient PWS docs

### PR DESCRIPTION
**Pull request by bachya**
**Description:**

This PR adds a small doc change to Ambient PWS to support two brightness sensors with different units,

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** https://github.com/home-assistant/home-assistant/pull/25284

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

<a href="https://gitpod.io/#https://github.com/home-assistant/home-assistant.io/pull/9903"></a>

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hey @bachya! Thanks for the PR, could you please target it at the `next` branch and rebase if needed? 👍

**Comment by bachya** [comment]
@frenck Done!

**Comment by MartinHjelmare** [comment]
There are unrelated commits in the branch.

**Comment by bachya** [comment]
@MartinHjelmare Those are remnants from switching from `current` to `next`. I had trouble dropping them during rebase, so I checked out `HEAD` on `upstream/next` for all unrelated files. Long story short, if you look at what files this PR changes, you’ll only see mine; once the PR is squashed, we should be good, yes?

**Comment by MartinHjelmare** [comment]
If you rebase the relevant commits onto latest next you will get a clean branch.

You're technically correct that once we squash those dirty commits, they will not show in the target branch, but it's a bad habit to have dirty branches.

**Comment by frenck** [comment]
It is not good at all, even when squashing. Your cleanup commit is reverting changes.

Edit: Hmz might work, nevertheless, I do agree with @MartinHjelmare.
Right now you probably are of better of getting a clean branch from `next` and cherry-pick your changes onto that.

**Pull request closed without merging**
