### PR TITLE
Replaces all redirected URLs in all content

### PR DESCRIPTION
**Pull request by frenck**
**Description:**

We have a lot of links in our website, that link to a place that is actually a redirect.
I've taken the Netlify redirects file to search and replace links to use the actual resulting link.

Small helper script
```py
with open('old_urls.txt') as r:
    redirects = dict(redirect.split(' ', 1) for redirect in r)

files = glob.glob("source/**/*.markdown")
files.extend(glob.glob("source/**/*.md"))

for file in files:
    with open(file) as md:
        contents = md.read()
        for redirect in redirects:
            contents = contents.replace(redirect, redirects[redirect].rstrip())

        with open(file, 'w', encoding='utf-8') as fh:
            fh.write(contents)
```

**Pull request in home-assistant (if applicable):**n/a

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
Notified by @klaasnicolaas of an error in this PR, will correct this later today.

**Comment by frenck** [comment]
Fixed.

**Review by fabaff — CHANGES_REQUESTED** [review]
The links should point to the anchor if there is one.

- `[lights](/components/tellstick/)` -> `[lights](components/tellstick#light)`
- `[aREST](/components/arest/)`-> `[aREST](/components/arest#switch)`

**Comment by frenck** [comment]
@fabaff While I do appreciate the feedback, this is a search/replace of things that are now causing unneeded internal redirects (which is bad for SEO as well) and does not change current navigational behavior.

I'm not sure on how I can do that in this case.

**Comment by frenck** [comment]
Second thought, the replacement happens based on the `source/_redirects` file.
Let's see if I can adjust that file programmatically to already have those more specific redirects in the first place. If that succeeds, adjusting this PR will be easy.

I've marked this PR in WIP to put it on hold and prevent merging.

**Comment by frenck** [comment]
I've opened up #10495 to address the anchors in the redirects file (which is used as a source for this PR).

**Comment by frenck** [comment]
- Did a hard reset/rebased onto `current`
- Ran the script again (based on the newer `_redirects` file from #10495)

Comments addressed! 🎉 

Thanks, @fabaff, much better result this way 👍

**Comment by frenck** [comment]
NVM 🤦‍♂ New issue...
Edit: resolved.

**Review by balloob — APPROVED** [review]

**Pull request merged**
