### PR TITLE
Add docs for upcoming Lyft sensor changes

### PR DESCRIPTION
**Pull request by bachya**
**Description:**

This PR adds documentation changes for the Lyft PR defined below.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** https://github.com/home-assistant/home-assistant/pull/20491

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by rohankapoorcom — DISMISSED** [review]
Looks great!

**Comment by rohankapoorcom** [comment]
@bachya Doesn't this actually need to be off of next?

**Comment by bachya** [comment]
From https://developers.home-assistant.io/docs/en/documentation_index.html:

>* Create a Pull Request (PR) against the next branch of home-assistant.io if your documentation is a new feature, platform, or component.
>* Create a Pull Request (PR) against the current branch of home-assistant.io if you fix stuff, create Cookbook entries, or expand existing documentation.

**Comment by rohankapoorcom** [comment]
I read this as a "new feature" since it does change the behavior of the code and someone reading the docs as is (without the code change) would not be able to use those new default values.

Please clarify if my understanding of this change is incorrect.

**Comment by MartinHjelmare** [comment]
Docs changes due to source changes that will be released in the next version of home assistant should go in the `next` branch.

**Comment by bachya** [comment]
Got it! Thank you both. I’ll change the branch.

**Review by frenck — APPROVED** [review]

**Pull request merged**
