### PR TITLE
Documentation update - systemmonitor- Mandatory argument required for swap_free on 0.116.0b0

### PR DESCRIPTION
**Pull request by townsmcp**
swap_free generates an error on restart if no arg is supplied

## Proposed change
    Add example arg and display the rags are mandatory with this sensor

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by townsmcp** [comment]
Sorry guys, I’m new to editing.
Just installed 116.0b.0 and got an error message about system monitor. Ran a check config and was told the swap_free requires args.

**Comment by JeffResc** [comment]
@townsmcp If you're having an issue with Home Assistant, I would recommend submitting an issue on the [home-assistant/core](https://github.com/home-assistant/core) repo using [this form](https://github.com/home-assistant/core/issues/new/choose). Let me know if that helps :)

**Comment by townsmcp** [comment]
> @townsmcp If you're having an issue with Home Assistant, I would recommend submitting an issue on the [home-assistant/core](https://github.com/home-assistant/core) repo using [this form](https://github.com/home-assistant/core/issues/new/choose). Let me know if that helps :)

Thank you. Will add the update to documentation there

**Review by frenck — CHANGES_REQUESTED** [review]
There are unrelated commits in this PR. Please clean it up by git rebasing this PR onto the `next` branch.

While you are at it, please update the title of the PR to be more descriptive.

Thanks 👍

**Comment by townsmcp** [comment]
> There are unrelated commits in this PR. Please clean it up by git rebasing this PR onto the `next` branch.
> 
> While you are at it, please update the title of the PR to be more descriptive.
> 
> Thanks 👍

I have changed the title and some text in the comments.
I believe it is now set to ‘next, branch to?

**Comment by frenck** [comment]
@townsmcp Yes, it is set to target the `next` branch, however, it isn't based upon a clean branch of the `next` branch. Hence, you'll see an unrelated commit in this PR.

Please use git rebase to rebase this PR onto the latest `next` branch to address that issue. Thanks 👍

**Comment by frenck** [comment]
Closing this PR as there was no response + the issue has been fixed upstream.

**Pull request closed without merging**
