### PR TITLE
Template sensor attribute docs

### PR DESCRIPTION
**Pull request by gadgetchnnel**
**Description:**
Added documentation for the new **attribute_templates** option for the template snesor and binary sensor.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant/pull/20410

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by DubhAd — APPROVED** [review]
👍

**Comment by klaasnicolaas** [comment]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by klaasnicolaas** [comment]
Parent PR is still open

**Comment by gadgetchnnel** [comment]
Closing this, as the original parent PR has been closed, and is being split into separate binary_sensor and sensor PRs

**Pull request closed without merging**
