### PR TITLE
added docs for webostv play media video

### PR DESCRIPTION
**Pull request by trullock**
## Proposed change

Added usage example to webostv docs to support playing video files

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/97207
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by thecode** [comment]
@frenck this PR was targeted to a wrong branch, should be targeted to `next` and parent PR is not merged yet

**Comment by frenck** [comment]
@thecode I think this didn't land on `current`, I made an error during releasing 2023.8 (which I've corrected now I think). Could you check that?

../Frenck

**Comment by thecode** [comment]
> @thecode I think this didn't land on `current`, I made an error during releasing 2023.8 (which I've corrected now I think). Could you check that?
> 
> ../Frenck

Yes, this not on `current` and not on `next`. @trullock please make the PR again starting from the `next` branch, sorry for the inconvenience. Thanks 👍

**Comment by trullock** [comment]
Apologies everyone, I did originally accidentally branch off `current` but I rebased off `next` and re-pushed so I thought this was correct... I'll start again and update the associated feture PR

**Pull request merged**
