### PR TITLE
Update google_assistant.markdown

### PR DESCRIPTION
**Pull request by IIIdefconIII**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by DubhAd — CHANGES_REQUESTED** [review]
`youre` should be `your`

The formatting is lost when displayed, and appears under the previous bullet

**Comment by frenck** [comment]
@IIIdefconIII Can you please explain the reasoning behind this?

Since your phone does not have to be set to English... As far as I know, the phone must be set to a language that Google Assistant supports.

On iOS this works differently, since the Assistant language can be set separately from the phone language.

**Comment by IIIdefconIII** [comment]
As far as I know, the phone must be set to a language that Google Assistant supports. Google assistant does work on dutch, but i only got it working in english phone setup. i think its google home that should support it instead of google assistant

**Comment by frenck** [comment]
@IIIdefconIII 
Wel both assistant & home support German for example (and many others).

So that renders this docs proposal to: Incorrect.

**Comment by DubhAd** [comment]
So, knowing that it simply needs to be a supported language, you've made the incorrect statement deliberately. I'd suggest you open a fresh PR with *accurate* instructions once you've validated your instructions.

**Pull request closed without merging**
