### PR TITLE
Use presence detection in automations

### PR DESCRIPTION
**Pull request by c0ffeeca7**
## Proposed change

Add tutorial page to getting started
- using presence detection in automations
- add tutorial on presence detection as condition
- presence detection as trigger is topic of separate PR

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

## Summary by CodeRabbit

- **New Features**
  - Added a new navigation link for "Presence detection in automations" under the "Getting started" section for easier access.
  - Introduced a comprehensive guide on implementing presence detection as a condition in automation setups, enhancing practical application.
  
- **Content Updates**
  - Updated an existing markdown link to direct users to relevant content about integrating presence detection into automations.

### CODE REVIEW

**Review by frenck — COMMENTED** [review]
Isn't the more interesting use case here to also trigger when you get home and the lights turn on?

**Comment by c0ffeeca7** [comment]
> Isn't the more interesting use case here to also trigger when you get home and the lights turn on?

- yes, topic for another PR
- point here is to work with the sunset automation, which we already created. and where it would make sense to run it only when someone is home.

**Comment by frenck** [comment]
> yes, topic for another PR

👍 

> point here is to work with the sunset automation, which we already created. and where it would make sense to run it only when someone is home.

Don't agree with that statement. The automation is set up in an incorrect/inflexible way, making it hard to do now.

From an automation perspective, this automation is a wrong practice from the get-go (which happens a lot in our community, I don't blame them, as our triggers contain to much "hidden condition logic" in them).

In general, automation should trigger things, check conditions, and do actions.

Right now, the automation has a mix-up of the sunset trigger that is "conditionally", making it hard to add more triggers as it will mess up stuff.

A better approach, in general, is to trigger "sun" changes and have sunset as an actual condition already. Adding a presence condition and trigger at that point, will make the automation work in the case set here, but also when arriving home (as it will trigger an check the conditions).

**Comment by c0ffeeca7** [comment]
> > yes, topic for another PR
> 
> 👍
> 
> > point here is to work with the sunset automation, which we already created. and where it would make sense to run it only when someone is home.
> 
> Don't agree with that statement. The automation is set up in an incorrect/inflexible way, making it hard to do now.
> 
> From an automation perspective, this automation is a wrong practice from the get-go (which happens a lot in our community, I don't blame them, as our triggers contain to much "hidden condition logic" in them).
> 
> In general, automation should trigger things, check conditions, and do actions.
> 
> Right now, the automation has a mix-up of the sunset trigger that is "conditionally", making it hard to add more triggers as it will mess up stuff.
> 
> A better approach, in general, is to trigger "sun" changes and have sunset as an actual condition already. Adding a presence condition and trigger at that point, will make the automation work in the case set here, but also when arriving home (as it will trigger an check the conditions).

Thank you for the detailed explanation. Let me rework it.

**Pull request closed without merging**
