### PR TITLE
RFLink devices documentation

### PR DESCRIPTION
**Pull request by javicalle**
**Description:**
General review for RFLink platform devices documentation. I began with misdocumented **_deprecated_** attributes and finished covering all the RFLink platform.

There is 3 kind of review:
* misdocumented **_deprecated_** attributes
* homogeneous configuration for RFLink platform devices
* added minimal configurations & "Additional configuration examples" section

I followed @emontnemery `configuration` definition for his `binary_sensor` that I think is more appropriate than the existing one.

Any comments are welcomed.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by javicalle** [comment]
Now, it's fine to me

**Comment by javicalle** [comment]
What is needed to approve and merge this PR?
I will began to work in some changes at RFLink devices documentation and I do not want to create conflicts with this one.

**Comment by frenck** [comment]
@javicalle Sorry for leaving you in the dark for so long.
Could you take a look at the merge conflicts and ping me if they are resolved? 👍

**Comment by javicalle** [comment]
I'll take a look and give you some feedback.

**Comment by javicalle** [comment]
I have done a manual merge. I hope don't loose anything along the way.

**Comment by javicalle** [comment]
@frenck Now it's all done
If you were kind enough to review, I would be very grateful.

I hope not to cause too many problems

**Review by DubhAd — APPROVED** [review]
👍

**Comment by javicalle** [comment]
Thanks.

**Pull request merged**
