### PR TITLE
Documentation for extra sensors BMW Connected Drive

### PR DESCRIPTION
**Pull request by gerard33**
**Description:**
Documentation for extra sensors of the BMW Connected Drive component.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#12591

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
@gerard33 Thanks! Looking good! Can be merged as soon as the parent PR gets merged.

**Review by MartinHjelmare — DISMISSED** [review]

**Comment by MartinHjelmare** [comment]
Please rebase on latest next branch, to make the build pass. Then we can merge.

**Comment by frenck** [comment]
Rebased. Can be merged as soon as the build passes.

**Review by frenck — APPROVED** [review]

**Comment by gerard33** [comment]
Thanks!

**Pull request merged**
