### PR TITLE
Describe available type options for googleassistant component

### PR DESCRIPTION
**Pull request by sagilo**

### CODE REVIEW

**Review by c727 — CHANGES_REQUESTED** [review]
this list is not correct, valid types are these: https://developers.google.com/actions/smarthome/guides/

**Review by frenck — DISMISSED** [review]

**Comment by frenck** [comment]
It actually is correct. Home Assistant maps those to the Google domain types.

https://github.com/home-assistant/home-assistant/blob/d5612b5ccc4b30ed62022a5b042459ac03425b1e/homeassistant/components/google_assistant/smart_home.py#L35

**Review by frenck — APPROVED** [review]

**Review by frenck — CHANGES_REQUESTED** [review]
Type was removed! I've missed that, sorry.

**Comment by frenck** [comment]
Closing this PR, since the option was removed and therefore, this change is obsolete.

@sagilo Nevertheless, thank you for taking the time to create this PR.

**Pull request closed without merging**
