### PR TITLE
Option `json_path_attributes` incorrect

### PR DESCRIPTION
**Pull request by borpin**
## Proposed change

Option `json_path_attributes` should be `json_attributes_path`.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue:

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
I think this PR should go into the `current` branch

**Review by frenck — APPROVED** [review]
Rebased the PR onto the `current` branch. Please, @borpin, make sure you are using the right branches. Saves us a bit of time 😉 

Looking good! Thanks for fixing that 👍

**Comment by borpin** [comment]
> Rebased the PR onto the `current` branch. Please, @borpin, make sure you are using the right branches. Saves us a bit of time 😉

Sorry, not quite sure the difference 🙍‍♂. Last time it went onto current and should have been on next and this time on next and should have been current 😉. Ho hum, third time lucky I guess 😀

**Comment by frenck** [comment]
It is listed in the type of change you check in the checkboxes, you checked:

> Adjusted missing or incorrect information in the current documentation (current branch).

Pretty clear to me? 🤷‍♂

**Pull request merged**
