### PR TITLE
Add directions to play an m3u playlist for music

### PR DESCRIPTION
**Pull request by dimmingmuse**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by frenck** [comment]
I'm going to pass on this. While I appreciate the addition it:

- Doesn't pass the build.
- It is a replica of the example above it (with a different file extension).

Nevertheless, thanks for contributing 👍

**Comment by dimmingmuse** [comment]
Up to you, but there is no information online that I could find on how to do this.

**Comment by frenck** [comment]
It was in the exact example above the one you were trying to add.

**Comment by dimmingmuse** [comment]
Like I said, up to you.  I searched the documentation on how to add a playlist.  It was not at all clear to me that music playlists could be added in the same way as a smart video playlist.  (which I still don't know or care about)  Maybe I'm just not very good at gleaning information, but this was not at all clear to me.  So, maybe it's just me...

**Pull request closed without merging**
