### PR TITLE
Add warning re hub version.

### PR DESCRIPTION
**Pull request by Bodge-IT**
Make clarification on hub API access status as it really was not clear.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
And how do we recognize the v1 or v2? So far I know, I have the V2 and working with Home Assistant 😉

**Comment by Bodge-IT** [comment]
Ah OK, I thought I had v2, I know I cannot open access to the API through the MiHome app, with my version.  Needs more research from me then.  I just wanted to support users making a buying choice on Xiaomi stuff, as I currently have yet one more doorstop on my hands.

**Comment by klaasnicolaas** [comment]
Well if you have problems with connecting the hub, with the latest hub and firmware. 
Take a look at this PR: https://github.com/home-assistant/home-assistant.io/pull/8890

**Comment by Bodge-IT** [comment]
So the identifier is if the text on back goes around the edge of the hub instead of as a block, centered toward the bottom.

I think this info needs adding.  And as for the fix, it is out of reach of many (technically or effort wise) and they should be warned.  Current text still not clear enough.

My h/w is LM16-IGW_v1.0.3 and my board doesn't look like the image provided for the param change process in the PR.  Also only port 4567 open on device.

**Review by frenck — CHANGES_REQUESTED** [review]
As clarified by @klaasnicolaas, #8890 is going to add some additional instructions.
This makes this additional note not true.

Either change the note or close the PR.

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
I've updated the description a bit so it works with the content added in #8890

**Pull request merged**
