### PR TITLE
rfxtrx: Documenation update

### PR DESCRIPTION
**Pull request by elupus**
## Proposed change

* Replace codename RTS with Somfy RTS.
* Clearify that repeats should be avoided.
* Link to more up to date hardware
* Remove old yaml configuration reference

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by elupus** [comment]
This could possibly be against next branch. Changes was suggested by RFXCOM. There is no harm in it being against next.

**Comment by frenck** [comment]
I don't get why this should go into `next` and not `current`?

**Comment by frenck** [comment]
I don't get why this should go into `next` and not `current`?

**Comment by elupus** [comment]
Sorry, i misswrote. I meant it could possibly go into current. I just happened to open it against next, and there is nothing critical in it to go into current.

**Comment by frenck** [comment]
Lets rebase it onto current

**Comment by elupus** [comment]
Rebased to current.

**Review by frenck — APPROVED** [review]
Thanks, @elupus 👍

**Pull request merged**
