### PR TITLE
Add `hass` user to sudoers

### PR DESCRIPTION
**Pull request by AdithyanI**
I was confused on why the simple switch command was not working. Then I realized I had to `hass` user to `sudo` group before using switch command.
Maybe, some other beginner also has a same question.

### CODE REVIEW

**Comment by Landrash** [comment]
`hass` user is a system user. This user account is not meant to have elevated privileges. 
To issue commands with elevated privileges use the `pi` user.

**Comment by AdithyanI** [comment]
@Landrash 
For example, if I have a switch

``` yaml
switch:
  platform: command_line
  switches:
    arest_pin4:
      command_on: "sudo /home/pi/433Utils/RPi_utils/./codesend 1135923 1 183"
``` 

My log says this,

```log
16-09-27 19:23:24 homeassistant.components.switch.command_line: Command failed: sudo /home/pi/433Utils/RPi_utils/./codesend 1135923 1 183
```
I was able to resolve this problem by adding `hass` to `sudoers` is that wrong?


In my case, how can I elevate myself to `pi` user and then run the command?
I used raspberry-pi-all-in-one-installed to get HA.

**Comment by Landrash** [comment]
@AdithyanI Your use case is a real corner case. It's possible to run as your doing now and by granting `sudo` privileges to your `hass` account.
Another workaround would be to use the [https://en.wikipedia.org/wiki/Setuid] flag on your executable. This on the other hand wont work if the `codesend` command is a shell script since Linux in general is configured to ignore this flag on shell scripts.
The proper way on the other hand would most likely be to figure out what permissions is needed for the `hass` account to run the `codesend` command and granting it only these.

Reasoning for not adding `sudo` privileges to the `hass` account in general is that we always should design with security in mind and do our best to keep permissions to a bare minimum.

**Comment by AdithyanI** [comment]
Hi @Landrash 
Thanks for the detailed reply :+1: 
So, definitely my solution would be the wrong one. 
But, at-least we could include a note describing what you have written above.
Beginners like me at-least would know the cause of the error and then each can decide the solution that best fits his purpose.

**Comment by Landrash** [comment]
I'm even a bit unsure about the note since it's preferable that the docs be simple and straight to the point.
If you can come up with a good one then please open up a pull request and I'll happily have a look at it :)

**Pull request closed without merging**
