### PR TITLE
Add documentation on using offsets on time trigger

### PR DESCRIPTION
**Pull request by tsvi**
## Proposed change

Add explanation on time trigger offset feature

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: home-assistant/core#120858
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

## Summary by CodeRabbit

- **New Features**
  - Introduced new trigger types: Sunset/Sunrise trigger and Sun elevation trigger.
  - Enhanced Time triggers with new options: Time string, Input datetime, and Multiple times.
  - Added support for sensors of datetime device class with offsets, allowing triggers to activate based on time adjustments.
  - Included new sections for Webhook data, Webhook security, Related topics, and Sentence wildcards.
  - Enabled multiple entity IDs for the same trigger and the ability to disable triggers.

- **Improvements**
  - Expanded State trigger section with details on attribute changes and holding a state or attribute.
  - Updated documentation with a video tutorial for Trigger IDs and clarified guidance on using multiple time formats.

- **Documentation**
  - Added detailed explanations and examples for using sensors with offsets in automation triggers, including cautions about potential issues with positive offsets.

### CODE REVIEW

**Comment by tsvi** [comment]
@coderabbitai summary

**Comment by tsvi** [comment]
@coderabbitai full review

**Comment by tsvi** [comment]
@coderabbitai full review

**Comment by tsvi** [comment]
@coderabbitai summary

**Review by c0ffeeca7 — APPROVED** [review]
Thank you, @tsvi :+1:

**Pull request merged**
