### PR TITLE
Updating fastdotcom docs

### PR DESCRIPTION
**Pull request by erwindouna**
## Proposed change

Update the ping integration documentation, added the config flow and removed the YAML configuration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by rohankapoorcom** [comment]
It might be worth waiting until this PR is merged and import the common task created there: https://github.com/home-assistant/home-assistant.io/pull/28614 on this page.

**Comment by erwindouna** [comment]
Great tip. This is perfect for standardizing.

**Review by frenck — CHANGES_REQUESTED** [review]
This PR is targeting an incorrect branch.

As it depends on a parent PR in the Core code base, it means this documentation depends on a next (future) release of Home Assistant. Therefore the documentation PR needs to target the `next` branch.

Please change the target of this PR to the `next` branch and git rebase your PR onto the `next` branch as well.

../Frenck

**Comment by erwindouna** [comment]
Creating new PR, whereas the rebranching brought in conflicts, as well as cluttering the PR's commits and files

**Pull request closed without merging**
