### PR TITLE
Fixing typos in getting started..

### PR DESCRIPTION
**Pull request by minudika**
Fixed some word organization of some sentences and few cases of letters.

### CODE REVIEW

**Comment by balloob** [comment]
You accidentally changed the auto-generated file. Change this page instead: https://github.com/home-assistant/home-assistant.github.io/blob/current/source/getting-started/index.markdown

**Comment by minudika** [comment]
@balloob sorry :( did not notice that. I will add those changes to the correct file. :)

**Comment by balloob** [comment]
No worries!

Also please open your PR against `current` so the changes can go live right away.

**Comment by Landrash** [comment]
@minudika Open a new pull request when you changed the other file :)

**Pull request closed without merging**
