### PR TITLE
Consolidate MQTT Documentation

### PR DESCRIPTION
**Pull request by ikifar2012**
## Proposed change
Consolidate MQTT Docs into one markdown file similar to #14579 

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by ikifar2012** [comment]
I can update this if needed

**Comment by frenck** [comment]
Yes, please, that would be awesome!

**Comment by ikifar2012** [comment]
I am working on this again, I have gotten it up to speed... Now to add the new platforms

**Comment by ikifar2012** [comment]
It doesn't look like I can re-open this PR, I guess someone can re-open it again when I am done all my changes? it doesn't seem to be tracking the changes in draft mode

**Comment by SeanPM5** [comment]
Re-opened it for you now

**Comment by ikifar2012** [comment]
I am ready for review

**Comment by ikifar2012** [comment]
I find it odd the bot has not removed the stale tag

**Comment by ikifar2012** [comment]
Will have to add the changes in #16785 once it is merged

**Comment by ikifar2012** [comment]
I just don't want this to go stale

**Comment by ikifar2012** [comment]
What else am I missing?

**Comment by ikifar2012** [comment]
Are we still planning on doing this?

**Pull request closed without merging**
