### PR TITLE
Added Chrome on Linux + minor updates

### PR DESCRIPTION
**Pull request by jladefoged**
**Description:**

Added Chrome on Linux
Updated Firefox on Linux and Windows
Updated Chromium on Linux

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by frenck** [comment]
@ladefoged81 Could you please elaborate on how you determined these versions?

**Comment by jladefoged** [comment]
@frenck I've used the about box in the help menus in the browsers. Is this incorrect?

**Comment by frenck** [comment]
@ladefoged81 Judging by the page description, it kinda is (Well I think it should be an addition, instead of a replacement).

I'll consult this internally an get back to you.

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
I've checked it with one of the authors of the page, and it seems to be correct.
So this PR = 👍 

Happy Hacktoberfest 🎉 

../Frenck

**Pull request merged**
