### PR TITLE
manual config example for tplink component

### PR DESCRIPTION
**Pull request by dlashua**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by fabaff** [comment]
Looks like a duplicate of #8866

**Comment by dlashua** [comment]
> Looks like a duplicate of #8866

This PR is for a change to the tplink/light documentation. #8866 is a PR for a change to the tplink/switch documentation. Both are needed.

**Comment by dlashua** [comment]
I see confusion about this issue a few times a day in the various forums. Please merge this PR or let me know what needs to be changed so it can be merged.

**Comment by frenck** [comment]
The docs have been addressed in #7338.

**Pull request closed without merging**
