### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by madmat777**
## Proposed change
Added LB2 as broadlink integration has been patched to support LB2 style Smart Bulbs (LB26 and LB27).

## Type of change
- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information
- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/63530
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: #61911

## Checklist
- [x ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @madmat777, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#21053).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by raman325** [comment]
please rebase your branch on `next`

**Comment by madmat777** [comment]
@raman325 sorry for the bother on this. I totally missed all the other commits and am unsure on how they got bundled into my simple commit. Is it just easier if I close the request? I don't want to make it worse by handling this the wrong way.

**Comment by raman325** [comment]
It's because your branch is branched off of 'current' instead of next. If you did this via the GitHub editor you may just want to close this and create a new branch. Make sure you are on the next branch in the repo before you attempt to edit the file

**Comment by madmat777** [comment]
Wrong Branch. Closed.

**Comment by madmat777** [comment]
@raman325 
Thanks for your help.  New pull created on Next branch. 
https://github.com/home-assistant/home-assistant.io/pull/21055

**Pull request closed without merging**
