### PR TITLE
Add description of Enphase Envoy phase data

### PR DESCRIPTION
**Pull request by catsmanac**
## Proposed change

Add the availability of phase production and consumption data when using an Enphase Envoy metered with current transformer (CT) clamps installed on more then 1 phase.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/107744
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Please rebase your branch to the `next` branch

**Review by janiversen — CHANGES_REQUESTED** [review]
This is wrong

**Comment by catsmanac** [comment]
tried rebase but ran into conflicts in text which is not mine. I don't master rebase for sure, so to avoid a bigger mess I'll better cancel this one. For now I won't move to avoid messing it up further.

**Comment by MartinHjelmare** [comment]
Please open a new PR using a new fresh branch based on the correct branch. Make sure to target the correct branch when opening the PR. Thanks!

**Comment by catsmanac** [comment]
Thanks for your advice @MartinHjelmare

**Pull request closed without merging**
