### PR TITLE
Update zha.markdown with ZigStar USB Discovery

### PR DESCRIPTION
**Pull request by Hedda**
## Proposed change

Add the ID info about ZHA USB Discovery of ZigStar Stick v4 (CC2652 + CH340B variant) open source hardware. More info here:

https://zig-star.com/projects/zigbee-stick-v4/

https://github.com/mercenaruss/zigbee-stick-v4

ZHA docs update PR submitted on behalf of @mercenaruss (who is the maker of ZigStar USB sticks and ZigStar LAN gateways).

Note that https://github.com/home-assistant/core/pull/59559 will allow mercenaruss to close upstream issue/request ->  https://github.com/mercenaruss/zigbee-stick-v4/issues/7

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/59559
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by Hedda** [comment]
ZHA docs update PR submitted on behalf of @mercenaruss

**Comment by mercenaruss** [comment]
> ZHA docs update PR submitted on behalf of @mercenaruss

@Hedda thank you for your help, please change the name to: ZigStar Coordinator.

I don't produce any another variant, only one. So need a more simple name: ZigStar Coordinator.

When i will all lan/poe gateway will another name: ZigStar LAN Gateway.

Again thank you for you work.

**Comment by Hedda** [comment]
@mercenaruss Changed "_ZigStar Stick v4_" to just "_ZigStar Stick_" but otherwise I think would be best to leave 'as is' for now and then do new PR just changing that detail in the ZHA docs after you have updated all your sites to use the new name chosen because right now can see that they all still old "**ZigStar Stick v4**" name. Thus it will certainly be more confusing to change the name in ZHA docs first when you have not already changed it upstream. So be sure to change the name on all sites upstream first:

https://zig-star.com/projects/zigbee-stick-v4/

https://www.tindie.com/products/zigstar/zigstar-stick-v4/

https://github.com/mercenaruss/zigbee-stick-v4

IMHO, remember that users have the option to reflash these sticks with Zigbee Router firmware and use them as Zigbee routers instead Zigbee coordinators. Thus personally I think you should leave the name as "ZigStar Stick" or use other similar general suffix (like ex. "ZigStar USB Stick", "ZigStar USB Dongle", or "ZigStar USB Adapter" which all work well as generic suffixes in product name).

PS: Regardless I believe that the HA developers will want to keep such off-topic discussions elsewhere so maybe instead create a new issue at your https://github.com/mercenaruss/zigbee-stick-v4/issues repo for that that discussion or better yet enable GitHub Discussions https://docs.github.com/en/discussions to allow "ZigStar discussions" under its own community repo like https://github.com/zigstar/zigstar_community_resources/discussions or one of your other exisitng GiHub repos to use as a generic ZigStar communication forum. They won't like such discussions in a PR.

**Review by Adminiuga — APPROVED** [review]
Lgtm

**Pull request merged**
