### PR TITLE
Update Google Cast integration

### PR DESCRIPTION
**Pull request by eerovil**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/35114
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Please rebase your branch to the `next` branch en push again.

**Comment by eerovil** [comment]
Rebase is done.

**Comment by klaasnicolaas** [comment]
Well not really, I see still some unrelated commits in your PR that has refereces to commits in the `current` branch.

**Comment by eerovil** [comment]
Sorry about that. Now it's fixed.

**Review by frenck — APPROVED** [review]
Thanks, @Eerovil!

I've had to remove one small part, which is the custom integration.
We can't do that, as it might imply supported/endorsement from Home Assistant.

Otherwise 👍

**Pull request merged**
