### PR TITLE
Documentation for google_assistant media controls

### PR DESCRIPTION
**Pull request by ZephireNZ**
## Proposed change

Add documentation for media playback, and remove the warning around sources (this was fixed with home-assistant/core#30418

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: home-assistant/core#35803
- Link to parent pull request in the Brands repository: N/A
- This PR fixes or closes issue: N/A

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by ZephireNZ** [comment]
Not sure if removing the docs for the media player source should be a separate PR, happy to split it up if so 😊

**Review by frenck — APPROVED** [review]
I think it is fine @ZephireNZ! Thanks for the PR 👍

**Comment by ZephireNZ** [comment]
Oops, I've done it again - this should have been rebased against `current` not `next` 🙈 

home-assistant/core#35803 is in 0.111

**Comment by frenck** [comment]
I missed that as well, will cherry-pick it to `current` 👍 

Edit: Done ✅

**Pull request merged**
