### PR TITLE
Update transmisson.markdown

### PR DESCRIPTION
**Pull request by jonudewux**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):**
https://github.com/home-assistant/home-assistant/pull/20575

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
We have a small problem because this PR is a duplicate of this PR #7816, so it might be better to close this PR and check if your suggested changes can be included in the other PR.

**Comment by MartinHjelmare** [comment]
We should rebase this after the other PR is merged. The last commit here is not included in the other PR. That commit is the only relevant commit in this branch.

**Comment by klaasnicolaas** [comment]
We can close this PR, I added the `scan_interval` in the other PR

**Comment by MartinHjelmare** [comment]
The parent PR here that adds scan_interval hasn't been merged.

I would prefer to keep these additions separate.

**Pull request closed without merging**
