### PR TITLE
Update media_player.webostv.markdown

### PR DESCRIPTION
**Pull request by DetroitEE**
**Description: Add instructions for enabling WakeOnLan on newer model LG TVs**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by frenck** [comment]
@DetroitEE Thanks for the PR. A couple of questions:
- There is a merge conflict, could you please resolve this?
- This PR is against the `next` branch, which suggests it has pending and/or recent code changes in the main repository. Could you point me to the specific PR or change?
- The build is failing. Quite possibly you based of an outdated fork/branch. A rebase should fix that.

**Comment by DetroitEE** [comment]
I'm a user not a developer; I was just trying to add one sentence to the documentation to help people trying to use Wake On LAN (added in line 78). There were no other changes. I'm sorry, but I'm not sure how to address the issues you've raised.

**Comment by DetroitEE** [comment]
OK I changed it to the current branch. Please let me know what else I need to do. @frenck

**Comment by frenck** [comment]
I'll assign this one to myself, will pick it up soon.

**Comment by frenck** [comment]
The base has been fixed by recent releases.
Still, there is a merge conflict to be solved. Could you take a look @DetroitEE?

**Comment by DetroitEE** [comment]
Should be all set.

**Review by DubhAd — APPROVED** [review]
👍

**Pull request merged**
