### PR TITLE
Updated documentation for influxdb-integration

### PR DESCRIPTION
**Pull request by andreas-berg**
## Proposed change
HomeAssistant Core PR-#83939 introduces the feature to add full Flux-queries in influxdb-sensors.
This change updates the documentation for these new features.

https://github.com/home-assistant/core/pull/83939

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by jbouwh** [comment]
It seems to me this PR needs to rebased and targeted against `next` since there is a related parent PR

**Comment by andreas-berg** [comment]
> It seems to me this PR needs to rebased and targeted against `next` since there is a related parent PR

👍 I'll do it

**Comment by andreas-berg** [comment]
Yeah, this is a mess, retargeting PR to next suggest a massive change, sorry! 
Pls advice, should I just scrap this PR and do a new PR from a fork of the next-branch?

**Comment by thecode** [comment]
> Yeah, this is a mess, retargeting PR to next suggest a massive change, sorry! Pls advice, should I just scrap this PR and do a new PR from a fork of the next-branch?

Would be better to make a new PR

**Comment by andreas-berg** [comment]
Closing this PR and creating a new one

**Pull request closed without merging**
