### PR TITLE
Add text-input class to integration search input

### PR DESCRIPTION
**Pull request by joshmcrty**
## Proposed change

The `text-input` class is used by InuitCSS to change the cursor from `pointer` to `text` when an `input` is focused. Currently when you try to select or edit text in the integration search input, the mouse cursor remains a pointer.

Before:

https://github.com/user-attachments/assets/d7cd395f-f0c2-44c3-abb3-403a8f68b919

After:

https://github.com/user-attachments/assets/cd60df2c-8da8-4e61-9d70-f66b402a7655

See Intuit source that sets these styles here:

https://github.com/home-assistant/home-assistant.io/blob/8b68bfdd0c26be01e94ea00e320f2d952741ae4c/sass/inuitcss/generic/_reset.scss#L64-L81

https://github.com/home-assistant/home-assistant.io/blob/8b68bfdd0c26be01e94ea00e320f2d952741ae4c/sass/inuitcss/base/_forms.scss#L15-L30

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

## Summary by CodeRabbit

- **New Features**
	- Enhanced styling for the search input element with a new class.
	- Improved user interface with a visual cue for text-editable areas.
	- Maintained effective filtering mechanism for components based on user input, categories, and versions.

- **Bug Fixes**
	- Ensured existing functionality of the filtering process remains intact and responsive to URL hash changes.

### CODE REVIEW

**Comment by mrdarrengriffin** [comment]
I agree with your change here. If you could amend the following to have `cursor: text;` also in this PR, that would be great
https://github.com/home-assistant/home-assistant.io/blob/6b95b2406f2158c74eefd2cf23257737a29677ba/sass/inuitcss/base/_forms.scss#L25-L30

**Comment by joshmcrty** [comment]
> I agree with your change here. If you could amend the following to have `cursor: text;` also in this PR, that would be great
> 
> https://github.com/home-assistant/home-assistant.io/blob/6b95b2406f2158c74eefd2cf23257737a29677ba/sass/inuitcss/base/_forms.scss#L25-L30

@mrdarrengriffin I'm happy to make the additional change, but I have a couple questions first:

1. This would change the UI behavior so that the cursor would be `text` on hover, not just once the input is clicked on. Is that the desired behavior?
2. Should we edit the InuitCSS files, or is there another HA-specific theme/tweaks file that the change should go in? Maybe in `https://github.com/home-assistant/home-assistant.io/blob/current/sass/homeassistant/base/_global.scss`? The InuitCSS source file says to style these via your theme stylesheet.

Thanks!

**Comment by mrdarrengriffin** [comment]
> > I agree with your change here. If you could amend the following to have `cursor: text;` also in this PR, that would be great
> > https://github.com/home-assistant/home-assistant.io/blob/6b95b2406f2158c74eefd2cf23257737a29677ba/sass/inuitcss/base/_forms.scss#L25-L30
> 
> @mrdarrengriffin I'm happy to make the additional change, but I have a couple questions first:
> 
> 1. This would change the UI behavior so that the cursor would be `text` on hover, not just once the input is clicked on. Is that the desired behavior?
> 2. Should we edit the InuitCSS files, or is there another HA-specific theme/tweaks file that the change should go in? Maybe in `https://github.com/home-assistant/home-assistant.io/blob/current/sass/homeassistant/base/_global.scss`? The InuitCSS source file says to style these via your theme stylesheet.
> 
> Thanks!

1. A cursor of `default` (or `text`) implies that either text can be selected or the cursor can be placed for text input, so let's stick with that. A `pointer` indicates something is a link, so invalid in this case.
2. Yeah, let's keep the Inuit styles separate, throw it in global for `textarea, .text-input {` and we should be good.

I will then review once more via the PR preview.

**Comment by joshmcrty** [comment]
@mrdarrengriffin Sounds good, I thought that cursor behavior was unusual, definitely not what I would expect but it's what Inuit provides so I didn't want to change it if it was intentional. I've committed the requested changes.

**Comment by mrdarrengriffin** [comment]
> @mrdarrengriffin Sounds good, I thought that cursor behavior was unusual, definitely not what I would expect but it's what Inuit provides so I didn't want to change it if it was intentional. I've committed the requested changes.

Perfect. Everything looks fine to me on the preview.

Thanks for your contribution!

**Review by mrdarrengriffin — APPROVED** [review]

**Review by frenck — APPROVED** [review]
Looks good, thanks @joshmcrty 👍 

../Frenck

**Pull request merged**
