### PR TITLE
Changed gitignore list

### PR DESCRIPTION
**Pull request by klaasnicolaas**
**Description:**
I've re-adjusted it, I'd like to hear your opinion on what must be added to ensure that that people do not push sensitive data out when they take over the example script

See also the discussion on the related page
Related to #6994

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
@klaasnicolaas I guess we need to add `ip_bans.yaml` to be ignored as well.

**Comment by klaasnicolaas** [comment]
@frenck But `ip_bans.yaml` is already on the list to be ignored 😉

**Comment by frenck** [comment]
You are so right @klaasnicolaas 🤦‍♂️ 

I do think the `*` should stay in, since, you want to ignore everything by default.

**Comment by klaasnicolaas** [comment]
Yes, I doubted a bit about whether or not the `*` should be included. Maybe add a text, that at the moment that you really want to share your config on github you can better remove the `*`?

**Review by frenck — APPROVED** [review]

**Review by frenck — APPROVED** [review]

**Pull request merged**
