### PR TITLE
Xmpp async

### PR DESCRIPTION
**Pull request by flowolf**
**Description:**

xmpp async support with new lib.
also:
- TLSv1.1
- TLSv1.2
- `resource` option for JID

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#17283
## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by fabaff — DISMISSED** [review]
Thanks :bird:

**Review by fabaff — APPROVED** [review]

**Comment by flowolf** [comment]
@fabaff this will be in 0.81, won't it? so the version should be 0.81.

**Comment by fabaff** [comment]
Indeed, thanks.

**Comment by fabaff** [comment]
I will fix it after merging while updating the configuration section.

**Pull request merged**
