### PR TITLE
Add 'days_offset' parameter

### PR DESCRIPTION
**Pull request by LaStrada**
**Description:**
Add `days_offset` parameter for workday sensor.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#8824

### CODE REVIEW

**Review by Landrash — COMMENTED** [review]
I'm a tad unsure what this functionality adds?

**Comment by LaStrada** [comment]
[From the forum.](https://community.home-assistant.io/t/sensor-for-holidays-add-support-for-offset/17823)

This change will add support for offset so this sensor can be used to check if e.g. tomorrow is a workday. Example:

```yaml
binary_sensor:
  - platform: workday

# I'm using this to lower the temperature earlier if I'm going to work tomorrow.
binary_sensor:
  - platform: workday
    days_offset: 1 # Tomorrow

binary_sensor:
  - platform: workday
    days_offset: 2 # The day after tomorrow

binary_sensor:
  - platform: workday
    days_offset: -1 # Yesterday
```

**Review by Landrash — APPROVED** [review]
Looks good and can be merged after parent PR is merged.

**Review by fabaff — APPROVED** [review]
:bird:

**Pull request merged**
