### PR TITLE
Update deconz.markdown. Warning about firmware update button

### PR DESCRIPTION
**Pull request by bverkron**
## Proposed change

Add note about firmware update button in Phoscon interface not working. Recommend following official deconz process instead.

Firmware button doesn't work and breaks the Conbee II stick. Causes `Firmware Not found` issue. Stick has to be re-flashed manually to correct. deCONZ official discord states the following about the update button when used with this HA add-on.

Screen Shot 2020-10-18 at 11 54 27 AM

The link I included in the doc update is the one listed in that bot message.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by frenck** [comment]
The note you are adding applies to the firmware of the deCONZ stick and the Phoscon software. This is not related / nor a problem for the integration in Home Assistant.

This note does not belong in our documentation.

**Comment by bverkron** [comment]
But this seems to be a known issue specifically when running the firmware update within the deCONZ HA add-on and not elsewhere.

Even if it is related to the firmware directly if the issue only appears when running the deCONZ add-on isn't it worth mentioning to help the HA users from backing themselves into a corner when using the HA add-on provided via official store?

At minimum couldn't we at least update the firmware link to point to the deCONZ update instruction page instead of a directory of bin files?

**Comment by frenck** [comment]
This page is about integration, not an add-on...

Either way, this is not the correct place to add it, as the integration doesn't care about your firmware.

**Comment by bverkron** [comment]
What is the distinction between the add-on and the integration from a documentation perspective? The doc talks about both equally and says things like:

> Recommended way of running deCONZ
> An official add-on for deCONZ is available in the Home Assistant add-on store.

> Go to Settings → Gateway → Advanced → Authenticate app in the Phoscon App
(this is done via the official add-on)

The integration may not technically care about the firmware but the doc suggests updating it before reporting issues. Yet, there is insufficient instruction provided and a prevalent firmware update button in the UI along side other settings the doc talks about. IMO it's helpful to everyone to provide at least a comment about the button not working (regardless of the reason). It will save the users of the official add-on/integration headache and the devs and community members time having to address / troubleshoot issues that come up because of it.

If doc for the official add-on isn't the place to mention features within it that are broken then where is?

**Comment by frenck** [comment]
This part of the documentation describes what it hooks up too and what is needed for that. It documentation how to "integrate" as it is an integration. This is not related to dresden's inability to update firmware on their internals and thus not belong here.

As said before, the part you are trying to add does not belong here and is a bug which should be reported and solved by dresden.

**Pull request closed without merging**
