### PR TITLE
Update sensor.pvoutput.markdown

### PR DESCRIPTION
**Pull request by Marcel030nl**
**Description:**
Used the {% raw %} tag.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

### CODE REVIEW

**Comment by Landrash** [comment]
@Marcel030nl Have you tested this one locally? Always recommended and I made that assumption with your original pull request.

**Comment by Marcel030nl** [comment]
Hi @Landrash. I have not tested this locally; only the preview-mode in github. I'm not a developer (or experienced github user) but I want to contribute to the documentation. I expected that my changes would be verified by a reviewer.

If there is a way to test these content changes I'm willing to set this up. The current live page does not show these importent raw-tags. I hope we can fix this together.

**Comment by Landrash** [comment]
No problem.  I'll test it locally before merging 😊

**Comment by Marcel030nl** [comment]
Thank you.
Looking forward to see this patch live as the current information (=live site) is not correct.

**Pull request merged**
