### PR TITLE
Templating: open external links in new tab

### PR DESCRIPTION
**Pull request by ThomDietrich**
Not sure if Kramdown is supported by the used rendering engine. Please test! Thanks

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Hello @klaasnicolaas,
PR is already against current and another meta change. 
On second thought. You or one of the other main contributors/maintainers should discuss how to deal with external facing links in general. For sure the links in this PR are not the only ones and maybe a more systematic and sustainable solution to this issue can be found. Food for thought. Best!

**Comment by klaasnicolaas** [comment]
@frenck what are your thoughts on this PR?

**Comment by frenck** [comment]
We don't use Kramdown.

image

We have discussed the opening of external links in a new window in the past, at the time we decided not to do that.

However, if we wanted to, it would be an easy adjustment to do that globally.

For reference: <https://github.com/home-assistant/home-assistant.io/blob/next/plugins/output_modder.rb#L18>

**Comment by ThomDietrich** [comment]
Thanks for the answer and testing Franck.

> However, if we wanted to, it would be an easy adjustment to do that globally.

You say this and closed the PR. Are we going to track this topic in another issue or who is going to build a PR for this?

**Edit:**

> at the time we decided not to do that.

I'd suggest to reevaluate this now. The current behavior is not to norm and feels immature

**Comment by frenck** [comment]
> You say this and closed the PR. 

Yes, this PR does not work as intended.

> Are we going to track this topic in another issue or who is going to build a PR for this?

I don't see a direct reason for this, but feel free to open up an issue to discuss this.

> I'd suggest to reevaluate this now. The current behavior is not to norm and feels immature

I don't agree with that call, especially since you didn't elaborate on any reasoning for it.

**Comment by ThomDietrich** [comment]
Closing the PR was the right call.
I didn't give a reason as I thought it's basically clear and I like to keep discussions short and action-oriented.

That's an oversight on my side, sorry for that. I'll open a proper issue to start a discussion.

**Comment by ThomDietrich** [comment]
I'm always willing to accept new facts.

According to this source https://css-tricks.com/use-target_blank/#article-header-id-2 it is in fact not correct to generally change the default behavior for "external" links.

I'll rest my case ;)

**Pull request closed without merging**
