### PR TITLE
Add UPB service descriptions

### PR DESCRIPTION
**Pull request by gwww**
## Proposed change

Add descriptions for custom services.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [X] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/34692
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by frenck** [comment]
Is there a parent PR for this?

**Comment by gwww** [comment]
Added

**Comment by gwww** [comment]
Not sure I was clear. The code is already merged. Docs are coming in late as I didn't know that custom service docs should be added.

**Review by frenck — APPROVED** [review]
Thanks, @gwww!

I've made a tiny adjustment and changed entity_id to be optional.
Since this integration uses `async_register_entity_service` it means that a user can target these entities using areas as well, hence entity ID is optional.

**Comment by gwww** [comment]
Thank you @frenck. I appreciate all the hard work that you and the rest of the contributors do!

**Pull request merged**
