### PR TITLE
media_extractor: add cookie file docs (pending pr in core)

### PR DESCRIPTION
**Pull request by RickeyWard**
## Proposed change

Added cookie file support to media_extractor core component, this is only relevant should that get accepted and merged.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: <edit after other pr is created they both want references to each other>
- Link to parent pull request in the Brands repository: NONE
- This PR fixes or closes issue: fixes NONE

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by c0ffeeca7** [comment]
Hi, @RickeyWard 
Thank you for contributing! :tada: 
As this doc change depends on a parent PR being merged in the future, please base it against the `next` branch.
Then, mention [#104973](https://github.com/home-assistant/core/pull/104973) under *Link to parent pull request in the codebase*

**Comment by frenck** [comment]
I've marked this PR, as changes are requested that need to be processed.
Please un-draft it once it is ready for review again by clicking the **"Ready for review"** button.

Thanks! 👍 

../Frenck

[_Learn more about our pull request process._](https://developers.home-assistant.io/docs/review-process#prs-are-being-drafted-when-changes-are-needed)

**Comment by RickeyWard** [comment]
Just to be clear, if this is suppose to target _next_ should I rebase on _next_ and then close this and start a new PR against next?

**Comment by RickeyWard** [comment]
I apologized for the inconvenience, I changed the target to next and rebased on upstream/next but the diff is looking really odd. I'm going to restart this PR

**Pull request closed without merging**
