### PR TITLE
Added links for web addresses

### PR DESCRIPTION
**Pull request by cvwillegen**
**Description:**

The documentation for the DSMR sensor has a couple of links to external web sites. These were not enclosed by tags, so a user couldn't click on those links to go to the intended pages.

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [X] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
@cvwillegen Thanks for noticing!

Please note, we use Markdown. While HTML is valid, we should always prefer the Markdown methods when possible. I've updated the PR to use the Markdown annotations, and also fixed another link.

**Comment by cvwillegen** [comment]
@frenck Thanks for the tweaks! Anything I need to do before this is reviewed and (hopefully...) merged?

**Comment by frenck** [comment]
@cvwillegen Will pick it up from here 😉

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
@cvwillegen Thanks for the PR! 👍

**Pull request merged**
