### PR TITLE
Mention Evergy is now supported by the Opower integration

### PR DESCRIPTION
**Pull request by tronikos**
## Proposed change

Mention Evergy is now supported by the Opower integration

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/96506
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by joostlek** [comment]
Just saw the page and wanted to say a general notice, the page is saying "More than 175 utilities use Opower.' shouldn't that be utility companies?

**Comment by tronikos** [comment]
It seems both are correct

https://www.oracle.com/industries/utilities/opower-energy-efficiency/ says: "More than 175 utilities help customers reduce energy usage with the Opower home energy reports..."

https://en.wikipedia.org/wiki/Opower says: "Opower was an American company founded in 2007, that provides a software-as-a-service customer engagement platform for utilities." 

https://en.wikipedia.org/wiki/Public_utility says: "A public utility company (usually just utility) is an organization that maintains the infrastructure for a public service (often also providing a service using that infrastructure)."

**Comment by joostlek** [comment]
Oh I did not know, thanks for the clarification!

**Review by c0ffeeca7 — APPROVED** [review]
LGTM. thank you, @tronikos :+1:

**Pull request merged**
