### PR TITLE
docs(command_line): Commands missing template type

### PR DESCRIPTION
**Pull request by rpatterson**
## Proposed change

Fix the reference documentation for the `command` fields that are missing the `template` type.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

### CODE REVIEW

**Comment by gjohansson-ST** [comment]
`notify` doesn't seem to a template?

**Comment by rpatterson** [comment]
> `notify` doesn't seem to a template?

Details? Actually, NM. I made assumptions.

**Comment by gjohansson-ST** [comment]
It was correct to change this for `sensor` and `binary_sensor` so too bad you deleted the PR.
If you want please make a new one but exclude `notify` then.

**Comment by rpatterson** [comment]
> It was correct to change this for `sensor` and `binary_sensor` so too bad you deleted the PR. If you want please make a new one but exclude `notify` then.

Ah, thanks for the detail, @gjohansson-ST. That really helps me understand your previous comment better. At the time, that detail would have helped me correct my PR.

Not so much from this PR but other participation and contribution, the HA community vibe makes it a place where I can't afford to put in more time and effort. I'm demoting myself to "lurking user" in the HA world, so no more clicking the "Edit" button for me! A shame given that I'm a big fan of the "if you see something, fix something" ethic. Best of luck!

**Pull request closed without merging**
