### PR TITLE
Update fan documentation for entity model separation of fan speeds into percentages and presets modes

### PR DESCRIPTION
**Pull request by bdraco**
## Proposed change

Update fan documentation for entity model separation of fan speeds into percentages and presets modes

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/45407
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by bdraco** [comment]
Marking as draft until the `preset_mode` concern is addressed

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by bdraco** [comment]
Procedurally, I'm not sure if this needs to wait until after release to merge since we are now in beta since it shouldn't go out until .3

**Comment by frenck** [comment]
The documentation follows the same procedures as the core repository.
The documentation for the beta and thus .2 is now in the `rc` branch. The `next` branch tracks the Core's `dev` branch.

**Comment by bdraco** [comment]
> The documentation follows the same procedures as the core repository.
> 
> The documentation for the beta and thus .2 is now in the `rc` branch. The `next` branch tracks the Core's `dev` branch.

Thanks!

**Pull request merged**
