### PR TITLE
Add a diagram of the components to help understand the different installation types

### PR DESCRIPTION
**Pull request by lawm**
## Proposed change
I think a diagram of the components would help people understand the different installation types.

I created a diagram with diagrams.net (free, no account needed).  The 'source' of the diagram is checked in as the components.draw.io file.

## Type of change
- [x] Added a diagram to the Installation page (`current` branch).

## Additional information
Please review the diagram and the HTML/CSS part.

## Checklist
- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @lawm, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#17670).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by lawm** [comment]
screenshot 
image

**Comment by frenck** [comment]
This belongs in our developer documentation, this is not material for an end user.

We have parts for this already at: https://developers.home-assistant.io/docs/architecture_index


Besides, this diagram is incorrect. For example a Supervised installation has the same system dependencies as the Home Assistant Operating System.


I am going to close this on this end of the docs.

**Comment by lawm** [comment]
Ok, I missed the dev docs.
I still think the user docs on installation could be clearer, but I don't have any suggestions at the moment.

**Pull request closed without merging**
