### PR TITLE
Set-up a plant by specifying one device name

### PR DESCRIPTION
**Pull request by Djebouh**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#23889

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Please cleanup the unrelated commits and rename the PR

**Review by frenck — CHANGES_REQUESTED** [review]
@Djebouh There are a lot of unrelated commits in this PR.
Could you please rebase this PR to clean it up?
Thanks already! 👍

**Comment by Djebouh** [comment]
@frenck rebase just done
Thanks for your advise

**Comment by Djebouh** [comment]
home-assistant/home-assistant#23889 has been rejected

**Pull request closed without merging**
