### PR TITLE
Add new sensors to the palazzetti integration

### PR DESCRIPTION
**Pull request by dotvav**
## Proposed change

This PR adds new sensors to the Palazzetti doc, in relation with https://github.com/home-assistant/core/pull/130800

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/130800
- Link to parent pull request in the Brands repository: N/A
- This PR fixes or closes issue: fixes N/A

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

## Summary by CodeRabbit

- **Documentation**
	- Updated the Palazzetti integration documentation for improved clarity and completeness.
	- Corrected spelling of "Palazzetti" in the climate entity section.
	- Enhanced functionality description to include stove control features.
	- Added a new section detailing supported sensors and their capabilities, such as temperature readings and pellet quantity.

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @dotvav 👍 

../Frenck

**Comment by dotvav** [comment]
@frenck FYI the parent PR isn't merged yet.
https://github.com/home-assistant/core/pull/130804

**Comment by frenck** [comment]
@dotvav 

CleanShot 2024-11-22 at 09 53 19@2x

☝️ the cause

**Comment by dotvav** [comment]
@frenck Oh, my. I copied the wrong PR link. Should I make a revert PR or we wait for someone to confirm @zweckj 's review?

**Comment by frenck** [comment]
Fixed 😉

**Pull request merged**
