### PR TITLE
yaml.markdown: Link configuration.yaml at first usage

### LINKED ISSUE #28924: Where to find the configurtion.yaml....
### Feedback

Would be great if it would be mentioned were the configuration.yaml is located / stored if there is e.g. a build in tool to edit the file , e.g. via the web front end...

### URL

https://www.home-assistant.io/docs/configuration/yaml/

### Version

2023.9.2

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by reedy**
## Proposed change

Link to configuration.yaml's documentation at first usage

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #28924

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by klaasnicolaas — CHANGES_REQUESTED** [review]
I don't think we need to merge this change, but that's mainly because we don't use text in single quotes as a link.

**Comment by frenck** [comment]
> because we don't use text in single quotes as a link.

I think we do?

Looking at this, I think it is smart and could be applied to any occurrence of `configuration.yaml`, as it provides help and more context to the ones that need it.

**Comment by reedy** [comment]
> > because we don't use text in single quotes as a link.
> 
> 
> 
> I think we do?

Pretty sure there's a few examples around, and not just what I may have introduced...


> Looking at this, I think it is smart and could be applied to any occurrence of `configuration.yaml`, as it provides help and more context to the ones that need it.

Usually I find if it's a question that one newer person has had, it's a question that many others have had. And things you can do to make onboarding better/easier is always a good thing.

Can we do this a bit more automatically? Like as a build step, doing a string replace?

I suspect there might be a few other similar ones that could be beneficial.

Or would it require at least changing all usages/mentions like this into a template/variable or similar?

**Comment by frenck** [comment]
> Can we do this a bit more automatically? Like as a build step, doing a string replace?

We should not. It can also be used in code snippets.

**Comment by reedy** [comment]
You mean you don't want to write a backtracking regex to look for whether we're in a code block? ;)

**Comment by frenck** [comment]
> You mean you don't want to write a backtracking regex to look for whether we're in a code block? ;)

I mean we should just use Markdown and don't rely on magic.

**Comment by reedy** [comment]
Can this be merged then, as is?

**Comment by frenck** [comment]
We are awaiting @klaasnicolaas, he left this review. Please have patience, as most people do this in their spare time.

../Frenck

**Comment by klaasnicolaas** [comment]
> I think we do?

I indeed see that we are applying it on more places, but that is more sporadic. Of course it is a good improvement, but perhaps we need to be consistent in how we handle links and highlighted text... it can be confusing.

But otherwise this PR is good to go for merging.

**Comment by frenck** [comment]
Alright, so agreed we can move forward I guess.

That said, this change is invalid nevertheless, as it links to itself 😉 

../Frenck

**Comment by reedy** [comment]
Copy paste is hard (sometimes)!

**Review by frenck — COMMENTED** [review]
Thanks, @reedy 👍 

../Frenck

**Review by frenck — APPROVED** [review]
Thanks, @reedy 👍 

../Frenck

**Comment by reedy** [comment]
I'll have a bit of a think about proliferating this a bit more throughout the other doc pages. Though, maybe as I'm making changes to other docs for other reasons, I can include a similar change to this too.

A very quick search suggests there's over 2000 mentions of the string `configuration.yaml` alone. But as you mention, numerous in code samples as parts of comments etc etc.

**Pull request merged**
