### PR TITLE
Add my repository of configuration files

### PR DESCRIPTION
**Pull request by jonathanadams**
**Description:**
Adding another github location of example configuration files. Hopefully people will find them useful as I'm busy expanding my deployment and experimenting with new hardware and features.

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
This is something for the `current` branch

**Comment by jonathanadams** [comment]
Do I need to submit a new pull request or will someone rebase? I am quite new to git.

**Comment by klaasnicolaas** [comment]
It doesn't matter to us, although we prefer a rebase. But since you are still new with Git, a new PR is also fine.

**Comment by jonathanadams** [comment]
See PR #9406

**Pull request closed without merging**
