### PR TITLE
Add more specific SimpliSafe authorization code instructions

### LINKED ISSUE #20024: Not understanding what code to use?  I assume the code in the URL after the email from SS?
### Feedback

Tried the code in the url and it does not work.
https://tsv.prd.platform.simplisafe.com/v1/tsv/confirm?code=xxxxxx.x.xx...........
I used the information after code=xxx and got invalid authentication
### URL

https://www.home-assistant.io/integrations/simplisafe/

### Version

2021.10.6

### Additional information

Updated integration, deleted, tried to reinstall and code fails.

### LINKED ISSUE #20165: SimpliSafe documentation is unclear on 2021.11.0 Core
### The problem

Upgraded to new Core version today and my SimpliSafe integration that was working stopped working. I would try to use the authcode and it would say invalid. 
I rolled back and did a restore to core-2021.10.6, and I was able to re-verify and get it working with no issues.

### What version of Home Assistant Core has the issue?

core-2021.11.0

### What was the last working version of Home Assistant Core?

2021.10.6

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

SimpliSafe

### Link to integration documentation on our website

_No response_

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bachya**
## Proposed change

My latest SimpliSafe docs were Safari-centric (since that's the browser I use). This PR updates things to add more clarity for users of other browsers.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: N/A
- Link to parent pull request in the Brands repository: N/A
- This PR fixes or closes issue: https://github.com/home-assistant/home-assistant.io/issues/20024 and https://github.com/home-assistant/home-assistant.io/issues/20165

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by flatfooted** [comment]
I am still unable to authenticate using the webapp code.  I have updated to the latest home assistant.  I reviewed his changes to the documentation and it is still not working.  I found the url with the code variable and it does not authenticate.  The error message Invalid Authentication appears when submitting the webapp code from the url.

**Comment by bachya** [comment]
@flatfooted Please provide exact steps and screenshots.

**Comment by flatfooted** [comment]
Ok so it worked in Chrome.  I tested it out on Firefox, iOS and Chrome.  Both Chrome and Firefox were used on a laptop.  I had to inspect the page that was trying to be launched in Chrome and copy the code variable from there.

**Comment by bachya** [comment]
@flatfooted FWIW, those are the instructions that this PR will add to the docs.

**Comment by mcdan** [comment]
Thanks for the write up! For me running Firefox 94.0.1 on OSX it did not give me a URL with `code` in the url params. However on Chrome 95.0.4638.69 on the same OSX machine it worked great. Thanks for keeping all these docs up to date.

**Review by frenck — APPROVED** [review]
Thanks, @bachya 👍

**Pull request merged**
