### PR TITLE
List ZigStar UZG-01 Zeconf Availability

### PR DESCRIPTION
**Pull request by mercenaruss**
## Proposed change
List ZigStar UZG-01 Zeconf domain

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:  https://github.com/home-assistant/core/pull/98657
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Please rebase your branch to the `next` branch

**Comment by mercenaruss** [comment]
> Please rebase your branch to the `next` branch

Not really familiar with rebase git,but i think i rebased to next branch.
If not give me please a dummy instruction.

**Comment by frenck** [comment]
> > Please rebase your branch to the `next` branch
> 
> Not really familiar with rebase git,but i think i rebased to next branch. If not give me please a dummy instruction.

Unfortunately, you didn't. It seems like you just changed the target branch and didn't git rebase the PR. This is visible by the amount of unrelated commits now in this PR:

CleanShot 2023-08-20 at 13 57 18

If you don't know how to rebase, I suggest to close this PR and create a new one that originates from the `next` branch directly instead.

../Frenck

**Comment by puddly** [comment]
@mercenaruss Can you please open a new pull request with this change against the `next` branch?

**Pull request closed without merging**
