### PR TITLE
Create automation_knx.markdown

### PR DESCRIPTION
**Pull request by Jpsy**
The KNX information for HA is rather rudimentary and there are more open questions than answers. 
Even if I am a beginner, I think it is a good idea to share my findings.
This knowledge will grow fast and I will keep this overview updated.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by adonno — CHANGES_REQUESTED** [review]
This is currently a general KNX configuration. This is already explained in the KNX components. 
As there is no automation currently in it , the title might be misleading. Please add the automation. 

I would also change the name of the different components to English ones.

**Review by adonno — APPROVED** [review]

**Comment by adonno** [comment]
@Jpsy mind getting in touch with me ? in the home assistant discord or via twitter ?

**Review by adonno — DISMISSED** [review]

**Comment by Jpsy** [comment]
I have now added the first basic KNX automation example. More complex stuff will follow.
I actually thought about translating the names but decided against it for two reasons:
* Keeping the names in German nicely differentiates between HA terms and arbitrary names. It also shows how HA slugifys names to entity_ids and handles special characters in the process.
* More important: These examples are taken from my own installation with only minor simplifications. So they are working and tested. Translating names would change entity_ids and would create a great risk of breaking the examples. Maintaining the examples as my own installation evolves would also become much more challenging. I consider this price to high for the gain.

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Thanks, @Jpsy 👍

**Comment by Jpsy** [comment]
Very welcome Fr(e|a)nck. :)
Thanks for brushing it up a bit.
I will add more examples soon while I further explore HA.

**Pull request merged**
