### PR TITLE
Correct link to /integrations/media_source

### PR DESCRIPTION
**Pull request by NateRobinsonS**
Fixed link to the "Media Source" integration.  Link is now /integrations/media_source.  It was (incorrectly) /integrations/media-source.

## Proposed change

Fixed broken link to /integrations/media_source

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @NateRobinsonS, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#20692).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by allenporter** [comment]
Thank you for this!

I do have a pending or that is fixing this in https://github.com/home-assistant/home-assistant.io/pull/20656 and the surrounding text.

**Comment by allenporter** [comment]
The other PR was submitted which contains this fix so should not be needed now. Thank you for the fix, however!

**Comment by NateRobinsonS** [comment]
Thanks for the update.  I should have checked for an open PR first.

-Nate

**Pull request closed without merging**
