### PR TITLE
Update manual.markdown

### PR DESCRIPTION
**Pull request by 0n3man**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
Hi there, @0n3man!

Could you please elaborate on this change?

Thanks 👍

**Comment by 0n3man** [comment]
The example from the web page is incorrectly using ha_alarm in a few places when it should be using home_alarm.  Once I changed this variable the example works.

**Comment by frenck** [comment]
?

That depends on your system. Every system can have a different entity IDs. This serves merely as an example...

Adjusting examples to ones personal setup is not something we should do 😉 

Thanks for contributing, but this does not need adjustment.

**Comment by 0n3man** [comment]
I think you're mistaken.  That example is associated with alarm_control_panel.   The variable ha_alarm isn't part of the alarm_control_panel and so anyone trying to make this work will not be able to get it going. Being that I'm new to this maybe there is some other related component that would bring in ha_alarm.  If that's the case then the example should make that clear.  So one way or another their should be something that makes this clear or your example is simply causing people to waste time.

**Comment by frenck** [comment]
`ha_alarm` isn't a variable, it is an entity ID, which is different for everybody. It can be manually changed or be different depending on the integration used...

I'm sorry, no mistake.

For example, in my case, it is `alarm_control_panel.huis` which is also not the example, and does not match your change either.

**Comment by 0n3man** [comment]
Trying one last time.  The page https://www.home-assistant.io/integrations/manual/ has 7 code examples that work together.  5 of them use the entity id of alarm_control_panel.home_alarm, two of them use alarm_control_panel.ha_alarm.  So the totality of the example does not work.  The change just makes the example code consistent so the examples will work together.

**Pull request closed without merging**
