### PR TITLE
Add information to use Freebox Delta cameras

### PR DESCRIPTION
**Pull request by nachonam**
Related to PR https://github.com/home-assistant/core/pull/88104

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/88104
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by Quentame — DISMISSED** [review]

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Review by frenck — CHANGES_REQUESTED** [review]
Oh, I just noticed.

This PR is targeting the `current` branch, however, it depends on a new feature in a PR in the Core branch, meaning it depends on a next/future release of Home Assistant. This PR should be targeting the `next` branch.

Please adjust the target branch of this PR to target `next` and git rebase your changes.

Thanks 👍 

.../Frenck

**Comment by Quentame** [comment]
@nachonam : may you reset the branch & only pick the interesting commit ?

**Review by frenck — CHANGES_REQUESTED** [review]
There are unrelated commits in this PR. Please git rebase your changes onto the `next` branch.

**Comment by nachonam** [comment]
Replaced by clear pull https://github.com/home-assistant/home-assistant.io/pull/27099

**Pull request closed without merging**
