### PR TITLE
Added TeddyCloud

### PR DESCRIPTION
**Pull request by g3gg0**
this change adds TeddyCloud, an open source Toniebox cloud replacement into the list

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by jbouwh — CHANGES_REQUESTED** [review]
I looks it is planned to use MQTT discovery. I does not seem this one fits in the list.

**Comment by g3gg0** [comment]
Thanks for your response.

TeddyCloud registers the devices (tonieboxes) in the household as MQTT sensors via the server, which also registers as a device.
Whenever a button is pressed or a title is played, HA gets updates via MQTT.

Where do you think it would fit better?

**Comment by jbouwh** [comment]
> Thanks for your response.
> 
> TeddyCloud registers the devices (tonieboxes) in the household as MQTT sensors via the server, which also registers as a device. Whenever a button is pressed or a title is played, HA gets updates via MQTT.
> 
> Where do you think it would fit better?

Is this documented? I cannot find this through the proposed link.

**Comment by jbouwh** [comment]
> Thanks for your response.
> 
> TeddyCloud registers the devices (tonieboxes) in the household as MQTT sensors via the server, which also registers as a device. Whenever a button is pressed or a title is played, HA gets updates via MQTT.
> 
> Where do you think it would fit better?

Say the documentation was updated. Let's merge it

**Review by jbouwh — APPROVED** [review]
LGTM,
Thnx @g3gg0 👍

**Comment by g3gg0** [comment]
yeah, we just merged develop into master and made a release.
<3 thanks for merging!

**Comment by g3gg0** [comment]
Just for completeness here a video of home assistant in action with a Toniebox, using TeddyCloud as server:
https://www.youtube.com/watch?v=WqVnnrtgd6k

It first shows three genuine tonies playing music on the Toniebox.
Then a NFC tag, triggering playback and setting volume on some HA-controlled playback device.
The latter use case is not "standard" and only possible with TeddyCloud.

**Comment by jbouwh** [comment]
Nice

**Pull request merged**
