### PR TITLE
Shelly battery powered devices are now fully supported

### PR DESCRIPTION
**Pull request by thecode**
## Proposed change

Shelly battery powered devices are now fully supported

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/45406
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: https://github.com/home-assistant/core/issues/40276

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — APPROVED** [review]

**Comment by luckyzor** [comment]
@frenck hello, first of all, congrats to you and all contributors for your hard work! c
an you tell me when this fix will be available?

thank you in advance.

**Comment by frenck** [comment]
Next release.

**Comment by denniswham** [comment]
I assume you mean 2021.3.0. Or 2021.2.2 (pretty please 😉)? And indeed many thanks to the contributors for the hard work!

**Comment by thecode** [comment]
2021.3.0

**Comment by frenck** [comment]
@denniswham Its a new feature, those never end up in patch releases.

**Comment by luckyzor** [comment]
Concerning this feature, will it need cloud enabled?

Because for the recognition of light or socket it appears we need to use the cloud and I didn't found any information about that

**Comment by frenck** [comment]
@luckyzor If you has support questions, please use or community forum or discord chat. We like to keep PRs on topic of the code.

**Pull request merged**
