### PR TITLE
Fix links to `device_class` for MQTT sensor

### PR DESCRIPTION
**Pull request by emontnemery**
**Description:**
Fix links to `device_class`

## Checklist:

- [x] Branch: Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by emontnemery** [comment]
The link generated by `type: device_class` is a bit misleading, could some magic be done so we could specify which list of device classes to link to?

**Comment by frenck** [comment]
Hmmm... ok we definitely should improve on this, however, I think we should avoid temporary changing it to the string type.

If we change it now, they will be harder to find if we have a real fix for it.

**Comment by emontnemery** [comment]
@frenck OK, makes sense, I reverted to `device_class`

Btw, and unrelated to this PR, the MQTT docs is really hard to read due to so many options.
Do you think it would make sense to simply sort the options alphabetically?

**Review by frenck — APPROVED** [review]
Thanks, @emontnemery!

Happy Hacktoberfest 🎉

**Comment by frenck** [comment]
About the additional comment, I like it!
Will hook up on Discord about it.

**Pull request merged**
