### PR TITLE
Added time_format, trim_leading_zero

### PR DESCRIPTION
**Pull request by iprak**
## Proposed change

The [WorldClock ](https://www.home-assistant.io/integrations/worldclock/) sensor generates time in the fixed "%H:%M" format. This PR addes the capability to define a custom format.

- Allow defining custom format instead of the default  "%H:%M"
- Allow removing leading zeros e.g. 9:30 PM instead of 09:30 PM

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/36157
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This PR depends on a feature that has a parent PR in the core codebase of Home Assistant, and therefore depends on the next release of Home Assistant.

Please adjust this PR to target the `next` branch and git rebase the PR if needed.

Thanks 👍

**Comment by iprak** [comment]
I did initially submit a PR ([13592](https://github.com/home-assistant/home-assistant.io/pull/13592)) on _next_ but the probot-home bot commented that I should use current branch so I closed that request. I have reopened that PR; this is my first PR on home-assistant so I must have messed up something.

**Comment by frenck** [comment]
The bot was telling to either adjust the branch or add a link to the parent PR... in this case, there is a parent PR and a link was needed.

This PR still needs to be git rebased onto, and targeted against the `next` branch.

**Review by frenck — APPROVED** [review]
Thanks, @InduPrakash 👍

**Pull request merged**
