### PR TITLE
Slit ZHA Recommended from Other Supported Adapters

### PR DESCRIPTION
**Pull request by Hedda**
## Proposed change

Slit ZHA Recommended Adapters from Other Supported Adapters into two suggestions as per feedback from @puddly.

> The technical reasons for why some some adapters are better-supported than others don't belong in user documentation but this PR is correctly ordering them. I don't want to encourage people to buy anything but TI, SiLabs, or a Conbee (in that order) and expect a smooth experience with ZHA.
> 
> Perhaps we can instead split this into two sections: "Recommended Adapters" and a less-prominent "Other Supported Adapters" (or something similar)?

With this PR the "**_Recommended Zigbee radio adapters and modules_**" section with modern/newer hardware from Silicon Labs, Texas Instruments, and Dresden Elektronik, then an "**_Other support but not recommended Zigbee radio adapters or modules_**" section with legacy/older   hardware from Silicon Labs, Texas Instruments, and Dresden Elektronik, as well as Digi XBee and ZiGate.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
You already had a PR open for this one. Please close this PR and update the other one instead. 

Thanks 👍 

../Frenck

**Comment by frenck** [comment]
@Hedda Friendly notification to process the review comment on this PR. Thanks! 👍

**Comment by Hedda** [comment]
@frenck The old PR was locked by github-actions bot so I can not reopen that old PR myself, please see ->https://github.com/home-assistant/home-assistant.io/pull/23895

**Comment by klaasnicolaas** [comment]
Reopened and unlocked the conversation

**Comment by Hedda** [comment]
Closing this as https://github.com/home-assistant/home-assistant.io/pull/23895 been reopened and updated.

**Pull request closed without merging**
