### PR TITLE
Update Z-Wave documentation OpenZWave 1.4

### PR DESCRIPTION
**Pull request by pauldegraaff**
## Proposed change

Update to the Z-Wave integration documentation to inform users that this integration is based on OpenZWave 1.4, which is EOL since 2019. And that there is a new Z-Wave Home Assistant integration named OpenZWave (beta) which is based on OpenZWave 1.6.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by firstof9 — COMMENTED** [review]
This seems reasonable to me.

**Review by firstof9 — DISMISSED** [review]

**Review by firstof9 — APPROVED** [review]
That looks better.

**Comment by frenck** [comment]
Duplicate of #15533

**Comment by pauldegraaff** [comment]
No it is not a duplicate.

**Comment by frenck** [comment]
Yes it is.

**Comment by pauldegraaff** [comment]
> 
> 
> Yes it is.

It is a complete different file "control-panel.markdown " versus "zwave.markdown"

**Comment by pauldegraaff** [comment]
@frenck can you re-open this. It really is a complete different file/subject as compared to the one you linked. This is an update to the actual z-wave integration page. I am busy linking z-wave main / z-wave integration and the OpenZWave (beta) to each other with this information.

**Pull request closed without merging**
