### PR TITLE
Update lock.nuki.markdown

### PR DESCRIPTION
**Pull request by franfos**
**Description:**
Updated documentation to reflect the changes on the Nuki lock component on PR  #21030

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#21030

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
I think this is something for in the `next` branch

**Comment by franfos** [comment]
Yes, you are right. I didn't check destination branch. First commit. How can I solve it?

**Comment by klaasnicolaas** [comment]
That is not how it works 😉 Make on your fork a new branch of the `next` branch, do your commits and make a new PR here.

**Comment by franfos** [comment]
> That is not how it works 😉 Make on your fork a new branch of the `next` branch, do your commits and make a new PR here.

Ok, thanks. I will do that way. I'm waiting for the acceptance of the PR #21030
I've closed this PR. Do I have to do anything else with it? Remove it?

**Comment by klaasnicolaas** [comment]
No, only open a new PR for the documentation and we will help you further 😉

**Pull request closed without merging**
