### PR TITLE
Add timeout information about shutdown trigger

### PR DESCRIPTION
**Pull request by tetele**
## Proposed change

It's a good idea to inform users about the fact that they have only so much time to run automations triggered by Home Assistant shutting down, as a result of [this PR](https://github.com/home-assistant/core/pull/91165).

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/91165
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by tetele** [comment]
> It seems that this PR is targeted against an incorrect branch since it has a parent PR on one of our codebases. Documentation that needs to be updated for an upcoming release should target the next branch. Please change the target branch of this PR to next and rebase if needed.

I'm not sure how to go about this. I've fixed a bug that requires some documentation. Should I really rebase against next?

**Review by frenck — CHANGES_REQUESTED** [review]
> I'm not sure how to go about this. I've fixed a bug that requires some documentation. Should I really rebase against next?

Yes, this documentation change depends on a PR in the Core repository that will be in a future (next) release of Home Assistant. For that reason, this PR should target and be based on the `next` branch.

Please change the target of this PR to `next` and git rebase your changes onto the `next` branch.

Thanks! 👍 

../Frenck

**Comment by tetele** [comment]
Yeah, sorry for the notifications everybody, I didn't know you can't change the branch you want to merge into when doing a pull request.

**Comment by tetele** [comment]
Replaced with https://github.com/home-assistant/home-assistant.io/pull/26987

**Pull request closed without merging**
