### PR TITLE
Update Eight Sleep Docs

### PR DESCRIPTION
**Pull request by mezz64**
Include requirement for at least two prior sleep sessions, update sensor list.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

### CODE REVIEW

**Comment by Landrash** [comment]
@mezz64 Is this associated with a PR or is it live already?

**Comment by mezz64** [comment]
It's already live. There were some changes during the PR process that didn't get reflected in the docs.

**Comment by Landrash** [comment]
Could you rebase this on the current branch so we can push it out asap? :)

**Comment by mezz64** [comment]
I was having a hard time getting this rebased to current so i'm going to close this one and PR #2599 should be good to go.

**Pull request closed without merging**
