### PR TITLE
Update thinkingcleaner docs with static ip option

### PR DESCRIPTION
**Pull request by MansM**
Replaces: https://github.com/home-assistant/home-assistant.io/pull/12304

functional change is: https://github.com/home-assistant/core/pull/32542
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue:

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Please document configuration options using a configuration block on both the sensor & switch.

For more information see our developer documentation: <https://developers.home-assistant.io/docs/documentation_create_page#configuration>

**Comment by frenck** [comment]
@MansM I've seen you've been updating the PR.

Please note, you must add a configuration block to each platform. So add it twice, to both the switch and sensor. Thanks 👍

**Comment by MansM** [comment]
@frenck I am a bit in doubt on this. As most people are probably not give their device a static ip I kept it totally separate.

**Comment by frenck** [comment]
@MansM Is how we document, we prefer standards over exceptions. So please adjust.

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Pull request merged**
