### PR TITLE
Update Monoprice docs to reflect recent changes

### PR DESCRIPTION
**Pull request by OnFreund**
## Proposed change

No need to use spaces instead of source names anymore.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/35107
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
@OnFreund This PR depends on multiple parents?

So now one has merged... And we should do what?

Please separate each documentation change to match one parent PR.

Thanks 👍

**Comment by OnFreund** [comment]
This was originally a single backend PR but I was encouraged to split it up. Is it ok if I turn this into a draft and change back once the second PR is merged?

**Comment by frenck** [comment]
Well, @OnFreund, the problem is, we are less than 24 hours away from the beta cut. There is now a change in our main codebase that is documented in this PR. But there is also a change documented in this PR that is not in our codebase.

Please reduce this PR to match the merged parent PR and create a new one for the other parent PR that is still open.

**Comment by OnFreund** [comment]
@frenck done

**Review by frenck — APPROVED** [review]
Thanks, @OnFreund 👍

**Pull request merged**
