### PR TITLE
Update govee_ble supported devices list

### PR DESCRIPTION
**Pull request by Neekster**
## Proposed change

Improve govee_ble documentation to add two new supported devices that I confirmed to be working and add additional clarity and organization.

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

None of the above are applicable to this PR

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
There are unrelated commits in this PR

CleanShot 2022-08-04 at 13 40 00

Please git rebase your commits in this PR onto the latest `current` branch.

Thanks! 👍 

../Frenck

**Comment by Neekster** [comment]
@frenck I'm only seeing the one 'current' branch. 
image
image
image
image

**Comment by frenck** [comment]
@Neekster You need to git rebase... using `git`, not GitHub.

**Comment by Neekster** [comment]
> @Neekster You need to git rebase... using `git`, not GitHub.

I knew I was missing something obvious. I tried Git, but I'm way in over my head. I'll try to figure it out this weekend, but for now it might be better to either drop the changes or have you implement them. They're pretty minor, so if it's too much of a hassle for you, it's no big deal.

**Pull request closed without merging**
