### PR TITLE
Documentation for home-assistant/home-assistant#18227

### PR DESCRIPTION
**Pull request by emontnemery**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#18227

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. 
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by emontnemery** [comment]
Are the documentation changes OK to reflect the changes in home-assistant/home-assistant#18227?
The three versions of MQTT light are now a single platform with 3 supported configuration schemas.

Obviously, the configuration.yaml samples need to be updated and some wording rephrased.
But should the documentation source files also be renamed or restructured in some other way?

**Comment by fabaff** [comment]
It should be only documentation for "MQTT Light" (aka one page) and all three former platforms should be redirected to that page.

**Comment by emontnemery** [comment]
@fabaff OK, makes sense. How do I make the old pages redirect?

**Comment by tjorim** [comment]
You will need to add extra variables to the headers: https://developers.home-assistant.io/docs/en/documentation_standards.html#renaming-pages.

**Comment by emontnemery** [comment]
@tjorim Thanks!!

**Comment by emontnemery** [comment]
Documentation has been updated as suggested by @fabaff

**Review by balloob — APPROVED** [review]

**Pull request merged**
