### PR TITLE
Add platinum level to Hue integration

### PR DESCRIPTION
**Pull request by balloob**
**Description:**
Add quality scale level to Hue component.

Made possible by #6364

CC @fabaff 

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by fabaff — APPROVED** [review]
I will fix the conflict that will most likely occur later.

https://github.com/home-assistant/home-assistant.io/commit/53556a28d942aa92ec8269aa729f5373ba9bc77b

**Comment by Swamp-Ig** [comment]
Have found [an issue](https://github.com/home-assistant/home-assistant/issues/17025) that makes this not true. Sorry!

### [Silver](https://developers.home-assistant.io/docs/en/integration_quality_scale_index.html#silver)
* Raise PlatformNotReady if unable to connect during platform setup (if appropriate)

**Comment by balloob** [comment]
The Hue platforms are only set up if the bridge connection has been established correctly. This is done at the component level, hence a PlatformNotReady is not needed. See https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/hue/bridge.py#L61

**Comment by balloob** [comment]
Locked because no discussion in PRs.

**Pull request merged**
