### PR TITLE
Reduce weight of integrations page + list everything once

### PR DESCRIPTION
**Pull request by frenck**
## Proposed change

This PR focusses on reducing a bit of the integrations listing page, without major restructuring.

Currently, each integration is on the page for each category it is listed in.
This has been adjusted, the integration is just added to the javascript once, with a list of categories on each of them.

The search and filters have been adjusted to deal with that.

As a result, the all integrations page looks way cleaner, is less heavy and less data is transferred.

The downside of this, would be the missing categories on the cards. However, I'm not sure if that is a big "miss". Categories still do work (you can even still search for a category).

The magnitude of reduction: The list of integrations in the source is now 984 instead of 1556. That is more than 30% reduction, including the number of card elements displayed on the all integrations page.

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue:

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
Github seems to be having issues with external builds again (the actions failed a couple of times as well).

However, Netlify did build. Result for this PR can be found here: <https://5e5eee33cac6e200095e18d6--home-assistant-docs.netlify.com/integrations/#all>

**Comment by balloob** [comment]
Nice! Can we still have the main (1st) category on the card?

**Comment by frenck** [comment]
I did consider that to be honest. So some reasoning why I didn't :

- The category names on the card, do not match the slug that is displayed on the card. If you click on `Media Player` as the category, the card will show `media-player`. Fixable, but still.

Screen Shot 2020-03-04 at 01 41 56

- We don't have a rule or general use of: First listed element is the main category. Most of them are alphabetically sorted in the frontmatter. Fixable, but needs checking/adjusting ~900 pages.

**Comment by frenck** [comment]
I could branch of this PR and make a version that just picks the first category. Let's see what it does / how it looks.

**Comment by balloob** [comment]
I can write you a JS function btw to convert binary-sensor -> Binary Sensor.

**Comment by balloob** [comment]
I looked at it again, let's drop the category from the card.

**Pull request merged**
