### PR TITLE
Remove owner requirement for analytics

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Limitation has been removed with 2021.4.1 (https://github.com/home-assistant/frontend/pull/8842).

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by spacegaier** [comment]
`current` is correct as this is already live. No rebase required.

**Comment by hmmbob** [comment]
I don't think this should be removed, as the setting is still only visible for / configurable by admin users. The PR you refer to specifically mentions this. 

A change from _owner_ to _administrator_ makes sense to me, but completely removing it doesn't. I've answered multiple people who couldn't find the setting and weren't logged in as admin that this was the reason.

**Comment by spacegaier** [comment]
> 
> 
> I don't think this should be removed, as the setting is still only visible for / configurable by admin users. The PR you refer to specifically mentions this.
> 
> A change from _owner_ to _administrator_ makes sense to me, but completely removing it doesn't. I've answered multiple people who couldn't find the setting and weren't logged in as admin that this was the reason.

That's a very good point. I adjusted the PR.

**Review by frenck — APPROVED** [review]
Thanks, @spacegaier 👍

**Pull request merged**
