### PR TITLE
No longer valid

### PR DESCRIPTION
**Pull request by aidbish**
https://github.com/home-assistant/home-assistant.io/issues/9712

<a href="https://gitpod.io/#https://github.com/home-assistant/home-assistant.io/pull/9737"></a>

### CODE REVIEW

**Comment by frenck** [comment]
@aidbish Thanks, as a general tip: Prefix the issue number with "Closes" or "Fixes".

E.g. : `Closes #9712`

This causes the related issue to be closed by GitHub Automatically when the PR is merged.

**Review by frenck — CHANGES_REQUESTED** [review]
This is not enough, it has to be removed from the navigation as well.
The navigation bar still has the link to this page, causing a 404 now.

**Comment by aidbish** [comment]
@frenck Could you guide me to where i can edit the navigation part, i cannot see a edit on github for that part

Is this the area that needs removing. https://imgur.com/a/g5ybsYC

**Comment by frenck** [comment]
<https://github.com/home-assistant/home-assistant.io/blob/next/source/_includes/asides/hassio_navigation.html>

**Comment by aidbish** [comment]
https://github.com/home-assistant/home-assistant.io/pull/9740

**Comment by frenck** [comment]
@aidbish Please don't create separate PR's for those things. Instead, adjust this one.

**Comment by aidbish** [comment]
PR updated to remove navigation link

closes #9712

**Review by frenck — APPROVED** [review]
Thanks, @aidbish! 👍 

Good job there m8 🎖

**Pull request merged**
