### PR TITLE
Cleanup google assistant document

### PR DESCRIPTION
**Pull request by awarecan**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by frenck — DISMISSED** [review]

**Comment by frenck** [comment]
@awarecan Can you rebase this onto `current`? Since that should be the target base...

**Comment by awarecan** [comment]
This is for 0.80 release, should I target current?

**Comment by frenck** [comment]
@awarecan, Sorry, `next` is correct. I jumped on it too early.

**Review by DubhAd — APPROVED** [review]
👍

**Pull request merged**
