### PR TITLE
Update panasonic_viera markdown

### PR DESCRIPTION
**Pull request by dunstad**
This component works fine on my model, which hasn't been listed here yet. (TH-32ES500)

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by frenck** [comment]
Hi, @dunstad!

Thank you for this addition. Nevertheless, this PR is targeted against the wrong branch. Updates to the current release documentation must go into the `current` branch.

Please change the target branch and rebase if needed.

**Comment by dunstad** [comment]
Ah, sorry about that. I'll get it on the right one in a bit here.

**Comment by frenck** [comment]
Hi @dunstad,

You needed to rebase as well, which I've now done for you.

✅ Approved. Can be merged as soon as the build passes.

**Comment by dunstad** [comment]
Thanks for the help! I was having trouble getting the rebase done myself, so glad to have you beat me to the punch.

**Review by fabaff — APPROVED** [review]
Thanks :bird:

**Pull request merged**
