### PR TITLE
Improve Android TV Remote docs

### PR DESCRIPTION
**Pull request by Drafteed**
## Proposed change

Depends on https://github.com/home-assistant/core/pull/117126

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by tronikos** [comment]
I integrated some of your changes here in https://github.com/home-assistant/home-assistant.io/pull/32605 Thanks!

As mentioned in https://github.com/home-assistant/core/pull/116896 please limit your change to making url and app equivalent.

**Review by tronikos — APPROVED** [review]

**Comment by Drafteed** [comment]
@tronikos Thanks! I've edited the structure of the document a little bit. I also split the table with infos about apps into two sections, since it is not readable on a desktop due to long lines.

Before:



-----

After:

**Review by frenck — APPROVED** [review]
Thanks, @Drafteed 👍 

../Frenck

**Comment by Drafteed** [comment]
Thanks, @frenck 👍
As related https://github.com/home-assistant/core/pull/117126 is now merged, docs PR https://github.com/home-assistant/home-assistant.io/pull/32661 also need to be merged.

**Comment by frenck** [comment]
Thanks for that note @Drafteed.
Merged it as well 👍 

../Frenck

**Pull request merged**
