### PR TITLE
Added technical sensors

### PR DESCRIPTION
**Pull request by crallian**
## Proposed change

Updated documentation with added support for technical sensors.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: Pull request #31611 https://github.com/home-assistant/home-assistant/pull/31611

- This PR fixes or closes issue:

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by balloob** [comment]
It seems like you forked off `current` instead of `next` when you wrote your docs.

**Comment by klaasnicolaas** [comment]
Please perform a rebase, if you don't know how we can do it for you.

**Comment by crallian** [comment]
I am sorry, I realise that I must have started out in the wrong branch (current instead of next). I am not sure how to do a rebase, can you please help me?

**Comment by klaasnicolaas** [comment]
I did the rebase for you 😉

**Comment by crallian** [comment]
Wow, thank you klaasnicolaas!!

**Review by frenck — APPROVED** [review]

**Pull request merged**
