### PR TITLE
This variable

### PR DESCRIPTION
**Pull request by r-t-s**
## Proposed change

Add the 'this' variable for use in templates for scripts and automation.
It contains state information for entity.

See: https://github.com/home-assistant/core/pull/52774

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by r-t-s** [comment]
I update the description to include the PR for the code.
I had checked two boxes ... Current and New because I also updated some documentation from the current release at the same time. I am not sure if just updating this PR will allow the processing to proceed.

**Review by frenck — CHANGES_REQUESTED** [review]
There are unrelated commits in this PR, probably caused by this branch having `current` as its base.
Please git rebase this PR onto the `next` branch to clean it up.

**Comment by frenck** [comment]
image


Not merge, rebase 😬

**Comment by r-t-s** [comment]
I will need to re rlease this ... I have corrupted my branch

**Pull request closed without merging**
