### PR TITLE
Remove API Key instructions from Hydrawise docs

### PR DESCRIPTION
**Pull request by dknowles2**
## Proposed change

Remove the prerequisites section from the Hydrawise docs that discuss the need to obtain an API Key. This is no longer necessary with https://github.com/home-assistant/core/pull/106904 as you can now simply authenticate using username & password.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by joostlek** [comment]
Let's rebase this to current so we can get this in. If you ever notice that we forget to merge the docs (or label it for that matter) but the feature did, be sure to let us know on discord :)

**Comment by arohl** [comment]
> Let's rebase this to current so we can get this in. If you ever notice that we forget to merge the docs (or label it for that matter) but the feature did, be sure to let us know on discord :)

I note that because I authenticate via Apple, I don’t have a password. Does this mean I have to create a new account using my email address to use this integration now? Or is there some way to get the authentication dialog in the integration linked to the Apple authentication page?

**Comment by dknowles2** [comment]
> Let's rebase this to current so we can get this in. If you ever notice that we forget to merge the docs (or label it for that matter) but the feature did, be sure to let us know on discord :)

Done.

**Comment by dknowles2** [comment]
> > Let's rebase this to current so we can get this in. If you ever notice that we forget to merge the docs (or label it for that matter) but the feature did, be sure to let us know on discord :)
> 
> I note that because I authenticate via Apple, I don’t have a password. Does this mean I have to create a new account using my email address to use this integration now? Or is there some way to get the authentication dialog in the integration linked to the Apple authentication page?

Let's discuss in https://github.com/home-assistant/core/issues/116830#issuecomment-2094807709

**Review by klaasnicolaas — APPROVED** [review]
Thnx for making the changes in the docs 👍🏻

**Pull request merged**
