### PR TITLE
WIP: Update rfxtrx configuration variables section

### PR DESCRIPTION
**Pull request by tjorim**
Update all components for rfxtrx

### CODE REVIEW

**Review by fabaff — APPROVED** [review]
Thanks :bird:

**Comment by tjorim** [comment]
Please note it's still WIP.

**Comment by fabaff** [comment]
I know...

**Comment by frenck** [comment]
@tjorim Seems like this has been done already now?

**Comment by frenck** [comment]
Closing this PR, no response/stale.

**Pull request closed without merging**
