### PR TITLE
Update Nest Documentation back to Web Flow

### PR DESCRIPTION
**Pull request by devbdavis**
Note: This change should be reverted in the case the Desktop application flow can be supported. But is currently not supported and the community is seeking an updated set of instructions

## Proposed change

This change reverts the nest documentation back to the web auth flow, as the new Desktop Application flow is no longer supported

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information

Reverts(Note: manual revert with additions as a straight revert would not work here): https://github.com/home-assistant/home-assistant.io/commit/07729d6f00337a12bcf941747b3b1caf9212baec
Closes: https://github.com/home-assistant/core/issues/67662

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @brgaulin, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#22621).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by allenporter** [comment]
Thank you for sending this.

I don't recommend users go through this setup anymore as mentioned in the issue, its only for very advanced users.  That is, i used to spend hours per week answering questions about how to setup SSL.  In the issue, it has a link to current recommended instructions which are to apply a workaround, or do this complex SSL setup if you are advanced enough to know how to do it. The other PR to add the warning is a little more crisp in that regard about the current state and recommendations.

**Comment by devbdavis** [comment]
The challenge is, the warning means no one can setup nest integrations until this is resolved. And it has been going on for some time. Maybe we add a warning to this version that says, "We hope for a more simple install directions that don't require SSL to be available in the coming weeks"? 

Edit: Or maybe a note that this is nabu casa / advanced users only for the time being?

**Comment by devbdavis** [comment]
I'm also totally ok if this is 100% reverted as soon as soon as a different solution is available. If you know of one that is imminent(next month or so) We can definitely close this

**Comment by allenporter** [comment]
> The challenge is, the warning means no one can setup nest integrations until this is resolved

After discussion in https://github.com/home-assistant/home-assistant.io/pull/22610 I'm adding https://github.com/home-assistant/alerts.home-assistant.io/pull/525 which will add an alert to the top of the integration page that links to the github issue which links to the old version of the docs.

If we add this back to the official docs, even with caveats, it's still going to cause a lot of frustration and support effort from me, which I can't commit to. This is the rationale for why I've phrased the status the way I did in the github issue, to scare people away from trying to do this. (Basically, if you need the user friendly documentation then it's not for you, so I don't mind making it a little harder to get to -- and am working with Nest Developer Relations on the right solution for end users to get this resolved.)

**Pull request closed without merging**
