### PR TITLE
Update evohome.markdown

### PR DESCRIPTION
**Pull request by zxdavb**
Added info about Zones now being supported. Also a little tidy-up.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
@zxdavb I've rebased your PR onto the `current` branch.

Please note, updates to our current documentation, should originate from and go into the `current` branch. The `next` branch is for upcoming features and other changes that are related to the next release.

**Review by frenck — APPROVED** [review]

**Comment by MartinHjelmare** [comment]
This docs update is connected to https://github.com/home-assistant/home-assistant/pull/18428 which isn't merged yet.

**Comment by frenck** [comment]
@MartinHjelmare That is unfortunate, what would you suggest? Reverting this PR? (Well at least the part on the zones).

**Comment by MartinHjelmare** [comment]
Yeah, probably best to revert. I don't think the parent PR will go out in 0.83.

**Pull request merged**
