### PR TITLE
new NUT sensor 'output' variables

### PR DESCRIPTION
**Pull request by carlchan**
Added new output variables to example
Added example command line for 'upsc' to get list of NUT variables
Changed formatting of example output to more closely match actual 'upsc' output.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#15066

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
Hi there @carlchan,

thank you for the PR, nevertheless, since this is an documentation update of the `current` documentation, it should be branched of the `current` branch and targeting the `current` branch as wel.

Could you please update/rebase? 👍 

PS: A merge conflict appeared..

**Comment by carlchan** [comment]
@frenck I don't know if the output variable support has been merged into the current version of HA yet.  It's PR #15066 and approved but not yet merged, so should this still be going to current?

**Comment by frenck** [comment]
@carlchan Aah! You did not mention the PR, nor did you mention this PR on the parent PR. Please be sure to link them 😉 

Still.. there is a merge conflict left. Could you take a look?

**Review by fabaff — APPROVED** [review]
Thanks :bird:

**Pull request merged**
