### PR TITLE
Use bots to get the chat_id

### PR DESCRIPTION
**Pull request by magnushacker**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

### CODE REVIEW

**Comment by michaelarnauts** [comment]
Shouldn't it make sense to also keep the old instructions to not depend on 3th party bots?

**Comment by fabaff** [comment]
I would like to keep the different instructions. The way with a bot seems to be the easiest one but bots come and go...

**Comment by magnushacker** [comment]
Makes sense, I can revert the change and only add the information about the
ID bot.

Maybe an even better way would be to let the component discover the chat ID
itself? Is there a specific reason for requiring the user to provide the
chat ID in the config file?

**Comment by fabaff** [comment]
I picked the change.

**Pull request closed without merging**
