### PR TITLE
Add the Bittrex integration page

### PR DESCRIPTION
**Pull request by DevSecNinja**
## Proposed change

Add documentation for the new `bittrex` integration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [X] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [X] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/44618
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/2120
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by DevSecNinja** [comment]
Not sure why the bot thinks it should go to  `current` as it's a new integration.

**Comment by frenck** [comment]
You have not linked it up with a parent PR, thus it concludes it is not related to a code change.

**Comment by DevSecNinja** [comment]
> You have not linked it up with a parent PR, thus it concludes it is not related to a code change.

Thanks! I created this PR first but it's linked now.

**Review by frenck — DISMISSED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

**Comment by frenck** [comment]
Closing this PR as the parent PR has been closed.

**Pull request closed without merging**
