### PR TITLE
fix inconsistent virtual env location in guides

### PR DESCRIPTION
**Pull request by hellbe**
**Description:**
Some small changes to align installation guides with consistent `virtualenv` location.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

### CODE REVIEW

**Comment by Landrash** [comment]
Preferably we rewrite the manual rpi guide to follow the same as the guide lines as the manual installation instructions. That way the documentation is fairly consistent over all. The `venv` is placed at `/srv/homeassistant` on the hassbian image also so that way should probably be the the preferable instructions.
Something you would like to do @hellbe or should I?

**Comment by hellbe** [comment]
Sure, I can do it @Landrash. Will update the PR :)

**Comment by hellbe** [comment]
@Landrash Ok updated now, got confused for a moment whether `current` is the proper base?

Not able to test the updated instructions for RPi myself.

**Comment by Landrash** [comment]
I'll verify it in a pi before merging.
Thank you 😊

**Pull request merged**
