### PR TITLE
Improve wording/clarity and add new screenshots

### PR DESCRIPTION
**Pull request by Tediore**
**Description:**

Some parts of the onboarding and automation pages were in need of updating. I also included some new screenshots.

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

<a href="https://gitpod.io/#https://github.com/home-assistant/home-assistant.io/pull/11168"></a>

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Please rebase to the `current` branch

**Comment by Tediore** [comment]
Done.

**Comment by klaasnicolaas** [comment]
You have now only changed the target branch, you must also rebase your own branch on your fork to a current branch. Otherwise we will retain the unrelated commits.

**Comment by Tediore** [comment]
Sorry about that. I'm pretty new to GitHub so honestly I'm totally lost at this point. I might need to just close this PR and open a new one. I can't figure out how to rebase my branch and I don't want to waste your time asking you to help me figure that out.

**Comment by klaasnicolaas** [comment]
You could try this, do not know 100% if it works well.

- git checkout "branch name" (from which the PR is made)
- git rebase origin/current (rebase to which branch)
- git push -f -u "remote name" HEAD (push to the fork / PR)

**Comment by Tediore** [comment]
Thank you, I'll give it a shot. If it doesn't work, I'll just download my changes, delete my fork of home-assistant.io, make a new fork of it, and upload my changes to the current branch.

Sorry again. First time submitting a PR from a fork. All my previous PRs have been while working directly in the home-assistant.io repo.

**Comment by Tediore** [comment]
Will create a new fork and upload changes to the `current` branch.

Lesson learned...

**Pull request closed without merging**
