### PR TITLE
docs: update twitch OAuth app instructions

### PR DESCRIPTION
**Pull request by morremeyer**
## Proposed change

This adds instructions for the redirect URL to the Twitch Integration

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

_None_

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by ScottG489** [comment]
I'm not sure this is right. I tried using my instance's external URL and it fails to create the app. Strangely though, I get an error in my browser console when I click "Create" in the Twitch dev console:
```
[GraphQL] One or more GraphQL errors were detected on request 01HC2Q88EETQCPP0H6ZYZ7MD1G. CreateOauthApp: service error
vendor-70937b3561c439c270e6.js:1 Uncaught (in promise) Error: service error
```
So I can't confirm exactly what the issue is.

Regardless, I think the description here ("[...] the URL your Home Assistant instance uses") of what URL you need to provide isn't detailed enough. Is it just the base URL? Or is a path needed? Is it your external URL? I think an example would go a long way.

**Comment by frenck** [comment]
This indeed isn't correct. See also the breaking changes section of the 2023.10 release notes.

Closing the PR on this end for that reason.

../Frenck

**Comment by morremeyer** [comment]
Thanks for taking care of this. I thought I had already closed the PR, but apparently I didn't. I only noted the changes after opening the PR.

Sorry for the fuss!

**Comment by ScottG489** [comment]
@frenck I'm not sure this PR should be closed. The docs still need to be updated to tell the user how to create their app in Twitch. The existing docs only say:

> Create a new app at “Register Your Application” in the [Twitch developer portal](https://dev.twitch.tv/console/apps). Then get the Client ID and Client secret for the new application.

However, we need to tell the user what "OAuth Redirect URLs" they need to enter when creating a new app on Twitch's website. Or am I missing something here? I'm still getting console errors on their website so unfortunately I can't confirm.

**Comment by frenck** [comment]
@ScottG489 There is another PR open with the correct information (but has a review comment).

../Frenck

**Comment by morremeyer** [comment]
See #29166.

**Pull request closed without merging**
