### PR TITLE
Added cover group platform

### PR DESCRIPTION
**Pull request by cdce8p**
**Description:**
Added documentation for the `cover group` platform.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#12692

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by arsaboo — DISMISSED** [review]
Looks good...can be merged when the parent PR is merged.

**Review by frenck — DISMISSED** [review]
@cdce8p Looks good! Can be merged as soon as the parent PR gets merged. 🥇

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
- Rebased the PR in order to fix the build.
- Removed incorrect CLA check.

Parent PR is merged, I'll go ahead an merge this one in.

**Comment by cdce8p** [comment]
Thanks @frenck :+1:

**Comment by frenck** [comment]
No, no @cdce8p, thank you for this PR!

**Pull request merged**
