### PR TITLE
Rename generic_ip_camera.markdown to generic.markdown

### PR DESCRIPTION
**Pull request by davet2001**
## Proposed change

The "Generic IP Camera" integration is called `generic` in HA core but `generic_ip_camera` in the documentation.

This causes problems when the UI creates a link to the documentation.

Following https://github.com/home-assistant/core/pull/40511 it was agreed to update the documentation to match the integration name rather than customise the link.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information
Potentially this will break existing links to this part of the website, there are some:
https://www.google.com/search?q=%22home-assistant.io%2Fintegrations%2Fgeneric_ip_camera%2F%22

I have tried to update the redirects to cover this but I don't know if it works.

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by davet2001** [comment]
Is a simple rename all that is needed?  I don't fully know what the dependencies are.

**Review by frenck — CHANGES_REQUESTED** [review]
Seems ok!

The only thing missing right now, is a redirect from the old generic to the new generic location 👍

**Comment by davet2001** [comment]
Should be good now.

**Review by frenck — APPROVED** [review]
Thanks, @davet2001 👍

**Pull request merged**
