### PR TITLE
Remove contradiction in sunset condition

### PR DESCRIPTION
**Pull request by janick**
Remove contradiction in current documentation of sunset condition.

Current documentation documents a work-around (using an explicit 'or' to specify "before sunrise or after sunset").

Note "before sunrise / after sunset" example still does not work. Fixed in https://github.com/home-assistant/core/pull/76143

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/76143
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Could you rebase your branch to the `next` branch so that the unrelated commits disappear from your pull request.

**Comment by janick** [comment]
I thought I already did when I merged the 'next' branch in.

Guess I have to figure out how to rebase from here...

**Comment by janick** [comment]
This ought to do it...

**Review by frenck — APPROVED** [review]
Thanks, @janick 👍

**Pull request merged**
