### PR TITLE
Add the new sensor to the YouTube documentation

### PR DESCRIPTION
**Pull request by Alexwijn**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:  https://github.com/home-assistant/core/pull/123144
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

## Summary by CodeRabbit

- **New Features**
	- Added documentation for a new sensor that tracks "Views count" for connected YouTube channels in Home Assistant.

- **Documentation**
	- Enhanced clarity and completeness of the YouTube integration documentation.
	- Improved guidance on Jinja templating functionalities, including iterating multiple objects and merging action responses.
	- Expanded details on the APsystems integration, including new sensor categories and settings.
	- Introduced comprehensive documentation for the Anthropic Claude integration, detailing setup and configuration.
	- Updated the Amazon Polly integration documentation with new engine options and example configurations.
	- Added a new section for managing home cooling mode in the homematicip_cloud integration documentation.
	- Introduced new actions and features across various integrations, enhancing user experience and functionality.

### CODE REVIEW

**Comment by joostlek** [comment]
Oh lol, didn't knew I had this documented, thanks

**Comment by joostlek** [comment]
Please *rebase* on `next` (otherwise you'll be trying to cross branches and that doesnt work)

**Comment by Alexwijn** [comment]
Oh, you can't change target branch?

**Comment by Alexwijn** [comment]
Oh fixed that, although I made a mess with the reviewers. Hello all!

**Comment by joostlek** [comment]
Nope

**Pull request closed without merging**
