### PR TITLE
Add select platform to velbus

### PR DESCRIPTION
**Pull request by cereal2nd**
## Proposed change

Add the select platform to velbus docu

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/87568
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by cgarwood** [comment]
Closing and reopening to re-trigger CI.

**Comment by cgarwood** [comment]
I can't seem to get the netlify jobs to re-run. Flagging as parent-merged and will let one of the more experienced docs folks take a look.

**Comment by klaasnicolaas** [comment]
Unfortunately my attempt didn't work either, only being triggered on a new commit or @frenck starting a re-run.

**Review by frenck — APPROVED** [review]
Thanks, @Cereal2nd 👍 

../Frenck

**Pull request merged**
