### PR TITLE
Update govee_light_local.markdown

### PR DESCRIPTION
**Pull request by Doandu96**
Added google search links for each product.

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by c0ffeeca7 — APPROVED** [review]
Thank you, @Doandu96 :+1:

**Comment by klaasnicolaas** [comment]
I don't really see the added value in this and wonder whether we should allow this.

./Klaas

**Comment by Doandu96** [comment]
The added value would bei useability.

**Comment by klaasnicolaas** [comment]
Yes, but we can assume that users are able to search themselves in their own favorite search engine (not everyone likes to use Google given privacy concerns). A more useful link could be, e.g., a direct link to the specific product page at Govee.

./Klaas

**Comment by Doandu96** [comment]
I See your Point!👍

**Pull request merged**
