### PR TITLE
Added armed_night to manual_mqtt alarm doc

### PR DESCRIPTION
**Pull request by snjoetw**
**Description:**
Added armed_night to manual_mqtt alarm doc

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#9358

### CODE REVIEW

**Comment by frenck** [comment]
Docs are looking good 🥇 
Can be merged as soon as the parent PR is merged.

**Comment by MartinHjelmare** [comment]
Please add info on the new config settings for state and pending time too.

**Comment by snjoetw** [comment]
@frenck @MartinHjelmare, I've updated the PR with additional doc change, mostly copied over from my previous PR for manual alarm (https://github.com/home-assistant/home-assistant.github.io/commit/e2cb9f558df55097c0e8b320d0ae6630e6da3c98#diff-32497e39d8eb98b95bbd23bb0f54121f).

**Comment by frenck** [comment]
@snjoetw Made some small grammar corrections myself. Thanks for the update!

Since the parent PR is merged already, I will go ahead and merge this one in as well.

Well done! 🎖

**Pull request merged**
