### PR TITLE
Remove deprecated 'turn_on_action' and 'turn_off_action'

### PR DESCRIPTION
**Pull request by ikifar2012**
## Proposed change

Remove  deprecated 'turn_on_action' and 'turn_off_action' as per issue #14569 

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by JeffLIrion** [comment]
These examples shouldn't simply be removed, they should be converted to automations that use device triggers

**Comment by ikifar2012** [comment]
> These examples shouldn't simply be removed, they should be converted to automations that use device triggers

Can you provide an example?

**Comment by JeffLIrion** [comment]
3E31C806-50B1-472F-843A-C57BEEBC91B0

**Comment by ikifar2012** [comment]
> 3E31C806-50B1-472F-843A-C57BEEBC91B0
> 
> 

In this example you are calling a script. What does that script look like? so we can better adapt it into an example

**Comment by JeffLIrion** [comment]
You can replace the script call with the `turn_on_action` / `turn_off_action` sequences. This way, users will still see various ways of turning Kodi on/off using the current format.

**Comment by JeffLIrion** [comment]
Also, it would be good to include a link to the [Device Triggers](https://www.home-assistant.io/docs/automation/trigger/#device-triggers) documentation. I think if you put it in the Markdown as `[device triggers for automations](/automation/trigger/#device-triggers)` it will link correctly.

**Comment by ikifar2012** [comment]
Just looking into it I cannot seem to find any real documentation for device triggers, the docs seem to point you to MQTT device triggers https://www.home-assistant.io/docs/automation/trigger#device-triggers

**Comment by JeffLIrion** [comment]
> Just looking into it I cannot seem to find any real documentation for device triggers, the docs seem to point you to MQTT device triggers https://www.home-assistant.io/docs/automation/trigger#device-triggers

I think they're intended for use within the UI. But the screenshot and the link I provided are all that's needed here.

**Comment by ikifar2012** [comment]
In this case, what would the device id be? how would one find the device id?

**Comment by JeffLIrion** [comment]
From the device triggers documentation:

> In contrast to state triggers, device triggers are tied to a device and not necessarily an entity. To use a device trigger, set up an automation through the browser frontend. If you would like to use a device trigger for an automation that is not managed through the browser frontend, you can copy the YAML from the trigger widget in the frontend and paste it into your automation’s trigger list.

I got the device ID by starting to create an automation in the UI and viewing the YAML.

**Comment by ikifar2012** [comment]
Usually documentation contains easy automations for one to do when they are just getting started, this seems a little advanced and  uses an undocumented feature, I am unsure what we should do in terms of how do you explain it to a new user. As in is there a better way to get the device id? Is this device id feature officially supported? I am wondering if anyone else has any input on what we should do

**Comment by ikifar2012** [comment]
Closed as it appears solved in PR #15324

**Pull request closed without merging**
