### PR TITLE
Update USPS configuration

### PR DESCRIPTION
**Pull request by tjorim**
**Description:**
Using new config vars
Add linkable titles
Remove trailing spaces
Related to #6385

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by Vasiley** [comment]
This should not be merged ....USPS has been known to cause users to get banned from site

**Comment by tjorim** [comment]
What does that issue have to do with updating the documentation according to the standards or not?

Rather than just not merging this PR this should be addressed elsewhere in my opinion.
Maybe someone could open up a PR which adds a warning for users.

**Comment by Vasiley** [comment]
This componet does not work..what good does it do to update the docs

**Comment by arsaboo** [comment]
This PR only corrects the formatting, which is fine by me. 

If the component is not working and needs to be taken down, that is a separate issue.

**Review by arsaboo — APPROVED** [review]
Merging it, as it fixes the current docs. We may decide to take down this component entirely at some point.

**Pull request merged**
