### PR TITLE
add statsd logo

### PR DESCRIPTION
**Pull request by fuga2136**
relates to #1071

### CODE REVIEW

**Comment by robbiet480** [comment]
Thanks! 🐬 🍪 💯

**Comment by fabaff** [comment]
The logo seems to come from https://www.datadoghq.com/blog/statsd/. Can you please point to me the source of the file as I'm not able to find any reference in the [statsd](https://github.com/etsy/statsd) eco-system.

**Comment by fuga2136** [comment]
@fabaff your right -- a lot of digging reveals their actual logo for some reason statsd removed it from their README.md (https://github.com/etsy/statsd/pull/274/commits/49c6d107ac5be4d7f808e5c448f6c2e337d03acd) awhile back for some reason...and a reverse image search comes up empty for any other uses of it.

https://www.etsy.com/images/github/github-statsd.png

I'll submit another PR for to replace the logo.

**Comment by fuga2136** [comment]
#1091 opened for this

**Pull request merged**
