### PR TITLE
Update glances.markdown

### PR DESCRIPTION
**Pull request by engrbm87**
**Description:**
Update list of created sensors based on collected data from glances_api.

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#28639

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Review by frenck — CHANGES_REQUESTED** [review]
@engrbm87 Could you please resolve the merge conflicts? Thanks! 👍

**Comment by engrbm87** [comment]
> 
> 
> @engrbm87 Could you please resolve the merge conflicts? Thanks! 👍

I can't seem to find a link where i can solve the merge conflicts. I have initially updated the document directly on github so please let me know i can resolve the conflict.

**Comment by frenck** [comment]
@engrbm87 You can't.
You have to checkout it locally, rebase it onto the latest version of the origin `next` branch and resolve the conflict along the way. After that is done, you can push your changes back to GitHub.

**Comment by engrbm87** [comment]
@frenck I was only able to create a new PR #12050. I hope that would ok.

**Pull request closed without merging**
