### PR TITLE
updated hardware recommendation (Pi 4 etc.)

### PR DESCRIPTION
**Pull request by karolzlot**
also removed ref links

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch:  `current`
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
Those reflinks should not be removed, their belong to the org. Please restore.

**Comment by frenck** [comment]
Reading more closely, I'm going to decline this.

Several reasons:
- The getting started guide aims for HassOS, which cannot use an external drive.
- We recommend an A1 or A2 class card, not the one with 4K speeds. It is not about speed, it is about durability.

Nevertheless, thank you for taking the time to create this PR.

**Comment by karolzlot** [comment]
You are right, but please reopen, so I can make changes based on your feedback, and a few more

**Comment by frenck** [comment]
There is nothing in this PR that needs to be merged in. So please just create a new one.

**Pull request closed without merging**
