### PR TITLE
Madvr

### PR DESCRIPTION
**Pull request by iloveicedgreentea**
## Proposed change

This adds documentation for the upcoming madvr integration

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/120382
- Link to parent pull request in the Brands repository:  https://github.com/home-assistant/brands/pull/5612
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

## Summary by CodeRabbit

- **New Features**
  - Introduced integration for madVR Envy devices in Home Assistant, supporting commands, binary sensors, and sensors for device control and automation.

- **Changes**
  - Updated Jewish calendar integration: `weekly_portion` is now `parshat_hashavua` and `omer_count` is now `day_of_the_omer`.
  - Removed `strict_connection` parameter from the `ssl_profile` configuration.
  - Provided updated error handling and messaging for UniFi Protect integration.
  - Added new binary sensor for Ethernet status and troubleshooting section in Verisure integration.
  - Improved warnings and error messages related to Zigbee Coordinator stability in ZHA integration.

### CODE REVIEW

**Comment by frenck** [comment]
Please revert the changes of other parent PRs, these will need their own separate PRs once this one is merged.

There are also unrelated changes in this PR that must be removed. This Pr should only cover the adding of the initial Core PR.

../Frenck

**Review by frenck — CHANGES_REQUESTED** [review]
As per above.

**Comment by iloveicedgreentea** [comment]
I have no idea what happened here but this is a mess. Will close and open a new PR.

**Comment by iloveicedgreentea** [comment]
corrected PR https://github.com/home-assistant/home-assistant.io/pull/33626

**Pull request closed without merging**
