### PR TITLE
Documentation for new integration, WiLight (wilight) - PR Wilight initial # 35823

### PR DESCRIPTION
**Pull request by leofig-rj**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:  https://github.com/home-assistant/core/pull/35823
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/1635
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by leofig-rj** [comment]
brands PR #1635

**Review by klaasnicolaas — CHANGES_REQUESTED** [review]
You can remove the logo file from this pull request 😉

**Comment by leofig-rj** [comment]
> You can remove the logo file from this pull request 😉

Done! Thank you!

**Comment by leofig-rj** [comment]
New PR: Add WiLight integration #35867

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
