### PR TITLE
Installation of python_openzwave on OSX

### PR DESCRIPTION
**Pull request by olskar**
Add command needed for installation of python_openzwave on OSX to work. 
See https://github.com/home-assistant/home-assistant.github.io/issues/3653

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

### CODE REVIEW

**Comment by frenck** [comment]
Thanks, @olskar, that is a pretty nice addition. 🏅 
I've changed `OS X` to `macOS` since that is the official product title these days.

**Comment by fabaff** [comment]
I guess that this will be lost. The was a massive change of the Z-Wave section. We are going to merge `next` to `current` tomorrow.

**Comment by frenck** [comment]
I've added it to my list of thing to get back to... Thx for the heads up @fabaff

**Comment by fabaff** [comment]
Should be fixed now.

**Pull request merged**
