### PR TITLE
spelling mistakes

### PR DESCRIPTION
**Pull request by haqthat**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
@haqthat Thank you for this PR.
As you can see, there are many PRs/Commits of other people in here, this is caused by you originally based of the `next` branch.

Please rebase your changes onto the `current` branch. Thanks already 👍

**Comment by haqthat** [comment]
@frenck Newb here, how do I do that?  Sorry.

**Comment by frenck** [comment]
@haqthat 

Some information about it may be found here: https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase

**Comment by haqthat** [comment]
you can close those pulls then, I'll make the changes directly to current

the rebase is complaining about files I did not modify

CONFLICT (modify/delete): source/_components/climate.evohome.markdown
deleted in HEAD and modified in remove Oxford comma. Version remove Oxford
comma of source/_components/climate.evohome.markdown left in tree.
error: Failed to merge in the changes.

**Comment by frenck** [comment]
Looking forward to the new PR! 👍

**Pull request closed without merging**
