### PR TITLE
Add mention of setting global log transmit to true

### PR DESCRIPTION
**Pull request by gjbadros**
This documents PR https://github.com/home-assistant/core/pull/36211 which fixes a bug for multi-area deployments mis-reporting changed_by and changed_by_id on alarm_control_panel devices.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/36211
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [ X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This PR relies on a feature that is implemented in a parent PR in our core codebase. It, therefore, depends on a next release of Home Assistant and thus the `next` branch should be targeted.

Please change the target of this PR to the `next` branch and git rebase the PR if needed.

**Comment by gjbadros** [comment]
Targeting next branch now.

**Comment by frenck** [comment]
@gjbadros That is a good step, however, there are unrelated commits in this PR now because of that. Please git rebase this PR onto the `current` branch.

Thanks! 👍

**Comment by gjbadros** [comment]
Switched to https://github.com/home-assistant/home-assistant.io/pull/13613
since
it was easier to redo than figure out why the rebase was janky.

**Pull request closed without merging**
