### PR TITLE
Adding Nginx reverse proxy cookbook.

### PR DESCRIPTION
**Pull request by jeliasson**
**Description:**
Cookbook for Nginx reverse proxy.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

### CODE REVIEW

**Comment by fabaff** [comment]
I think that this should be incorporated into the existing [NGINX documentation](https://home-assistant.io/docs/ecosystem/nginx/).

**Comment by jeliasson** [comment]
This is merely a translation of [Apache Configuration](https://home-assistant.io/cookbook/apache_configuration/), also a cookbook. While Apache dont't have it's own [ecosystem documentation](https://home-assistant.io/docs/ecosystem/apache/), I think this may help for the time being.

**Comment by balloob** [comment]
I agree with @fabaff, should be part of the NGINX ecosystem. Apache cookbook entry should be moved there too.

**Comment by fabaff** [comment]
Added with #2330.

**Pull request closed without merging**
