### PR TITLE
Update media_player.mpd.markdown

### PR DESCRIPTION
**Pull request by yeralin**
Introducing new parameter "Name"

**Description:**
Added new optional parameter "Name" for mpd component.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#6553

### CODE REVIEW

**Comment by yeralin** [comment]
Updated docs due to comment of the reviewer: https://github.com/home-assistant/home-assistant/pull/6553#issuecomment-285988377

**Comment by fabaff** [comment]
This PR points to the wrong branch and I can't change it.

**Comment by yeralin** [comment]
@fabaff I completely messed it up. I'll create another pull request

**Comment by yeralin** [comment]
@fabaff I'm confused. You want me to create a PR to master branch, right?
But I couldn't find `source/_components/media_player.mpd.markdown` in master branch :/

**Comment by armills** [comment]
You want to create it against the `next` branch

**Pull request closed without merging**
