### PR TITLE
Updated manifest.json reference in thirteen-usd-voice-remote

### LINKED ISSUE #34140: Trying to build the $13 voice assistant doesn't work
### Feedback

This is a bug report, but for the website itself. I'm trying to configure my ATOM Echo to be a voice assistant for Home Assistant but I can't do that because the link to write the firmware is unrepairable broken.
You click in Connect, it shows you the list of devices, you select the correct one but get the error "Failed to download manifest". I checked using the Chrome's console and it's the file missing.

### URL

https://www.home-assistant.io/voice_control/thirteen-usd-voice-remote/

### Version

_No response_

### Additional information

The file https://firmware.esphome.io/voice-assistant/m5stack-atom-echo/manifest.json can't be found.

### PR DESCRIPTION
**Pull request by tjbenator**
…ant.io#34140

## Proposed change

This is to fix #34140.  Did some digging and saw that there was some recent changes to the build process for some esphome firmware. The manifest.json file moved locations which was referenced by the esp-web-install-button on this page.

From: `https://firmware.esphome.io/voice-assistant/m5stack-atom-echo/manifest.json`
To:       `https://firmware.esphome.io/wake-word-voice-assistant/m5stack-atom-echo/manifest.json`

I [searched](https://github.com/search?q=repo%3Ahome-assistant%2Fhome-assistant.io%20esp-web-install-button&type=code) this repo for `esp-web-install-button`  to check other pages, but didn't see any others that were impacted only `/voice_control/thirteen-usd-voice-remote.markdown`

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/esphome/firmware/pull/253
- Link to parent pull request in the Brands repository: N/A
- This PR fixes or closes issue: fixes #34140 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].
- [x]  I've tested this on my own M5Stack Atom Echo through the devcontainer to ensure it's now functioning as intended :) 

[standards]: https://developers.home-assistant.io/docs/documenting/standards

## Summary by CodeRabbit

- **New Features**
	- Updated the manifest URL for the voice remote documentation to support wake word functionality.
- **Documentation**
	- Improved clarity of the voice control device’s capabilities with an updated resource link.

### CODE REVIEW

**Comment by tjbenator** [comment]
Happy to correct the branch targeted, however I believe this needs to target `current` since it fixes the page for new installs.

**Review by c0ffeeca7 — APPROVED** [review]
Thank you for the fix, @tjbenator, thank you for reporting it, @mhalano :+1:

**Comment by mhalano** [comment]
@c0ffeeca7 Do we have a timeframe when the change will hit production? BTW, great nickname here on GitHub. :smiley:

**Comment by c0ffeeca7** [comment]
should become active later tonight.

**Comment by mhalano** [comment]
I will keep my Atom echo plugged then :smiley:

**Pull request merged**
