### PR TITLE
Update switch.flux.markdown

### PR DESCRIPTION
**Pull request by abmantis**
**Description:**
Add interval and transition time attributes.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#9700

### CODE REVIEW

**Comment by frenck** [comment]
The parent PR has been merged. The merge has been reverted by @balloob.

**Comment by abmantis** [comment]
@frenck From what I could find, the changes are still there and the PR is still merged. @balloob did revert, but not the changes. Maybe a mistake?

**Comment by abmantis** [comment]
@balloob @fabaff  this should already be merged since it the code changes are already released...

**Comment by balloob** [comment]
Yeah GitHub does something weird when you try to revert a PR after other PRs have been merged. It will create empty revert commits. Sorry for the confusion.

**Pull request merged**
