### PR TITLE
Update nuki.markdown

### PR DESCRIPTION
**Pull request by franfos**
According Home Assistant PR #22888

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#22888

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

<a href="https://gitpod.io/#https://github.com/home-assistant/home-assistant.io/pull/9841"></a>

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Please rebase this PR to the `next` branch

**Comment by klaasnicolaas** [comment]
There are still some unrelated commits in this PR

**Comment by frenck** [comment]
@franfos Please rebase this PR so we can get it merged...

**Comment by frenck** [comment]
Rebased PR onto next myself.

**Review by frenck — APPROVED** [review]

**Pull request merged**
