### PR TITLE
Reformat the configuration options

### PR DESCRIPTION
**Pull request by cgtobi**
**Description:**
Reformat configuration options of the wunderground sensor.
Related to #6385.

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hi @cgtobi, thanks for the PR.
Nevertheless, the build fails. Also, this PR changes the current documentation and should, therefore, target the `current` branch. Could you change the target and rebase if needed? 👍

**Comment by cgtobi** [comment]
@frenck this needs to be rebased onto `current`. Thanks in advance.

**Comment by frenck** [comment]
Rebased, awaiting build.

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Thanks, @cgtobi 👍 

Happy Hacktoberfest 🎉 

../Frenck

**Pull request merged**
