### PR TITLE
Feature component search

### PR DESCRIPTION
**Pull request by bdurrer**
**Description:**
Adds a search box to the component overview page and enables the user to quickly find components based on their `title `and `ha_category`.
* It uses isotope's advanced filter feature
* It's tested on Firefox, Chrome and IE11. 
* It's responsive. 
* It works with international component names like V**ä**sttrafik Public Transport
* Includes some minor improvements to the JavaScript in general.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** NONE

This is related to issue #1083. However, this PR only applies to the component page, not the complete website. It's meant to complement the category selection.
Making the whole page searchable would require a different approach (e.g. an json file which is parsed with fuse.js).

### CODE REVIEW

**Comment by balloob** [comment]
This is awesome!

Would you be able to rebase on top of the `current` branch? That way we can get this to everyone when we merge instead of waiting for the next release (1,5 weeks from now).

**Comment by bdurrer** [comment]
PHU! That was the scariest thing I did with GIT recently :simple_smile:
Still looking okay and works on my browsers.

One thing I dislike and couldn't come up with a good solution: Deleting in the search box until it's empty is the equivalent to the "all" filter. While that's semantically correct, the all filter's performance is terrible with 640 elements, it takes several seconds on IE and looks like the search somehow broke down. 
I don't know if we just accept that or maybe switch to "featured" when the search box is empty. The downside is, that "feature" is simply not the correct result set for an empty search

**Comment by fabaff** [comment]
@balloob was talking about to improve the loading process in the near future as there are too many requests and too much files. Going more for a on-demand approach than loading everything.

Let's merge it and wait for feedback.

**Comment by balloob** [comment]
Maybe we can filter out everything when an empty search is passed in ?

**Comment by balloob** [comment]
Put the search feature on social media: https://twitter.com/home_assistant/status/842758527009669120 👍

**Comment by bdurrer** [comment]
@fabaff I think the loading process is not the issue. Its a slow browser with a slow javascript engine. IE simply can't handle 640 elements being made visible and isotope probably isn't made for that amount either. Even Chrome takes 1-2 seconds to render the `all `filter.

@balloob Hm yeah, that would work I guess. According to my measurement one character search is slow too, but at least tolerable.

But I guess Fabian is right, let's wait and take a look for yourself on the website. I can push the empty-search later, it's a no-brainer.

**Comment by balloob** [comment]
@bdurrer since you are currently touching this code, I have an idea to make the page load super fast: for all the image objects, instead of specifying a `src` attribute we specify a `data-src` attribute. Then when isotope is showing the cards, it will go through all image elements that are not visible that are having a `data-src` attribute and set that as `src`.

**Comment by bdurrer** [comment]
That's what I would have done too. But first I'll test some css options, I think it's even easier solvable background-image, browser skip those nowadays [in certain cases].

or even create html elements on the fly and use a json as data repository. 🤔 

I created a new issue #2282 for this.

**Pull request merged**
