### PR TITLE
Update documentation for Yale Access Bluetooth adding new way to obtain the key/slot

### PR DESCRIPTION
**Pull request by dferrandizmont**
Added the Android - Yale Home method to obtain the key/slot.

## Proposed change

- Adding new way to retrieve the key / slot from the Yale Home app. Working from EU.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by bdraco — APPROVED** [review]
Thanks @dferrandizmont

**Comment by bdraco** [comment]
Just realized this need to go to current though

**Comment by bdraco** [comment]
It would probably be easiest to open a new one and copy that block into
https://github.com/home-assistant/home-assistant.io/edit/current/source/_integrations/yalexs_ble.markdown

**Comment by dferrandizmont** [comment]
I'll do it!

**Pull request closed without merging**
