### PR TITLE
Added doc for icons

### PR DESCRIPTION
**Pull request by DubhAd**
As it now supports icons, adding that to the docs

Icon description lifted from customizing page

### CODE REVIEW

**Review by Vasiley — APPROVED** [review]
:+1: as always

**Comment by c727** [comment]
not correct, revert it

#5839

**Comment by c727** [comment]
also, do reviewers once check if the syntax is correct and the page renders as expected?

**Comment by DubhAd** [comment]
Rather than "not correct, revert it" - how about some **useful detail** on why it's not correct or basically anything to help know what's gone wrong?

Also, within the GitHub UI, config blocks never render as expected.

**Comment by balloob** [comment]
Netlify build links to a copy of the live site with your changes

**Comment by c727** [comment]
@DubhAd are you kidding? you submit configs that are not implemented (so you havn't even tested it) and ask what's wrong?

**Comment by c727** [comment]
... and then people ask why the docs review process is a joke cc: @frenck

**Pull request merged**
