### PR TITLE
Add details about 'api_password'

### PR DESCRIPTION
**Pull request by fabaff**
**Description:**
Details about using with `api_password` were missing.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#14815

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by GruberMischa** [comment]
On April 23. I contacted MyStrom if there is a possibility to make https calls from the buttons.
They replied that they only can make 1 https connection (to their servers), but there is an experimental function which uses `gets` and `posts` instead of `get` and `post`.
But `HTTPS  is limited to AES128_CBC_SHA, AES256_CBC_SHA and TLS1.1` they added.

Maybe I can add this to the docs as _Experimental_?

**Comment by fabaff** [comment]
> Maybe I can add this to the docs as Experimental?

Please do. It would allow users to use the buttons if they have enable SSL/TLS.

I will merge it as soon as the checks are done. Can you please open a new Pull request against `next`? I moved some parts around and adding the "Experimental" to `current` will probably end-up in conflicts.

BTW, thanks for you help to improve that platform.

**Comment by GruberMischa** [comment]
Okey I will look into next week, when I will have time again.
Will also test it with my buttons, last time I checked, it was really experimental.

Nothing to thank for 😃

**Comment by GruberMischa** [comment]
@fabaff  for information:
I was testing the ```gets``` and ```posts``` experimental feature, but couldn't get a positiv result. They didn't work. Also home assistant didn't report any login attemps. So I didn't look more into it.
Maybe you have more luck, or we will just wait for TLS support.

**Pull request merged**
