### PR TITLE
Update rtorrent.markdown

### PR DESCRIPTION
**Pull request by smega**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/32353
- This PR fixes or closes issue:

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
@smega You checked the "Added documentation for a new feature I'm adding to Home Assistant" box, which makes sense from the content you are changing in this PR.

However, the parent PR isn't linked in the opening post and the branch is also targeting the `current` branch (although I expected it to be `next` in that case).

Please advise?

**Comment by smega** [comment]
I thought I had created the PR to the next branch.
Shall we decline the PR and and I create a new one to next?

**Comment by frenck** [comment]
I would recommend on adding the link to the parent PR to the openings post and rebase this PR onto the `next` branch.

**Comment by smega** [comment]
I am not really sure what you want me to do.
Can you just decline the PR and then I create a new one?

**Comment by klaasnicolaas** [comment]
I will rebase the PR for you 😉 So just wait and relax for now

**Review by klaasnicolaas — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged 👍

**Comment by smega** [comment]
I knew what rebase was but was not sure about link and parent PR.
Anyway thanks to both of you.

**Pull request merged**
