### PR TITLE
doc update for MQTT light shema template

### PR DESCRIPTION
**Pull request by orcema**

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Please update the PR description to use our PR template and fill out the form.

**Comment by orcema** [comment]
done, updated with PR template

**Comment by frenck** [comment]
That is the PR template for Core PRs... please use the one that matches this documentation repository.

**Comment by frenck** [comment]
?

**Comment by orcema** [comment]
replaced by 
[https://github.com/home-assistant/home-assistant.io/pull/21061](https://github.com/home-assistant/home-assistant.io/pull/21061)

**Pull request closed without merging**
