### PR TITLE
Update customizing-devices.markdown

### PR DESCRIPTION
**Pull request by DubhAd**
Added explicit note that the new format was introduced in 0.37, so that those still running older versions don't get confused when it all breaks.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @DubhAd,

It seems you haven't yet signed a CLA. Please do so [here](https://cla.home-assistant.io/sign/DubhAd?pr=1908).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by robbiet480** [comment]
Hey, sorry the CLA link was wrong, it's now been fixed. Please sign the CLA [here](https://home-assistant.io/developers/cla_sign_start/).

**Comment by DubhAd** [comment]
Thanks. The country details are messed up, with Scotland and Wales not being part of the UK. What it's listing as the UK is really England ;)

More importantly, the signing process never completes. After signing you get the message:

_Thank you for signing the Home Assistant Contributor license agreement. We are now redirecting you back to your pull request._

And that's it, nothing else happens

**Comment by robbiet480** [comment]
@DubhAd Thanks for the feedback on the countries, I'll get that fixed ASAP. As for the redirect bit, in the normally working system you would actually be redirected back to here but I manually built the link here so it doesn't know to redirect you back.

**Comment by DubhAd** [comment]
Then it's just a matter of waiting for a while for the status to be reported back? Thanks.

**Comment by robbiet480** [comment]
@DubhAd Something is wrong in the system with your PR, I'm looking into it and will get the status fixed in the next few minutes.

**Comment by DubhAd** [comment]
Heh. Typical ;) No worries. Worst case I pick this up again tomorrow, or through the week.

**Comment by robbiet480** [comment]
@DubhAd All fixed!

**Comment by DubhAd** [comment]
Awesome! Thanks.

**Comment by andrey-git** [comment]
Already put in in home-assistant/home-assistant.github.io#1913

**Pull request closed without merging**
