### PR TITLE
Added documentation for resource_template for REST sensor

### PR DESCRIPTION
**Pull request by fredrike**
**Description:**

Adds documentation for `resource_template` for the REST sensor

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#27869

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by balloob** [comment]
Ok to merge when conflicts resolved.

**Review by frenck — APPROVED** [review]
LGTM! ✔️ 

Thanks, @fredrike! 👍 

Happy Hacktoberfest 🎉

**Comment by fredrike** [comment]
> LGTM! 
> 
> Thanks, @fredrike! 
> 
> Happy Hacktoberfest

Thank you! Just made the t-shirt :). 

BTW, don't we need `{% raw %}`?

**Comment by frenck** [comment]
I ordered mine just now 👕 😉 

Yes we do, I just placed it around the whole code block, so the code inside the block stays clean.

**Pull request merged**
