### PR TITLE
evohome.markdown: Remove quotes from username and password

### PR DESCRIPTION
**Pull request by reedy**
## Proposed change

The example of using `"` around both the username and password is incorrect as per https://community.home-assistant.io/t/honeywell-evohome-europe-help/399250/10

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by frenck** [comment]
This change is not correct and will (in this case not make a difference).

The suggested change does, however, go against our recommended YAML guidelines.

../Frenck

**Comment by reedy** [comment]
> This change is not correct and will (in this case not make a difference).

It does make a difference though. The sensors didn't show up until I removed the quotes...

**Comment by frenck** [comment]
In YAML both are string constructs, for the parsers (and specs) there is no difference.

If you think this is an bug, please file an issue instead.

../Frenck

**Comment by reedy** [comment]
Indeed it is.

But when other people are saying to do it too (and apparently fixed an issue, as per the linked thread; I'd had mine quoted in config for months without them appearing in HA. When I quoted them yesterday they appeared after a restart. And yes, if obviously restarted it before too), it does seem like there a bug.

I'll try and get round to testing a little more thoroughly and file a bug report.

**Pull request closed without merging**
