### PR TITLE
Update picture-glance.markdown

### PR DESCRIPTION
**Pull request by ghost**
image is required as of 2021.4.6

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @wweber0815, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#17691).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by frenck** [comment]
That would mean a breaking change was introduced in a patch release?

Could you point me to the source of this change?

**Comment by ghost** [comment]
this is a documentation issue. i tried using the picture-glance card without "image:" in yaml which yielded an error. documentation says "image:" should be optional, but in fact it does not work without it - so i changed the documentation to "required: true". i did not check the code, just aligned the documentation with the behaviour in the ui.

https://github.com/home-assistant/home-assistant.io/pull/17691/commits/abe893d39830be8435d1ea7400cfb9db9d77f058#diff-60e17809eac8e99b5bd328b967807f883c6a82cabf55774abbacb8f142fc5ad4

**Comment by frenck** [comment]
> this is a documentation issue. i tried using the picture-glance card without "image:" in yaml which yielded an error.

Ok, but your PR states:

> image is required as of 2021.4.6

Could you point me to the source of that statement?

**Comment by frenck** [comment]
? Why did you close this @wweber0815?

**Pull request closed without merging**
