### PR TITLE
Remove Somfy documentation

### PR DESCRIPTION
**Pull request by tetienne**
## Proposed change

As announced with the latest release, Somfy will shutdown its Open API the June 21st. This PR removes everything related to the associated component.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/73527
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/3478
- This PR fixes or closes issue: fixes #

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
Please remove the resources in the brands repo too for somfy if they are not used for any other integration.

**Comment by MartinHjelmare** [comment]
Please add a line in the `_redirects` file for the removed integration too.

**Comment by tetienne** [comment]
@MartinHjelmare Thx for the remarks. Remarks applied.

**Review by MartinHjelmare — APPROVED** [review]
Thanks!

**Review by frenck — APPROVED** [review]
Thanks, @tetienne 👍

**Pull request merged**
