### PR TITLE
(Ignore) Add STATE_AUTO support to generic_thermostat

### PR DESCRIPTION
**Pull request by niklaswa**
**Description:**
Make the user aware of what `STATE_AUTO` does.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#15678

## Checklist:

- [X] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [X] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by frenck** [comment]
@niklaswa, thank you for this, nevertheless, the PR is targeted against the wrong branch.
Since this relies on a featured pending a parent PR in our code base, the documentation should go into the `next` branch. Please rebase.

**Comment by niklaswa** [comment]
Done. Looks weird but I hope that was right? 👀 @frenck

**Comment by frenck** [comment]
Yeah, it does, you should have rebased instead of changing the target in GitHub and merge in next.
Because of your actions, probably the only solution now is to close this PR and create a new one.

**Comment by niklaswa** [comment]
New one https://github.com/home-assistant/home-assistant.io/pull/5916 @frenck

**Pull request closed without merging**
