### PR TITLE
Rxftrx drop platform config

### PR DESCRIPTION
**Pull request by elupus**
## Proposed change

Update documentation for new way of configuring rfxtrx.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [X] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/37742

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by klaasnicolaas — CHANGES_REQUESTED** [review]
Maybe you can add shortlinks to parts of merged platforms. Make it easier to navigate directly to that part. You can find examples of how this has been done with other integrations.

**Comment by elupus** [comment]
@klaasnicolaas do you have an example integration or link to docs on how to do it?

**Comment by elupus** [comment]
Not sure you meant the ha_category field.

**Comment by klaasnicolaas** [comment]
https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/digital_ocean.markdown

And then this part:
```markdown
There is currently support for the following device types within Home Assistant:

- [Binary Sensor](/integrations/digital_ocean/#binary-sensor)
- [Switch](/integrations/digital_ocean/#switch)
```

Good by the way that you have also adjusted the `ha_category` 👍

**Comment by frenck** [comment]
@elupus Did a couple of minor tweaks. Other than that, we have merge conflicts to be resolved. Could you take a look?

Lastly, could you add a redirect from the old pages to the new? You can find our redirect file here: `source/_redirects`.

Thanks! 👍

**Comment by elupus** [comment]
added redirects and resolved conflicts

**Review by frenck — APPROVED** [review]
Awesome! Thanks! 👍

**Pull request merged**
