### PR TITLE
Update the hassbian image file size

### PR DESCRIPTION
**Pull request by joshmcrty**
The file size should match the current version of the image

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by ludeeus** [comment]
Do we need to display the filesize?
This will probaly change with every release.
The hass.io image does not display the filesize.

**Comment by joshmcrty** [comment]
@ludeeus that's a good point, but i wasn't sure if there is a specific reason for having it or not. if the consensus is not to show it i can update this PR to remove it.

**Comment by fabaff** [comment]
I would like to suggest that we remove it. For most users it doesn't matter if the file size is 440 MB or 450 MB.

**Comment by ludeeus** [comment]
I agree with @fabaff, this information is also displayed on GitHub after the user click the link.

**Comment by dale3h** [comment]
@joshmcrty Please go ahead and update the PR to remove the file size.

**Comment by joshmcrty** [comment]
OK, the file size has been removed

**Review by fabaff — APPROVED** [review]
Thanks :bird:

**Pull request merged**
