### PR TITLE
Updated documentation about running local development instance.

### PR DESCRIPTION
**Pull request by PeWu**
**Description:**
Updated documentation about running local development instance.

## Checklist:

  - [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`. 
  - [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by frenck** [comment]
Why would you run this without `venv`?

**Comment by PeWu** [comment]
I'm just following the instructions on this page.
The instructions say: "If you plan on providing isolation to your environment using venv..." so I skipped this part.
Everything works without `venv`. Why would I use `venv` if it works without it?

**Comment by fabaff** [comment]
We should do it the other way around and suggest to use a `venv`.

**Comment by PeWu** [comment]
Fine with me as long as the instructions are easy to follow.
@fabaff, your changes make it more clear.

**Comment by fabaff** [comment]
@PeWu thanks for bringing it up.

**Pull request merged**
