### PR TITLE
MQTT tracker discovery

### PR DESCRIPTION
**Pull request by PeteBa**
## Proposed change

Provides example documentation for extending discovery to mqtt device_trackers.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: [#42327](https://github.com/home-assistant/core/pull/42327)
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — APPROVED** [review]

**Comment by emontnemery** [comment]
@PeteBa In addition to adding an example to `source/_docs/mqtt/discovery.markdown` (which is done in this PR), `source/_integrations/device_tracker.mqtt.markdown` also needs to be updated to document both schemas and explain the difference between them.

As a starting point, maybe have a look at https://www.home-assistant.io/integrations/light.mqtt/ and https://www.home-assistant.io/integrations/vacuum.mqtt/

**Comment by frenck** [comment]
@emontnemery Maybe it is more helpful to create an issue (as a task) instead of a PR comment. As the latter is not trackable and actionable.

**Comment by PeteBa** [comment]
No worries guys. I think it is a good idea and will try and knock something out this weekend. [btw really like the recent mqtt refactor. great stuff]

**Comment by emontnemery** [comment]
@frenck alright, will do that next time 😅

**Pull request merged**
