### PR TITLE
Add raspihats binary_sensor documentation

### PR DESCRIPTION
**Pull request by florincosta**
**Description:**
The `raspihats` binary sensor platform allows you to read sensor values ​​using the digital inputs of the [raspihats](http://www.raspihats.com/) boards.

To use your `raspihats` boards in your installation, add the following to your `configuration.yaml` file:

```yaml
# Example configuration.yaml entry
binary_sensor:
  - platform: raspihats
    i2c_hats:
      - board: DI6acDQ6rly
        address: 0x60
        channels:
          - index: 0
            name: PIR Office
            invert_logic: true
            device_class: motion
          - index: 1
            name: PIR Bedroom
```

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#7665

### CODE REVIEW

**Comment by Landrash** [comment]
Looks good and can be merged when parent pr is merged.

**Comment by Landrash** [comment]
The documentation pr was missed when the component was merged. 
What's the pr for the added component? If that's been merged we could merge the documentation for both of them in this pr.

**Comment by florincosta** [comment]
Just added parent pr [#7639](https://github.com/home-assistant/home-assistant/pull/7639)

**Comment by Landrash** [comment]
As is now well have to wait until that is merged and merge this combined one for the documentation :)

**Comment by florincosta** [comment]
OK, but on parent pr _cla-bot — Waiting for status to be reported_... it's waiting for a long long time

**Pull request merged**
