### PR TITLE
bmw_connected_drive: added documentation for new services

### PR DESCRIPTION
**Pull request by ChristianKuehnel**
**Description:**
Added documentation for the newly implemented services. I did not really know what to write there. If you have a good example on how to document the services, please let me know.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#13497

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Docs look fine!
Took the liberty to tweak it a little.

Approved,  and can be merged as soon as the parent PR gets merged.

**Review by frenck — CHANGES_REQUESTED** [review]
@ChristianKuehnel A merge conflict appeared! 😢 

Could you please take a look?

**Comment by ChristianKuehnel** [comment]
@frenck Thx for the review. Fixed the merge conflict.

We had a change in between where I already updated to the new URL for the compatibility description...

**Review by MartinHjelmare — APPROVED** [review]

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Thanks, @ChristianKuehnel! 🥇

**Pull request merged**
