### PR TITLE
Fix "cameras" hyperlink which was invalid markdown

### PR DESCRIPTION
**Pull request by SEJeff**
Simply documentation fix.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @SEJeff,

It seems you haven't yet signed a CLA. Please do so [here](https://cla.home-assistant.io/sign/SEJeff?pr=1906).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by SEJeff** [comment]
I'd love to sign the CLA, but can't due to the auth bits being broken. Paging @robbiet480 !

**Comment by robbiet480** [comment]
Hey, sorry the CLA link was wrong, it's now been fixed. Please sign the CLA [here](https://home-assistant.io/developers/cla_sign_start/).

**Comment by SEJeff** [comment]
Thanks much sir! Signed.

**Pull request merged**
