### PR TITLE
Describe zip-file REQUIREMENT syntax

### PR DESCRIPTION
**Pull request by NovapaX**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by fabaff** [comment]
We shouldn't add those details. The default should be that `REQUIREMENT` point to a package which is available on PyPI because other ways slow down the tests. Adding information about way around this may encourage people not to follow this suggestion.

**Comment by NovapaX** [comment]
I wrote this more with custom components in mind....

**Comment by NovapaX** [comment]
I updated this to make clear this is not the desired approach for components included in home-assistant. I still think it's useful information for those creating custom components or for testing new builds/branches of upstream packages.

**Review by fabaff — APPROVED** [review]
:bird:

**Comment by fabaff** [comment]
The developer documentation was moved. I will manually add the changes at the right location.

**Comment by NovapaX** [comment]
Thanks for that! (I'm a bit short on time lately and my development time has reduces to zero unfortunately)

**Pull request closed without merging**
