### PR TITLE
Suggest avionmqtt as an alternative

### PR DESCRIPTION
**Pull request by oyvindkinsey**
Add note pointing to https://github.com/oyvindkinsey/avionmqtt as a better alternative to this component.

## Proposed change

The existing avion component is severely limited, and most likely doesn't work due to changes to Avi-on's web API. 
To provide a resource to users wanting to keep their Avi-on based systems alive (GE, Halo Home, ...), avionmqtt has been created which does provide a fully working alternative. This PR simply adds a reference to this project for those that would otherwise end up trying, and failing, at using the avion component.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

## Summary by CodeRabbit

- **New Features**
	- Added a note regarding the limited usefulness of the Avi-on Bluetooth dimmer switch integration, suggesting an alternative integration via MQTT.
  
- **Documentation**
	- Maintained existing setup and configuration instructions for the Avi-on integration within Home Assistant.

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
I don't think we allow these types of references on the integration page.

./Klaas

**Comment by oyvindkinsey** [comment]
Any suggestions apart from simply deleting the page then?

**Comment by klaasnicolaas** [comment]
It is an integration that is marked as legacy and currently has no codeowner, if anyone would like to get their hands on the code and update it they are more than welcome 🙏🏻 Otherwise I think the integration will eventually be nominated for removal 🤷🏻‍♂️ 

Normally we don't refer to custom integrations because we don't even recommend installing them (from HACS) in the first place.

Let's see what @frenck thinks about this.

./Klaas

**Comment by oyvindkinsey** [comment]
If HA would support persistent connections via its Bleak implementation,
then I'd be more than happy to do make this a proper integration. Maybe we
can move the bt part out (eg to an esphome device) and build it that way.
I'll take a look at that.

**Comment by oyvindkinsey** [comment]
I did some digging and see that it *is* possible to get an active persistent connection via ESPHome. Will look at creating a proper integration and simply replace this.

**Pull request closed without merging**
