### PR TITLE
ZHA USB discovery of SONOFF Zigbee 3.0 USB Dongle

### PR DESCRIPTION
**Pull request by Hedda**
## Proposed change

Add the ID info about USB Discovery of ITead SONOFF Zigbee 3.0 USB Dongle in the ZHA integration. More info on hardware here:

https://community.home-assistant.io/t/sonoff-zigbee-3-0-usb-dongle-plus-by-itead-is-based-on-texas-instruments-cc2652p-can-be-pre-ordered-for-10-99/340705

ZHA docs update PR submitted on behalf of @OpenMyDog (who submitted [the parent pull request to Home Assistant's core](https://github.com/home-assistant/core/pull/62171)).

Note! It should be noted that this USB discovery identifier only works out-of-the-box on dongles from newer batches that ITead currently ships, e.i. not with early dongles from the first two batches that were shipped in September and October of 2021). 

It can also work with the earlier shipped dongles as well but only if those users who own them themselves first update the product description by writing "Sonoff Zigbee 3.0 USB Dongle Plus" as a new description in the dongle's CP2102N EEPROM USB-to-UART chip, (I have however not managed to write updated product description to CP2102 EEPROM on a dongle from the first batches myself):

https://community.home-assistant.io/t/community-help-wanted-to-whitelist-all-compatible-zigbee-and-z-wave-usb-adapters-for-automatic-discovery-in-home-assistant-os/344412/13

https://community.home-assistant.io/t/community-help-wanted-to-whitelist-all-compatible-zigbee-and-z-wave-usb-adapters-for-automatic-discovery-in-home-assistant-os/344412/12

**_FYI, ITead has now posted a program that should let users themselves update the product description on already shipped dongles to supposedly match description already written to latest batch of dongles:_**

**_https://www.facebook.com/SONOFF.official/posts/2927251720919807_**

**_Tested it myself on a Windows 10 computer and it did not work for me (it closed without any messages)._**

**_Sadly ITead did not just release a script tool based on this open-source cp210x-program by VCTLabs:_**

**_https://github.com/VCTLabs/cp210x-program_**

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/62171
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by OpenMyDog** [comment]
@Hedda 
hi Hedda 
    in my new commit ,Merge tips ： docs-missing — Please open a documentation PR.
    Is this related to the unreviewed submission of your doc? If yes please tell me what to do next
    thanks

**Comment by Hedda** [comment]
> @Hedda hi Hedda in my new commit ,Merge tips ： docs-missing — Please open a documentation PR. Is this related to the unreviewed submission of your doc? If yes please tell me what to do next thanks

@OpenMyDog This here PR https://github.com/home-assistant/home-assistant.io/pull/20778 is meant to cover the missing ZHA docs for your PR https://github.com/home-assistant/core/pull/62171

So with this PR https://github.com/home-assistant/home-assistant.io/pull/20778 you should only need to add this URL to your original  initial post in https://github.com/home-assistant/core/pull/62171

**Comment by frenck** [comment]
What a PR story for a single-line change...
Like 99% of that isn't relevant or needed.

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Pull request merged**
