### PR TITLE
Added documentation for Neptune Apex.

### PR DESCRIPTION
**Pull request by jpelzer**
## Proposed change

Adds documentation for new integration Neptune Apex, the Neptune System Apex Aquacontroller, an aquarium automation system.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [X] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [X] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/34558
- Link to parent pull request in the Brands repository: Also needs re-revert

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by jpelzer** [comment]
> It seems that this PR is targeted against an incorrect branch. Documentation updates which apply to our current stable release should target the `current` branch. Please change the target branch of this PR to `current` and rebase if needed. If this is documentation for a new feature, please add a link to that PR in your description.

I think I'm correctly targeting 'next' for a new integration.

**Review by cogneato — APPROVED** [review]
Thanks again, @jpelzer

**Comment by frenck** [comment]
This one should not have been merged. It is depending on a parent PR upstream that is still open for review.

I'll open up a PR to revert this. @jpelzer This means you need to re-open your PR again... sorry about that!

**Comment by jpelzer** [comment]
Will do. Should I wait until the parent PR is done or just go ahead now @frenck ?

**Pull request merged**
