### PR TITLE
Add IoT class to Proximity & Cover

### PR DESCRIPTION
**Pull request by bmck8**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
There are unrelated commits in this PR. (e.g., geo_location, which you've already done).

Please make sure you are using a new branch each time you open up a PR. You can `git rebase` this PR onto the latest `current` branch to clean things up.

**Comment by bmck8** [comment]
> You can `git rebase` this PR onto the latest `current` branch to clean things up.

@frenck; just to ensure I've understood correctly. I should take a new branch from current, then rebase my current branch into the new branch. Once I've done that should I then force push?

**Comment by bmck8** [comment]
@frenck I hope I've fixed this now. I sought out some open source help to guide me on fixing this so it wasn't hanging open whilst I fumbled about

**Review by frenck — APPROVED** [review]
Well, Cover is in here as well. But fixed that by adjusting the title 😉 

Thanks, @bmck8! 👍 

Happy Hacktoberfest 🎉

**Pull request merged**
