### PR TITLE
Update installation-synology.markdown ref #1052

### PR DESCRIPTION
**Pull request by anchepiece**

### CODE REVIEW

**Comment by fabaff** [comment]
Can you point your Pull Requests to **current**? Seems not possible to change the base for this one.

**Comment by justweb1** [comment]
@fabaff I got it to change branch but now there is a conflict that @w1ll1am23 will need to fix. That is probably why it didn't work the first time.

**Comment by w1ll1am23** [comment]
@justweb1 not sure what I need to do here? It looks like maybe you merged your local branch with next? Shouldn't you only see the changes for installation-synology.markdown?

**Comment by robbiet480** [comment]
This PR will need to be entirely recreated. Make the changes directly off the current branch and resubmit. Thanks!

**Pull request closed without merging**
