### PR TITLE
Update the MariaDB connection details for recorder.

### PR DESCRIPTION
**Pull request by quentinsf**
**Description:**

Corrections to the database URLs when using MariaDB for Recorder.  This was originally opened as PR #8329 (since closed), and I've based the changes on the discussions there. 

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — APPROVED** [review]

**Review by frenck — CHANGES_REQUESTED** [review]
Thanks, @quentinsf. Nevertheless, I hate to say this... it is against the wrong branch.
Changes to the current documentation must be against the `current` branch.
Could you please change the target branch and rebase?

**Comment by quentinsf** [comment]
Ah, silly me - sorry - just working out how to do that...

**Comment by quentinsf** [comment]
Can't do it at present because current is changing too fast :-)  Will try again - probably in another PR, when you guys stop being so industrious!

Thanks,
Q

**Comment by frenck** [comment]
Let me pick this up for you @quentinsf

**Comment by frenck** [comment]
ooh, you actually merged some things in.
It is way easier now to create a new PR.

**Pull request closed without merging**
