### PR TITLE
Cisco Webex Teams: Documentation for email field

### PR DESCRIPTION
**Pull request by coreGreenberet**
## Proposed change

Added the description of the new "email" field

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [X] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/40593
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Please rebase your branch to the `next` branch

**Comment by coreGreenberet** [comment]
> 
> 
> Please rebase your branch to the `next` branch

done =)

**Comment by klaasnicolaas** [comment]
Not quite, we are still seeing commits coming from a `current` branch 😉

**Comment by coreGreenberet** [comment]
I dont know why, but I couldn't get the rebase to work.
I've recreated the change in a new PR #14637

**Pull request closed without merging**
