### PR TITLE
Add switchbot cloud vacuum support

### PR DESCRIPTION
**Pull request by Gigatrappeur**
Add vacuum details

## Proposed change

Modify documentation for mention vacuum support in switchbot cloud integration

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/125457
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by joostlek** [comment]
Please rebase your commit on the `next` branch

**Comment by Gigatrappeur** [comment]
Ok, I'll do it tonight

**Comment by Gigatrappeur** [comment]
I've attempt to reset to my commit 71a69a5 and rebase next branch and for finish I force push.  
So, Im' not sure if that's what you want?  
  
I have two commits:
- 3658276 (the first)
- 71a69a5 (the second is a correction of the first)

**Comment by joostlek** [comment]
Please reopen the PR, you're attaching a lot more commits than you need

**Comment by Gigatrappeur** [comment]
Ok, sorry for the lost time :-(  
I recreate a new pull request : #34745

**Pull request closed without merging**
