### PR TITLE
Adding formal structure description

### PR DESCRIPTION
**Pull request by akasma74**
I think it would be beneficial to have formal description of automation rule in this file.
I added simple fields (like id, alias, description etc) but don't quite get how to describe the complex trigger, condition and action parts - anyone?

**Description:**

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
@akasma74 It think you can't use the configuration plugin for this. It was not designed to handle this.

**Comment by akasma74** [comment]
Possibly, but what are the options?
I think ultimately it should be able to handle configuration description as there is need in that.

**Comment by frenck** [comment]
Sure, but at this point, it is not.
This PR is full of suggestions, things that still needs an answer and things that aren't working.
My suggestion would be to close this for now, until that is sorted. Feel free to open up an issue to discuss this further.

**Comment by akasma74** [comment]
well, from where I stand there is no point in opening another PR if there is no infrastructure that supports it.
And I might be wrong, but even if I open a new issue asking for support for configurations (as obviously I cannot push a PR for that) it won't go any further (as didn't many of more important issues) and will be eventually closed as stale or something.
Nevermind.

**Comment by frenck** [comment]
A PR that isn't able to merge isn't going anywhere.
Hence my suggestion to open up an issue to discuss things.
Nevertheless, feel free to open up a completed, mergeable PR.

**Comment by akasma74** [comment]
Got it, thanks!

**Pull request closed without merging**
