### PR TITLE
Add feedback block to all pages

### PR DESCRIPTION
**Pull request by frenck**
## Proposed change

This PR adds a feedback block to every page of our website, inviting people to suggests edits, provide feedback or view feedback on the current page they are looking at.

image

Future steps:
- A bot that labels created feedback issues with the integration labels
- Code owners mentioning for integration pages
- "View feedback"-button based on labels (now based on URL until the above is resolved).

PS: Some formatting changes done by Prettier 🤷 

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by TomBrien** [comment]
Looks like a little more padding is needed between the new div and the logo div in low page width views

image

**Comment by frenck** [comment]
rofl, @TomBrien 🤷 

I've re-used existing components. No clue on how to fix this.

**Comment by TomBrien** [comment]
Meh it's super minor I've got an idea of how to do it but won't happen till tomorrow at the earliest. Merge and tweak later I say.

**Review by TomBrien — DISMISSED** [review]

**Comment by frenck** [comment]
@TomBrien Fixed, thanks to Ludeeus :)

**Review by ludeeus — APPROVED** [review]

**Pull request merged**
