### PR TITLE
Update docker.markdown

### PR DESCRIPTION
**Pull request by bonterra**
A more detailed installation description for Docker on Raspberry Pi 3 with Raspbian.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Review by fabaff — APPROVED** [review]
Thanks :bird:

**Comment by balloob** [comment]
This PR broke the styling of the Docker page

image

**Comment by bonterra** [comment]
Looks fine to me?

home-assistant-docker

This screen shot is from Chromium but it looks the same in Firefox.

**Comment by balloob** [comment]
I already fixed it…

**Pull request merged**
