### PR TITLE
Capital letter in config not allowed?

### PR DESCRIPTION
**Pull request by thundergreen**
Hey guys. Was following your example by just copy paste it and had errors with capital letters. Ist that right that no capital letter are allowed ? Then we would have to change all the configs. I just made on to show you an example.

Greety

ThUnD3r|Gr33n

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

### CODE REVIEW

**Comment by Oliv3rDog** [comment]
Yes, capital letter not allowed. 
We need to change HDMI to hdmi and AV to av
Not sure how to help doing that.

**Comment by thundergreen** [comment]
Just change it on github and make a pull request

Am 01.02.2017 22:00 schrieb "Oliv3rDog" <notifications@github.com>:

**Comment by Oliv3rDog** [comment]
done... but I think @thundergreen  have already made it...

**Comment by thundergreen** [comment]
Only one example

Am 01.02.2017 22:39 schrieb "Oliv3rDog" <notifications@github.com>:

**Comment by fabaff** [comment]
I will take https://github.com/home-assistant/home-assistant.github.io/pull/1935 as both PR are fixing the same things.

**Pull request closed without merging**
