### PR TITLE
Refactor of documentation method for components (2019-0016)

### PR DESCRIPTION
**Pull request by frenck**
**Description:**

Currently, we have tons of platform pages, that tells the user to go look at the component/hub page.
As a result of this, we have a lot of "Hub" pages, for things that are actually not a hub.

This PR tries to solve that and adds/optimizes some other things in the process.

## Changes

- Adds support for specifying multiple categories in the `ha_category` frontmatter variable. While maintaining backwards compatibility.
- Ensured component still shows up in multiple categories (including search)
- Changed featured items category to ensure the component is only listed once (for the first category)
- Adds support for the `ha_config_flow` frontmatter variable, which will show a notice about this component being configurable via the UI on the component page.
- Adds a little more spacing around the logo's shown on the components page.
- Removes the list of other components in the same category from the component page (this reduces built times significantly): Added list of categories this component is in instead.
- **Migrated the Ikea Tradfri as an example:**
   - Removed platform pages (sensor, light, switch)
   - Added `redirect_from` to the main component page in order to keep old URL's working
   - Added `Light`, `Switch` and `Sensor` as categories, removed it from `Hub`.
   - Marked `ha_config_flow` since it does support that.

image

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** n/a

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by balloob — APPROVED** [review]
Awesome!

**Review by klaasnicolaas — APPROVED** [review]
This is great! 😄

**Comment by balloob** [comment]
@klaasnicolaas you can merge this one 👍

**Comment by klaasnicolaas** [comment]
Thnx for your PR @frenck 😄

**Comment by frenck** [comment]
Congratz on merging your first PR on the org @klaasnicolaas 🏅

**Pull request merged**
