### PR TITLE
Update Intent_script component configuration

### PR DESCRIPTION
**Pull request by klaasnicolaas**
**Description:**
Update style of Intent_script component documentation to follow new configuration variables description.
Related to #6385.

**Note:**
There are still a number of variables that are missing a description.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Who can help me think of some of description texts 🤔? I am not familiar with this component so I have no idea what I can put down 😄

**Comment by frenck** [comment]
@klaasnicolaas Not sure about your question here...
What exactly are you struggling with?

**Comment by klaasnicolaas** [comment]
See the lines with: `<- Need additional text>`.

I added some new variables because they were not described before but they are in the python code. Only I have no idea what some variables do, so it is difficult to formulate a good description 😉

**Comment by frenck** [comment]
@klaasnicolaas This took a while, sorry!

Updated the PR, what do you think?

**Review by frenck — APPROVED** [review]
@klaasnicolaas Agreed (discussed per Discord).

**Comment by thundergreen** [comment]
I agree that there are almost no dics available . I wanna just post another example what's poosible and not documented:

```
  snips_fenster:
    sequence:
      service: snips.say
      data_template:
        text: >
             {% if is_state('group.windows_doors', 'on') %}
             Achtung! Folgende Fenster oder Türen sind noch offen: {{ dict((states|selectattr('entity_id', 'in', state_attr('group.windows_doors', 'entity_id'))|list)|groupby('state'))['on']|map(attribute='name')|list|join(', ') }}
             {% elif is_state('group.windows_doors', 'off') %}
             Alle Fenster und Türen sind geschlossen
             {% endif %}
```

This qill "enable" TTS with snips and this script checks for open windows in group.windows_doors and tells via TTS  which windows / doors are open if no door or window is open --> A>nother message appears ( Alle Fenster und Türen sind geschlossen )

**Pull request merged**
