### PR TITLE
Consecutive volume steps delay in webostv

### PR DESCRIPTION
**Pull request by jthure**
Added section about Consecutive volume steps delay in webostv

## Proposed change

This documentation is related to a new feature in the webostv component. In the case where an sound output that only support relative volume stepping is used, the receiving speaker may have issues dealing several volume step commands arriving at the same time. Therefore should be possible to configure a time delay so that at least the configured amount of time has elapsed between two consecutive volume steps before the second one is fired.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- [Link to parent pull request in the codebase](https://github.com/home-assistant/core/pull/35367) 

## Checklist

- [ x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by frenck** [comment]
Rebased the PR onto the `current` branch and some small tweaks

**Review by frenck — APPROVED** [review]
Thanks, @jthure 👍

**Comment by jthure** [comment]
Thanks for reviewing my PR @frenck, but was it really correct to merge in with current? The core feature PR: https://github.com/home-assistant/core/pull/35367 which it refers to isn't merged yet

**Comment by frenck** [comment]
@jthure Meh. Sorry about that. Initially, the PR didn't contain a link to the parent PR, hence classified as `current`.

I'll correct this.

**Comment by jthure** [comment]
@frenck Okay, thanks. It's my first contribution to Homeassistant, so apologies if I did something wrong while creating the PR

**Comment by jthure** [comment]
@frenck The parent PR https://github.com/home-assistant/core/pull/35367 has been closed (the feature belongs in the underlying library aiopylgtv). So this PR can be reverted/removed

**Pull request merged**
