### PR TITLE
Add dreo integration

### PR DESCRIPTION
**Pull request by dreo-team**
Add documentation for Dreo fan

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/119075
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/5487
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by c0ffeeca7** [comment]
Thank you for contributing, @dreo-team :+1: 

If I see this correctly, the related core PR adds an entirely new integration, not just a new feature.
image

1. In the PR template above, please correct the entry.
2. In the [brands repository](https://github.com/home-assistant/brands), create a PR adding icons and logos. 
3. Then, in this documentation PR, provide the link to the brands PR.

**Comment by c0ffeeca7** [comment]
I'm [drafting this PR](https://developers.home-assistant.io/docs/review-process#prs-are-being-drafted-when-changes-are-needed), as changes are needed. Please undraft it, once the changes have been implemented and the PR is ready for review again.

**Comment by dreo-team** [comment]
Hey home-assistant!
Is it convenient to speed up the review process?
Thanks,
The Dreo Team

**Comment by dreo-team** [comment]
Hello! How is the PR review going?

**Comment by dreo-team** [comment]
Hello! Could you please tell me what stage the PR is at? Thank you!

**Comment by c0ffeeca7** [comment]
> Hello! Could you please tell me what stage the PR is at? Thank you!

As this is a documentation PR, it is waiting for the related parent to get merged.

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed.

**Pull request closed without merging**
