### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by JensTimmerman**
fix typo

## Proposed change
I fixed a typo, passowrd -> password

## Type of change
- [X] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by JensTimmerman** [comment]
@homeassistant It's not clear to me what the rc status is, is that current or next? can you please clarify this somewhere? It looks like next, since it's not in a stable release.

**Comment by JensTimmerman** [comment]
actually I think the rc branch is the best match? or do you want me to change to next after all?

**Review by frenck — CHANGES_REQUESTED** [review]
The `rc` branch should not be used directly (with the exception for things that only exist on that branch).

In this case, the `next` branch should have been used. Please change the target to the `next` branch and git rebase your changes.

../Frenck

**Comment by JensTimmerman** [comment]
@frenck thank you for the clarification,

**Pull request closed without merging**
