### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by ispysoftware**
## Proposed change
Adds note about the addition of the alarm control panel feature

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

https://github.com/home-assistant/core/pull/36468

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
Please rebase on latest next branch and remove the unrelated commits.

**Comment by ispysoftware** [comment]
err how do i do that?

**Comment by MartinHjelmare** [comment]
I usually switch to my local branch of next, then pull the upstream branch, ie next branch. Then switch back to my feature branch and do an interactive rebase of the feature branch on next branch. There you can remove not wanted commits. Then when done with the rebase, force push to remote feature branch.

**Comment by ispysoftware** [comment]
Right - this might take a while as I have no idea what i'm doing or what most of that means.

**Comment by ispysoftware** [comment]
do you have an example set of git commands to do this?

**Comment by MartinHjelmare** [comment]
https://hackernoon.com/beginners-guide-to-interactive-rebasing-346a3f9c3a6d

**Comment by ispysoftware** [comment]
I just added this 1 line of text using the edit link on the agent dvr page on home assistant website - i don't have a local copy of it on my computer - i just did it via the github website. Is it easier just to close this and try it again?

**Comment by MartinHjelmare** [comment]
Yes, you can do that too. Make sure you start from the correct base, ie next branch.

**Comment by ispysoftware** [comment]
https://github.com/home-assistant/home-assistant.io/pull/14243

**Pull request closed without merging**
