### PR TITLE
Add options to filter by iot class on integrations page

### PR DESCRIPTION
**Pull request by kknopper**
…

## Proposed change

   - Created more filter tags on the integrations page, matching the categories implementation. Now a user can select and filter integrations by their Internet of Things classification: (local push, local polling, cloud push, cloud polling, etc.).

- Created a class for the filter-titles, and took some liberties with styling here. Feel free to correct me here for best styling approach. Thought it would be best to now categorize the filters by `IoT Class` and `Categories`. Styled similarly to the `.note` class.

- Please note this is my first PR for this project; please correct me with any mistakes that do not follow standards.

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by timmo001 — APPROVED** [review]
Looks good!

**Comment by frenck** [comment]
I don't think this makes sense in how this is set up. I  think this is more of a subfilter or additional filter when looking at a category and (as done now) not a category on its own.

Personally, I won't see myself going to the Home Assistant website looking for a nice local push integration... 

I go there to find the device/brand I had my eye on or to find devices in certain categories. Being able to filter down on that, sounds more logical to me.

**Comment by kknopper** [comment]
@frenck I like your idea of a secondary filter, as it would definitely keep the ui more organized, since there's so many category filters already. I would love to try to implement this. Probably will just try to use a select dropdown to filter.

I also thought it might be useful to just show an icon in the corner of each integration card to show its IoT class (probably just the icons used here: https://www.home-assistant.io/blog/2016/02/12/classifying-the-internet-of-things/#classifiers)
 
This would be similar to the recent core update where integrations now show a cloud icon if they require cloud connectivity. 
This would probably have to be a separate issue; would love to hear your thoughts on this though.

**Comment by ludeeus** [comment]
I made a concept for secondary filtering last year <https://github.com/home-assistant/home-assistant.io/issues/16996#issuecomment-880515679> maybe that can help

**Comment by kknopper** [comment]
@ludeeus I'll take a look later tonight!

**Pull request closed without merging**
