### PR TITLE
Add InfluxDB Docker setup instructions

### PR DESCRIPTION
**Pull request by nwesterhausen**
Add instructions for setting up a functional and up-to-date InfluxDB instance to use with this component to the documentation.

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by frenck** [comment]
I actually do not agree on this change.

We should not be a setup/installation manual for 3rd party software. Secondly... where does this end? First Docker, next, manual Ubuntu? RedHat? And what if all components start doing this?

**Comment by nwesterhausen** [comment]
Currently the influxdb component page links to the home assistant blog post which goes over how to install influxdb and grafana and use them. Those instructions are now a few years old (dated December 2015) and cannot be followed with the current version of InfluxDB. 

I see your point, maybe instead we stop linking to the old blog post?

**Comment by frenck** [comment]
Removing the blog is a good option. Maybe, instead, we could link to a general installation instructions page of InfluxDB? For Hass.io maybe to the add-on available?

**Comment by nwesterhausen** [comment]
I went ahead and got rid of the setup instructions I added and replaced the link to the blog post with a link to influxdb install documentation and the forum post for the community add-on for hassio.

From what I saw by looking at other components in the history category, this seems appropriate.

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Agreed on the changes. I've made a little tweak.

Thank you for the update @nwesterhausen 👍 

Happy Hacktoberfest 🎉 

../Frenck

**Pull request merged**
