### PR TITLE
Updated automation to switch tariffs

### PR DESCRIPTION
**Pull request by ardeus-ua**
Great sensor, automation is checking the condition after HA start (to avoid wrong tariff) and then triggers on the time of tariff change.
It would be great if tariff time would be possible to configure within a sensor setup

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
`rc` is not the right branch to merge in it, please rebase to `current`

**Comment by frenck** [comment]
Dual tariff is not used in a large part of the world. Maybe add it as a second example instead of replacing the current?

**Comment by ardeus-ua** [comment]
As this component is actually made to measure dual tariff, or triple, you can easily expand to as many tariffs you want. My add is to switch to exact tariff, not to the next one. It may occur that you restart your HA right in a moment of tariff switch or your server's power source is not secured with UPS and you had power outage. This way you will know for sure. But to be honest, both examples will give users more possibilities to apply in their exact situation.

**Comment by frenck** [comment]
> But to be honest, both examples will give users more possibilities to apply in their exact situation.

Hence my suggestion on adding it as a second example, you've currently replaced it.

**Comment by ardeus-ua** [comment]
> Hence my suggestion on adding it as a second example, you've currently replaced it.
Agree. added instead of replacing

**Comment by frenck** [comment]
@ardeus-ua Your PR still has a build error. Are you planning on resolving that?

Furthermore, a merge conflict has appeared. Please resolve, so we can go ahead with the merge.

**Comment by frenck** [comment]
Since there was no response at all, I'm declaring this PR stale and closing it.
Feel free to re-open this PR when you feel like that is the appropriate thing to do.

**Pull request closed without merging**
