### PR TITLE
Grammatical error fixes

### PR DESCRIPTION
**Pull request by aedorado**
Github shows one commit on the next branch and 70 on the current branch. Can someone please point out if I am doing something wrong?

### CODE REVIEW

**Comment by Landrash** [comment]
@aedorado Your branch of the repository was created against the wrong branch :)
The current branch is a bit ahead on somethings right now since there's very many small fixes being submitted.

**Comment by aedorado** [comment]
Thanks @Landrash ! I don't think I did something wrong! Did I fork from the wrong branch? Can you please suggest a fix?

**Comment by Landrash** [comment]
You most likely made your branch from the wrong branch yes. In this case it's not really a problem since we can merge it into next and there's a release fairly imminent.

**Comment by aedorado** [comment]
@Landrash - Thank you. Can you please tell me how I can become an active part of the home-assistant project. I've been looking to contribute to open-source and I really like the connected home and devices idea. :)

**Comment by Landrash** [comment]
@aedorado Jump on [gitter](https://gitter.im/home-assistant/), join the [community](https://community.home-assistant.io/) or just review code here and help whoever you can.

I would suggest you start with getting your setup up to the standard you want, ask for help and in that way learn what you need and when possible help those with questions that you can answer.

**Comment by aedorado** [comment]
@Landrash - Thank you very much!

**Pull request merged**
