### PR TITLE
Reword Adguard intro

### PR DESCRIPTION
**Pull request by FletcherAU**
## Proposed change

* Rewords Adguard into to read slightly better.
* Remove several new lines in line with HA Docs standards.

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
I don't like the continues writing. Please revert the new-line changes.

**Comment by FletcherAU** [comment]
> I don't like the continues writing. Please revert the new-line changes.

Newlines have been removed outside of the two intro sentences. For the intro I didn't see a place where adding them in helped so would appreciate guidance if they're desired there.

**Comment by frenck** [comment]
I generally cut them around the 80 char line, mostly because if helps comparison in PRs and smaller terminal windows.

../Frenck

**Review by frenck — APPROVED** [review]
Thanks, @FletcherAU 👍 

../Frenck

**Pull request merged**
