### PR TITLE
Add documentation for Supervisor integration

### PR DESCRIPTION
**Pull request by avee87**
## Proposed change

Currently documentation for Supervisor integration doesn't exist for some reason. Adding it now.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Please rename the file to `hassio.markdown` to match the domain.

**Comment by avee87** [comment]
Hey @frenck, is there anything else that needs to be done in this PR to get it merged? It doesn’t depend on any Core PRs and it would be great to have it merged so we could add docs for new hassio sensors on top of it.

**Comment by frenck** [comment]
@avee87 With almost 700 PRs open in the org, it would require patience a bit...

**Review by frenck — APPROVED** [review]
Thanks, @avee87 👍

**Pull request merged**
