### PR TITLE
Correcting device_class link

### PR DESCRIPTION
**Pull request by DubhAd**
Yes, I know it isn't a link in the source, but it is in the live docs 🤷‍♂️

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
This should not be modified in this location.

https://github.com/home-assistant/home-assistant.io/blob/2dbbafef628c691de84a705dee6547a802795dd8/plugins/configuration.rb#L5

**Comment by fabaff** [comment]
The content is coming from https://github.com/home-assistant/home-assistant.io/blob/next/plugins/configuration.rb#L3 as @frenck already mentioned.

If `device_class` is included in a sensor the link is pointing to https://www.home-assistant.io/components/sensor/#device-class and for a binary sensor to https://www.home-assistant.io/components/sensor/#device-class.

For the Customizing entities page this is not working. Thus I suggest that we just display the string because below is a section that contains the links to the component pages.

**Comment by fabaff** [comment]
Was not working for covers: https://github.com/home-assistant/home-assistant.io/pull/6793

**Comment by frenck** [comment]
So is there anything to do now on this PR @DubhAd 🤷‍♀️

**Comment by frenck** [comment]
Closing this PR, since it is running stale.

**Pull request closed without merging**
