### PR TITLE
Update recorder docs - create PostgreSQL database with utf8 encoding

### PR DESCRIPTION
**Pull request by borpin**
## Proposed change

ref https://github.com/home-assistant/core/issues/44595

The issue appears to be caused by the PostgreSQL database I created first time not using `utf8` encoding. PostgreSQL default is `SQL_ASCII`.

Recreated the database with `utf8` encoding and the errors were not seen.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: https://github.com/home-assistant/core/issues/44595

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by bdraco** [comment]
Thanks.

Would you please update the url strings as well?  I'd put in a suggestion but your change it too far away for github to let me do it.

```
| PostgreSQL                     | `postgresql://SERVER_IP/DB_NAME`                                                                          |
| PostgreSQL                     | `postgresql://user:password@SERVER_IP/DB_NAME`                                                            |
| PostgreSQL (Socket)            | `postgresql://@/DB_NAME`                                                                                  |
| PostgreSQL (Custom socket dir) | `postgresql://@/DB_NAME?host=/path/to/dir`                                                                |
```

**Comment by borpin** [comment]
> Would you please update the url strings as well?

I don't think the url strings should be updated. That additional parameter you suggested is only required if the database is not `utf8` and from my reading is not something that should be used by default.

**Comment by bdraco** [comment]
> > Would you please update the url strings as well?
> 
> 
> 
> I don't think the url strings should be updated. That additional parameter you suggested is only required if the database is not `utf8` and from my reading is not something that should be used by default.

Thanks. In that case, I think that's useful information to include near the text you just added.

**Review by bdraco — APPROVED** [review]
LGTM

**Pull request merged**
