### PR TITLE
Update mvglive.markdown

### PR DESCRIPTION
**Pull request by 9R**
add documentation for home-assistant/home-assistant/pull/25304

**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

<a href="https://gitpod.io/#https://github.com/home-assistant/home-assistant.io/pull/9925"></a>

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @9R,

Thank for opening up a PR to update the docs.
I've seen you've checked off all the boxes, but please make sure you read them and understand them.

The PR is based against an incorrect branch. Since this change depends on a change in our codebase (a parent PR) and the parent PR depends on the next release of Home Assistant, the documentation change should go into our `next` branch.

Please update the PR to target the `next` branch and rebase if needed.

../Frenck

**Comment by 9R** [comment]
Hi @Frenck,

you are correct, I miss understood the checklist phrasing.

I have created the patch for the `next` branch in my fork 9R@10ea6e0, but I'm unable to replace it in this pull request.

Can you give me a hint, how to proceed?

**Comment by frenck** [comment]
@9R You don't have to create a new branch, update this one. I've changed the target here on the PR to `next`. As you can see, a bunch of other PRs/commits show up. That is because you started your branch from `current`, so effectively, you are trying to merge in other commits to `next` as well.

To solve this, you can rebase your branch onto the current branch.

```bash
git fetch
git checkout patch-1
git rebase --onto=origin/next patch-1~1
git push --force
```

That should do the trick.

**Comment by 9R** [comment]
@frenck: thx for the help, changing the target branch to `next` did the trick

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by frenck** [comment]
Done! Good job @9R 🎉

**Pull request merged**
