### PR TITLE
Procedure for OwnTracks & bridged MQTTs

### PR DESCRIPTION
**Pull request by surge919**
Added my procedure for settings up OwnTracks and bridged MQTT brokers for use with SmartThings

### CODE REVIEW

**Comment by fabaff** [comment]
I think that this would be a better fit for the [infrastructure](https://home-assistant.io/cookbook/#infrastructure) section in the Examples part.

**Comment by surge919** [comment]
Is this still correct?

New recipes can be added via the home-assistant.io repository
<https://github.com/home-assistant/home-assistant.io/tree/master/source/_cookbook>
.

The link is broken.

**Comment by fabaff** [comment]
No, that link is outdated. The repo was moved to home-assistant.github.io.

**Comment by surge919** [comment]
I'm having a bear of a time with this.
I created a fork and entered my info but the formatting isn't showing up.
Is there a write-up about this?

Here's what I have so far.

https://github.com/surge919/home-assistant.io/blob/next/source/_cookbook/owntracks_bridged_mqtts

thanks

**Comment by fabaff** [comment]
The pages are rendered when they are deployed. 

You need a header for your guide. Similar to that one.

```
---
layout: page
title: "Automation for rainy days"
description: "Basic example how to use weather conditions to set states"
date: 2015-10-08 19:05
sidebar: true
comments: false
sharing: true
footer: true
ha_category: Automation Examples
---
```

**Comment by surge919** [comment]
ok.. I think it's done.

https://github.com/surge919/home-assistant.io/blob/next/source/_cookbook/owntracks_bridged_mqtts

**Pull request closed without merging**
