### PR TITLE
added a set up guide video

### PR DESCRIPTION
**Pull request by JuanMTech**
Added an easy to follow video guide on how to get started with Zigbee and the Home Assistant ZHA integration.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by frenck** [comment]
Thanks for the video @JuanMTech. However, we are not adding it to the documentation.

There are 2 main reasons for us in this case:

- The setup of Proxmox is out of scope for Home Assistant. Not everybody uses Proxmox (in fact, the larger part of the community doesn't use it).
- The recommendation of the Raspbee for the Raspberry Pi is something we would definitely not recommend anybody in our community to use. While it can be used, it doesn't give you the flexibility to upgrade to another system later on OR mitigate Wi-Fi/device RF interference issues (which Conbee suffers from).

Nevertheless, great video in general 👍

**Comment by Gamester17** [comment]
@frenck Would you accept a similar video if he instead showed a stand-alone Raspberry Pi 3 or 4 with an SD-card that has official Home Assistant Operating System (a.k.a. Home Assistant OS, formerly known as Hass.io) with Zigbee adapter plugged directly in it?

* https://www.home-assistant.io/hassio/
  * https://www.home-assistant.io/hassio/installation/

@JuanMTech  IMHO, that was a great educational video in a very good pedagogical format, (though I hadn't heard of Proxmox). IMHO, recommend to not use Proxmox at all in your videos regardless if you wish all videos to reach a broader audience. Surely best to only show stand-alone Raspberry Pi 3 or 4, (maybe just at the end of the video you could refer to separate videos that show hypervisors setup as alternative options as an appendix).

FYI, Home Assistant OS (Hassos) official webpage currently only have instructions for the virtual appliance images with VirtualBox, Hyper-V, KVM, and VMware Workstation as virtualization hypervisors (probably as those are most common):

* https://www.home-assistant.io/hassio/
  * https://www.home-assistant.io/hassio/installation/

**Comment by frenck** [comment]
> Would you accept a similar video if he instead showed a stand-alone Raspberry Pi 3 or 4 with an SD-card that has official Home Assistant Operating System (a.k.a. Home Assistant OS, formerly known as Hass.io).

Please note that your formerly known as "Hass.io" isn't correct here. Nevertheless, the hardware isn't the point.

**Comment by Gamester17** [comment]
> Thanks for the video @JuanMTech. However, we are not adding it to the documentation.
> 
> There are 2 main reasons for us in this case:
> 
> * The setup of Proxmox is out of scope for Home Assistant. Not everybody uses Proxmox (in fact, the larger part of the community doesn't use it).
> * The recommendation of the Raspbee for the Raspberry Pi is something we would definitely not recommend anybody in our community to use. While it can be used, it doesn't give you the flexibility to upgrade to another system later on OR mitigate Wi-Fi/device RF interference issues (which Conbee suffers from).


> > Would you accept a similar video if he instead showed a stand-alone Raspberry Pi 3 or 4 with an SD-card that has official Home Assistant Operating System (a.k.a. Home Assistant OS, formerly known as Hass.io).
> 
> Please note that your formerly known as "Hass.io" isn't correct here. Nevertheless, the hardware isn't the point.


Hmm, what are the points that would have to be changed for videos similar to this to be acceptable on integration web pages? 

Maybe not recommending the ConBee II USB adapter at all? Or only recommend it together with a USB-extension cable? I know that is the default suggestion to all people with Zigbee USB-adapters as it will usually resolve most signal interference issues.

Or that JuanMTech mentioned RaspBee as an alternative? I know that RaspBee is an internal module for mounting on GPIO header on Raspberry Pi and that makes it much more sensitive to signal interference and something that can not simply be relieved by using a USB-extension cable to get the adapter away from the Raspberry Pi other devices that could interface, and therefore the RaspBee and other "internal" should perhaps not be recommended?

Personally, I currently recommend EFR32MG1 Series 1 based Silicon Labs USB-adapters like the latest Elelabs Zigbee USB Adapter for now, at least until you can buy EFR32MG21 Series 2 based USB-adapters that come pre-flashed out-of-the-box with ZHA compatible firmware.

Texas Instruments CC2531 USB adapters also work very good for their price however they are not compatible with Zigbee 3.0 so not as future-proof plus those CC2531 adapters without an external antenna have relatively poor reception too. The newer Texas Instruments adapter work great as well (and come with external antenna too) but they are unfortunately not readily available as of yet.

By the way, the main benefit with ConBee (and RaspBee) is that you can not only use it ZHA as it is also supported by deCONZ and Zigbee2MQTT so you get the option to try out all those three solutions for getting Zigbee into Home Assistant.

**Pull request closed without merging**
