### PR TITLE
Update toon.markdown

### PR DESCRIPTION
**Pull request by costastf**
**Description:**

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#29248

## Checklist:

- [ ] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [ ] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by costastf** [comment]
Hi @frenck this is the update of the documentation that goes with the MR I made on the component. If there is anything else I can do please ping me.

**Comment by klaasnicolaas** [comment]
Please rebase this PR to the `next` branch

**Comment by klaasnicolaas** [comment]
Whoops sorry everyone for getting a notification about reviewing this PR 😆

**Comment by costastf** [comment]
Closing this as the code it references has not been merged and it needs discussing.

**Pull request closed without merging**
