### PR TITLE
Add note regarding disabled sensors

### PR DESCRIPTION
**Pull request by epenet**
## Proposed change

Add an indication about disabled entities.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/42797
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by epenet** [comment]
@frenck / @klaasnicolaas 
I have a followup PR in the core: https://github.com/home-assistant/core/pull/42832, but this documentation PR has not yet been merged.

How should I proceed with the extra documentation PR?
- Should I update this documentation PR?
- Should I create a new PR based on `next`?
- Should I create a new PR based on this documentation PR?

**Comment by frenck** [comment]
Please have some patience. The PR has been marked corrected (`parent-merged` label) and will be processed before the next Home Assistant release goes out.

Thanks 👍

**Comment by epenet** [comment]
@frenck, I'm not in a hurry - I just want to know how to prepare the documentation PR for https://github.com/home-assistant/core/pull/42832

On top of this one regarding disabled entities, I am also adding suport for binary_sensor (and switch in a further PR)

**Review by frenck — APPROVED** [review]
Thanks, @epenet 👍

**Comment by epenet** [comment]
Thanks @frenck 

There was a little merge conflict in this one - which I've resolved in #15561 (a piece of text got duplicated)
Please tell me if you would prefer me to make a separate PR to fix the conflict

**Pull request merged**
