### PR TITLE
Update KNX for xknx 0.16.0

### PR DESCRIPTION
**Pull request by farmio**
## Proposed change

- Changes some headings so we have nicer TOC
- Removed some unnecessary sentences
- Added data attributes for the `knx_event`
- Added documentation for new RGB individual addressable lights

## Type of change

- [x] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/44749
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by frenck** [comment]
Rebased the PR onto `next` in order to get rid of the unrelated commit in this PR.

**Review by frenck — APPROVED** [review]
Thanks, @farmio 👍 

Happy New Year 🥂

**Comment by farmio** [comment]
@frenck Thank you! Afaik this will not be shipped with 2021.1, but 2021.2 so the milestone should be removed.

**Comment by frenck** [comment]
Thanks! Removed the milestone 👍

**Pull request merged**
