### PR TITLE
Fixes overflow issue in tables

### PR DESCRIPTION
**Pull request by ludeeus**
## Proposed change

Fixes table overflow issue, example <https://www.home-assistant.io/integrations/binary_sensor.xiaomi_aqara/>

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.
- [x] Bugfix for the website source.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by frenck** [comment]
image


Better, but still goes south (although this table might be one of the worst ones we have).

**Review by frenck — APPROVED** [review]

**Comment by ludeeus** [comment]
There is just too much data in that table, to ever be pretty.

**Comment by ludeeus** [comment]
The alternative:
image

**Comment by frenck** [comment]
Hehe lets merge this one, and replace the tables on that page for something more reable later on...

**Pull request merged**
