### PR TITLE
Added metadata version badge to README.md

### PR DESCRIPTION
**Pull request by omerome83**
Added a metadata badge from shields.io to display the current version on the README.md file. When clicked on, it redirects you to the home-assistant releases page (https://github.com/home-assistant/core/releases)

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — COMMENTED** [review]
Thank you for willing to contribute, but going to friendly decline this PR.

The README is used in all branches (not bound to the current version).

../Frenck

**Comment by omerome83** [comment]
> Thank you for willing to contribute, but going to friendly decline this PR.
> 
> The README is used in all branches (not bound to the current version).
> 
> ../Frenck

Oh okay. No problem!

**Comment by omerome83** [comment]
Would this be a good change if I were to make a PR for the home-assistant/core repo (https://github.com/home-assistant/core)?

**Comment by frenck** [comment]
It has not much added value, it faces the same issues.
Our website provides this information.

**Pull request closed without merging**
