### PR TITLE
Buildtime improvements

### PR DESCRIPTION
**Pull request by mjrider**
**Description:**
Remove compression, it is only used for stripping line endings, and most of them can be removed by not generating them.

## Checklist:

- [X] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [n/a] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by balloob** [comment]
That's slick !

**Comment by frenck** [comment]
I'll test this locally again to ensure the impact, but if all OK, that I'll merge `current` into `next` asap.

**Comment by mjrider** [comment]
on my machine:

build time:  
new:  165.026 seconds.  
old: 429.287 seconds.  

du -sch */public
116M	home-assistant.io-old/public
115M	home-assistant.io/public
231M	total

**Comment by frenck** [comment]
Netlify is a bit slower (but still a major improvement):

```
9:49:19 AM: Executing user command: bundle exec rake generate
9:49:19 AM: ## Generating Site with Jekyll
9:49:19 AM: 
9:49:23 AM: 
9:49:23 AM: directory source/stylesheets/
9:49:23 AM:    create source/stylesheets/screen.css
9:49:23 AM: Configuration file: /opt/build/repo/_config.yml
9:49:23 AM:             Source: source
9:49:23 AM:        Destination: public/
9:49:23 AM:  Incremental build: disabled. Enable with --incremental
9:49:23 AM:       Generating...
9:53:26 AM:                     done in 242.878 seconds.
9:53:26 AM:  Auto-regeneration: disabled. Use --watch to enable.
```

**Review by frenck — APPROVED** [review]

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Love it! Nice optimization @mjrider! Works like a charm. 👍

**Pull request merged**
