### PR TITLE
Fixed and Updated decora switch documentation

### PR DESCRIPTION
**Pull request by springstan**
**Description:**
- added default value for `name`
- fixed hidden configuration variables

**Result:**
grafik

**Pull request in home-assistant (if applicable):** home-assistant/home-assistant#28279<home-assistant PR number goes here>

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next Home Assistant release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by fabaff — APPROVED** [review]

**Comment by fabaff** [comment]
This needs to go to the `next` branch.

**Comment by springstan** [comment]
Should I open a new PR against the `next` branch and close this one?

**Comment by klaasnicolaas** [comment]
You can rebase this PR to the `next` branch or create a new PR.

**Comment by springstan** [comment]
Okay thanks! I created a new one #11051

**Pull request closed without merging**
