### PR TITLE
Describe using language in a TTS service.

### PR DESCRIPTION
**Pull request by andrey-git**
**Description:**

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#5047

### CODE REVIEW

**Comment by Landrash** [comment]
Looks good. I added descriptions for each example also. 
Thank and Merry Xmas :christmas_tree:

**Comment by Landrash** [comment]
Reverted since I merged this by mistake. Will merge again after parent PR is merged.

**Comment by andrey-git** [comment]
@Landrash Parent PR has been merged. (But not released yet)

**Comment by Landrash** [comment]
@andrey-git You delete the branch. Can't re-merge it without it =)

**Comment by andrey-git** [comment]
Restored

**Pull request merged**
