### PR TITLE
KNX component updates for xknx 0.11

### PR DESCRIPTION
**Pull request by farmio**
**Description:**
- Updated documentation to reflect changes to the knx component coming with the integration of [xknx 0.11](https://github.com/XKNX/xknx/releases/tag/0.11.0) 

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** 
home-assistant/home-assistant#24738

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

<a href="https://gitpod.io/#https://github.com/home-assistant/home-assistant.io/pull/9682"></a>

### CODE REVIEW

**Comment by frenck** [comment]
@farmio Assuming this is no longer WIP? If so, could you please remove the WIP state? Thanks 👍

**Comment by farmio** [comment]
There is an issue in the review of the parent PR.  Depending on the solution we will have to adapt this documentation changes.

**Comment by klaasnicolaas** [comment]
Now you only need to solve the merge conflict 😉

**Review by frenck — DISMISSED** [review]
Thanks, @farmio! 👍 

Some tips for next time:

- We don't use the term "Component" anymore, use "Integration" instead.
- Information blocks are `<div>` based now.
- You can't mix HTML & Markdown syntax. It can be done but requires to be enclosed by newlines.
- Please create a feature branch on your fork to work from
- Ensure you have updated to the latest upstream changes on your fork before starting working on the docs.

**Review by frenck — APPROVED** [review]

**Comment by farmio** [comment]
the parent PR home-assistant/home-assistant#24738 was merged to 0.97 . Could you please merge this to current? 
There could possibly be a merge conflict with #10084 now.

**Comment by frenck** [comment]
This is out of sync, correct this one myself.

**Comment by frenck** [comment]
Cherry-picked into `current`, should be visible on our website any time now.

**Pull request merged**
