### PR TITLE
Remove docs for deprecated Flu Near You integration

### PR DESCRIPTION
**Pull request by bachya**
## Proposed change

Flu Near You is scheduled for removal in 2022.10.0. This PR removes the docs.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [x] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/78700
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/3662
- This PR fixes or closes issue: N/A

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Please add an entry to the `_redirects` file for the removed integration.

**Review by klaasnicolaas — DISMISSED** [review]

**Comment by bachya** [comment]
I'm not sure what the issue with `CODEOWNERS` is?

**Review by MartinHjelmare — DISMISSED** [review]

**Comment by MartinHjelmare** [comment]
There's a merge conflict.

**Comment by frenck** [comment]
> I'm not sure what the issue with CODEOWNERS is?

We can ignore that. GitHub assumes all code owners are members in their listing (we use it for different purposes too).

**Review by frenck — APPROVED** [review]

**Pull request merged**
