### PR TITLE
Improve documentation for IronOS integration

### PR DESCRIPTION
**Pull request by tr4nt0r**
## Proposed change

Some improvements to the IronOS documentation

- Add paragraph describing minimum firmware requirements to connect to Home Assistant.
- Improved description for raw tip voltage sensor to further clarify the meaning of this value.
- Add Number to `ha_category`

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

## Summary by CodeRabbit

- **New Features**
	- Added a "Minimum requirements" section outlining connectivity needs for Pinecil V2 with IronOS version 2.21 or higher.
	- Introduced a new entry in the category section for better categorization.
- **Documentation**
	- Enhanced clarity and detail in the description of the "Raw tip voltage" control for improved user understanding.

### CODE REVIEW

**Comment by c0ffeeca7** [comment]
as the parent has been merged in the meantime, could you please rebase and point this to the current branch?

**Comment by tr4nt0r** [comment]
Sure, but I won't get to it until tomorrow 👍🏽

**Comment by tr4nt0r** [comment]
@c0ffeeca7 already rebased it

**Review by c0ffeeca7 — APPROVED** [review]
Thank you, @tr4nt0r :+1:

**Pull request merged**
