### PR TITLE
Documentation change for PR 115739

### PR DESCRIPTION
**Pull request by peteS-UK**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logos and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/115739
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by rajlaud — APPROVED** [review]
Thanks @peteS-UK.

Appreciate the reference to Lyrion. Once Lyrion finalizes logo, etc., we can also consider renaming the integration.

**Comment by peteS-UK** [comment]
resubmitting against correct branch

**Comment by peteS-UK** [comment]
The bot complained it was against the wrong base.  Changing the base pulled in all the other changes from everyone - confusing as hell.  So, just closed that PR and resubmitting a new one.  Sorry - first doc change and didn't know about the current/next thing

**Comment by peteS-UK** [comment]
Sorry about that.  Submitted a new one against the Next branch as required by the bot

Documentation change for PR 115739 by peteS-UK * Pull Request #32437 * home-assistant/home-assistant.io (github.com)<https://github.com/home-assistant/home-assistant.io/pull/32437>


From: Peter Sketch
Sent: Tuesday, April 23, 2024 4:57 PM
To: 'home-assistant/home-assistant.io' ***@***.***>; home-assistant/home-assistant.io ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [home-assistant/home-assistant.io] Documentation change for PR 115739 (PR #32436)

The bot complained it was against the wrong base.  Changing the base pulled in all the other changes from everyone - confusing as hell.  So, just closed that PR and resubmitting a new one.  Sorry - first doc change and didn't know about the current/next thing

**Pull request closed without merging**
