### PR TITLE
Improve amcrest error handling

### PR DESCRIPTION
**Pull request by pnbruckner**
**Description:**
Add max_errors and recheck_interval configuration variables.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#24262

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Is there a parent PR?

**Comment by pnbruckner** [comment]
It's coming next. Just stopped for lunch. :smile:

**Comment by klaasnicolaas** [comment]
Yeah sorry I'm always so fast with checking 😜

**Review by frenck — APPROVED** [review]
Thanks, @pnbruckner! 👍

**Pull request merged**
