### PR TITLE
Added combined energy intergration

### PR DESCRIPTION
**Pull request by timsavage**
## Proposed change

Documentation of new integration of [Combined Energy](http://combined.energy) into HA.Core

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/81724
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/3848

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by timsavage** [comment]
Not sure what is causing the deployment failure, the site generated successfully when I tested it locally.

The log has a stack trace from Ruby and references `integrations/index.html`

Exception:
```
Liquid Exception: undefined method `path' for #<Array:0x0000563b8dcaafe8> in integrations/index.html
```

**Comment by timsavage** [comment]
Found the issue was related to _next_ not being a valid version identifier. 

The error message from Jekyll is more Hyde...

**Review by edenhaus — DISMISSED** [review]
Please split this PR into multiple PRs to match the content of the core PR.
In other words, move the binary sensor related documentation into a new PR.

**Comment by frenck** [comment]
Closing PR as the parent PR has been closed

**Pull request closed without merging**
