### PR TITLE
Combine Nibe heatpump models

### PR DESCRIPTION
**Pull request by Tommatheussen**
## Proposed change

Some Nibe heatpump models share an identifier (in the enum on the Nibe library). This makes it so the UI selection does not show my model (F1245), because F1145 already is in the list. Selecting F1145 does work with my heatpump model.
This change might make it easier for users to distinguish which entry they should select. 

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by elupus — APPROVED** [review]
I think that could make sense. Though i think it should have listed all in the selection.

**Comment by Tommatheussen** [comment]
Indeed, I guess it doesn't list all of them because the Enum values on the library are not unique?

**Comment by elupus** [comment]
@Tommatheussen I've opened a fix for the selection issue. Do you still think this change make sense. This list does end up short, but might be less easy to find your model?

**Comment by Tommatheussen** [comment]
No, if the selection issue is fixed it makes sense to just remove this one, it basically was just a temp fix to help users decide which entry to pick.

**Pull request closed without merging**
