### PR TITLE
Issue 2142: Sort components alphabetically

### PR DESCRIPTION
**Pull request by bdurrer**
**Description:**
The elements on the components overview page are not sorted alphabetically (at least not naturally).
This PR solves Issue #2142 and slightly improves the JS by separating static options from interaction based changes.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** NONE

### CODE REVIEW

**Comment by bdurrer** [comment]
This PR _might_ have a merge conflict with PR #2275 ... we'll see, it's actually quite easily solveable.

**Comment by fabaff** [comment]
Would be nice if you rebase this PR on top of the `current` branch as well.

**Comment by bdurrer** [comment]
@fabaff there you go!

**Comment by robbiet480** [comment]
Thanks! 🐬 🍪 💯

**Pull request merged**
