### PR TITLE
make api key mandatory for PI-hole

### PR DESCRIPTION
**Pull request by mib1185**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/85264
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by MartinHjelmare** [comment]
The parent PR is tagged for a patch release. Not sure if we should cherry pick or change base here.

**Comment by frenck** [comment]
Change base in that case :)

**Review by frenck — CHANGES_REQUESTED** [review]
This PR needs rebasing onto `current`, as the parent PR has been targeting the current stable release (in a patch release).

../Frenck

**Comment by frenck** [comment]
@mib1185 Why did you close the PR?

**Comment by mib1185** [comment]
- #25623

**Comment by frenck** [comment]
Why didn't you just rebase this PR? 🤷

**Comment by mib1185** [comment]
sorry ... i was a bit confused, so i just created a new one ... maybe i had not enough ☕ today  🙈

**Pull request closed without merging**
