### PR TITLE
Updated docs for support of multiple elk devices.

### PR DESCRIPTION
**Pull request by gjbadros**
**Description:**
I just submitted the PR for the multiple elk devices: change for support of multiple elk devices.\

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#22573

## Checklist:

- [x] Branch: `next` is for changes and new documentation that will go public with the next [home-assistant](https://github.com/home-assistant/home-assistant) release. Fixes, changes and adjustments for the current release should be created against `current`.
- [x] The documentation follows the [standards][standards].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Thanks for your PR, @gjbadros!

Nevertheless, since this PR depends on a parent PR in our code base, it should target the `next` branch (since it depends on a next/future release).

**Comment by gjbadros** [comment]
Got it; I clicked that branch "next" option -- I didn't want to assert this has to be accepted into the next version, but now I think I understand that that just reflects that there's a dependency on a PR before the doc change should go live.

**Comment by gjbadros** [comment]
Docs, gurus: is there a way to structurally document that the configuration fields can be repeated for multiple hosts?  I inserted a devices: element so it could clearly contain a list of -host and other configuration fields, but that results in a breaking change to users who only have a single elk m1 controller.  I'd rather leave "devices" out, but then I don't see how to make clear that the subsequent configuration can be repeated multiple times. 

Thoughts?

**Comment by klaasnicolaas** [comment]
I close this PR because the parent PR is also closed

**Pull request closed without merging**
