### PR TITLE
Add documentation for zwave_js.invoke_cc_api service

### PR DESCRIPTION
**Pull request by raman325**
## Proposed change
See https://github.com/home-assistant/core/pull/70466/files for more info

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/70466

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by MartinHjelmare — APPROVED** [review]
Is there a good example where this service is needed?

**Comment by raman325** [comment]
It's hard to say what's a good example because there are too many different setups and use cases. But as an example, the Wake Up CC or Clock CC's can't be acted against fully with the `setValue` API. This is effectively a backstop for CC's because you can always do something with the CC API but you may not be able to with the `setValue` API

**Comment by MartinHjelmare** [comment]
Ok. I think we're not really highlighting the usefulness of this service.

**Comment by frenck** [comment]
As the beta is about to cut, I'm going to merge this one in to be complete.

**Pull request merged**
