### PR TITLE
Update kira.markdown

### PR DESCRIPTION
**Pull request by Alan-K2**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:
- This PR fixes or closes issue:

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Please change the target branch to `current` and rebase if necassary 😉

**Comment by Alan-K2** [comment]
is that OK?

**Comment by frenck** [comment]
@Alan-K2 Nope, you need to git rebase this PR onto the `current` branch in order to get rid of the unrelated commits.

Furthermore, I wonder why you didn't update the original PR to begin with?

**Comment by Alan-K2** [comment]
@frenck I am sorry I am still finding my way with GitHub. I will try to update.

**Comment by frenck** [comment]
@Alan-K2 Let's rebase this one and close the other PR (since this one is more complete).

I can do the rebase if you like?

**Comment by Alan-K2** [comment]
@frenck If you can sort that would be very helpful thank you.

**Comment by frenck** [comment]
OK now I made a fault and lost the changes in the rebasing process 😢 
Please accept my sincere apologies, it is the first time that this has ever happened to me 😞

**Comment by Alan-K2** [comment]
@frenck no problem, my fault for creating two files in the first place!. I will try again with a new PR.

**Pull request closed without merging**
