### PR TITLE
Document zwave_js changes for lib bump to 0.52.0

### PR DESCRIPTION
**Pull request by raman325**
## Proposed change
The term `heal` has been changed to `rebuild routes`. We have changed the language in the backend and in the frontend in the linked PRs, but need to update the docs as well.

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/100833
- Link to parent pull request in the frontend repository: https://github.com/home-assistant/frontend/pull/18009

## Checklist

- [ ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by MartinHjelmare — CHANGES_REQUESTED** [review]
I think we should update the section about logging.

**Comment by raman325** [comment]
> I think we should update the section about logging.

In what sense? There is a separate PR for adding the logging feature to the core and a separate corresponding docs PR

**Comment by MartinHjelmare** [comment]
That's what I meant.

**Comment by raman325** [comment]
So is any change needed here or are we good to merge as is?

**Review by MartinHjelmare — APPROVED** [review]
I think we're good.

**Pull request merged**
