### PR TITLE
added documentation for (new) TOLO Sauna (tolo) integration

### PR DESCRIPTION
**Pull request by MatthiasLohr**
## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/55619
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by gtdiehl** [comment]
@MatthiasLohr Have you created a PR in the [brands](https://github.com/home-assistant/brands) repository? I didn't see one. This is so your integration has a logo and icon on the website and within Home Assistant.

**Comment by MatthiasLohr** [comment]
@gtdiehl no, I haven't. I informed the manufacturer about my idea to add their sauna to Home Assistant, they liked the idea but did not provide a logo (yet?). Not sure when or if they will provide a logo in the future. Anyways, I have a list of planned merge requests to extend the integration (adding more platforms such as light control etc.), so I will update the documentation accordingly anyways. And as soon as I get a logo, I will also update this.

**Comment by frenck** [comment]
Rebased to deal with the CI issue, also made a small tweak :)

**Comment by MatthiasLohr** [comment]
Thx :)

**Comment by frenck** [comment]
@MatthiasLohr Please also open a PR on our brand repository: https://github.com/home-assistant/brands

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Thanks, @MatthiasLohr 👍

**Comment by MatthiasLohr** [comment]
> @MatthiasLohr Please also open a PR on our brand repository: https://github.com/home-assistant/brands

I would really like to, but the manufacturer didn't provide me with a logo (yet). I just sent a mail to the manufacturer with "hey, it has been merged, it looks bad without logo, would be great if you could provide one now".

Unfortunately, I'm not affiliated with them at all, so I can't push things here... this integration is just a hobby project.

**Pull request merged**
