### PR TITLE
Add Intellidrive documentation

### PR DESCRIPTION
**Pull request by sreisi**
## Proposed change

Add the basic documentation to the reisinger intellidrive integration

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase:  https://github.com/home-assistant/core/pull/88540
- Link to parent pull request in the Brands repository:  https://github.com/home-assistant/brands/pull/4145
- This PR fixes or closes issue: fixes #

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Review by frenck — DISMISSED** [review]
Very basic, but not wrong.

If there is more information (or more introduction) possible, that would be preferred. Nevertheless, it does meet the requirements, so:

✅ Approved. Can be merged as soon as the parent PR gets merged.
⚠️ The `ha_release` might need an update before merging this one in.

**Review by frenck — CHANGES_REQUESTED** [review]
Seems like you have merged an incorrect branch into this PR, as there is now all sort of unrelated commits here. Please git rebase your changes onto the `next` branch to clean it up.

Thanks 👍 

../Frenck

**Comment by sreisi** [comment]
> Seems like you have merged an incorrect branch into this PR, as there is now all sort of unrelated commits here. Please git rebase your changes onto the `next` branch to clean it up.
> 
> Thanks 👍
> 
> ../Frenck

Okay I just improved the documentation a bit and corrected the ha_release tag. What do I have to do now so I can do the rebase? Sorry but I am a hard github noob, I only know TFS.

**Comment by sreisi** [comment]
Sorry for the stupid question, but after I must have updated something wrong, all the commits from other constributors are now in my PR.
How can I remove this again? When I try to rebase the VS code, the terminal tells me that everything is up to date.
When I rebase my branch here in GitHub, it just adds more commits from others.
Can anyone give me a step by step guide on what to do now? 

I have already searched in the developer documentation, but apparently I lack too much basic git knowledge.

**Pull request closed without merging**
