### PR TITLE
Add iPhone 12 screenshot to homepage for screenshot

### PR DESCRIPTION
**Pull request by johanf85**
## Proposed change

The iPhone on the homepage is displayed with an old model, nowadays phones have less large bezels. So I decided to propose a a new version with an iPhone 12, which gives an up to date feel. 

I used the website https://mockuphone.com/device/iphone12black to generate a screenshot with a phone. Next to that I took the status bar from this photoshop psd: https://www.free-mockup.com/downloads/iphone-x-with-status-bar-icons-free-psd-mockup/

I used the same Home Assistant screenshot as the current one. I also kept the size of the image as large as the current one, 612 x 636 pixels.

The current phone is white, there is now no newest iphone with a white front. 

There was also a problem with the image not adding to the bottom of the section, see this picture:

i noticed that adding display:block; as CSS for the image solves this. I just added it in inline styling right now, as there isn't a class on the image to use.   

Maybe it's cool to add a html5 animation in the iPhone mockup photo, showing some features of Home Assitant. But that's just an idea, maybe I will propose a commit for that in the future.  

## Type of change

*   [x] Spelling, grammar or other readability improvements (`current` branch).
*   [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
*   [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
    *   [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
*   [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
*   [ ] Removed stale or deprecated documentation.

## Additional information

*   Link to parent pull request in the codebase:
*   Link to parent pull request in the Brands repository:
*   This PR fixes or closes issue:

## Checklist

*   [x] This PR uses the correct branch, based on one of the following:
    *   I made a change to the existing documentation and used the `current` branch.
    *   I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
*   [x] The documentation follows the Home Assistant documentation [standards](https://developers.home-assistant.io/docs/documenting/standards).

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @johanf85, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;home-assistant.io#18374).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by frenck** [comment]
Nice!

Although...

image


Maybe it needs a bit of lossless compression/optimization.

**Comment by johanf85** [comment]
I agree on the size, on closer inspection I also see that the image has gotten a bit stretched during the process. Because the old iphone bezels were larger, the screenshot got bigger now. Is there a higher res image available of the used screenshot on the current photo?

**Comment by johanf85** [comment]
I did some modifications and added a new image to my branch, so there is now a different one.

This is the current:



Image size: 613px x 636px - 25 kB

I kept the ratio of the screenshot part (without the phone) the same as the original, therefore there is no stretching of the screenshot content, but will the total image be smaller.

Proposed image:



Image size: 594px x 553 px - 41 kB

I saved the image as PNG-8 which made the download size smaller. 

Source used for iPhone 12 parts: https://designmodo.com/iphone-mockups/#iphone-12-mockup-set

**Comment by johanf85** [comment]
Did you have a look @frenck ?

**Comment by johanf85** [comment]
Did a new PR

**Pull request closed without merging**
