### PR TITLE
Extend Ring doorbell camera documentation by adding a python_script to o download the video

### PR DESCRIPTION
**Pull request by tchellomello**
**Description:**

 This PR extend the Ring Door Bell camera documentation by adding an example of how to 

```python
# obtain ring doorbell camera object
# replace the camera.front_door by your camera entity
ring_cam = hass.states.get('camera.front_door')

subdir_name = 'ring_{}'.format(ring_cam.attributes.get('friendly_name'))

# get video URL
data = {
    'url': ring_cam.attributes.get('video_url'),
    'subdir': subdir_name,
}

# call downloader component to save the video
hass.services.call('downloader', 'download_file', data)
```

### CODE REVIEW

**Comment by arsaboo** [comment]
Is it possible to rename the file (may be to `ring_date_time` or something)?

**Comment by tchellomello** [comment]
@arsaboo  I'll work on extending the `downloader` component to specify the filename. Hope to send a PR soon.

**Comment by tchellomello** [comment]
@arsaboo  PR #10059 which allows specifying a filename to the `downloader` component. 

If gets approved then we can extend the documentation by passing the filename with a friendly name like "<CAMERA_NAME>_<TIMESTAMP>.mp4"

**Review by fabaff — APPROVED** [review]
:bird:

**Comment by tchellomello** [comment]
:+1:

**Comment by richcakes** [comment]
tchellomello, you stated in this old post "If gets approved then we can extend the documentation by passing the filename with a friendly name like <CAMERA_NAME>_<TIMESTAMP>.mp4."  
Did the camera_name timestamp.mp4  happen for the ring app?

**Pull request merged**
