### PR TITLE
Docs for the new growatt_rs232 integration

### PR DESCRIPTION
**Pull request by ArdescoConsulting**
## Proposed change
⚠️ This is the documentation for the new growatt_rs232 integration I'm going to PR soon in the code repo.

New Growatt integration thats uses RS232 modbus i.s.o. the Growatt cloud service.

## Type of change
New Documentation

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist
- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

This is my first integration so kindly point me in the right direction if something is missing ;)

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Please rebase the branch on your fork to the `next` branch and push again.

**Comment by ArdescoConsulting** [comment]
@klaasnicolaas
This is my first PR so I don't really know how to do rebase the branch on your fork to the next branch and push again.
I saw that I have to correct the text (usb -> USB)
Thanks

**Comment by klaasnicolaas** [comment]
Give me a minute, I will perform the rebase for you 😉

**Comment by klaasnicolaas** [comment]
Rebase is done, please fix the other Lint errors

**Comment by ArdescoConsulting** [comment]
OK thanks.
The Lint errors are fixed.

**Comment by frenck** [comment]
closing PR as the parent has been closed.

**Pull request closed without merging**
