### PR TITLE
Create circuit.markdown

### PR DESCRIPTION
**Pull request by braam**
Documentation for new integration circuit. 
See: https://github.com/home-assistant/core/pull/35756/

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [x] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [x] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/35756/
- Link to parent pull request in the Brands repository: https://github.com/home-assistant/brands/pull/1657
- This PR fixes or closes issue: doc-missing

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Please rebase the branch on your fork to the `next` branch

**Comment by braam** [comment]
rebase not working -- help

**Comment by braam** [comment]
Changed base to: next

**Comment by klaasnicolaas** [comment]
Not only do you need to adjust the target branch, you also have to rebase the branch on your fork to `next` 😉

**Comment by braam** [comment]
Should be fine now.

**Comment by braam** [comment]
hmm looks like I commited to the remote branch, not the local one.
Is this fixable or should I make a new PR?

**Comment by braam** [comment]
Can check if everything is fine now? I managed to get the other commits away.
Only my first one stays.
Thanks.

**Review by frenck — APPROVED** [review]
Thanks, @braam 👍

**Pull request merged**
