### PR TITLE
Update emoncms.markdown

### PR DESCRIPTION
**Pull request by borpin**
## Proposed change

Modifications made to reflect proposed changes to the code to allow the 'unit' included in the API Payload with each sensor to be used if present.

Clarify URL to be used for self hosted installs (varies by install type).

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [ ] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
- [x] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/home-assistant/pull/32042
- This PR fixes or closes issue: https://github.com/home-assistant/home-assistant/issues/31251

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documentation_standards.html

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Please change the target to `next` and rebase this PR if needed.

**Comment by borpin** [comment]
> Please change the target to `next` and rebase this PR if needed.

~~Sorry I don't understand this request~~

Ok I see, it is off the wrong branch.  I simply clicked on the 'edit in GitHub' on the docs page and did not see anything about which base to use. I'm not sure how to change the base in GitHub. Sorry.

**Comment by frenck** [comment]
This PR is going into the `current` branch, which is the documentation for the current stable release (0.105). However, you have opened up a PR for this on our codebase, which means, the change of the documentation is only valid when your code has been merged and released in the next version of Home Assistant.

Hence, you need to target the `next` branch, not the `current` branch.

Changing branches might bring in commits that are currently on your fork already, so you might need to rebase your commit onto the origin/upstream `next` branch to make sure you only bring your commit along.

**Comment by borpin** [comment]
Closing this PR. I will raise a new one and be careful next time to choose the right branch :grin:

**Pull request closed without merging**
