### PR TITLE
Add instructions for 2FA access to unifi OS

### PR DESCRIPTION
**Pull request by tsvi**
Based on the following comment in the forum:
https://community.home-assistant.io/t/2fa-added-to-the-unifi-ubiquiti-component/293031/4

Tested, and seems to work

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: 
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [ ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by Kane610** [comment]
What happens next time you restart home assistant and 2fa has changed?

**Comment by tsvi** [comment]
Just tested the restart procedure and it seems to work.

**Comment by tsvi** [comment]
> Just tested the restart procedure and it seems to work.

Tested a restart of core and a complete reset of host

**Comment by Kane610** [comment]
> > Just tested the restart procedure and it seems to work.
> 
> Tested a restart of core and a complete reset of host

I'm confused how this can work for a long time. isn't the 2FA code lifetime only one minute?

If this works well I'd really like to add support to the integration as well. I just need to understand it better first.

**Comment by tsvi** [comment]
@Kane610 I suppose this is due to the following line.

https://github.com/Kane610/aiounifi/blob/ffe342cafc073ade1a7eb1b1a8c5b804da753953/aiounifi/controller.py#L124

Probably, when sending the password with a specific 2FA and "remember" set to True, the endpoint once actually authenticating, remembers the specific hash of the password|2FA as valid as well.

At least that's what I would do if I would be implementing an API endpoint for supporting 2FA as well as non-2FA.

**Comment by Kane610** [comment]
> @Kane610 I suppose this is due to the following line.
> 
> https://github.com/Kane610/aiounifi/blob/ffe342cafc073ade1a7eb1b1a8c5b804da753953/aiounifi/controller.py#L124
> 
> Probably, when sending the password with a specific 2FA and "remember" set to True, the endpoint once actually authenticating, remembers the specific hash of the password|2FA as valid as well.
> 
> At least that's what I would do if I would be implementing an API endpoint for supporting 2FA as well as non-2FA.

Aah possibly, but for how long...

If you can extend this PR by adding a bit of detail regarding what user and 2FA this relates to I could approve this PR. IE is this only UniFi, what accounts does this work with, etc. Its a bit short right now.

**Review by Kane610 — CHANGES_REQUESTED** [review]
Extend this to what context this will work with, is it only UniFi, what accounts, any specific 2FA, through cloud, local only, etc...

**Pull request closed without merging**
