### PR TITLE
Update dublin_bus_transport` documentation

### PR DESCRIPTION
**Pull request by ialex87**
## Proposed change

Updating the `dublin_bus_transport` documentation as per changes I'm trying to push in PR https://github.com/home-assistant/core/pull/37894

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [x] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: [37894](https://github.com/home-assistant/core/pull/37894)
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [x ] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [x ] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Please change the target branch to `next` and also rebase the branch on your fork to `next`

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by ialex87** [comment]
Thanks guys, that was really quick, now I will have to wait for [#37894](https://github.com/home-assistant/core/pull/37894) to be reviewed. 

Cheers!

**Comment by frenck** [comment]
Closing this PR as the parent PR has been closed.

**Pull request closed without merging**
