### PR TITLE
Enhance sun component doc update

### PR DESCRIPTION
**Pull request by pnbruckner**
**Description:**

home-assistant PR #15961 adds new attributes and configuration items to the Sun component. Update documentation accordingly.

**Pull request in [home-assistant](https://github.com/home-assistant/home-assistant) (if applicable):** home-assistant/home-assistant#15961

Note: PR #6023 was mistakenly opened on the wrong fork branch. This PR replaces it.

## Checklist:

- [x] Branch: Fixes, changes and adjustments should be created against `current`. New documentation for platforms/components and features should go to `next`.
- [x] The documentation follow the [standards][standards].

[standards]: https://home-assistant.io/developers/documentation/standards/

### CODE REVIEW

**Comment by pnbruckner** [comment]
Sorry for any confusion and extra work caused by me incorrectly creating a PR (#6023) on the wrong fork branch. I hope I resolved that problem correctly with this new PR.

**Comment by tjorim** [comment]
Hi @pnbruckner, thanks for these extra monitored conditions! While changing this documentation anyway, would you mind updating the Configuration variables:-section to use the new {% configuration %} tags as explained [here](https://developers.home-assistant.io/docs/en/documentation_create_page.html#configuration)?
I would also recommend moving the more extensive example configuration.yaml a bit down, under the variables setting for example, and swapping out the extra lines that are currently comments as normal text above it. Thanks for helping out.

**Comment by pnbruckner** [comment]
Hi @tjorim, yes, I can do that. Question: do I still use `### {% linkable_title Configuration variables %}` before the new `{% configuration %}` tag?

**Comment by tjorim** [comment]
That's not needed, the template will include it automatically.

**Comment by pnbruckner** [comment]
Ok, have a look see and let me know if I did it right. Can't tell myself what it will look like. Hmm, just saw the check failed. It's complaining about line 5 column 12, but I didn't change anything there.

**Comment by tjorim** [comment]
Possibly because of the colon followed by a space ("Options are: ") or so.
I usually wrap parts that contain some special characters with `"`,
maybe try that for the monitored_conditions description.

**Comment by pnbruckner** [comment]
Well, that didn't work. I guess I'll install the stuff I need to do local testing and see if I can figure out what's wrong.

**Comment by pnbruckner** [comment]
I give up! I tried following the fairly straightforward installation instructions provided [here](https://developers.home-assistant.io/docs/en/documentation_index.html), but it doesn't work. In trying to figure out how to get this stuff installed and working it started to get complex really fast. :(

So I just tried one more time. I quoted all the descriptions and defaults in the config section.

**Comment by tjorim** [comment]
Congrats, all fine now!

**Comment by pnbruckner** [comment]
Any idea how I'm supposed to be able to see what the page is actually going to look like if I can't install the required dev tools? I'd be happy to install and use them, but the instructions for how to do so seem to be lacking. Granted I'm no Linux/Ruby expert, but I'm not a novice either.

**Comment by pnbruckner** [comment]
Suggested changes to the sun component were rejected, so no need for these corresponding doc changes.

**Pull request closed without merging**
