### PR TITLE
Add plant domain to the group integration

### PR DESCRIPTION
**Pull request by McGiverGim**
## Proposed change

The plant support in groups was removed and added again later here: https://github.com/home-assistant/core/pull/41519
The documentation was not updated to reflect this change.

~~I used the UI of Github for this change, and it modifies too the latest line in the file, I don't know if this is a problem.~~

## Type of change

- [ ] Spelling, grammar or other readability improvements (`current` branch).
- [X] Adjusted missing or incorrect information in the current documentation (`current` branch).
- [ ] Added documentation for a new integration I'm adding to Home Assistant (`next` branch).
  - [ ] I've opened up a PR to add logo's and icons in [Brands repository](https://github.com/home-assistant/brands).
- [ ] Added documentation for a new feature I'm adding to Home Assistant (`next` branch).
- [ ] Removed stale or deprecated documentation.

## Additional information

- Link to parent pull request in the codebase: https://github.com/home-assistant/core/pull/41519
- Link to parent pull request in the Brands repository: 
- This PR fixes or closes issue: 

## Checklist

- [X] This PR uses the correct branch, based on one of the following:
  - I made a change to the existing documentation and used the `current` branch.
  - I made a change that is related to an upcoming version of Home Assistant and used the `next` branch.
- [X] The documentation follows the Home Assistant documentation [standards][].

[standards]: https://developers.home-assistant.io/docs/documenting/standards

### CODE REVIEW

**Comment by McGiverGim** [comment]
Is my first PR to Home Assistant, I'm not too sure why it needs rebase. I'm up to date with the origin `current` branch.

**Review by frenck — CHANGES_REQUESTED** [review]
It is based off, and targeting the wrong branch. As this documentation change depends on a parent PR in the codebase, it mean this documentation change only applies when a next version of Home Assistant is released.

Hence it should target the `next` branch. Please change the target and git rebase if needed.

**Comment by McGiverGim** [comment]
Thanks @frenck, maybe I have marked the wrong options.

This change applies to the current version. The parent PR that I linked was merged into 0.116.2, but simply the documentation was not updated.

After that, do you think is better to target it for the next branch?

**Review by frenck — APPROVED** [review]
Thanks, @McGiverGim 👍 

You are absolutely right! Merging this to `current` is indeed the correct move in this case.

Happy Hacktoberfest 🎉

**Pull request merged**
